select
    pi.id,
    pi.connected_account_id,
    pi.payment_method_types,
    pi.amount as amount_in_cents,
    round(pi.amount / 100.0, 2) as amount,
    pi.amount_capturable as amount_capturable_in_cents,
    round(pi.amount_capturable / 100.0, 2) as amount_capturable,
    pi.amount_received as amount_received_in_cents,
    round(pi.amount_received / 100.0, 2) as amount_received,
    pi.application,
    pi.application_fee_amount,
    pi.canceled_at,
    pi.cancellation_reason,
    pi.capture_method,
    pi.confirmation_method,
    pi.created,
    pi.currency,
    pi.description,
    pi.last_payment_error_type,
    pi.last_payment_error_code,
    pi.last_payment_error_decline_code,
    pi.last_payment_error_doc_url,
    pi.last_payment_error_message,
    pi.last_payment_error_param,
    pi.last_payment_error_source_id,
    pi.last_payment_error_charge_id,
    pi.livemode,
    pi.metadata,
    pi.on_behalf_of,
    pi.receipt_email,
    pi.statement_descriptor,
    pi.status,
    pi.transfer_data_destination,
    pi.transfer_group,
    pi.payment_method_id,
    pi.customer_id,
    pi.source_id,
    pi._fivetran_synced,
    pi.metadata:"customer_name" as metadata__customer_name,
    pi.metadata:"email" as metadata__email,
    pi.metadata:"total_insurances" as metadata__total_insurances,
    pi.metadata:"pick_up_location" as metadata__pick_up_location,
    pi.metadata:"brand" as metadata__brand,
    pi.metadata:"return_date" as metadata__return_date,
    pi.metadata:"total_taxes" as metadata__total_taxes,
    pi.metadata:"phone" as metadata__phone,
    pi.metadata:"pick_up_date" as metadata__pick_up_date,
    pi.metadata:"total_extras" as metadata__total_extras,
    pi.metadata:"total_price" as metadata__total_price,
    pi.metadata:"total_revenue" as metadata__total_revenue,
    pi.metadata:"return_location" as metadata__return_location,
    pi.metadata:"total_rack_rate" as metadata__total_rack_rate,
    pi.metadata:"prefixed_id" as metadata__prefixed_id,
    pi.metadata:"transaction_type" as metadata__transaction_type,
    pi.metadata:"vehicle" as metadata__vehicle
from {{ source('analytics_stripe_vsg_resla_com', 'payment_intent') }} as pi
