select
    c.id,
    c.connected_account_id,
    c.amount as amount_in_cents,
    round(c.amount / 100.0, 2) as amount,
    c.amount_refunded as amount_refunded_in_cents,
    round(c.amount_refunded / 100.0, 2) as amount_refunded,
    c.application,
    c.billing_detail_address_city,
    c.billing_detail_address_country,
    c.billing_detail_address_line_1,
    c.billing_detail_address_line_2,
    c.billing_detail_address_postal_code,
    c.billing_detail_address_state,
    c.billing_detail_email,
    c.billing_detail_name,
    c.billing_detail_phone,
    c.application_fee_amount as application_fee_amount_in_cents,
    round(c.application_fee_amount / 100.0, 2) as application_fee_amount,
    c.calculated_statement_descriptor,
    c.captured,
    c.created,
    c.currency,
    c.description,
    c.destination,
    c.failure_code,
    c.failure_message,
    c.fraud_details_user_report,
    c.fraud_details_stripe_report,
    c.livemode as is_live_mode,
    c.metadata,
    c.on_behalf_of,
    c.outcome_network_status,
    c.outcome_reason,
    c.outcome_risk_level,
    c.outcome_risk_score,
    c.outcome_seller_message,
    c.outcome_type,
    c.paid as is_paid,
    c.receipt_email,
    c.receipt_number,
    c.receipt_url,
    c.refunded as is_refunded,
    c.shipping_address_city,
    c.shipping_address_country,
    c.shipping_address_line_1,
    c.shipping_address_line_2,
    c.shipping_address_postal_code,
    c.shipping_address_state,
    c.shipping_carrier,
    c.shipping_name,
    c.shipping_phone,
    c.shipping_tracking_number,
    c.card_id,
    c.bank_account_id,
    c.source_id,
    c.source_transfer,
    c.statement_descriptor,
    c.status,
    c.transfer_data_destination,
    c.transfer_group,
    c.balance_transaction_id,
    c.customer_id,
    c.invoice_id,
    c.payment_intent_id,
    c.payment_method_id,
    c.transfer_id,
    c._fivetran_synced,
    c.rule_rule,
    c.metadata:reservation_id::int as reservation_id,
    c.metadata:platform_id::text as platform_id,
    c.metadata:user_full_name::text as user_full_name,
    c.metadata:user_id::int as user_id
from {{ source('analytics_stripe_vsg_resla_com', 'charge') }} as c
