select
    p.id,
    p.connected_account_id,
    p.amount as amount_in_cents,
    round(p.amount / 100.0, 2) as amount,
    p.arrival_date::date as arrival_date,
    p.automatic,
    p.created,
    p.currency,
    p.description,
    p.failure_code,
    p.failure_message,
    p.livemode,
    p.metadata,
    p.method,
    p.reconciliation_status,
    p.source_type,
    p.statement_descriptor,
    p.status,
    p.type,
    p.destination_bank_account_id,
    p.destination_card_id,
    p.balance_transaction_id,
    p.failure_balance_transaction_id,
    p._fivetran_synced
from {{ source('analytics_stripe_vsg_resla_com', 'payout') }} as p
