select
    si.id,
    si.on_behalf_of,
    si.description,
    si.status,
    si.usage,
    si.application,
    si.cancellation_reason,
    si.created,
    si.livemode,
    si.mandate,
    si.single_use_mandate,
    si.metadata,
    si.payment_method_id,
    si.customer_id,
    si._fivetran_synced,
    si.metadata:"vehicle" as metadata__vehicle,
    si.metadata:"id" as metadata__id,
    si.metadata:"customer_name" as metadata__customer_name,
    si.metadata:"email" as metadata__email,
    si.metadata:"phone" as metadata__phone,
    si.metadata:"pick_up_date" as metadata__pick_up_date,
    si.metadata:"prefixed_id" as metadata__prefixed_id,
    si.metadata:"return_location" as metadata__return_location,
    si.metadata:"total_extras" as metadata__total_extras,
    si.metadata:"total_insurances" as metadata__total_insurances,
    si.metadata:"total_rack_rate" as metadata__total_rack_rate,
    si.metadata:"transaction_type" as metadata__transaction_type,
    si.metadata:"pick_up_location" as metadata__pick_up_location,
    si.metadata:"brand" as metadata__brand,
    si.metadata:"return_date" as metadata__return_date,
    si.metadata:"total_price" as metadata__total_price,
    si.metadata:"total_taxes" as metadata__total_taxes,
    si.metadata:"total_revenue" as metadata__total_revenue
from {{ source('analytics_stripe_vsg_resla_com', 'setup_intent') }} as si
