select
    tr.reservation_id,
    tr.guest,
    tr.vehicle as vehicle_name,
    tr.vehicle_name as vehicle_model,
    regexp_substr(tr.vehicle, '[^\\(]+\\((\\w+)', 1, 1, 'e') as license_plate_state,
    regexp_substr(tr.vehicle, '[^\\(]+\\(\\w+ #(\\w+)\\b', 1, 1, 'e') as license_plate_number,
    regexp_substr(tr.vehicle, '^[^\\(]+\\(\\w+ #\\w*\\W+(\\w+)\\b', 1, 1, 'e') as license_plate_unknown_id,
    regexp_substr(tr.vehicle, '[^\\(]+\\(\\w+ #\\w*\\W+\\w+\\W+(.*)\\)', 1, 1, 'e') as vehicle_rental_indicator,
    tr.trip_start,
    tr.trip_end,
    ceil(datediff('minute', tr.trip_start, tr.trip_end) / 24 / 60) as trip_days,
    tr.trip_days as trip_days_original,
    tr.pickup_location,
    tr.return_location,
    tr.trip_status,
    tr.check_in_odometer,
    tr.check_out_odometer,
    tr.distance_traveled,
    tr.trip_price,
    tr.boost_price,
    tr.discount_3_day,
    tr.discount_1_week,
    tr.discount_2_week,
    tr.discount_3_week,
    tr.discount_1_month,
    tr.discount_2_month,
    tr.discount_3_month,
    tr.early_bird_discount,
    tr.host_promotional_credit,
    tr.delivery,
    tr.excess_distance,
    tr.extras,
    tr.cancellation_fee,
    tr.additional_usage,
    tr.late_fee,
    tr.improper_return_fee,
    tr.airport_operations_fee,
    tr.tolls_and_tickets,
    tr.on_trip_ev_charging,
    tr.post_trip_ev_charging,
    tr.smoking,
    tr.cleaning,
    tr.fines_paid_to_host,
    tr.gas_reimbursement,
    tr.gas_fee,
    tr.other_fees,
    tr.non_refundable_discount,
    tr.sales_tax,
    tr.total_earnings,
    tr.file_name,
    split_part(replace(tr.file_name, '.csv', ''), '-', 1) as turo_account_short_code,
    tr._es_update_timestamp
from {{ source('analytics_vehicle_solutions', 'turo_rentals') }} as tr
