with credit_review_rpo_board_output as (
    {{ generate_monday_table_from_column_map('7794516544') }}
)

select
-- Explicitly name columns so schema changes break this model.

    mmb.item_id,
    mmb.signor_name,
    mmb.name,
    mmb.total_pdi,
    mmb.total_base_rental_quote,
    mmb.credit_approval,
    mmb.total_t3_charges,
    mmb.rpo_potential_profit,
    mmb.request_date,
    mmb.total_eqs_cost,
    mmb.rent_contribution,
    mmb.total_margin,
    mmb.sales_rep_email,
    mmb.applied_rent,
    mmb.documents_and_pictures,
    mmb.rsm_email,
    mmb.total_ext_warranty_quote,
    mmb.gm_email,
    mmb.total_monthly_rent,
    mmb.dealership_or_rental_fleet,
    mmb.upload_customer_amort_form,
    mmb.signor_email_address,
    mmb.gross_profit_margin,
    mmb.yard_name,
    mmb.eqs_dnet,
    mmb.customer_quote_approval,
    mmb.conversion_price,
    mmb.rpo_status,
    mmb.subitems,
    mmb.team_assign,
    mmb.rsm_approval,
    mmb.rpo_term_months,
    mmb.quote_date,
    mmb.rpo_program,
    mmb.total_pm_quote,
    mmb.total_freight_charges,
    mmb.total_discounts,
    mmb.rpo_begin_date,
    mmb.gross_profit,
    mmb.total_asset_sales_price_quote,
    mmb.conversion,
    mmb.total_carrying_cost,
    mmb.credit_application,
    mmb.subitems_sales_tax,
    mmb.rpo_end_date,
    mmb.sales_rep,
    mmb.full_term_rental_revenue
from credit_review_rpo_board_output as mmb
