with fleet_ops_rpo_board_output as (
    {{ generate_monday_table_from_column_map('7794522385') }}
)

select
-- Explicitly name columns so schema changes break this model.

    mmb.item_id,
    mmb.total_asset_sales_price_quote,
    mmb.signor_name,
    mmb.state_filing_number,
    mmb.quote_date,
    mmb.sales_rep_email,
    mmb.total_margin,
    mmb.total_eqs_cost,
    mmb.request_date,
    mmb.total_sales_tax,
    mmb.documents_and_pictures,
    mmb.name,
    mmb.conversion,
    mmb.total_carrying_cost,
    mmb.total_pm_quote,
    mmb.rpo_program,
    mmb.date_rpo_addendum_generated,
    mmb.rpo_term_months,
    mmb.rsm_approval,
    mmb.applied_rent,
    mmb.team_assign,
    mmb.total_discounts,
    mmb.subitems,
    mmb.customer_quote_approval,
    mmb.rpo_status,
    mmb.signed_rpo,
    mmb.rental_agreement_link,
    mmb.rpo_end_date,
    mmb.sales_rep,
    mmb.credit_application,
    mmb.total_monthly_rent,
    mmb.rpo_beginning_date,
    mmb.dealership_or_rental_fleet,
    mmb.gross_profit_margin,
    mmb.total_pdi,
    mmb.rent_contribution,
    mmb.total_freight_charges,
    mmb.ucc_filed,
    mmb.total_ext_warranty_quote,
    mmb.gross_profit,
    mmb.credit_approval,
    mmb.total_t3_charges,
    mmb.rental_invoice_number,
    mmb.rsm_email,
    mmb.full_term_rental_revenue,
    mmb.gm_email,
    mmb.upload_customer_amort_form,
    mmb.signor_email_address,
    mmb.total_base_rental_quote,
    mmb.conversion_price,
    mmb.yard_name,
    mmb.total_eqs_dnet
from fleet_ops_rpo_board_output as mmb
