with insurance_lsd_board_output as (
    {{ generate_monday_table_from_column_map('6829207248') }}
)

select
-- Explicitly name columns so schema changes break this model.

    mmb.item_id,
    mmb.abs_owner,
    mmb.link_to_lsd_asset_management,
    mmb.lsd_designation_date,
    mmb.repair_date,
    mmb.customer_name,
    mmb.lender_contact_information,
    mmb.total_loss,
    mmb.ins_claim_filed,
    mmb.last_action_taken,
    mmb.test_board,
    mmb.rental_contract,
    mmb.reminder_date,
    mmb.repair_invoice,
    mmb.rpp,
    mmb.total_turn_time,
    mmb.special_tag_optional,
    mmb.open_closed,
    mmb.rpp_status_comments,
    mmb.customer_quote_needed,
    mmb.type_of_loss,
    mmb.incident_location,
    mmb.rpp_charge,
    mmb.amount_paid_es_fault,
    mmb.make,
    mmb.closed_date,
    mmb.need_lender_contact,
    mmb.model,
    mmb.rpp_status,
    mmb.amount_due_from_3p,
    mmb.total_loss_mirror,
    mmb.branch_id,
    mmb.link_to_lsd_fleet_ops,
    mmb.customer_quote,
    mmb.lender_lessor,
    mmb.responsible_payer,
    mmb.vendor_name,
    mmb.serial_number,
    mmb.customer_insurance_company,
    mmb.amount_collected,
    mmb.work_order,
    mmb.file_notes,
    mmb.customer_ins_policy_number,
    mmb.branch_name,
    mmb.date_of_incident,
    mmb.assets_owner,
    mmb.will_ins_pay_lender_directly,
    mmb.reported_by,
    mmb.general_manager,
    mmb.asset_year,
    mmb.assigned,
    mmb.confidential_file_notes,
    mmb.fmv_quote,
    mmb.name,
    mmb.report_date,
    mmb.subitems,
    mmb.fmv_quote_needed,
    mmb.documents_and_photos,
    mmb.rental_contract_date,
    mmb.google_drive_link
from insurance_lsd_board_output as mmb
