select
    p.productgroupid as product_group_id,
    p.glcode as gl_code,
    p.name,
    p.description,
    p.documenttext as document_text,
    p.parentid as parent_id,
    p.treelevel as tree_level,
    p.treesequence as tree_sequence,
    p.level1id as level_1_id,
    p.level2id as level_2_id,
    p.level3id as level_3_id,
    p.level4id as level_4_id,
    p.level5id as level_5_id,
    p.nextspecialsuffix as next_special_suffix,
    p.glcodecost as gl_code_cost,
    p.deleted = 1 as is_deleted,
    p.glcodeinventory as gl_code_inventory,
    p._fivetran_deleted,
    p._fivetran_synced
from {{ source('analytics_bt_dbo', 'productgroup') }} as p
