select
    invoicelineid as invoice_line_id,
    vatamount as vat_amount,
    settlementamountincurrency as settlement_amount_in_currency,
    description,
    settlementdiscount as settlement_discount,
    vatamountincurrency as vat_amount_in_currency,
    taxgroupid as tax_group_id,
    vmiruleid as vmi_rule_id,
    branchid as bt_branch_id,
    unitamount as unit_amount,
    perid as per_id,
    totaltaxincurrency as total_tax_in_currency,
    linenumber as line_number,
    totalcost as total_cost,
    quantitycredited as quantity_credited,
    itemnumber as item_number,
    taxcodes as tax_codes,
    totaltax as total_tax,
    deliverynotelineid as delivery_note_line_id,
    orderlineid as order_line_id,
    manualchargeamountincurrencycredited as manual_charge_amount_in_currency_credited,
    datetimecreated as datetime_created,
    internalcosttotalmargin as internal_cost_total_margin,
    linetype as line_type,
    nonsalesamountincurrency as non_sales_amount_in_currency,
    notes,
    totalvmicostincurrency as total_vmi_cost_in_currency,
    settlementamount as settlement_amount,
    salesanalysiscodeid as sales_analysis_code_id,
    totalreportingcost as total_reporting_cost,
    pickingnotelineid as picking_note_line_id,
    nonsalesamount as non_sales_amount,
    unitamountincurrency as unit_amount_in_currency,
    quantity,
    productid::integer as product_id,
    totalamountincurrency as total_amount_in_currency,
    totalamount as total_amount,
    invoiceid as invoice_id,
    exportedtodatawarehouse as exported_to_data_warehouse,
    totalweight as total_weight,
    totalvmicost as total_vmi_cost,
    createdbyid as created_by_id,
    vatrateid as vat_rate_id,
    totalvolume as total_volume,
    totalmargin as total_margin,
    punchcardcouponid as punch_card_coupon_id,
    vmiexchangerate as vmi_exchange_rate,
    _fivetran_deleted,
    _fivetran_synced

from {{ source('analytics_bt_dbo', 'invoiceline') }}
