select
    creditnoteid as credit_note_id,
    settlementdiscount as settlement_discount,
    taxverifiedbyid as tax_verified_by_id,
    nondiscountamount as non_discount_amount,
    daterequired as date_required,
    paymenttermsid as payment_terms_id,
    vehicleid as vehicle_id,
    showeurosoncreditnote as show_euros_on_credit_note,
    customerid as customer_id,
    offlinecreditnotenumber as offline_credit_note_number,
    branchid as bt_branch_id,
    orderid as order_id,
    emailed,
    creditonhold as credit_on_hold,
    correctedusetaxexemptcert as corrected_use_tax_exempt_cert,
    totalcost as total_cost,
    deliveryaddressid as delivery_address_id,
    totalvatamountincurrency as total_vat_amount_in_currency,
    printed,
    internalcosttotalmargin as internal_cost_total_margin,
    lastmodifiedbyid as last_modified_by_id,
    sent,
    taxsettlementamount as tax_settlement_amount,
    correctedtaxareaid as corrected_tax_area_id,
    vehicletypeid as vehicle_type_id,
    cashaccountbalanceamount as cash_account_balance_amount,
    nondiscountamountincurrency as non_discount_amount_in_currency,
    approvedbyid as approved_by_id,
    dispatchapihold as dispatch_api_hold,
    invoiceid as invoice_id,
    wmsrefusedontruckorderid as wms_refused_on_truck_order_id,
    computerid as computer_id,
    deliveryareaid as delivery_area_id,
    totalweight as total_weight,
    ourref as our_ref,
    createdbyid as created_by_id,
    settlementdate as settlement_date,
    imaged,
    contractinvoicing as contract_invoicing,
    totalmargin as total_margin,
    commissiontotalcost as commission_total_cost,
    creditdate as credit_date,
    taxareaid as tax_area_id,
    exchangerate as exchange_rate,
    description,
    invoiceaddressid as invoice_address_id,
    deliveryaddress as delivery_address,
    contractid as contract_id,
    notepadcaseid as notepad_case_id,
    totaltaxincurrency as total_tax_in_currency,
    taxadjustmenttype as tax_adjustment_type,
    journeyid as journey_id,
    edisendinvoice as edi_send_invoice,
    faxed,
    contractinvoicinglineid as contract_invoicing_line_id,
    totaltax as total_tax,
    paidbyid as paid_by_id,
    edidocumentid as edi_document_id,
    yourref as your_ref,
    deleted,
    duedate as due_date,
    datetimecreated as datetime_created,
    nonsalesamountincurrency as non_sales_amount_in_currency,
    notes,
    settlementamount as settlement_amount,
    creditnotenumber as credit_note_number,
    taxusagetypeid as tax_usage_type_id,
    nonsalesamount as non_sales_amount,
    totalvatamount as total_vat_amount,
    arcustomerid as ar_customer_id,
    markedasreturned as marked_as_returned,
    otherflags as other_flags,
    usetaxexemptcertificate as use_tax_exempt_certificate,
    totalamountincurrency as total_amount_in_currency,
    totalamount as total_amount,
    contactid as contact_id,
    datetimelastmodified as datetime_last_modified,
    currencyid as currency_id,
    contact,
    rebill,
    scalegrossweight as scale_gross_weight,
    takenbyid as taken_by_id,
    cashsale as cash_sale,
    invoiceaddress as invoice_address,
    authorizedbyid as authorized_by_id,
    araddressid as ar_address_id,
    datetimereleased as datetime_released,
    releasedbyid as released_by_id,
    outstandingrefund as outstanding_refund,
    reasonid as reason_id,
    datetimeapproved as datetime_approved,
    handling,
    _fivetran_deleted,
    _fivetran_synced

from {{ source('analytics_bt_dbo', 'creditnoteheader') }}
