select
    supplierreturnid as supplier_return_id,
    exchangerate as exchange_rate,
    dateinspected as date_inspected,
    daterequired as date_required,
    totalcostincurrency as total_cost_in_currency,
    datetimecompleted as datetime_completed,
    creditamount as credit_amount,
    branchid as bt_branch_id,
    returnaddress as return_address,
    returnaddressid as return_address_id,
    totalcost as total_cost,
    datereturned as date_returned,
    supplierid as supplier_id,
    journeyid as journey_id,
    headernotes as header_notes,
    purchaseorderid as purchase_order_id,
    supplierreturnnumber as supplier_return_number,
    createdfromcreditnoteid as created_from_credit_note_id,
    returnareaid as return_area_id,
    deleted,
    completednotes as completed_notes,
    datetimecreated as datetime_created,
    lastmodifiedbyid as last_modified_by_id,
    notes,
    returncity as return_city,
    returnednotes as returned_notes,
    otherflags as other_flags,
    reference,
    completedbyid as completed_by_id,
    creditnotenumbers as credit_note_numbers,
    dispatchapihold as dispatch_api_hold,
    datetimelastmodified as datetime_last_modified,
    returntype as return_type,
    inspectionrequired as inspection_required,
    currencyid as currency_id,
    stockreceiptid as stock_receipt_id,
    totalweight as total_weight,
    inspectionnotes as inspection_notes,
    createdbyid as created_by_id,
    postingdate as posting_date,
    returnstatus as return_status,
    completed,
    totalvolume as total_volume,
    reasonid as reason_id,
    _fivetran_deleted,
    _fivetran_synced

from {{ source('analytics_bt_dbo', 'supplierreturnheader') }}
