select
    -- === IDs ===
    branchid as bt_branch_id,
    branchcode as bt_branch_code,
    glcode as gl_code,
    tradingas as trading_as,
    name,
    latitude,
    longitude,
    divisionid as division_id,
    regionid as region_id,
    createdbyid as created_by_id,
    lastmodifiedbyid as last_modified_by_id,
    quickaccountid1 as quick_account_id_1,
    quickaccountid2 as quick_account_id_2,
    quickaccountid3 as quick_account_id_3,
    quickaccountid4 as quick_account_id_4,
    quickaccountid5 as quick_account_id_5,
    i4gomerchantid as i4go_merchant_id,
    epicorpaymentgatewayprivatelabelmerchantid as epicor_payment_gateway_private_label_merchant_id,
    defaultstocklocationid as default_stock_location_id,
    deliveryareaid as delivery_area_id,
    edibranchwmsmessageformatid as edi_branch_wms_message_format_id,
    stockcountreasonid as stock_count_reason_id,
    cashaccountid as cash_account_id,

    defaulttransfervehicleid as default_transfer_vehicle_id,
    defaultvehicletypeid as default_vehicle_type_id,
    facilitycode as facility_code,
    computerid as computer_id,
    taxareaid as tax_area_id,
    udflocationid as udf_location_id,
    bluetarpmerchantid as blue_tarp_merchant_id,

    -- === Dates/Times ===
    edibranchwmsstartdate as edi_branch_wms_start_date,
    datetimecreated as datetime_created,
    datetimelastmodified as datetime_last_modified,
    backorderslastcheckedupto as back_orders_last_checked_up_to,

    -- === Numbers ===
    shift4capturesignaturethresholdamount as shift4_capture_signature_threshold_amount,

    calculatedjobcreditlimitextensionpercentage as calculated_job_credit_limit_extension_percentage,
    maximumavocostandsellprice as maximum_avo_cost_and_sell_price,
    minimumfinancechargeamount as minimum_finance_charge_amount,
    epicorpaymentgatewaycapturesignaturethresholdamount as epicor_payment_gateway_capture_signature_threshold_amount,
    edibranchnextnumber as edi_branch_next_number,

    -- === Booleans / Flags ===
    disableprivatelabelpromocodes as disable_private_label_promo_codes,
    ignoreinternalcost as ignore_internal_cost,
    validaterewardscard as validate_rewards_card,
    sendpreliminaryliennoticewhenjobcreditlimitchanges as send_preliminary_lien_notice_when_job_credit_limit_changes,
    autoassigndeliveryareafromcoordinates as auto_assign_delivery_area_from_coordinates,
    roundcashowing as round_cash_owing,
    multicompanygloffset as multi_company_gl_offset,
    autoapplyfinancialcharges as auto_apply_financial_charges,
    interimrunning as interim_running,
    skipsignaturecaptureduringshift4cardonfiletransactions
        as skip_signature_capture_during_shift4_card_on_file_transactions,
    usesignaturecapturesettingsforcollectnowwhencompletingwmscollectlaterorders
        as use_signature_capture_settings_for_collect_now_when_completing_wms_collect_later_orders,
    deleted = 1 as is_deleted,
    requirecampaignoncustomer as require_campaign_on_customer,
    allowduplicatesupplierproductcodespersupplier as allow_duplicate_supplier_product_codes_per_supplier,
    allowzerovalueinvcredinfinancials as allow_zero_value_inv_cred_in_financials,
    includeinaccountsautomatchstoredprocedure as include_in_accounts_auto_match_stored_procedure,
    autogeneratestatements as auto_generate_statements,
    usecalculatedjobcreditlimit as use_calculated_job_credit_limit,
    enableautomatedblendedbatchsellingoption as enable_automated_blended_batch_selling_option,
    requireusertoacceptsignaturesfromsignaturecapture as require_user_to_accept_signatures_from_signature_capture,
    sendseparateinvoicesforeachjob as send_separate_invoices_for_each_job,
    appendmanufacturedkittoexistingworkorderfromsales as append_manufactured_kit_to_existing_work_order_from_sales,
    autogeneratefinancialcharges as auto_generate_financial_charges,
    udfremittoactive as udf_remitto_active,
    workordersupdatesourceonpurchaseorderchanges as work_orders_update_source_on_purchase_order_changes,
    availableinwebtrack as available_in_web_track,
    showproductsalespopupinkitentry as show_product_sales_popup_in_kit_entry,

    -- === Strings / Other ===
    additionalcostformat as additional_cost_format,
    udfremittocity as udf_remitto_city,
    defaultimportfolder as default_import_folder,
    printer1 as printer_01,
    printer2 as printer_02,
    printer3 as printer_03,
    printer4 as printer_04,
    printer5 as printer_05,
    printer6 as printer_06,
    printer7 as printer_07,
    printer8 as printer_08,
    printer9 as printer_09,
    printer10 as printer_10,
    i4goserialnumber as i4go_serial_number,
    i4gocardsecuritycoderequired as i4go_card_security_code_required,
    i4gostreetaddressprompt as i4go_street_address_prompt,
    epicorpaymentgatewayprivatelabelusername as epicor_payment_gateway_private_label_username,
    epicorpaymentgatewayprivatelabelpassword as epicor_payment_gateway_private_label_password,
    epicorpaymentgatewayprivatelabelprocessor as epicor_payment_gateway_private_label_processor,
    epicorpaymentgatewayprivatelabelbinrange as epicor_payment_gateway_private_label_bin_range,
    telephone1 as telephone_1,
    telephone2 as telephone_2,
    collectlaterformatsetcredit as collect_later_format_set_credit,
    country,
    postcode as post_code,
    site,
    taxconnectcompanycode as tax_connect_company_code,
    defaultordercopyfromoption as default_order_copy_from_option,
    logofile as logo_file,
    signaturecaptureforcollectnoworders as signature_capture_for_collect_now_orders,
    avoformatset as avo_format_set,
    signaturecapturefordirectorders as signature_capture_for_direct_orders,
    pickingnoteformat as picking_note_format,
    bluetarpclientkey as blue_tarp_client_key,
    transferdeliveryformatset as transfer_delivery_format_set,
    excluderestockfromcredittaxcalc as exclude_restock_from_credit_tax_calc,
    i4gopostalcodeprompt as i4go_postal_code_prompt,
    pickingzonemask as picking_zone_mask,
    creditcontroluserids as credit_control_user_ids,
    collectlaterformatsetcash as collect_later_format_set_cash,
    pickingzonesformatnumbers as picking_zones_format_numbers,
    udfremittostate as udf_remitto_state,
    quickaccountlabel1 as quick_account_label_1,
    quickaccountlabel2 as quick_account_label_2,
    quickaccountlabel3 as quick_account_label_3,
    quickaccountlabel4 as quick_account_label_4,
    quickaccountlabel5 as quick_account_label_5,
    countgroupmask as count_group_mask,
    defaultordercopyoption as default_order_copy_option,
    quickshippassword as quick_ship_password,
    specialorderackdocumentformatset as special_order_ack_document_format_set,
    defaultcopytemplateoracceptquotebysectionoption as default_copy_template_or_accept_quote_by_section_option,
    collatejourneysetprintingby as collate_journey_set_printing_by,
    edibranchreference1 as edi_branch_reference_1,
    edibranchreference2 as edi_branch_reference_2,
    collatedocumentprintingby as collate_document_printing_by,
    recordpickingstarted as record_picking_started,
    defaultallowaddressoverride as default_allow_address_override,
    udfllcassignment as udf_llc_assignment,
    i4gocardholdernameprompt as i4go_card_holder_name_prompt,
    deliverynoteformat as delivery_note_format,
    signaturecaptureforcollectlatercashorders as signature_capture_for_collect_later_cash_orders,
    signaturecaptureforcollectlaterorders as signature_capture_for_collect_later_orders,
    city,
    depositreceiptformat as deposit_receipt_format,
    signaturecaptureforreturntobranchcreditnotes as signature_capture_for_return_to_branch_credit_notes,
    deliveryformatsetcredit as delivery_format_set_credit,
    creditlimitcheckhierarchyoption as credit_limit_check_hierarchy_option,
    yardbookrefmask as yard_book_ref_mask,
    collectnowpickingdocumentformatset as collect_now_picking_document_format_set,
    calctaxbasedonbranchtaxarea as calc_tax_based_on_branch_tax_area,
    orderamendprintformatset as order_amend_print_format_set,
    promptforsignaturewhencollectnowordergoesoncreditholdandisnotreleasedimmediately
        as prompt_for_signature_when_collect_now_order_goes_on_credit_hold_and_is_not_released_immediately,
    quickshipusername as quick_ship_username,
    county,
    promptrewardscardonorder as prompt_rewards_card_on_order,
    creditcontroltelephone as credit_control_telephone,
    defaultworksorderallocatesource as default_works_order_allocate_source,
    promptforsignaturewhenchangingwmsordertypetocollectlaternow
        as prompt_for_signature_when_changing_wms_order_type_to_collect_later_now,
    confirmposforspecials as confirm_pos_for_specials,
    defaultformergingnondirectposforwos as default_for_merging_non_direct_pos_for_wos,
    addressvalidationmethod as address_validation_method,
    address1 as address_1,
    address2 as address_2,
    address3 as address_3,
    collectionnoteformat as collection_note_format,
    signaturecapturefordeliveredorders as signature_capture_for_delivered_orders,
    binlocationmask as bin_location_mask,
    udfremittoname as udf_remitto_name,
    defaultordersaletype as default_order_sale_type,
    defaultdaysuntilquoteexpiry as default_days_until_quote_expiry,
    creditcontrolemail as credit_control_email,
    shift4defaulturl as shift4_default_url,
    pickingnoteprinter as picking_note_printer,
    udfremittoaddress1 as udf_remitto_address_1,
    udfremittoaddress2 as udf_remitto_address_2,
    ctiipaddress as cti_ip_address,
    fax,
    defaultwmspickingstatus as default_wms_picking_status,
    udfsubsidiary as udf_subsidiary,
    _fivetran_deleted,
    _fivetran_synced

from {{ source('analytics_bt_dbo', 'branch') }}
