select
    branchid as bt_branch_id,
    length,
    productbatchid as product_batch_id,
    productid as product_id,
    totalstockvaluation as total_stock_valuation,
    collectedstandardselldatetime as collected_standard_sell_datetime,
    transactiontotalpricewithadd as transaction_total_price_with_add,
    sourcetype as source_type,
    transactionunitpricewithadd as transaction_unit_price_with_add,
    deliveredstandardselldatetime as delivered_standard_sell_datetime,
    averagecost as average_cost,
    deliveredsellperid as delivered_sell_per_id,
    directsellperid as direct_sell_per_id,
    averagecostdatetime as average_cost_datetime,
    buystockconversion as buy_stock_conversion,
    lastcostdatetime as last_cost_datetime,
    commissioncost as commission_cost,
    collectedsellperid as collected_sell_per_id,
    internalcostperid as internal_cost_per_id,
    transactionquantity as transaction_quantity,
    userid as user_id,
    standardbuydatetime as standard_buy_datetime,
    standardsell as standard_sell,
    sourcenumber as source_number,
    averagecostwithadd as average_cost_with_add,
    transactionunitprice as transaction_unit_price,
    internalcostdatetime as internal_cost_datetime,
    negativeinventoryadjustment as negative_inventory_adjustment,
    directstandardselldatetime as direct_standard_sell_datetime,
    oldstockactual as old_stock_actual,
    lastcostwithadd as last_cost_with_add,
    sourceid as source_id,
    buyperid as buy_per_id,
    transactiontotalprice as transaction_total_price,
    sellperid as sell_per_id,
    standardselldatetime as standard_sell_datetime,
    standardbuy as standard_buy,
    lastcostperid as last_cost_per_id,
    newstockactual as new_stock_actual,
    deliveredstandardsell as delivered_standard_sell,
    directstandardsell as direct_standard_sell,
    internalcost as internal_cost,
    postingdate as posting_date,
    lastcost as last_cost,
    commissioncostdatetime as commission_cost_datetime,
    collectedstandardsell as collected_standard_sell,
    commissioncostperid as commission_cost_per_id,
    averagecostperid as average_cost_per_id,
    _fivetran_deleted,
    _fivetran_synced

from {{ source('analytics_bt_dbo', 'productprice') }}
