select
    invoiceid as invoice_id,
    settlementamountincurrency as settlement_amount_in_currency,
    settlementdiscount as settlement_discount,
    nondiscountamount as non_discount_amount,
    totalamountineuros as total_amount_in_euros,
    paymenttermsid as payment_terms_id,
    customerid as customer_id,
    branchid as bt_branch_id,
    orderid as order_id,
    emailed,
    totalcost as total_cost,
    totalvatamountincurrency as total_vat_amount_in_currency,
    printed,
    invoicenumber as invoice_number,
    internalcosttotalmargin as internal_cost_total_margin,
    sent,
    taxsettlementamount as tax_settlement_amount,
    groupby as group_by,
    paymentmethodid as payment_method_id,
    nondiscountamountincurrency as non_discount_amount_in_currency,
    approvedbyid as approved_by_id,
    totalweight as total_weight,
    ourref as our_ref,
    createdbyid as created_by_id,
    settlementdate as settlement_date,
    imaged,
    fromdate as from_date,
    totalmargin as total_margin,
    exchangerate as exchange_rate,
    description,
    generatorid as generator_id,
    deliveryaddress as delivery_address,
    invoicestatusid as invoice_status_id,
    totaltaxincurrency as total_tax_in_currency,
    faxed,
    edidocumentid as edi_document_id,
    paidbyid as paid_by_id,
    totaltax as total_tax,
    yourref as your_ref,
    invoicedate as invoice_date,
    deleted,
    datetimecommissionpaid as datetime_commission_paid,
    datetimecreated as datetime_created,
    duedate as due_date,
    nonsalesamountincurrency as non_sales_amount_in_currency,
    notes,
    settlementamount as settlement_amount,
    nonsalesamount as non_sales_amount,
    totalvatamount as total_vat_amount,
    totalamountincurrency as total_amount_in_currency,
    totalamount as total_amount,
    currencyid as currency_id,
    contact,
    cashsale as cash_sale,
    invoiceaddress as invoice_address,
    datetimereleased as datetime_released,
    releasedbyid as released_by_id,
    deliverynoteid as delivery_note_id,
    todate as to_date,
    datetimeapproved as datetime_approved,
    _fivetran_deleted,
    _fivetran_synced

from {{ source('analytics_bt_dbo', 'invoiceheader') }}
