select
    s.stockreceiptcostid as stock_receipt_cost_id,
    s.expectedcostprice as expected_cost_price,
    s.fullyinvoiced as fully_invoiced,
    s.pendingactions as pending_actions,
    s.totalcostprice as total_cost_price,
    s.unitcostprice as unit_cost_price,
    s.datereceived as date_received,
    s.branchid as bt_branch_id,
    s.orderid as order_id,
    s.perid as per_id,
    s.stockreceiptlineid as stock_receipt_line_id,
    s.quantitycredited as quantity_credited,
    s.orderlineid as order_line_id,
    s.purchaseorderid as purchase_order_id,
    s.enteredinadvance as entered_in_advance,
    s.packid as pack_id,
    s.totalmanualcost as total_manual_cost,
    s.quantityinvoiced as quantity_invoiced,
    s.worksorderid as works_order_id,
    s.creditnoteid as credit_note_id,
    s.productid as product_id,
    s.stockadjustmentid as stock_adjustment_id,
    s.stockquantityreceived as stock_quantity_received,
    s.worksorderlineid as works_order_line_id,
    s.stockreceiptid as stock_receipt_id,
    s.inputperid as input_per_id,
    s.totaladditionalcost as total_additional_cost,
    s.customerreturnlineid as customer_return_line_id,
    s.customerreturnid as customer_return_id,
    s.stockquantityused as stock_quantity_used,
    s.quantityused as quantity_used,
    s.quantityreceived as quantity_received,
    s.purchaseorderlineid as purchase_order_line_id,
    s.creditnotelineid as credit_note_line_id,
    s._fivetran_deleted,
    s._fivetran_synced
from {{ source('analytics_bt_dbo', 'stockreceiptcost') }} as s
