select
    invoiceid as invoice_id,
    invoicelineid as invoice_line_id,
    taxsequence as tax_sequence,
    taxareaid as tax_area_id,
    taxgroupid as tax_group_id,
    applysettlementdiscount as apply_settlement_discount,
    taxrateid as tax_rate_id,
    basedonamountincurrency as based_on_amount_in_currency,
    taxamount as tax_amount,
    taxcode as tax_code,
    taxjurisdictiontype as tax_jurisdiction_type,
    taxjurisdictionregion as tax_jurisdiction_region,
    basedonamount as based_on_amount,
    taxjurisdictionname as tax_jurisdiction_name,
    calculation,
    promotiontaxholidayid as promotion_tax_holiday_id,
    taxusagetypeid as tax_usage_type_id,
    promotionid as promotion_id,
    rate,
    customertaxexemptionid as customer_tax_exemption_id,
    taxname as tax_name,
    othertaxid as other_tax_id,
    taxid as tax_id,
    rounding,
    taxontax as tax_on_tax,
    taxjurisdictioncode as tax_jurisdiction_code,
    documentcode as document_code,
    taxamountincurrency as tax_amount_in_currency,
    _fivetran_deleted,
    _fivetran_synced

from {{ source('analytics_bt_dbo', 'invoicetax') }}
