select
    stockadjustmentid as stock_adjustment_id,
    productbatchid as product_batch_id,
    adjuststockonorder as adjust_stock_on_order,
    adjuststockreserved as adjust_stock_reserved,
    adjuststocksuspense as adjust_stock_suspense,
    adjuststockthirdpartymemoqty as adjust_stock_third_party_memo_qty,
    adjuststocksuspensememoqty as adjust_stock_suspense_memo_qty,
    adjuststockduememoqty as adjust_stock_due_memo_qty,
    packid as pack_id,
    pieces,
    stockadjustmentheaderid as stock_adjustment_header_id,
    stockbatchid as stock_batch_id,
    adjuststockawaitingprocessnotavailable as adjust_stock_awaiting_process_not_available,
    adjuststockthirdparty as adjust_stock_third_party,
    adjuststockawaitingprocessnotavailablememoqty as adjust_stock_awaiting_process_not_available_memo_qty,
    adjuststockonordermemoqty as adjust_stock_on_order_memo_qty,
    adjuststockreservedmemoqty as adjust_stock_reserved_memo_qty,
    adjuststockactualmemoqty as adjust_stock_actual_memo_qty,
    adjuststockawaitingprocess as adjust_stock_awaiting_process,
    length,
    dontupdateacp as dont_update_acp,
    overridetransactiontype as override_transaction_type,
    reelid as reel_id,
    adjuststockawaitingprocessmemoqty as adjust_stock_awaiting_process_memo_qty,
    adjuststockallocatedmemoqty as adjust_stock_allocated_memo_qty,
    adjuststockdue as adjust_stock_due,
    branchstockactualbeforeadjustment as branch_stock_actual_before_adjustment,
    adjuststockactual as adjust_stock_actual,
    adjuststockallocated as adjust_stock_allocated,
    _fivetran_deleted,
    _fivetran_synced
from {{ source('analytics_bt_dbo', 'stockadjustment') }}
