select
    m.manualorderlinetypeid as manual_order_line_type_id,
    m.allowsettlementdiscount as allow_settlement_discount,
    m.allowonsupplierreturn as allow_on_supplier_return,
    m.allowdescriptionoverrideonsales as allow_description_override_on_sales,
    m.name,
    m.allowonpurchaseorder as allow_on_purchase_order,
    m.defaultcostprice as default_cost_price,
    m.glcodepayable as gl_code_payable,
    m.glcodecost as gl_code_cost,
    m.regionid as region_id,
    m.lastmodifiedbyid as last_modified_by_id,
    m.defaultsellprice as default_sell_price,
    m.removecostonposting as remove_cost_on_posting,
    m.lastmodifieddatetime as last_modified_datetime,
    m.overridesalesanalysiscode as override_sales_analysis_code,
    m.paymentmethodid as payment_method_id,
    m.applytoallstockreceiptswhenfixedamount as apply_to_all_stock_receipts_when_fixed_amount,
    m.giftcardterms as gift_card_terms,
    m.proratecostoverstocklines as prorate_cost_over_stock_lines,
    m.cashaccountbalance as cash_account_balance,
    m.divisionid as division_id,
    m.acevisagiftcard as ace_visa_gift_card,
    m.defaultglcode as default_gl_code,
    m.allowcodeoverrideonsales as allow_code_override_on_sales,
    m.costprorateby as cost_prorate_by,
    m.includeinmargincalculation as include_in_margin_calculation,
    m.productgroupid as product_group_id,
    m.automaticitemcharge as automatic_item_charge,
    m.removesettlementdiscountoncost as remove_settlement_discount_on_cost,
    m.automaticlinecharge as automatic_line_charge,
    m.installedsalesinvoicing as installed_sales_invoicing,
    m.defaulttaxgroupid as default_tax_group_id,
    m.defaultdescription as default_description,
    m.costweightperid as cost_weight_per_id,
    m.allowcostoverrideonsales as allow_cost_override_on_sales,
    m.deleted,
    m.allowontransfer as allow_on_transfer,
    m.postvariancetomoltid as post_variance_to_molt_id,
    m.salesanalysiscodeid as sales_analysis_code_id,
    m.promotiontype as promotion_type,
    m.nonsalesamount as non_sales_amount,
    m.allowtaxgroupoverrideonsales as allow_tax_group_override_on_sales,
    m.allowonsalesorder as allow_on_sales_order,
    m.availabletoallusers as available_to_all_users,
    m.productid as product_id,
    m.automaticuplift as automatic_uplift,
    m.giftcard as gift_card,
    m.glcodesales as gl_code_sales,
    m.defaultcode as default_code,
    m.allowpriceoverrideonsales as allow_price_override_on_sales,
    m.delivery,
    m.costvaluetype as cost_value_type,
    m._fivetran_deleted,
    m._fivetran_synced
from {{ source('analytics_bt_dbo', 'manualorderlinetype') }} as m
