-- Basic entries without retained earnings (3900)
select
    gle.pk_gl_detail_id,
    gle.fk_gl_entry_id,
    gle.fk_gl_resolve_id,
    gle.entry_date,
    gle.entry_date as raw_entry_date,
    gle.account_number,
    gle.account_name,
    gle.fk_account_id,
    gle.account_normal_balance,
    gle.account_type,
    gle.department_id,
    gle.market_id,
    gle.market_name,
    gle.department_name,
    gle.entity_id,
    gle.entity_name,
    gle.extended_entity_name,
    gle.raw_amount::number(38, 2) as raw_amount,
    gle.entry_description,
    gle.journal_title,
    gle.debit_credit_sign,
    gle.debit_credit,
    gle.net_amount::number(38, 2) as net_amount,
    gle.positive_revenue_sign,
    iff(
        gle.account_type = 'balancesheet',
        iff(gle.account_normal_balance = 'debit', -1, 1),
        1
    ) as balance_sheet_sign,
    gle.applied_sign * balance_sheet_sign as applied_sign,
    (
        gle.raw_amount
        * gle.debit_credit_sign
        * gle.positive_revenue_sign
        * balance_sheet_sign
    )::number(38, 2) as amount,
    gle.raw_entry_amount::number(38, 2) as raw_entry_amount,
    gle.net_entry_amount::number(38, 2) as net_entry_amount,
    (
        gle.raw_entry_amount * gle.debit_credit_sign * gle.positive_revenue_sign
        * balance_sheet_sign
    )::number(38, 2
    ) as entry_amount,
    gle.exchange_rate,
    gle.currency_code,
    gle.base_currency_code,
    gle.exchange_rate_date,
    gle.fk_expense_type_id,
    gle.expense_type,
    gle.expense_category,
    gle.intacct_module,
    gle.journal_type,
    gle.extended_journal_type,
    gle.date_reversed,
    gle.fk_reversed_from_journal_id,
    gle.fk_journal_id,
    gle.journal_transaction_number,
    gle.line_number,
    gle.document,
    gle.url_journal,
    gle.fk_subledger_header_id,
    gle.fk_subledger_line_id,
    gle.fk_ud_loan_id,
    gle.gl_dim_transaction_identifier,
    gle.asset_id,
    gle.gl_dim_asset_id,
    gle.fk_created_by_user_id,
    gle.created_by_username,
    gle.created_by_name,
    gle.fk_updated_by_user_id,
    gle.updated_by_username,
    gle.updated_by_name,
    gle.entry_state,
    gle.journal_state,
    gle.is_statistical,
    gle.combined_state,
    true as is_true_entry,
    gle.date_created,
    gle.date_updated,
    gle._es_update_timestamp,
    'int_gl_detail' as source
from {{ ref('int_gl_detail') }} as gle
where
    gle.combined_state = 'Posted'
    and not gle.is_statistical
    -- Covered in retained earnings section
    and gle.account_number not in ('3900')

union all

-- Get net income to sub in for retained earnings entries. These are added to the balance but not created as entries 
-- by Sage
select
    md5(
        last_day(gle.entry_date) || '-' || gle.account_number || '-'
        || coalesce(gle.department_id, 'no department') || '-'
        || coalesce(gle.entity_id, 'no entity')
    ) as pk_gl_detail_id,
    null as fk_gl_entry_id,
    null as fk_gl_resolve_id,
    last_day(gle.entry_date) as entry_date,
    last_day(gle.entry_date) as raw_entry_date,
    gla.account_number,
    gla.account_name,
    gla.pk_account_id as fk_account_id,
    gla.account_normal_balance,
    gla.account_type,
    gle.department_id,
    gle.market_id,
    gle.market_name,
    gle.department_name,
    gle.entity_id,
    gle.entity_name,
    gle.extended_entity_name,
    abs(sum(gle.net_amount))::number(38,2) as raw_amount,
    null as entry_description,
    'Net Income for Retained Earnings, '
    || left(last_day(gle.entry_date)::text, 7)
    || ', generated by BA' as journal_title,
    iff(sum(gle.net_amount)::number(38, 2) >= 0, 1, -1) as debit_credit_sign,
    iff(sum(gle.net_amount)::number(38, 2) >= 0, 'debit', 'credit')
        as debit_credit,
    sum(gle.net_amount)::number(38, 2) as net_amount,
    gle.positive_revenue_sign,
    iff(
        gla.account_type = 'balancesheet',
        iff(gla.account_normal_balance = 'debit', -1, 1),
        1
    ) as balance_sheet_sign,
    iff(sum(gle.net_amount) >= 0, 1, -1)
    * gle.positive_revenue_sign
    * balance_sheet_sign as applied_sign,
    sum(gle.amount)::number(38, 2) as amount,
    null as raw_entry_amount,
    null as net_entry_amount,
    null as entry_amount,
    1 as exchange_rate,
    'USD' as currency_code,
    'USD' as base_currency_code,
    last_day(gle.entry_date) as exchange_rate_date,
    null as fk_expense_type_id,
    null as expense_type,
    null as expense_category,
    '2.GL' as intacct_module,
    'BA' as journal_type,
    'Generated by BA, non-Sage' as extended_journal_type,
    null as date_reversed,
    null as fk_reversed_from_journal_id,
    null as fk_journal_id,
    null as journal_transaction_number,
    null as line_number,
    null as document,
    null as url_journal,
    null as fk_subledger_header_id,
    null as fk_subledger_line_id,
    null as fk_ud_loan_id,
    null as gl_dim_transaction_identifier,
    null as asset_id,
    null as gl_dim_asset_id,
    null as fk_created_by_user_id,
    null as created_by_username,
    null as created_by_name,
    null as fk_updated_by_user_id,
    null as updated_by_username,
    null as updated_by_name,
    'Posted' as entry_state,
    'Posted' as journal_state,
    false as is_statistical,
    'Posted' as combined_state,
    false as is_true_entry,
    max(gle.date_created) as date_created,
    max(gle.date_updated) as date_updated,
    current_timestamp()::timestamp_tz as _es_update_timestamp,
    'net income for retained earnings' as source
from {{ ref('int_gl_detail') }} as gle
    inner join {{ ref('stg_analytics_intacct__gl_account') }} as gla
        on '3900' = gla.account_number
where
    gle.combined_state = 'Posted'
    and not gle.is_statistical
    and gle.account_type = 'incomestatement'
group by
    md5(
        last_day(gle.entry_date) || '-' || gle.account_number || '-'
        || coalesce(gle.department_id, 'no department') || '-'
        || coalesce(gle.entity_id, 'no entity')
    ), null, null, last_day(gle.entry_date
    ), last_day(gle.entry_date
    ),
    gla.account_number,
    gla.account_name,
    gla.pk_account_id,
    gla.account_normal_balance,
    gla.account_type,
    gle.department_id,
    gle.market_id,
    gle.market_name,
    gle.department_name,
    gle.entity_id,
    gle.entity_name,
    gle.extended_entity_name, null,
    'Net Income for Retained Earnings, '
    || left(last_day(gle.entry_date)::text, 7)
    || ', generated by BA', gle.positive_revenue_sign,
    iff(
        gla.account_type = 'balancesheet',
        iff(gla.account_normal_balance = 'debit', -1, 1),
        1
    ),
    last_day(gle.entry_date), current_timestamp()::timestamp_tz

union all

-- Back date retained earnings entries so we can add up to the correct balance
select
    gle.pk_gl_detail_id,
    gle.fk_gl_entry_id,
    gle.fk_gl_resolve_id,
    add_months(gle.entry_date, -1) as entry_date,
    gle.entry_date as raw_entry_date,
    gle.account_number,
    gle.account_name,
    gle.fk_account_id,
    gle.account_normal_balance,
    gle.account_type,
    gle.department_id,
    gle.market_id,
    gle.market_name,
    gle.department_name,
    gle.entity_id,
    gle.entity_name,
    gle.extended_entity_name,
    gle.raw_amount::number(38, 2) as raw_amount,
    gle.entry_description,
    gle.journal_title,
    gle.debit_credit_sign,
    gle.debit_credit,
    gle.net_amount::number(38, 2) as net_amount,
    gle.positive_revenue_sign,
    iff(
        gle.account_type = 'balancesheet',
        iff(gle.account_normal_balance = 'debit', -1, 1),
        1
    ) as balance_sheet_sign,
    gle.applied_sign * balance_sheet_sign as applied_sign,
    (
        gle.raw_amount
        * gle.debit_credit_sign
        * gle.positive_revenue_sign
        * balance_sheet_sign
    )::number(38, 2) as amount,
    gle.raw_entry_amount::number(38, 2) as raw_entry_amount,
    gle.net_entry_amount::number(38, 2) as net_entry_amount,
    (gle.entry_amount * balance_sheet_sign)::number(38, 2) as entry_amount,
    gle.exchange_rate,
    gle.currency_code,
    gle.base_currency_code,
    gle.exchange_rate_date,
    gle.fk_expense_type_id,
    gle.expense_type,
    gle.expense_category,
    gle.intacct_module,
    gle.journal_type,
    gle.extended_journal_type,
    gle.date_reversed,
    gle.fk_reversed_from_journal_id,
    gle.fk_journal_id,
    gle.journal_transaction_number,
    gle.line_number,
    gle.document,
    gle.url_journal,
    gle.fk_subledger_header_id,
    gle.fk_subledger_line_id,
    gle.fk_ud_loan_id,
    gle.gl_dim_transaction_identifier,
    gle.asset_id,
    gle.gl_dim_asset_id,
    gle.fk_created_by_user_id,
    gle.created_by_username,
    gle.created_by_name,
    gle.fk_updated_by_user_id,
    gle.updated_by_username,
    gle.updated_by_name,
    gle.entry_state,
    gle.journal_state,
    gle.is_statistical,
    gle.combined_state,
    true as is_true_entry,
    gle.date_created,
    gle.date_updated,
    gle._es_update_timestamp,
    'Retained earnings entries' as source
from {{ ref('int_gl_detail') }} as gle
where
    gle.combined_state = 'Posted'
    and not gle.is_statistical
    and gle.account_number = '3900' -- Covered in retained earnings section

order by entry_date, account_number, entity_id, department_id, fk_expense_type_id
