select
    line_item_id,
    rate_tier_id,
    ITL_REP_RATE_TIER_ID,
    grace_rate_tier_id,
    business_segment_id,
    order_created_date,
    line_item_type_id,
    billing_approved_date,
    amount,
    price_per_unit,
    number_of_units,
    deal_floor,
    floor_rate,
    benchmark_rate,
    book_rate,
    grace_floor_rate,
    grace_benchmark_rate,
    grace_online_rate as grace_book_rate,
    pnd_tier3,
    pnd_tier2,
    pnd_tier1,
    coalesce(grace_floor_rate is not null and grace_book_rate is not null, false) as grace_period_flag,
    coalesce(deal_floor is not null, false) as deal_floor_flag,
    _es_update_timestamp
from {{ source('fleet_optimization_gold', 'v_fact_rate_achievement') }}
