select
    c.id,
    c.account_balance,
    c.balance,
    c.created,
    c.currency,
    c.address_city,
    c.address_country,
    c.address_line_1,
    c.address_line_2,
    c.address_postal_code,
    c.address_state,
    c.name,
    c.bank_account_id,
    c.source_id,
    c.default_card_id,
    c.delinquent,
    c.description,
    c.email,
    c.phone,
    c.invoice_prefix,
    c.invoice_settings_default_payment_method,
    c.invoice_settings_footer,
    c.livemode,
    c.metadata,
    c.shipping_address_city,
    c.shipping_address_country,
    c.shipping_address_line_1,
    c.shipping_address_line_2,
    c.shipping_address_postal_code,
    c.shipping_address_state,
    c.shipping_carrier,
    c.shipping_name,
    c.shipping_phone,
    c.shipping_tracking_number,
    c.tax_info_tax_id,
    c.tax_info_type,
    c.tax_exempt,
    c.tax_info_verification_status,
    c.tax_info_verification_verified_name,
    c.is_deleted,
    c._fivetran_synced,
    c.metadata:"id" as metadata__id,
    c.metadata:"customer_name" as metadata__customer_name,
    c.metadata:"email" as metadata__email,
    c.metadata:"return_location" as metadata__return_location,
    c.metadata:"total_insurances" as metadata__total_insurances,
    c.metadata:"total_rack_rate" as metadata__total_rack_rate,
    c.metadata:"pick_up_location" as metadata__pick_up_location,
    c.metadata:"brand" as metadata__brand,
    c.metadata:"return_date" as metadata__return_date,
    c.metadata:"total_taxes" as metadata__total_taxes,
    c.metadata:"vehicle" as metadata__vehicle,
    c.metadata:"phone" as metadata__phone,
    c.metadata:"pick_up_date" as metadata__pick_up_date,
    c.metadata:"prefixed_id" as metadata__prefixed_id,
    c.metadata:"total_extras" as metadata__total_extras,
    c.metadata:"transaction_id" as metadata__transaction_id,
    c.metadata:"transaction_uuid" as metadata__transaction_uuid,
    c.metadata:"total_price" as metadata__total_price,
    c.metadata:"total_revenue" as metadata__total_revenue
from {{ source('analytics_stripe_vehicle_solutions', 'customer') }} as c
