select
    t.id,
    t.created_at,
    t.platform_id,
    t.platform,
    t.stripe_payment_intent_id,
    t.category,
    t.reference,
    t.status,
    t.captured_amount / 100 as captured_amount, -- convert from cents to dollars. use this field for calculations
    t.refunded_amount / 100 as refunded_amount,
    t.type,
    t.external_id,
    t.updated_at,
    t.stripe_charge_id,
    t.cost / 100 as cost,
    t.stripe_reserve_applied_payment_intent_id,
    t.description,
    t.label,
    t.allow_discount,
    t.discount_amount / 100 as discount_amount,
    t.tax_code,
    t.addon_id,
    t.additional_id,
    t.discount_id,
    t.initiated_at,
    t.associated_transaction_id,
    t.number_of_days,
    t.user_id,
    t.effective_date,
    t.avalara_line_id,
    t.fee_id,
    t.reimbursement_id,
    t.charge_amount,
    t.charge_quantity,
    t.release_date,
    t.card_last_4,
    t._fivetran_deleted,
    t._fivetran_synced
from {{ source('analytics_vsg_postgres__public', 'transactions') }} as t
