---
version: 2
models:
  - name: stg_es_warehouse_inventory__provider_part_numbers
    description: Model for es_warehouse.inventory.provider_part_numbers
    columns:
      - name: provider_part_number_id
        description: ""
        data_tests:
          - not_null
          - unique
      - name: provider_id
        description: ""
      - name: part_number
        description: ""
      - name: date_created
        description: ""
      - name: date_updated
        description: ""
      - name: _es_update_timestamp
        description: "{{ doc('_es_update_timestamp') }}"
