SELECT
    ecd1m.employee_id::int as employee_id,
    ecd1m.first_name,
    ecd1m.last_name,
    ecd1m.work_email,
    ecd1m.employee_type,
    ecd1m.employee_status,
    ecd1m.date_hired,
    ecd1m.date_rehired,
    ecd1m.employee_title,
    ecd1m.location,
    ecd1m.default_cost_centers_full_path,
    ecd1m.direct_manager_employee_id::int as direct_manager_employee_id,
    ecd1m.direct_manager_name,
    ecd1m.work_phone,
    ecd1m.date_terminated,
    ecd1m.nickname,
    ecd1m.market_id::int as market_id,
    ecd1m.ee_state,
    ecd1m.doc_uname,
    ecd1m.tax_location,
    ecd1m.pay_calc,
    ecd1m.hires,
    ecd1m.rehires,
    ecd1m.terminations,
    ecd1m.headcount,
    ecd1m.greenhouse_application_id,
    ecd1m.disc_code,
    ecd1m.position_effective_date,
    ecd1m._es_update_timestamp
FROM {{ source('analytics_payroll', 'ee_company_directory_12_month') }} as ecd1m
qualify row_number() over (partition by employee_id, date_trunc('day', _es_update_timestamp) order by _es_update_timestamp desc) = 1