view: semaphore_wokb_integration_v2 {
  derived_table: {
    sql:
WITH cte_wo AS (
SELECT
    wo.asset_id,
    wo.work_order_id,
    wo.date_created as date_of_semaphore,
    wo.date_completed,
    wo.work_order_status_name,
    wo.description,
    wo.billing_notes,
    wo.solution,
    mk."NAME" as market,
    'awc' as awc_flag
FROM
    es_warehouse.work_orders.work_orders wo
LEFT JOIN es_warehouse.public.markets mk on
    wo.branch_id = mk.market_id
WHERE
    wo.asset_id IN (
    SELECT
        PK_ID_JSON:asset_id
    FROM
        data_science.public.data_metrics
    WHERE
        DATA_SOURCE = 'awc')
    AND wo.description LIKE '%work order generated by data science%'
)
, cte_wo_details AS (
select
    cte_wo.asset_id,
    PARAMETERS:work_order_id AS work_order_id,
    ca.date_created,
    user_id,
    username,
    first_name || ' ' || last_name || ' [' || email_address || ']' AS FullName,
    command,
    PARAMETERS
from
    es_warehouse.public.command_audit ca
join es_warehouse.public.users
        USING(user_id)
join cte_wo on
    PARAMETERS:work_order_id = cte_wo.work_order_id
where
    ca.date_created > '2/28/2021'
)
--, wo_info_collated as (
--  select
--  distinct
--    asset_id,
--    work_order_id,
--    date_created as date_of_semaphore
--  FROM cte_wo_details;
--)
, work_order_id_cte as (
  select
    asset_id,
    work_order_id,
    date_created,
    date_updated,
    datediff(day, cte_wo.date_of_semaphore, work_orders.date_created) as days_around_awc
--    case
--      when cte_wo.work_order_id = work_orders.work_order_id then 0
--      else datediff(day, cte_wo.date_of_semaphore, work_orders.date_created)
--    end as days_around_awc
  from es_warehouse.work_orders.work_orders
  join cte_wo using (asset_id)
  where work_orders.date_created between
    -- Lower bound on timestamp comes first
    dateadd(day, -60, cte_wo.date_of_semaphore)
    -- Upper bound on timestamp comes second
    and dateadd(day, 60, cte_wo.date_of_semaphore)
)
, work_order_parsed as (
  select
    work_order_id_cte.asset_id,
    work_order_id_cte.days_around_awc,
    work_order_notes.work_order_id,
    work_order_id_cte.date_created,
    work_order_notes.note
--    ccc.ccc_id,
--    ccc.complaint,
--    ccc.cause,
--    ccc.correction
  from es_warehouse.work_orders.work_order_notes
  join work_order_id_cte using (work_order_id)
  -- Currently remove wokb until the notes are parsed again.
  --join data_science.wokb.ccc using (work_order_note_id)
)
, dtc_cte as (
  select
    asset_id,
    listagg('SPN: ' || spn || ' - Count: ' || times_seen, '; ') as dtc_code_list
  from (
    select
      asset_id,
      suspect_parameter_number as spn,
      --listagg(suspect_parameter_number, ', ') as dtc_code_list
      count(suspect_parameter_number) as times_seen
    from es_warehouse.public.tracking_diagnostic_codes
    join cte_wo using (asset_id)
    where tracking_diagnostic_codes.report_timestamp
      between dateadd(day, -60, cte_wo.date_of_semaphore)
      and dateadd(day, 60, cte_wo.date_of_semaphore)
    and suspect_parameter_number in (select distinct spn from es_warehouse.public.spn)
    group by asset_id, spn
    order by asset_id, spn::numeric asc
  )
  group by asset_id
)
select
  work_order_parsed.asset_id,
  work_order_parsed.days_around_awc as days_spread,
  work_order_parsed.work_order_id,
  work_order_parsed.date_created as work_order_date_created,
  work_order_parsed.note,
--  work_order_parsed.ccc_id,
--  work_order_parsed.complaint,
--  work_order_parsed.cause,
--  work_order_parsed.correction,
  dtc_cte.dtc_code_list
  --dtc_cte.report_timestamp as dtc_report_timestamp
from work_order_parsed
left join dtc_cte on (work_order_parsed.asset_id = dtc_cte.asset_id)
order by asset_id, days_spread


  ;;# # You can specify the table name if it's different from the view name:
  # sql_table_name: my_schema_name.tester ;;
  #
  # # Define your dimensions and measures here, like this:
  # dimension: user_id {
  #   description: "Unique ID for each user that has ordered"
  #   type: number
  #   sql: ${TABLE}.user_id ;;
  # }
  #
  # dimension: lifetime_orders {
  #   description: "The total number of orders for each user"
  #   type: number
  #   sql: ${TABLE}.lifetime_orders ;;
  # }
  #
  # dimension_group: most_recent_purchase {
  #   description: "The date when each user last ordered"
  #   type: time
  #   timeframes: [date, week, month, year]
  #   sql: ${TABLE}.most_recent_purchase_at ;;
  # }
  #
  # measure: total_lifetime_orders {
  #   description: "Use this for counting lifetime orders across many users"
  #   type: sum
  #   sql: ${lifetime_orders} ;;
  # }
}

  dimension: asset_id {}
  dimension: days_spread {}
  dimension: work_order_date_created {}
  dimension: note {}
#  dimension: date_of_semaphore {}
#  dimension: cause {}
#  dimension: complaint {}
#  dimension: correction {}
  dimension: dtc_code_list {}

}
# view: semaphore_wokb_integration_0_2 {
#   # Or, you could make this view a derived table, like this:
#   derived_table: {
#     sql: SELECT
#         user_id as user_id
#         , COUNT(*) as lifetime_orders
#         , MAX(orders.created_at) as most_recent_purchase_at
#       FROM orders
#       GROUP BY user_id
#       ;;
#   }
#
#   # Define your dimensions and measures here, like this:
#   dimension: user_id {
#     description: "Unique ID for each user that has ordered"
#     type: number
#     sql: ${TABLE}.user_id ;;
#   }
#
#   dimension: lifetime_orders {
#     description: "The total number of orders for each user"
#     type: number
#     sql: ${TABLE}.lifetime_orders ;;
#   }
#
#   dimension_group: most_recent_purchase {
#     description: "The date when each user last ordered"
#     type: time
#     timeframes: [date, week, month, year]
#     sql: ${TABLE}.most_recent_purchase_at ;;
#   }
#
#   measure: total_lifetime_orders {
#     description: "Use this for counting lifetime orders across many users"
#     type: sum
#     sql: ${lifetime_orders} ;;
#   }
# }
