with source as (
  select * 
  from {{ source('quotes_quotes','quote') }}
),

renamed as (
  select
    _es_update_timestamp,
    _es_load_timestamp,

    id                            as quote_id,
    has_pdf,
    location_description,
    company_id,
    delivery_fee,
    delivery_type_id,
    rsp_company_id,
    po_id                         as po_id,
    contact_email,
    created_date                  as quote_created_at,
    contact_id,
    state_specific_tax_percentage,
    last_modified_by,
    start_date,
    sales_tax_percentage,
    rpp_id,
    order_created_date            as order_created_at,
    branch_id,
    new_company_name,
    delivery_type_name,
    contact_name,
    company_name,
    rpp_name,
    deliver_to,
    pickup_fee,
    is_tax_exempt,
    last_modified_date,
    contact_phone,
    ordered_by,
    end_date,
    order_id,
    sales_rep_id,
    location_id,
    quote_number,
    order_created_by,
    expiry_date,
    ordered_by_phone,
    created_by,
    delivery_mileage,
    po_name,
    ordered_by_email,
    site_contact_name,
    site_contact_phone,
    deliver_to_address,
    deliver_to_latitude,
    deliver_to_longitude,
    project_type,
    new_location_info,
    missed_rental_reason_other,
    missed_rental_reason,
    escalation_id,
    request_source_id,
    duplicated_from_quote_id,
    customer_id,
    phase_name,
    job_id,
    job_name,
    phase_id,
    scope_of_work
  from source
)

select * from renamed
