view: 3g_sunset {

  derived_table: {
    sql:
SELECT DISTINCT * FROM (
WITH CONFIG AS (
SELECT T.DEVICE_SERIAL, C.FIELD_VALUE AS APN_VALUE
FROM ES_WAREHOUSE.TRACKERS.CURRENT_MOREY_DEVICE_FIELD_CONFIGURATIONS AS C
INNER JOIN ES_WAREHOUSE.TRACKERS.TRACKERS AS T ON T.TRACKER_ID = C.TRACKER_ID
WHERE C.CONFIGURATION_EID = '426'
),
ASSET_CUSTOMER AS (
SELECT EA.ASSET_ID
, EA.RENTAL_ID
, C.COMPANY_ID AS CUSTOMER_ID
, C.NAME  AS CUSTOMER_NAME
, MAX(EA.START_DATE) OVER (PARTITION BY EA.ASSET_ID) AS MAX_START_DATE
FROM ES_WAREHOUSE.PUBLIC.EQUIPMENT_ASSIGNMENTS EA
  LEFT JOIN ES_WAREHOUSE.PUBLIC.RENTALS AS R ON EA.RENTAL_ID = R.RENTAL_ID
  LEFT JOIN ES_WAREHOUSE.PUBLIC.ORDERS AS O ON R.ORDER_ID = O.ORDER_ID
  LEFT JOIN ES_WAREHOUSE.PUBLIC.USERS AS U ON O.USER_ID = U.USER_ID
  LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C ON U.COMPANY_ID = C.COMPANY_ID
WHERE EA.END_DATE IS NULL
AND EA.START_DATE <= CURRENT_TIMESTAMP
QUALIFY MAX_START_DATE = EA.START_DATE
 AND MAX(EA.EQUIPMENT_ASSIGNMENT_ID) OVER (PARTITION BY EA.ASSET_ID) = EA.EQUIPMENT_ASSIGNMENT_ID
)
,
UNPLUGGED AS (
SELECT  ASSET_ID, VALUE AS UNPLUGGED
FROM ES_WAREHOUSE.PUBLIC.ASSET_STATUS_KEY_VALUES
WHERE LOWER(NAME) = 'unplugged'
    ),
RSSI AS (
SELECT  ASSET_ID, VALUE AS RSSI
FROM ES_WAREHOUSE.PUBLIC.ASSET_STATUS_KEY_VALUES
WHERE LOWER(NAME) = 'rssi'
    ),
OOL_TIMESTAMP AS (
SELECT  ASSET_ID, VALUE_TIMESTAMP AS OOL_TIMESTAMP
FROM ES_WAREHOUSE.PUBLIC.ASSET_STATUS_KEY_VALUES
WHERE LOWER(NAME) = 'out_of_lock'),
GPS AS (
SELECT ASSET_ID, st_y(to_geography(value)) AS LATITUDE,st_x(to_geography(value)) AS LONGITUDE
FROM ES_WAREHOUSE.PUBLIC.ASSET_STATUS_KEY_VALUES AS ASKV
WHERE LOWER(NAME) = 'location'
),
ASSET_RENTAL_STATUS AS (
SELECT ASSET_ID, VALUE AS RENTAL_STATUS
FROM ES_WAREHOUSE.PUBLIC.ASSET_STATUS_KEY_VALUES AS ASKV
WHERE LOWER(NAME) = 'asset_inventory_status'
),
LAST_CHECKIN AS (
SELECT ASSET_ID, VALUE AS LAST_CHECKIN_TIMESTAMP
FROM ES_WAREHOUSE.PUBLIC.ASSET_STATUS_KEY_VALUES AS ASKV
WHERE LOWER(NAME) = 'last_checkin_timestamp'
),
BATTERY AS (
SELECT ASSET_ID, VALUE AS BATTERY_VOLTAGE
FROM ES_WAREHOUSE.PUBLIC.ASSET_STATUS_KEY_VALUES AS ASKV
WHERE LOWER(NAME) = 'battery_voltage'
),
OWN_PROGRAM_ASSETS AS (
SELECT DISTINCT ASSET_ID, 'Yes' AS OWN_PROGRAM
FROM ES_WAREHOUSE.PUBLIC.V_PAYOUT_PROGRAMS
WHERE (END_DATE >= CURRENT_TIMESTAMP OR END_DATE IS NULL)
),
ASSET_ADDRESS AS (
SELECT  ASSET_ID, VALUE AS ADDRESS
FROM ES_WAREHOUSE.PUBLIC.ASSET_STATUS_KEY_VALUES
WHERE LOWER(NAME) = 'street'),
ASSET_CITY AS (
SELECT ASSET_ID, VALUE AS CITY
FROM ES_WAREHOUSE.PUBLIC.ASSET_STATUS_KEY_VALUES
WHERE LOWER(NAME) = 'city'),
ASSET_STATE AS (
SELECT ASKV.ASSET_ID, ST.NAME AS STATE
FROM ES_WAREHOUSE.PUBLIC.ASSET_STATUS_KEY_VALUES AS ASKV
LEFT JOIN ES_WAREHOUSE.PUBLIC.STATES AS ST ON ASKV.VALUE = ST.STATE_ID
WHERE LOWER(ASKV.NAME) = 'state_id'),
ASSET_ZIPCODE AS (
SELECT  ASSET_ID, VALUE AS ZIPCODE
FROM ES_WAREHOUSE.PUBLIC.ASSET_STATUS_KEY_VALUES
WHERE LOWER(NAME) = 'zip_code'),
MOREY_MAX_DATE_COMPLETED AS (
SELECT T.DEVICE_SERIAL, MAX(MFUR.DATE_COMPLETED) AS COMPLETED_UPDATE_TIMESTAMP
FROM ES_WAREHOUSE.PUBLIC.TRACKERS AS T
LEFT JOIN ES_WAREHOUSE.PUBLIC.TRACKERS_MAPPING AS TMAP ON T.TRACKER_ID = TMAP.ESDB_TRACKER_ID
LEFT JOIN ES_WAREHOUSE.TRACKERS.MOREY_FIRMWARE_UPDATE_REQUESTS AS MFUR
ON TMAP.TRACKER_TRACKER_ID = MFUR.TRACKER_ID
GROUP BY  T.DEVICE_SERIAL
)
SELECT DISTINCT T.DEVICE_SERIAL AS TRACKER_SERIAL, T.TRACKER_ID, A.ASSET_ID, T.COMPANY_ID AS OWNER_COMPANY_ID, C.NAME AS OWNER_COMPANY_NAME, A.MAKE, A.MODEL, AA.CATEGORY,
CASE WHEN TT.NAME = 'MC-4+' AND MPT.DEVICE_TYPE IS NULL THEN 'MC-4+/KORE'
WHEN TT.NAME = 'MC-4+' AND MPT.DEVICE_TYPE IS NOT NULL THEN 'MC-4+/TWILIO'
ELSE TT.NAME END AS TRACKER_TYPE,
TRK.FIRMWARE_VERSION AS TRACKER_FIRMWARE_VERSION,
TRK.MODEM_FIRMWARE_VERSION,
A.INVENTORY_BRANCH_ID, MKT.NAME AS INVENTORY_BRANCH, OOL.OOL_TIMESTAMP , UNP.UNPLUGGED AS UNPLUGGED,GPS.LATITUDE, GPS.LONGITUDE,
TSC.LATEST_GPS_FIX_TIMESTAMP,ARS.RENTAL_STATUS, LC.LAST_CHECKIN_TIMESTAMP, B.BATTERY_VOLTAGE,
IFF(OWN.OWN_PROGRAM IS NULL,'No','Yes') as OWN_PROGRAM,
ADR.ADDRESS||','||CITY.CITY||','||ST.STATE||','||Z.ZIPCODE AS LOCATION,
CASE WHEN TT.NAME IN ('MC-3','MC-4+','MC-4','FJ2500LA','FJ2500LS','MCX 101','GL500M','GL520M') THEN 'High Risk'
--WHEN TT.NAME = 'MC-4+' AND HRD.SERIAL_NUMBER IS NULL THEN 'Low Risk'
WHEN TT.NAME = 'TTU 1220' AND HRD.SERIAL_NUMBER IS NOT NULL THEN 'High Risk'
WHEN TT.NAME = 'TTU 1220' AND HRD.SERIAL_NUMBER IS NULL THEN 'Low Risk'
WHEN TT.NAME IN ('TTU 2830','LMU 3030','TTU 07') AND DATEDIFF(MONTH, OOL.OOL_TIMESTAMP::DATE, CURRENT_TIMESTAMP::date) > 6 THEN 'Low Risk'
WHEN TT.NAME IN ('TTU 2830','LMU 3030','TTU 07') AND HRD.SERIAL_NUMBER IS NOT NULL  AND DATEDIFF(MONTH, OOL.OOL_TIMESTAMP::DATE, CURRENT_TIMESTAMP::date) <= 6 THEN 'High Risk'
WHEN TT.NAME IN ('TTU 2830','LMU 3030','TTU 07') AND HRD.SERIAL_NUMBER IS NOT NULL AND OOL.OOL_TIMESTAMP IS NULL THEN 'High Risk'
ELSE 'N/A' END AS RISK_LEVEL,
CASE WHEN TT.NAME IN ('MC-3','MC-4','MC-4+') AND TRK.FIRMWARE_VERSION IN ('2.1.7','2.1.10','2.1.11','2.1.12') AND TRK.MODEM_FIRMWARE_VERSION IN ('30.55,A01.00','_30.55_ENG0106,A01.00') THEN 'Completed'
WHEN TT.NAME IN ('TTU 2830','LMU 3030','TTU 07','TTU 1220') AND SPLIT_PART(TRK.PART_INFO,':',0) NOT LIKE '%H%' AND TRK.FIRMWARE_VERSION IS NOT NULL AND TRK.MODEM_FIRMWARE_VERSION IS NOT NULL THEN 'Completed'
WHEN TT.NAME IN ('MC-3','MC-4','MC-4+') AND ((TRK.FIRMWARE_VERSION NOT IN ('2.1.7','2.1.10','2.1.11','2.1.12') OR TRK.FIRMWARE_VERSION IS NULL) OR TRK.MODEM_FIRMWARE_VERSION NOT IN ('30.55,A01.00','_30.55_ENG0106,A01.00') OR  TRK.MODEM_FIRMWARE_VERSION IS NULL) THEN 'Not Completed'
WHEN TT.NAME IN ('TTU 2830','LMU 3030','TTU 07') AND SPLIT_PART(TRK.PART_INFO,':',0) LIKE '%H%' THEN 'Not Completed'
WHEN TT.NAME IN ('TTU 2830','LMU 3030','TTU 07') AND SPLIT_PART(TRK.PART_INFO,':',0) IS NULL THEN 'Not Completed'
WHEN TT.NAME = 'TTU 1220' AND TRK.FIRMWARE_VERSION IS NOT NULL AND TRK.MODEM_FIRMWARE_VERSION IS NOT NULL THEN 'Completed'
WHEN TT.NAME = 'TTU 1220' AND TRK.FIRMWARE_VERSION IS NULL OR TRK.MODEM_FIRMWARE_VERSION IS  NULL THEN 'Not Completed'
WHEN TT.NAME IN ('FJ2500LA','FJ2500LS','MCX 101','GL500M','GL520M') THEN 'N/A'
ELSE 'EXCLUDE' END AS UPDATE_STATUS, SPLIT_PART(TRK.PART_INFO,':',0) AS PART_INFO,
CASE WHEN A.ASSET_ID IS NULL THEN 'NOT ASSIGNED' WHEN OWN.OWN_PROGRAM = 'Yes' THEN 'OWN_PROGRAM' WHEN T.COMPANY_ID IN (1854,1855,155,420,61036) THEN 'ES' ELSE 'CUSTOMER' END AS OWNER_GROUP,
CASE WHEN OOL.OOL_TIMESTAMP IS NOT NULL AND UNP.UNPLUGGED = 'true' THEN 'Out of Lock/Unplugged'
WHEN OOL.OOL_TIMESTAMP IS NOT NULL AND UNP.UNPLUGGED = 'false' THEN 'Out of Lock'
WHEN T.TRACKER_ID IS NULL THEN 'Untracked' ELSE 'Working' END AS TRACKER_STATE, ACUST.CUSTOMER_ID, ACUST.CUSTOMER_NAME, K.KEYPAD_ID, K.SERIAL_NUMBER AS KEYPAD_SERIAL,
MDD.COMPLETED_UPDATE_TIMESTAMP, MFURS.status AS MOREY_FIRMWARE_UPDATE_REQUEST_STATUS, RSSI.RSSI AS RSSI, CONFIG.APN_VALUE AS APN_VALUE, TRK.ICCID
FROM ES_WAREHOUSE.PUBLIC.TRACKERS AS T
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS AS A ON T.TRACKER_ID = A.TRACKER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS_AGGREGATE AS AA ON A.ASSET_ID = AA.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C ON T.COMPANY_ID = C.COMPANY_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.TRACKER_TYPES AS TT ON T.TRACKER_TYPE_ID = TT.TRACKER_TYPE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.MARKETS AS MKT ON A.INVENTORY_BRANCH_ID = MKT.MARKET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.TRACKERS_MAPPING AS TMAP ON T.DEVICE_SERIAL = TMAP.TRACKER_DEVICE_SERIAL
LEFT JOIN ES_WAREHOUSE.TRACKERS.TRACKERS AS TRK ON TMAP.TRACKER_TRACKER_ID = TRK.TRACKER_ID
LEFT JOIN OOL_TIMESTAMP AS OOL ON OOL.ASSET_ID = A.ASSET_ID
LEFT JOIN UNPLUGGED AS UNP ON A.ASSET_ID = UNP.ASSET_ID
LEFT JOIN GPS AS GPS ON A.ASSET_ID = GPS.ASSET_ID
LEFT JOIN ASSET_RENTAL_STATUS AS ARS ON A.ASSET_ID = ARS.ASSET_ID
LEFT JOIN LAST_CHECKIN AS LC ON A.ASSET_ID = LC.ASSET_ID
LEFT JOIN BATTERY AS B ON A.ASSET_ID = B.ASSET_ID
LEFT JOIN OWN_PROGRAM_ASSETS AS OWN ON A.ASSET_ID = OWN.ASSET_ID
LEFT JOIN ASSET_ADDRESS AS ADR ON A.ASSET_ID = ADR.ASSET_ID
LEFT JOIN ASSET_CITY AS CITY ON A.ASSET_ID = CITY.ASSET_ID
LEFT JOIN ASSET_STATE AS ST ON A.ASSET_ID = ST.ASSET_ID
LEFT JOIN ASSET_ZIPCODE AS Z ON A.ASSET_ID = Z.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.TRACKER_STATE_CACHE AS TSC on T.TRACKER_ID = TSC.TRACKER_ID
LEFT JOIN ASSET_CUSTOMER AS ACUST ON A.ASSET_ID = ACUST.ASSET_ID
LEFT JOIN RSSI AS RSSI ON A.ASSET_ID = RSSI.ASSET_ID
LEFT JOIN ANALYTICS.PUBLIC.HIGH_RISK_DEVICES AS HRD ON T.DEVICE_SERIAL = HRD.SERIAL_NUMBER
LEFT JOIN ES_WAREHOUSE.TRACKERS.KEYPADS AS K ON TMAP.TRACKER_TRACKER_ID = K.TRACKER_ID
LEFT JOIN MOREY_MAX_DATE_COMPLETED AS MDD ON T.DEVICE_SERIAL = MDD.DEVICE_SERIAL
LEFT JOIN ES_WAREHOUSE.TRACKERS.MOREY_FIRMWARE_UPDATE_REQUESTS AS MFUR
ON (TMAP.TRACKER_TRACKER_ID = MFUR.TRACKER_ID) AND (MFUR.DATE_COMPLETED = MDD.COMPLETED_UPDATE_TIMESTAMP)
LEFT JOIN ES_WAREHOUSE.TRACKERS.MOREY_FIRMWARE_UPDATE_REQUEST_STATUSES  AS MFURS
ON MFURS.MOREY_FIRMWARE_UPDATE_REQUEST_STATUS_ID = MFUR.MOREY_FIRMWARE_UPDATE_REQUEST_STATUS_ID
LEFT JOIN CONFIG AS CONFIG ON T.DEVICE_SERIAL = CONFIG.DEVICE_SERIAL
LEFT JOIN ANALYTICS.PUBLIC.MC4_PLUS_TWILIO AS MPT ON T.DEVICE_SERIAL = MPT.MOREY_SN
WHERE T.DEVICE_SERIAL NOT IN ('OEMDD-BT-NODE-484352030','OEMDD-BT-NODE-484352063','OEMDD-BT-NODE-485361003','0','OEMDD-BT-NODE-534813018')
AND T.TRACKER_ID NOT IN  (
127312,
123336,
127526,
124288,
157974,
169252,
124414,
123785,
119546,
127549,
147824,
161377,
153021,
143224,
140884,
128446,
124075,
124294,
116900,
113008,
61657,
61929,
78513,
113380,
62306,
75405,
65990,
71673,
75926,
77957,
66804,
61655,
62340,
61818,
61827,
62757,
61653,
61652,
62756,
77436,
59657,
68307,
71868,
68318,
76047,
54386,
45522,
54155,
55557,
41640,
53121,
52375,
107626,
105618,
106878,
107504,
106835,
607,
13637,
3955,
1462,
1465,
1467,
1469,
1470,
1473,
1475,
1477,
1479,
1484,
1486,
1488,
1490,
1493,
1495,
1498,
1734,
648,
17599,
13628,
13632,
110387,
113504,
117585,
119213,
113149,
116912,
119273,
117611,
117495,
113409,
110999,
117573,
117575,
123540,
138562,
147859,
147830,
169259,
124290
)
AND LEFT(T.DEVICE_SERIAL,3) <> '453'
AND T.DEVICE_SERIAL IS NOT NULL
AND LEFT(T.DEVICE_SERIAL,1) <> '-'
AND T.DEVICE_SERIAL <> ''
AND T.TRACKER_ID IS NOT NULL
AND (A.COMPANY_ID <> 155 OR A.COMPANY_ID IS NULL)
AND left(t.DEVICE_SERIAL,2) <> '35'
)
                           ;;
  }

  dimension: tracker_serial {
    type: string
    sql: ${TABLE}.TRACKER_SERIAL ;;
  }

  dimension: tracker_id {
    type: number
    sql: ${TABLE}.TRACKER_ID ;;
  }

  dimension: asset_id {
    type: string
    sql: ${TABLE}.ASSET_ID ;;
  }

  dimension: owner_company_id {
    type: number
    sql: ${TABLE}.OWNER_COMPANY_ID ;;
  }

  dimension: owner_company_name {
    type: string
    sql: ${TABLE}.OWNER_COMPANY_NAME ;;
  }

  dimension: make {
    type: string
    sql: ${TABLE}.MAKE ;;
  }

  dimension: model {
    type: string
    sql: ${TABLE}.MODEL ;;
  }

  dimension: category {
    type: string
    sql: ${TABLE}.CATEGORY ;;
  }

  dimension: tracker_type {
    type: string
    sql: ${TABLE}.TRACKER_TYPE ;;
  }

  dimension: tracker_firmware_version {
    type: string
    sql: ${TABLE}.TRACKER_FIRMWARE_VERSION ;;
  }

  dimension: modem_firmware_version {
    type: string
    sql: ${TABLE}.MODEM_FIRMWARE_VERSION ;;
  }

  dimension: inventory_branch_id {
    type: number
    sql: ${TABLE}.INVENTORY_BRANCH_ID ;;
  }

  dimension: inventory_branch {
    type: string
    sql: ${TABLE}.INVENTORY_BRANCH ;;
  }

  dimension: ool_timestamp {
    type: date_time
    sql: ${TABLE}.OOL_TIMESTAMP ;;
  }

  dimension: unplugged {
    type: string
    sql: ${TABLE}.UNPLUGGED ;;
  }

  dimension: latitude {
    type: string
    sql: ${TABLE}.LATITUDE ;;
  }

  dimension: longitude {
    type: string
    sql: ${TABLE}.LONGITUDE ;;
  }

  dimension: gps_coordinates {
    type:  location
    sql_latitude: ${latitude} ;;
    sql_longitude: ${longitude} ;;
  }

  dimension: latest_gps_fix_timestamp {
    type: date_time
    sql: ${TABLE}.LATEST_GPS_FIX_TIMESTAMP ;;
  }

  dimension: rental_status {
    type: string
    sql: ${TABLE}.RENTAL_STATUS ;;
  }

  dimension: last_checkin_timestamp {
    type: string
    sql: ${TABLE}.LAST_CHECKIN_TIMESTAMP ;;
  }

  dimension: asset_battery {
    type: string
    sql: ${TABLE}.BATTERY_VOLTAGE ;;
  }

  dimension: iccid {
    type: string
    sql: ${TABLE}.ICCID ;;
  }

  dimension: own_program {
    type: string
    sql: ${TABLE}.OWN_PROGRAM ;;
  }

  dimension: location {
    type: string
    sql: ${TABLE}.LOCATION ;;
  }

  dimension: risk_level {
    type: string
    sql: ${TABLE}.RISK_LEVEL ;;
  }

  dimension: rssi {
    type: string
    sql: ${TABLE}.RSSI ;;
  }

  dimension: update_status {
    type: string
    sql: ${TABLE}.UPDATE_STATUS ;;
  }

  dimension: part_info {
    type: string
    sql: ${TABLE}.PART_INFO ;;
  }

  dimension: owner_group {
    type: string
    sql: ${TABLE}.OWNER_GROUP  ;;
  }

  dimension: tracker_state {
    type: string
    sql: ${TABLE}.TRACKER_STATE ;;
  }

  dimension: customer_id {
    type: number
    sql: ${TABLE}.CUSTOMER_ID ;;
  }

  dimension: keypad_id {
    type: string
    sql: ${TABLE}.KEYPAD_ID ;;
  }

  dimension: keypad_serial {
    type: string
    sql: ${TABLE}.KEYPAD_SERIAL ;;
  }

  dimension: customer_name {
    type: string
    sql:CASE WHEN ${TABLE}.CUSTOMER_NAME IS NULL THEN 'NOT ON RENT' ELSE ${TABLE}.CUSTOMER_NAME END  ;;
  }

  dimension: completed_update_timestamp {
    type: date_time
    sql: ${TABLE}.COMPLETED_UPDATE_TIMESTAMP ;;
  }

  dimension: morey_firmware_update_request_status {
    type: string
    sql: ${TABLE}.MOREY_FIRMWARE_UPDATE_REQUEST_STATUS ;;
  }

  dimension: apn_value {
    type: string
    sql: ${TABLE}.APN_VALUE ;;
  }

  measure: update_completed_count {
    type: sum
    sql: case when ${update_status} = 'Completed' then 1 else 0 end  ;;
  }

  measure: update_not_completed {
    type: sum
    sql: case when ${update_status} = 'Not Completed' then 1 else 0 end  ;;
  }

  }
