view: d365_item_qty_chg_n90 {

  derived_table: {
    sql:
    -- SUM CHANGE BY DATE RANGE 30-90
SELECT
  QTY_CHG_N90,
  PART_ID,
  ITEM_NAME
FROM
(WITH QTY_CHG AS (
SELECT
    PART_ID
    , QTY
    , ITEM_NAME
    , CASE
        WHEN DATEDIFF(DAY, DATE_PHYSICAL, GETDATE()) < 30 THEN '0-30'
        WHEN DATEDIFF(DAY, DATE_PHYSICAL, GETDATE()) < 90 THEN '30-90'
        ELSE '90+'
    END AS DATE_PHYSICAL_RANGE
FROM
(SELECT
    IT.ITEMID AS PART_ID
    , CPST.NAME AS PART_DESCRIPTION
    , CAST(IT.DATEPHYSICAL AS DATE) AS DATE_PHYSICAL
    , IT.QTY AS QTY
    , IT.QTY * IT.COSTAMOUNTPOSTED * -1 AS COST_CHG
    , ITA.NAMEALIAS AS ITEM_NAME
FROM
    ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.CUSTPACKINGSLIPTRANS CPST
LEFT JOIN ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.INVENTTRANSORIGIN ITO
    ON CPST.INVENTTRANSID = ITO.INVENTTRANSID
LEFT JOIN ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.INVENTTRANS IT
    ON ITO.RECID = IT.INVENTTRANSORIGIN AND CPST.PACKINGSLIPID = IT.PACKINGSLIPID
LEFT JOIN ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.INVENTDIM ID
    ON IT.INVENTDIMID = ID.INVENTDIMID
LEFT JOIN ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.CUSTPACKINGSLIPJOUR CPSJ
    ON CPST.PACKINGSLIPID = CPSJ.PACKINGSLIPID
LEFT JOIN ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.WHSSHIPMENTTABLE WHSSHIP
    ON WHSSHIP.ORDERNUM = ITO.REFERENCEID
LEFT JOIN ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.SALESTABLE SALESHEADER
    ON CPST.SALESID = SALESHEADER.SALESID
LEFT JOIN ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.CUSTTABLE CT
    ON CT.ACCOUNTNUM = CPSJ.ORDERACCOUNT
LEFT JOIN ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.INVENTTABLE ITA
    ON ITA.ITEMID = IT.ITEMID
--WHERE
    --ID.INVENT_SERIAL_ID IS NOT NULL
     --ND CPST.SALES_ID ='SOv001061'
    --AND CT.ESADMIN_ID_CUSTOM = 22926
ORDER BY WHSSHIP.SHIPMENTID DESC
)
)
SELECT
    SUM(QTY) AS QTY_CHG_N90
    , PART_ID
    , ITEM_NAME
FROM
    QTY_CHG
WHERE
    DATE_PHYSICAL_RANGE = '30-90' OR DATE_PHYSICAL_RANGE = '0-30'
GROUP BY
    PART_ID, ITEM_NAME
ORDER BY
    PART_ID)


      ;;
  }

  dimension: QTY_CHG_N90 {
    type: number
    sql: ${TABLE}.QTY_CHG_N90 ;;
  }

  dimension: PART_ID {
    type: string
    sql: ${TABLE}.PART_ID ;;
  }

  dimension: ITEM_NAME {
    type: string
    sql: ${TABLE}.ITEM_NAME ;;
  }

}
