view: d365_inventory_valuation_by_location {

  derived_table: {
    sql:
      --SUMMARY
SELECT
*
FROM
(
WITH DISTINCT_ONHAND AS (
SELECT DISTINCT
    IT.RECID, IT.ITEMID AS ITEM_ID, ID.WMSLOCATIONID AS W_MSLOCATION_ID, ITA.NAMEALIAS AS NAME_ALIAS, ITA.WFSOLDPARTNUMBER AS OLD_PART_NUMBER, RECENT_NAME.PRODUCT_NAME AS PRODUCT_NAME, ID.INVENTLOCATIONID AS INVENT_LOCATION_ID, IT.STATUSRECEIPT AS STATUS_RECEIPT, IT.STATUSISSUE AS STATUS_ISSUE, IT.QTY AS QTY, WMSL.LOCPROFILEID AS LOC_PROFILE_ID, ID.INVENTSTATUSID AS INVENT_STATUS, ITA.PRODUCTLIFECYCLESTATEID AS PRODUCT_LIFECYCLE_STATE
FROM
    ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.INVENTTRANS IT
LEFT JOIN
    ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.INVENTDIM ID
    ON IT.INVENTDIMID = ID.INVENTDIMID AND IT.DATAAREAID = ID.DATAAREAID
LEFT JOIN
    ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.WMSLOCATION WMSL
    ON WMSL.WMSLOCATIONID = ID.WMSLOCATIONID
LEFT JOIN
    ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.INVENTTABLE ITA
    ON ITA.ITEMID = IT.ITEMID
LEFT JOIN
    (SELECT SL.ITEMID AS ITEM_ID, SL.NAME AS PRODUCT_NAME, NEW.MAX_DATE AS MAX_DATE
    FROM ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.SALESLINE AS SL
    INNER JOIN (SELECT
    ITEMID
    ,
    MAX(SHIPPINGDATEREQUESTED) AS MAX_DATE
    FROM
    ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.SALESLINE
    GROUP BY ITEMID) AS NEW
    ON SL.ITEMID = NEW.ITEMID AND SL.SHIPPINGDATEREQUESTED = NEW.MAX_DATE
    GROUP BY SL.ITEMID, SL.NAME, NEW.MAX_DATE) RECENT_NAME
    ON RECENT_NAME.ITEM_ID = ITA.ITEMID
WHERE
    ID.INVENTSITEID = 'KCK'
)
SELECT
    CONCAT(DISTINCT_ONHAND.ITEM_ID, '-', DISTINCT_ONHAND.W_MSLOCATION_ID) AS VALUE_REPORT_ID,
    DISTINCT_ONHAND.ITEM_ID AS D365_ITEM_ID,
    DISTINCT_ONHAND.NAME_ALIAS AS ITEM_NAME,
    DISTINCT_ONHAND.OLD_PART_NUMBER AS OLD_PART_NUMBER,
    DISTINCT_ONHAND.PRODUCT_NAME AS PRODUCT_NAME,
    DISTINCT_ONHAND.INVENT_STATUS AS INVENT_STATUS,
    DISTINCT_ONHAND.PRODUCT_LIFECYCLE_STATE AS PRODUCT_LIFECYCLE_STATE,
    SUM(CASE
          WHEN DISTINCT_ONHAND.STATUS_RECEIPT = 3 THEN DISTINCT_ONHAND.QTY
          WHEN DISTINCT_ONHAND.STATUS_RECEIPT = 2 THEN DISTINCT_ONHAND.QTY
          WHEN DISTINCT_ONHAND.STATUS_RECEIPT = 1 THEN DISTINCT_ONHAND.QTY
          WHEN DISTINCT_ONHAND.STATUS_ISSUE = 3 THEN DISTINCT_ONHAND.QTY
          WHEN DISTINCT_ONHAND.STATUS_ISSUE = 2 THEN DISTINCT_ONHAND.QTY
          WHEN DISTINCT_ONHAND.STATUS_ISSUE = 1 THEN DISTINCT_ONHAND.QTY
          ELSE 0 END) AS ON_HAND_QUANTITY,
    DISTINCT_ONHAND.INVENT_LOCATION_ID AS INVENT_LOCATION_ID,
    DISTINCT_ONHAND.W_MSLOCATION_ID AS BIN_LOCATION,
    itr2.MVA_PRICE AS UNIT_COST
FROM DISTINCT_ONHAND
LEFT JOIN
    (SELECT
        ITEMID AS ITEM_ID,
        MVAPRICE AS MVA_PRICE
    FROM
        (SELECT
            AVG(DIV0NULL(COSTSUM,QTYSUM)) AS MVAPRICE,
            ITEMID
        FROM
            (SELECT
                *
            FROM
                (
                SELECT
                    SUM(PL.PURCHPRICE * PURCHQTY) AS COSTSUM,
                    SUM(PL.PURCHQTY) AS QTYSUM,
                    PL.ITEMID AS ITEMID
                FROM
                    ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.PURCHLINE PL
                LEFT JOIN
                    ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.PURCHTABLE PT
                        ON PT.PURCHID = PL.PURCHID
                WHERE
                    PT.PURCHSTATUS = 3
                    AND PL.PURCHSTATUS = 3
                    AND PL.ITEMID IS NOT NULL
                GROUP BY
                    PL.ITEMID
                ORDER BY
                    PL.ITEMID)
                UNION ALL
                (
                SELECT
                    COSTSUM,
                    QTYSUM,
                    to_varchar(ITEM_ID) AS ITEMID
                FROM
                    (
                    -- SELECT
                    --     SUM(COSTAMOUNTPHYSICAL*-1) AS COSTSUM,
                    --     SUM(QTY*-1) AS QTYSUM,
                    --     ITL.ITEM_ID AS ITEM_ID
                    -- FROM
                    --     ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.INVENTTRANSFERLINE ITL
                    -- LEFT JOIN
                    --     ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.INVENTTRANSFERTABLE ITT
                    --     ON ITL.TRANSFER_ID = ITT.TRANSFER_ID
                    -- LEFT JOIN
                    --     ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.INVENTTRANSORIGIN ITO
                    --     ON ITO.INVENTTRANSID = ITL.INVENT_TRANS_ID
                    -- LEFT JOIN
                    --     ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.INVENTTRANS IT
                    --     ON IT.INVENTTRANSORIGIN = ITO.RECID
                    -- WHERE
                    --     ITT.TRANSFER_STATUS = 2
                    -- GROUP BY
                    --     ITL.ITEM_ID
                    --     )
                    -- UNION ALL
                    -- (
                    SELECT
                        SUM(IJTR.COSTAMOUNT*-1) AS COSTSUM,
                        SUM(IJTR.QTY*-1) AS QTYSUM,
                        IJTR.ITEMID AS ITEM_ID
                    FROM
                        ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.INVENTJOURNALTRANS IJTR
                    LEFT JOIN
                        ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.INVENTJOURNALTABLE IJTA
                    ON IJTR.JOURNALID = IJTA.JOURNALID
                    WHERE IJTR.QTY < 0
                    GROUP BY
                        IJTR.ITEMID
                        )
                    )
                )
        GROUP BY ITEMID
        )
    ) itr2
ON
    itr2.ITEM_ID = DISTINCT_ONHAND.ITEM_ID
WHERE
    DISTINCT_ONHAND.LOC_PROFILE_ID <> 'User'
    AND DISTINCT_ONHAND.W_MSLOCATION_ID <> 'DONOTUSE'
GROUP BY
    DISTINCT_ONHAND.ITEM_ID, DISTINCT_ONHAND.INVENT_LOCATION_ID, DISTINCT_ONHAND.W_MSLOCATION_ID, itr2.MVA_PRICE, DISTINCT_ONHAND.NAME_ALIAS, DISTINCT_ONHAND.OLD_PART_NUMBER, DISTINCT_ONHAND.PRODUCT_NAME, DISTINCT_ONHAND.PRODUCT_LIFECYCLE_STATE, DISTINCT_ONHAND.INVENT_STATUS
)
GROUP BY
    VALUE_REPORT_ID, D365_ITEM_ID, ITEM_NAME, OLD_PART_NUMBER, PRODUCT_NAME, ON_HAND_QUANTITY, INVENT_LOCATION_ID, BIN_LOCATION, UNIT_COST, INVENT_STATUS, PRODUCT_LIFECYCLE_STATE
     ;;
  }

  dimension: VALUE_REPORT_ID {
    type:  string
    sql: ${TABLE}.VALUE_REPORT_ID  ;;
    primary_key: yes
  }

  dimension: D365_ITEM_ID {
    type: string
    sql: ${TABLE}.D365_ITEM_ID ;;
  }

  dimension: ITEM_NAME {
    type: string
    sql: ${TABLE}.ITEM_NAME ;;
  }

  dimension: OLD_PART_NUMBER {
    type: string
    sql: ${TABLE}.OLD_PART_NUMBER;; }


  measure: ON_HAND_QUANTITY  {
    type: sum
    sql: ${TABLE}.ON_HAND_QUANTITY  ;;
  }

  dimension: INVENT_LOCATION_ID {
    type: string
    sql: ${TABLE}.INVENT_LOCATION_ID ;;
  }

  dimension: BIN_LOCATION {
    type: string
    sql: ${TABLE}.BIN_LOCATION ;;
  }

  dimension: UNIT_COST {
    type: number
    sql: ${TABLE}.UNIT_COST ;;
  }

  dimension: PRODUCT_NAME {
    type: string
    sql: ${TABLE}.PRODUCT_NAME ;;
  }

  dimension: INVENT_STATUS {
    type: string
    sql: ${TABLE}.INVENT_STATUS ;;
  }

  dimension: PRODUCT_LIFECYCLE_STATE {
    type: string
    sql: ${TABLE}.PRODUCT_LIFECYCLE_STATE ;;
  }
}
