view: d365_open_order_totals_kck {
 derived_table: {
  sql:
      --SUMMARY
SELECT * FROM (
WITH DISTINCT_PURCH AS (
    SELECT
        PURCH_LINE.RECID
        ,
        PURCH_LINE.ITEMID AS D365_ITEM_ID
        ,
        PURCH_LINE.QTYORDERED AS ORDER_QTY
        ,
        PURCH_LINE.PURCHSTATUS
        ,
        PURCH_LINE.PURCHID
        ,
        PURCH_LINE.LINENUMBER
        ,
        PURCH_TABLE.INVENTLOCATIONID
    FROM
        ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.PURCHLINE PURCH_LINE
    LEFT JOIN
        ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.PURCHTABLE PURCH_TABLE
        ON PURCH_TABLE.PURCHID = PURCH_LINE.PURCHID
    WHERE
        PURCH_LINE.PURCHSTATUS = 1
        AND PURCH_TABLE.INVENTLOCATIONID = 'KCK'
        AND PURCH_LINE.ITEMID IS NOT NULL
    ORDER BY
        D365_ITEM_ID
)
SELECT
    DISTINCT_PURCH.D365_ITEM_ID AS D365_ITEM_ID
    ,
    SUM(DISTINCT_PURCH.ORDER_QTY) AS SUM_ON_ORDER_QTY
    -- PURCH_TABLE.PURCH_STATUS
FROM
    DISTINCT_PURCH
GROUP BY
    DISTINCT_PURCH.D365_ITEM_ID
ORDER BY
    D365_ITEM_ID
);;
}

dimension: D365_ITEM_ID {
  type: string
  sql: ${TABLE}.D365_ITEM_ID ;;
  primary_key: yes
}

measure: SUM_ON_ORDER_QTY  {
  type: sum
  sql: ${TABLE}.SUM_ON_ORDER_QTY  ;;
}

}
