view: kore_sims_iccids {
 derived_table: {
  sql:

SELECT ICCID, CASE WHEN TRACKER_ID = 0 THEN 'No Tracker Found' ELSE TRACKER_ID END AS TRACKER_ID, DEVICE_SERIAL, ASSET_ID, MAKE, MODEL, COMPANY_NAME, OWNERSHIP, TRACKER, DEVICE_TYPE, LAST_CHECK_IN, D365_PHYSICAL_DATE, DATE_INSTALLED, DATE_UNINSTALLED FROM (
WITH TRACK2 AS (
SELECT
    ICCID,
    TO_VARCHAR(CASE
        WHEN LINK IS NULL THEN TO_VARCHAR('0')
        WHEN LINK IS NOT NULL THEN TO_VARCHAR(TRACKER_ID)
    END) AS TRACKER_ID
    , IS_ACTIVE
    , DEVICE_SERIAL
    , DEVICE_TYPE
FROM
(
WITH TRACK AS (
WITH TCOM_TO_ATA AS (
SELECT
    TRY_CAST(TCOM.device_serial AS VARCHAR) AS DEVICE_SERIAL
    ,
    TCOM.is_active
    ,
    TO_VARCHAR(TCOM.iccid) as ICCID
    ,
    TCOM.TRACKER_ID AS TCOM_TRACKER_ID
FROM ES_WAREHOUSE.PUBLIC.ASSET_TRACKER_ASSIGNMENTS ATA
LEFT JOIN TRACKERS.PUBLIC.TRACKERS TCOM ON
ATA.TRACKER_ID = TCOM.TRACKER_ID
)
, TRA AS (
SELECT TRY_CAST(T.device_serial AS VARCHAR) AS DEVICE_SERIAL, T.TRACKER_ID, TT.NAME AS DEVICE_TYPE
FROM ES_WAREHOUSE.PUBLIC.TRACKERS T LEFT JOIN ES_WAREHOUSE.PUBLIC.TRACKER_TYPES TT ON T.TRACKER_TYPE_ID = TT.TRACKER_TYPE_ID
)
SELECT DISTINCT TRA.DEVICE_SERIAL, IS_ACTIVE, ICCID, TCOM_TRACKER_ID, TRA.TRACKER_ID, TRA.DEVICE_TYPE FROM TCOM_TO_ATA LEFT JOIN TRA ON TCOM_TO_ATA.DEVICE_SERIAL = TRA.DEVICE_SERIAL
)
, KSI AS (
SELECT TO_VARCHAR(ICCID) AS ICCID FROM ANALYTICS.FINANCIAL_SYSTEMS.KORE_SIMS_ICCIDS
)
SELECT KSI.ICCID AS ICCID, TRACK.ICCID AS LINK, TRACK.TRACKER_ID AS TRACKER_ID, TRACK.DEVICE_SERIAL AS DEVICE_SERIAL, TRACK.IS_ACTIVE AS IS_ACTIVE, TRACK.DEVICE_TYPE AS DEVICE_TYPE FROM KSI LEFT JOIN TRACK ON KSI.ICCID = TRACK.ICCID
))
, D365ID AS (SELECT REPLACE(INVENTSERIALID,'-','') AS INVENTSERIALID, INVENTDIMID FROM ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.INVENTDIM ID)
SELECT TRACK2.ICCID, TRACK2.TRACKER_ID, TRACK2.DEVICE_SERIAL, ATA.ASSET_ID AS ASSET_ID, TM.MAKE AS MAKE, TM.MODEL AS MODEL, TM.COMPANY_NAME AS COMPANY_NAME, TM.OWNERSHIP AS OWNERSHIP, TM.TRACKER AS TRACKER, TM.LAST_CHECKIN_TIMESTAMP AS LAST_CHECK_IN, IT.DATEPHYSICAL AS D365_PHYSICAL_DATE, ATA.DATE_INSTALLED, ATA.DATE_UNINSTALLED, TRACK2.DEVICE_TYPE AS DEVICE_TYPE FROM TRACK2
LEFT JOIN
    ES_WAREHOUSE.PUBLIC.ASSET_TRACKER_ASSIGNMENTS ATA
    ON ATA.TRACKER_ID = TRACK2.TRACKER_ID
LEFT JOIN
    ANALYTICS.BI_OPS.TELEMATICS_MOTHERSHIP TM
    ON TM.ASSET_ID = ATA.ASSET_ID
LEFT JOIN
    D365ID
    ON D365ID.INVENTSERIALID = TRACK2.DEVICE_SERIAL
LEFT JOIN
    ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.inventtrans IT
    ON IT.inventdimid = D365ID.inventdimid
ORDER BY TRACK2.ICCID
)
;;
}

dimension: ICCID {
  type:  string
  sql:  ${TABLE}.ICCID ;;
  primary_key: yes
}

dimension: TRACKER_ID {
  type: string
  sql: ${TABLE}.TRACKER_ID ;;
}

dimension: DEVICE_SERIAL {
  type: string
  sql: ${TABLE}.DEVICE_SERIAL ;;
}

dimension: ASSET_ID {
    type:  string
    sql:  ${TABLE}.ASSET_ID ;;
  }

dimension: MAKE {
  type: string
  sql: ${TABLE}.MAKE ;;
}

dimension: MODEL {
  type: string
  sql: ${TABLE}.MODEL ;;
}

dimension: COMPANY_NAME {
  type:  string
  sql:  ${TABLE}.COMPANY_NAME ;;
}

dimension: OWNERSHIP {
  type: string
  sql: ${TABLE}.OWNERSHIP ;;
}

dimension: TRACKER {
  type: string
  sql: ${TABLE}.TRACKER ;;
}

dimension: DEVICE_TYPE {
  type: string
  sql: ${TABLE}.DEVICE_TYPE ;;
}

dimension: LAST_CHECK_IN {
  type: date
  sql: ${TABLE}.LAST_CHECK_IN ;;
}

dimension: D365_PHYSICAL_DATE {
  type: date
  sql: ${TABLE}.D365_PHYSICAL_DATE ;;
}

dimension: DATE_INSTALLED {
  type: date
  sql: ${TABLE}.DATE_INSTALLED ;;
}

dimension: DATE_UNINSTALLED {
  type: date
  sql: ${TABLE}.DATE_UNINSTALLED ;;
}
}
