view: subscription_revenue_summary {

  derived_table: {
    sql:
   --SUMMARY
SELECT I.BILLING_APPROVED_DATE::DATE AS BILLING_APPROVED_DATE,
MONTH(I.BILLING_APPROVED_DATE::DATE) AS BILLING_APPROVED_MONTH,
YEAR(I.BILLING_APPROVED_DATE::DATE) AS BILLING_APPROVED_YEAR,
LIT.NAME AS LINE_ITEM_TYPE, LIT.LINE_ITEM_TYPE_ID AS LINE_ITEM_TYPE_ID,
SUM(LI.AMOUNT) AS REVENUE
FROM ES_WAREHOUSE.PUBLIC.INVOICES AS I
LEFT JOIN ES_WAREHOUSE.PUBLIC.PURCHASE_ORDERS AS PO
ON I.PURCHASE_ORDER_ID = PO.PURCHASE_ORDER_ID
LEFT JOIN  ES_WAREHOUSE.PUBLIC.LINE_ITEMS AS LI
ON I.INVOICE_ID = LI.INVOICE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.LINE_ITEM_TYPES AS LIT
ON LI.LINE_ITEM_TYPE_ID = LIT.LINE_ITEM_TYPE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ORDERS AS O
ON I.ORDER_ID = O.ORDER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.USERS AS U
ON O.USER_ID = U.USER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C
ON U.COMPANY_ID = C.COMPANY_ID
WHERE LI.LINE_ITEM_TYPE_ID IN (30,31,32,33,34)
AND I.BILLING_APPROVED_DATE::DATE >= '1/1/2020'
AND U.COMPANY_ID <> 1854
GROUP BY I.BILLING_APPROVED_DATE::DATE , MONTH(I.BILLING_APPROVED_DATE::DATE),
YEAR(I.BILLING_APPROVED_DATE::DATE),
LIT.NAME, LIT.LINE_ITEM_TYPE_ID
HAVING SUM(LI.AMOUNT) > 0
ORDER BY I.BILLING_APPROVED_DATE::DATE, LIT.LINE_ITEM_TYPE_ID
                         ;;
  }

  dimension: billing_approved_date {
    type: date
    sql: ${TABLE}.BILLING_APPROVED_DATE ;;
  }

  dimension: billing_approved_month {
    type: number
    sql: ${TABLE}.BILLING_APPROVED_MONTH ;;
  }

  dimension: billing_approved_year {
    type: number
    sql: ${TABLE}.BILLING_APPROVED_YEAR ;;
  }

  dimension: line_item_type {
    type: string
    sql: ${TABLE}.LINE_ITEM_TYPE ;;
  }

  dimension: line_item_type_id {
    type: number
    sql: ${TABLE}.LINE_ITEM_TYPE_ID ;;
  }

  measure: revenue {
    type: sum
    sql: ${TABLE}.REVENUE ;;
  }
  }
