view: telematics_warehouse_internal_ordering_inventory {
    derived_table: {
      sql:

-- Telematics Branch Inventory to Warehouse Inventory--
WITH BRANCH_TELE_INVENTORY AS (
WITH BRANCH_STORE_INVENTORY AS (
WITH BRANCH_STORES AS (
WITH STORES AS ( WITH BRAN AS (SELECT TO_VARCHAR(PARENT_ID) as PARENT_ID, TO_VARCHAR(STORE_ID) AS STORE_ID, TO_VARCHAR(BRANCH_ID) AS BRANCH_ID, NAME FROM es_warehouse.inventory.stores WHERE STORE_TYPE_ID = 1)
, STO AS (SELECT TO_VARCHAR(PARENT_ID) as PARENT_ID, TO_VARCHAR(STORE_ID) AS STORE_ID, NAME FROM es_warehouse.inventory.stores WHERE STORE_TYPE_ID > 1)
SELECT STO.STORE_ID, STO.NAME AS STORE_NAME, BRAN.BRANCH_ID, BRAN.NAME AS BRANCH_NAME FROM STO
LEFT JOIN BRAN ON STO.PARENT_ID = BRAN.STORE_ID)
, BRANCHES AS (SELECT TO_VARCHAR(STORE_ID) AS STORE_ID, NAME AS STORE_NAME, TO_VARCHAR(BRANCH_ID) AS BRANCH_ID, NAME AS BRANCH_NAMW FROM es_warehouse.inventory.stores WHERE STORE_TYPE_ID = 1)
SELECT * FROM STORES UNION SELECT * FROM BRANCHES
)
, STORE_PARTS AS (
WITH S_P AS (SELECT PART_ID, TO_VARCHAR(STORE_ID) AS STORE_ID, QUANTITY, AVAILABLE_QUANTITY, DATE_UPDATED FROM es_warehouse.inventory.store_parts)
SELECT S_P.STORE_ID, S_P.PART_ID AS ESDBPARTID, ITA.ITEMID AS D365ITEMID, S_P.QUANTITY, S_P.AVAILABLE_QUANTITY FROM S_P LEFT JOIN ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.INVENTTABLE ITA ON S_P.PART_ID = ITA.ESDBPARTID_CUSTOM WHERE ITA.ESDBPARTID_CUSTOM IS NOT NULL
)
, DEP AS (SELECT to_varchar(DEPARTMENTID) AS DEPARTMENTID, TITLE FROM analytics.intacct.department)
SELECT BRANCH_STORES.STORE_ID, BRANCH_STORES.STORE_NAME, BRANCH_STORES.BRANCH_ID, DEP.TITLE AS BRANCH_NAME, STORE_PARTS.D365ITEMID, STORE_PARTS.QUANTITY FROM BRANCH_STORES
LEFT JOIN STORE_PARTS ON BRANCH_STORES.STORE_ID = STORE_PARTS.STORE_ID
LEFT JOIN DEP on DEP.DEPARTMENTID = BRANCH_STORES.BRANCH_ID
WHERE STORE_PARTS.D365ITEMID IS NOT NULL
)
SELECT BRANCH_ID, BRANCH_NAME, D365ITEMID, SUM(QUANTITY) AS BRANCH_QUANTITY FROM BRANCH_STORE_INVENTORY GROUP BY BRANCH_ID, BRANCH_NAME, D365ITEMID
)
, TELE_WAREHOUSE_INVENTORY AS (
-- D365 Telematics Warehouse Inventory Totals--
SELECT
D365_ITEM_ID, ITEM_NAME, OLD_PART_NUMBER, PRODUCT_NAME, INVENT_STATUS, PRODUCT_LIFECYCLE_STATE, SUM(ON_HAND_QUANTITY) AS WAREHOUSE_QUANTITY, ESDB_PART_ID, ESDB_PART_NAME, ESDB_MANUFACTURER_NUMBER
FROM
(
WITH DISTINCT_ONHAND AS (
SELECT DISTINCT
    IT.RECID, IT.ITEMID AS ITEM_ID, ID.WMSLOCATIONID AS W_MSLOCATION_ID, ITA.NAMEALIAS AS NAME_ALIAS, ITA.WFSOLDPARTNUMBER AS OLD_PART_NUMBER, RECENT_NAME.PRODUCT_NAME AS PRODUCT_NAME, ID.INVENTLOCATIONID AS INVENT_LOCATION_ID, IT.STATUSRECEIPT AS STATUS_RECEIPT, IT.STATUSISSUE AS STATUS_ISSUE, IT.QTY AS QTY, WMSL.LOCPROFILEID AS LOC_PROFILE_ID, ID.INVENTSTATUSID AS INVENT_STATUS, ITA.PRODUCTLIFECYCLESTATEID AS PRODUCT_LIFECYCLE_STATE, PARTS.PART_ID as ESDB_PART_ID, PARTS.NAME AS ESDB_PART_NAME, PARTS.MANUFACTURER_NUMBER AS ESDB_MANUFACTURER_NUMBER
FROM
    ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.INVENTTRANS IT
LEFT JOIN
    ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.INVENTDIM ID
    ON IT.INVENTDIMID = ID.INVENTDIMID AND IT.DATAAREAID = ID.DATAAREAID
LEFT JOIN
    ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.WMSLOCATION WMSL
    ON WMSL.WMSLOCATIONID = ID.WMSLOCATIONID
LEFT JOIN
    ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.INVENTTABLE ITA
    ON ITA.ITEMID = IT.ITEMID
LEFT JOIN
    es_warehouse.inventory.parts PARTS
    ON PARTS.PART_ID = ITA.ESDBPARTID_CUSTOM
LEFT JOIN
    (SELECT SL.ITEMID AS ITEM_ID, SL.NAME AS PRODUCT_NAME, NEW.MAX_DATE AS MAX_DATE
    FROM ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.SALESLINE AS SL
    INNER JOIN (SELECT
    ITEMID
    ,
    MAX(SHIPPINGDATEREQUESTED) AS MAX_DATE
    FROM
    ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.SALESLINE
    GROUP BY ITEMID) AS NEW
    ON SL.ITEMID = NEW.ITEMID AND SL.SHIPPINGDATEREQUESTED = NEW.MAX_DATE
    GROUP BY SL.ITEMID, SL.NAME, NEW.MAX_DATE) RECENT_NAME
    ON RECENT_NAME.ITEM_ID = ITA.ITEMID
WHERE
    ID.INVENTSITEID = 'KCK'
)
SELECT
    DISTINCT_ONHAND.ITEM_ID AS D365_ITEM_ID,
    DISTINCT_ONHAND.NAME_ALIAS AS ITEM_NAME,
    DISTINCT_ONHAND.OLD_PART_NUMBER AS OLD_PART_NUMBER,
    DISTINCT_ONHAND.PRODUCT_NAME AS PRODUCT_NAME,
    DISTINCT_ONHAND.INVENT_STATUS AS INVENT_STATUS,
    DISTINCT_ONHAND.PRODUCT_LIFECYCLE_STATE AS PRODUCT_LIFECYCLE_STATE,
    SUM(CASE
          WHEN DISTINCT_ONHAND.STATUS_RECEIPT = 3 THEN DISTINCT_ONHAND.QTY
          WHEN DISTINCT_ONHAND.STATUS_RECEIPT = 2 THEN DISTINCT_ONHAND.QTY
          WHEN DISTINCT_ONHAND.STATUS_RECEIPT = 1 THEN DISTINCT_ONHAND.QTY
          WHEN DISTINCT_ONHAND.STATUS_ISSUE = 3 THEN DISTINCT_ONHAND.QTY
          WHEN DISTINCT_ONHAND.STATUS_ISSUE = 2 THEN DISTINCT_ONHAND.QTY
          WHEN DISTINCT_ONHAND.STATUS_ISSUE = 1 THEN DISTINCT_ONHAND.QTY
          ELSE 0 END) AS ON_HAND_QUANTITY,
    DISTINCT_ONHAND.INVENT_LOCATION_ID AS INVENT_LOCATION_ID,
    itr2.MVA_PRICE AS UNIT_COST,
    DISTINCT_ONHAND.ESDB_PART_ID AS ESDB_PART_ID,
    DISTINCT_ONHAND.ESDB_PART_NAME AS ESDB_PART_NAME,
    DISTINCT_ONHAND.ESDB_MANUFACTURER_NUMBER AS ESDB_MANUFACTURER_NUMBER
FROM DISTINCT_ONHAND
LEFT JOIN
    (SELECT
        ITEMID AS ITEM_ID,
        MVAPRICE AS MVA_PRICE
    FROM
        (SELECT
            AVG(DIV0NULL(COSTSUM,QTYSUM)) AS MVAPRICE,
            ITEMID
        FROM
            (SELECT
                *
            FROM
                (
                SELECT
                    SUM(PL.PURCHPRICE * PURCHQTY) AS COSTSUM,
                    SUM(PL.PURCHQTY) AS QTYSUM,
                    PL.ITEMID AS ITEMID
                FROM
                    ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.PURCHLINE PL
                LEFT JOIN
                    ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.PURCHTABLE PT
                        ON PT.PURCHID = PL.PURCHID
                WHERE
                    PT.PURCHSTATUS = 3
                    AND PL.PURCHSTATUS = 3
                    AND PL.ITEMID IS NOT NULL
                GROUP BY
                    PL.ITEMID
                ORDER BY
                    PL.ITEMID)
                UNION ALL
                (SELECT
                    COSTSUM,
                    QTYSUM,
                    to_varchar(ITEM_ID) AS ITEMID
                FROM
                    (SELECT
                        SUM(COSTAMOUNTPHYSICAL*-1) AS COSTSUM,
                        SUM(QTY*-1) AS QTYSUM,
                        ITL.ITEM_ID AS ITEM_ID
                    FROM
                        ANALYTICS.MICROSOFT_DYNAMICS_365_FO.INVENT_TRANSFER_LINE ITL
                    LEFT JOIN
                        ANALYTICS.MICROSOFT_DYNAMICS_365_FO.INVENT_TRANSFER_TABLE ITT
                        ON ITL.TRANSFER_ID = ITT.TRANSFER_ID
                    LEFT JOIN
                        ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.INVENTTRANSORIGIN ITO
                        ON ITO.INVENTTRANSID = ITL.INVENT_TRANS_ID
                    LEFT JOIN
                        ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.INVENTTRANS IT
                        ON IT.INVENTTRANSORIGIN = ITO.RECID
                    WHERE
                        ITT.TRANSFER_STATUS = 2
                    GROUP BY
                        ITL.ITEM_ID)
                    UNION ALL
                    (SELECT
                        SUM(IJTR.COSTAMOUNT*-1) AS COSTSUM,
                        SUM(IJTR.QTY*-1) AS QTYSUM,
                        IJTR.ITEMID AS ITEM_ID
                    FROM
                        ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.INVENTJOURNALTRANS IJTR
                    LEFT JOIN
                        ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.INVENTJOURNALTABLE IJTA
                    ON IJTR.JOURNALID = IJTA.JOURNALID
                    WHERE IJTR.QTY < 0
                    GROUP BY
                        IJTR.ITEMID)
                    )
                )
        GROUP BY ITEMID
        )
    ) itr2
ON
    itr2.ITEM_ID = DISTINCT_ONHAND.ITEM_ID
WHERE
    DISTINCT_ONHAND.LOC_PROFILE_ID <> 'User'
    AND DISTINCT_ONHAND.W_MSLOCATION_ID <> 'DONOTUSE'
GROUP BY
    DISTINCT_ONHAND.ITEM_ID, DISTINCT_ONHAND.INVENT_LOCATION_ID, DISTINCT_ONHAND.W_MSLOCATION_ID, itr2.MVA_PRICE, DISTINCT_ONHAND.NAME_ALIAS, DISTINCT_ONHAND.OLD_PART_NUMBER, DISTINCT_ONHAND.PRODUCT_NAME, DISTINCT_ONHAND.PRODUCT_LIFECYCLE_STATE, DISTINCT_ONHAND.INVENT_STATUS, DISTINCT_ONHAND.ESDB_PART_ID, DISTINCT_ONHAND.ESDB_PART_NAME, DISTINCT_ONHAND.ESDB_MANUFACTURER_NUMBER
)
GROUP BY
    D365_ITEM_ID, ITEM_NAME, OLD_PART_NUMBER, PRODUCT_NAME, INVENT_STATUS, PRODUCT_LIFECYCLE_STATE, ESDB_PART_ID, ESDB_PART_NAME, ESDB_MANUFACTURER_NUMBER
HAVING
    INVENT_STATUS = 'AVAILABLE' AND PRODUCT_LIFECYCLE_STATE = 'Operational'
ORDER BY
    D365_ITEM_ID
)
SELECT BRANCH_TELE_INVENTORY.BRANCH_ID AS BRANCH_ID, BRANCH_TELE_INVENTORY.BRANCH_NAME AS BRANCH_NAME, TELE_WAREHOUSE_INVENTORY.ESDB_PART_ID AS ESDB_PART_ID, BRANCH_TELE_INVENTORY.BRANCH_QUANTITY AS BRANCH_ONHAND_QUANTITY, TELE_WAREHOUSE_INVENTORY.D365_ITEM_ID AS D365_ITEM_ID, TELE_WAREHOUSE_INVENTORY.ITEM_NAME AS WAREHOUSE_ITEM_NAME, TELE_WAREHOUSE_INVENTORY.WAREHOUSE_QUANTITY AS WAREHOUSE_ONHAND_QUANTITY, CONCAT(BRANCH_ID, 'TELE', D365_ITEM_ID) AS UNIQUE_IDENTIFIER
FROM BRANCH_TELE_INVENTORY LEFT JOIN TELE_WAREHOUSE_INVENTORY ON BRANCH_TELE_INVENTORY.D365ITEMID = TELE_WAREHOUSE_INVENTORY.D365_ITEM_ID

        ;;
        }

    dimension: UNIQUE_IDENTIFIER {
      type:  string
      sql:  ${TABLE}.UNIQUE_IDENTIFIER ;;
      primary_key: yes
    }

    dimension: BRANCH_ID {
      type: string
      sql: ${TABLE}.BRANCH_ID ;;
    }

  dimension: BRANCH_NAME {
    type: string
    sql: ${TABLE}.BRANCH_NAME ;;
  }

    dimension: ESDB_PART_ID {
      type: string
      sql: ${TABLE}.ESDB_PART_ID ;;
    }

  dimension: D365_ITEM_ID {
    type: string
    sql: ${TABLE}.D365_ITEM_ID ;;
  }

  dimension: WAREHOUSE_ITEM_NAME {
    type: string
    sql: ${TABLE}.WAREHOUSE_ITEM_NAME ;;
  }

    dimension: BRANCH_ONHAND_QUANTITY {
      type: number
      sql: ${TABLE}.BRANCH_ONHAND_QUANTITY ;;
    }

    dimension: WAREHOUSE_ONHAND_QUANTITY {
      type: number
      sql: ${TABLE}.WAREHOUSE_ONHAND_QUANTITY ;;
    }
  }
