view: telematics_branch_trend {

  derived_table: {
    sql:
   SELECT RS.ASSET_ID AS ASSET_ID, RS.RENTAL_STATUS AS RENTAL_STATUS, RS.DATE_START::DATE AS DATE_START, RS.DATE_END::DATE AS DATE_END,
RB.RENTAL_BRANCH_ID AS RENTAL_BRANCH_ID, M.NAME AS BRANCH,
COALESCE(A.SERIAL_NUMBER,A.VIN) AS SERIAL_VIN, A.YEAR AS YEAR, A.MAKE AS MAKE, A.MODEL AS MODEL, A.TRACKER_ID AS TRACKER_ID
FROM ES_WAREHOUSE.SCD.SCD_ASSET_RENTAL_STATUS AS RS
LEFT JOIN ES_WAREHOUSE.SCD.ASSET_SCD_RENTAL_BRANCH AS RB
ON RS.ASSET_ID = RB.ASSET_ID AND RS.DATE_START::DATE BETWEEN RB.DATE_START AND RB.DATE_END::DATE
AND RS.DATE_END::DATE BETWEEN RB.DATE_START::DATE AND RB.DATE_END::DATE
LEFT JOIN ES_WAREHOUSE.PUBLIC.MARKETS AS M
ON RB.RENTAL_BRANCH_ID = M.MARKET_ID
LEFT JOIN ES_WAREHOUSE.SCD.SCD_ASSET_COMPANY AS AC
ON RS.ASSET_ID = AC.ASSET_ID AND RS.DATE_START::DATE BETWEEN AC.DATE_START::DATE AND AC.DATE_END::DATE
AND RS.DATE_END::DATE BETWEEN AC.DATE_START AND AC.DATE_END::DATE
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS AS A
ON RS.ASSET_ID = A.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS_AGGREGATE AS AA
ON RS.ASSET_ID = AA.ASSET_ID
left join ES_WAREHOUSE."PUBLIC".asset_tracker_assignments ata
on RS.asset_id=ata.asset_id
WHERE lower(RS.RENTAL_STATUS) = 'on rent'
AND BRANCH IS NOT NULL
AND AC.COMPANY_ID = 1854
AND A.TRACKER_ID IS NULL  AND ATA.TRACKER_ID IS NULL AND SUBSTR(TRIM(A.SERIAL_NUMBER), 1, 3) != 'RR-'
and AA.category not in ('Attachments','AG Tractors','Agriculture & Landscaping','Cutting & Coring','Electrical Equipment','Fans',
'Fans & Dehumidifiers','Forklift Attachments','Forklift and Telehandler Attachments','Fuel Storage','Heaters','Masonry & Tile Saws','Mixers','Power Tools','Power Tools & Small Equipment',
'Pressure Washers & Pumps','Rammers','Surface Preparation','Storage Containers','Water Truck','Water Trailer','Waste Containers', 'Pony Motors',
'Attachments - CTL and Skid Steers',
'Attachments - Mini Excavators',
'Attachments - Track Excavators','Plate Compactors',
'Ramps','Tractor Trailers','Trailers','Water Trailers','Misc. Trailers','Equipment Trailers''Centrifugal Pumps','Submersible Pumps',
'Attachments - Dozers')
and a.make not in ('AIRMASTER','AMERICAN PNEUMATIC TOOL','ARMADILLO','ARROW MATERIAL HANDLING', 'ARROW MATERIAL','BLUE DIAMOND','B&B','B&B STEEL PRODUCTS','Big Tex','BOBCAT 250','BOSCH','BS60-4As','B-RAD','CEPCO','CDI','CENTRAL MACHINERY','CENTEX',
'CHICAGO PNEUMATIC','Clarke','CONSTRUCTION ELECTRICAL PRODUCTS','COPPUS','CORE CUT','DAYTON','DEWALT','D&E MANUFACTURING','Diamond','Drill','DRI-EAZ','E-BOX','EDCO','EQUIPRITE','FIRMAN','FOSTORIA','GAR-BRO','GEARENCG MFG','Generic','GENERAC','GME','GODWIN','GREENLEE','HAUL MASTER','HARRINGTON','HILMAN ROLLERS','HILTI','Hilti','H&M','HUSQVARNA','LIND EQUIPMENT','Industrial Air Tool','IRONTON','Jobox',
'LoadTrail','MAKITA','MAGNUM','Mi-T-M Corporation','MESTEK','MICHIGAN PNEUMATIC','MILWAUKEE','MILLER','MISKIN','MSA','Motorola','MOTOROLA','PALADIN','Pallet Jack','POTTY PORTABLES','Powerhorse','POWER BREEZER','POWER TEAM','PINNACLE','Portacool','PORTACOOL','PROTO','PT3','RIDGID','Salvation','SATELLITE INDUSTRIES','SIMPSON','SOUTHWIRE','SOUTHWIRE COMPANY','STAR INDUSTRIES','STIHL',
'STRONGWAY','Sumner','SUMNER','TEXAS','Texas Pneumatic Tools, Inc.','TITAN','TPI','TOKU','TORCUP','TRYSTAR','UNIVERSAL TOOL','US HAMMER','WERK-BRAU','WOODS','VESTIL','VIRNIG')
and a.model not in ('1001142247','01970-3R02','1YNW7','6 Fork Extensions','413-R','4HDX2','444-624','48" Pallet Forks','8-Way Distribution Box','15H','10 Ton Hook','17L53-SS-ES','24" Shop Fan','AERO 40FP','Aero 40FP','BS50-4As','BS60-4As','BVP 18/45',
'CICST-280','CP1260','CP1290','CP4608','CST-280','CST280','CRT48','CT36','CT48','DG150','DPU90r','DPU4545HEH','DPU4545','Dump Hopper','DPH-38','Drill','EMP 205IC','eu2200i','EU2200i','FLEXTEC 350X','FT350X','FX25','GP2500A','GP5500','GP6600',
'GP6600A','GP9700','GP9700V','GPS9700V','HB36','HB980','HI400','H1400','HDR155','H51','Invertec V275-FS',' Invertec V275-S','INVERTEC V275-S','J6014C','Jib Winch','LF100','LN-25X','LN25','LN25 PRO','LM25 PRO','MCH-3','Millermatic 211','MOTRDU4100','Multimatic 215','MPB 60A','MPB 90A',
'MC94SH8','M2500','Pallet Jack','Pallet fork attachment','PAS2400','PST2','PT2','PT3','PT3A','PT4','PT4A','RB300ME','S3C','SB552','SLA-10','SLC-24','Telehandler Bucket','TE-50 AVR','TE 1000-AVR','THUNDERBOLT 160 DC',
'TE-3000 AVR','TOMAHAWK 375 AIR Plasma Cutter','TLR33','TNB-4M','Triple L 4610','TZ-34/20','TPB-90','UT7K','V275-S','WMS-100','WP1550AW','WP1550Aw','WP1550Aw US','WT5C','X-Tractor 1GC')
and (
a.make||a.model not in (
'KENT125R',
'FRDCW24III',
'CLARKCJ55',
'MIKASAMVC-82VHW',
'ESSEX SILVER-LINESL-8',
'MILLER ELECTRICFILTAIR 130',
'POWERHORSE52313',
'WACKER NEUSONPT2A',
'SANY36" HD BUCKET',
'SANY12" Mini Excavator Bucket',
'JOHN DEERE60" Loader Forks',
'CASE51469715',
'SPX POWER TEAMP159',
'STRIKERSC-80',
'WACKER NEUSONPDT3A',
'WACKER NEUSONBPU5545A',
'PRO-LINK4048-U448',
'LOWEBP-210',
'CIDHHDFF',
'HOUGEN MFGHMD130',
'HOUGEN MFGHMD917',
'ANTHONY WELDED PROD.85-10',
'HOUGEN MFGHMD904',
'WACKER NEUSON80" Bucket',
'M&B MAGSPT785',
'YALEMPB040-E',
'JETPTW-2748',
'WERNERR410050',
'EDGE72" Angle Broom',
'RITRONRLR-465-N',
'FURUKAWAHPI35IIFB',
'SPY785',
'JOHN DEEREWheel Loader Jib',
'Great NorthernSURFACE CLEANER',
'TAG MANUFACTURING5R094497',
'EDGELAF5672-0032',
'LINCOLN ELECTRICRemote Output Control',
'ULINEDF25',
'BILLY GOATSC181H',
'BOBCAT76" LANDPLANE',
'TOMAHAWK78" Brush Grapple',
'GROUND HOGC-71-5 Two Man Auger',
'BOBCATGRPL 72 ROOT',
'UNITECEBM 352/3 PSV',
'JOHN DEEREStandard Construction Fork Frame',
'DOOSAN72" Pallet Fork 106W',
'POWERHORSE9000 ES',
'BALLYMOREBALLYPAL45N',
'SANY24" HD BUCKET',
'TSURUMILB-480',
'BOBCATPALLET FORKS HD',
'DANUSERT3',
'FELCO36" Bucket',
'SKID PROLFFG',
'SKID PROLXG420S',
'STRIKERTNB-7J',
'WACKER NEUSONPDT3',
'WACKER NEUSONPDT2',
'MULTIQUIPGAW180HEA',
'KENT125R',
'CLARKCGC40',
'MIKASAMVC-82VHW',
'VERMEERVPT300',
'JETJBC-2',
'ABATEMENT TECHNOLOGIESAG3000MCCK',
'ABATEMENT TECHNOLOGIESAG8000PAS',
'ABATEMENT TECHNOLOGIESPAS750',
'AEROSPACE9143',
'AGRILAND500gal Fuel Cell',
'ALLEGRO9518-03',
'ALLEN436VP',
'ALLENTWP4365HF',
'ALLENTWP4469HF',
'AMERICANAPG3009N',
'ASCOAVTRON 2705',
'ASCO2805',
'BesseySC 110V',
'BESTTB6X12',
'BESTTB82X16T',
'BETTER BUILT100 Gallon Transfer Tank',
'BETTER BUILT29211677',
'BILLY GOATKV650H',
'BRIGGS & STRATTONP3000',
'BULLDOG1000W Light Cart',
'CLARKWPX45',
'CLEMCOBLASTER 11260',
'Columbus McKinnon09002W',
'CORNELL8NNT-RP-EM18DB-3',
'CROWNWP3035-45',
'DIAMOND C TRAILERSDSA-12T',
'DIAMOND C TRAILERSHDT-20',
'DIAMOND C TRAILERSHDT-22T',
'DIAMOND C TRAILERSHDT-18T',
'DOOLITTLEDeckover',
'DOOLITTLEEZ Load GT',
'DOOLITTLEMD821414KSR',
'DOOSANAC25',
'DURALIFTHPT27X48PH-12H',
'ENERPACHCG-2006',
'ESCOAPS-438',
'ESCOM-300',
'ESSEX SILVER-LINE1218R',
'ESSEX SILVER-LINEESL17',
'GARDNER BENDERB2000',
'GEARWRENCHP95-525 GEARWRENCH',
'GEARWRENCHPHD0535 GEARWRENCH',
'GENIEGL-8',
'GENIESLC-18',
'SULLAIRMPB 30A',
'GRACOUltimate MX II 650',
'HOBARTIronman 230',
'HONEYWELLBWC2-H',
'HOUGEN MFGHMD934',
'HydrotechSC Pressure Washer',
'HYSTERW45ZHD',
'INGERSOLL RAND285B-6',
'INGERSOLL RAND2145QiMAX',
'INGERSOLL-RANDW7152P-K22',
'INGERSOLL-RAND3A2SA',
'INGERSOLL-RAND5980A1',
'INGERSOLL-RAND2171XP',
'INTERQUIPLKS450-3.2',
'JLGTriple L 7614',
'KARCHERKM 75/40 W BP',
'KEEN OVENSK-10',
'KEEN OVENSK-50',
'KEMCOU14',
'KEY PLANTAHPS4',
'KOBALT1/2" Torque Wrench',
'KOSHINKTH-80S',
'LAMARDL',
'LANDAMHC3',
'LANDAPHW4-30024B',
'LE JEUNEGS-91EZ',
'LedwelPony Motor',
'LINCOLNLHC857-100',
'LINCOLN ELECTRICDual Maverick 200/200X',
'LINCOLN ELECTRICK2269-3',
'LINCOLN ELECTRICK3430-1',
'LINCOLN ELECTRICK4277-1',
'LINCOLN ELECTRICPOWER MIG 210MP',
'LINCOLN ELECTRICRanger 305 LPG',
'LINCOLN ELECTRICTOMAHAWK 1000',
'LOADTRAILSH7712',
'LOADTRAILTilt-Deck Rental Trailer',
'MAXXDG6X8320',
'MILLER ELECTRICDynasty 210 DX',
'MILLER ELECTRICMILLERMATIC 252',
'MILLER ELECTRICWELDER 4 PACK',
'MINE SAFETY APPLIANCES (MSA)10105756',
'MINE SAFETY APPLIANCES (MSA)10127422',
'MINE SAFETY APPLIANCES (MSA)10152669',
'MINE SAFETY APPLIANCES (MSA)10127427',
'MINE SAFETY APPLIANCES (MSA)10128627',
'MINNICHSD1',
'MULTIQUIPBPX',
'MULTIQUIPGA6HR',
'MULTIQUIPJ36H55',
'MULTIQUIPMB25A',
'MULTIQUIPMC12PH',
'MULTIQUIPMC94PH8',
'MULTIQUIPMQ600HTB',
'MULTIQUIPWM120PHD',
'MULTIQUIPWM90PH8',
'MULTIQUIPGA6HR',
'New BreedTW6900',
'NIKONXS5',
'NORSTAR22T',
'NORTHERN1131',
'NORTHROCKModel 2',
'NORTHSTAR20" Surface Cleaner',
'PARAGON PROPanellft 460',
'PetolP95-525',
'PetolPHD0535',
'PHOENIX4038550',
'POWERHORSE7000',
'POWR-FLITENM2000',
'QUINCYQT-7.5',
'RAD TORQUE SYSTEMSBL500',
'RED ROOTile Scraper',
'RICEPTH20',
'RICE HYDRODPH-3B',
'RICE HYDROMTP-1',
'RICE HYDROMTP-5',
'RICE HYDROHP-1/55',
'ROPER WHITNEYModel 20',
'RUBBERMAIDA23i Shop Cart',
'SOKKIAB20 32X',
'SPANCOF4000',
'SPECTRALL300N-2',
'SPX POWER TEAM9644',
'TAMCOTOKUSLCH-3R-S',
'TENNANTT600E',
'TORNADO98451',
'TRANSCUBE20TCG(G)W-NA',
'TRELAWNYHAND-HELD SCABBLER',
'UNITEC21" Chain Saw',
'UNITECCS 536664-3',
'WACKER NEUSONPG2A',
'WACKER NEUSONBTS635',
'WACKER NEUSONGP 5600A',
'WACKER NEUSONGP3800A',
'WACKER NEUSONGPS9700A',
'WACKER NEUSONIEC58/120/8',
'WACKER NEUSONIRFU65',
'WACKER NEUSONM1500',
'WACKER NEUSONSurge Trailer',
'WERNERWRD6204',
'WERNERWRD6206 ',
'WERNERWRD6212',
'WOBBLE LIGHT111104',
'WORKSITE LIGHTINGDWXPLEDIL50-12V',
'WORKSITE LIGHTINGPetroPRO-MAX',
'WORKSITE LIGHTINGPetroPRO-Handy',
'WACKER NEUSONPG3A',
'WACKERP35A',
'WACKER NEUSONP35A',
'Diesel LaptopsDIESEL LAPTOP',
'MEGADECK103635 Mat'
) and a.model <> 'Dozer Rake') and a.asset_id not in (129442,129438,125855)
and a.asset_id not in (131277,75798,135200,126657,116163,132500,137948,137949,102636,130341,137947)
                         ;;
  }

  dimension: asset_id {
    type: number
    sql: ${TABLE}.ASSET_ID ;;
  }

  dimension:rental_status {
    type: string
    sql: ${TABLE}.RENTAL_STATUS ;;
  }

  dimension: date_start {
    type: date
    sql: ${TABLE}.DATE_START ;;
  }

  dimension: date_end {
    type: date
    sql: ${TABLE}.DATE_END ;;
  }

  dimension: rental_branch_id {
    type: number
    sql: ${TABLE}.RENTAL_BRANCH_ID ;;
  }

  dimension: branch {
    type: string
    sql: ${TABLE}.BRANCH ;;
  }

  dimension: serial_vin {
    type: string
    sql: ${TABLE}.SERIAL_VIN ;;
  }

  dimension: year {
    type: string
    sql: ${TABLE}.YEAR ;;
  }

  dimension: make {
    type: string
    sql: ${TABLE}.MAKE ;;
  }

  dimension: model {
    type: string
    sql: ${TABLE}.MODEL ;;
  }

  dimension: tracker_id {
    type: number
    sql: ${TABLE}.TRACKER_ID ;;
  }



  set: trend_details {
    fields: [asset_id,serial_vin,rental_status,rental_branch_id,branch,date_start,date_end,year,make,model,tracker_id]
  }

  measure: 1_to_3_weeks {
    type: count_distinct
    drill_fields: [trend_details*]
    sql: case when datediff(day,current_date,${date_start}) between 7 and 21 then ${asset_id} else 0 end ;;
  }

  measure: 1_to_3_months {
    type: count_distinct
    drill_fields: [trend_details*]
    sql: case when datediff(day,current_date,${date_start}) between 30 and 90 then ${asset_id} else 0 end ;;
  }


  measure: 1_year {
    type: count_distinct
    drill_fields: [trend_details*]
    sql: case when year(${date_start}) = year(current_date)-1   then ${asset_id} else 0 end ;;
  }

  }
