view: telematics_warehouse_all_shipments {
  derived_table: {
    sql:

    --SUMMARY
--TELE All Shipments--
SELECT * FROM (
SELECT
    *
    ,
    ROW_NUMBER() OVER(PARTITION BY SERIAL_FORMATTED ORDER BY PHYSICAL_DATE) AS SERIAL_NUMBER_SHIPPED_INSTANCE
FROM (
SELECT SERIAL_FORMATTED, PART_DESCRIPTION, PART_ID,
    CASE
        WHEN PART_ID = '1000720' THEN 'CAMERA'
        ELSE DEVICE_TYPE
    END AS DEVICE_TYPE
    ,
    SALES_PRICE, PHYSICAL_DATE, CUSTOMER_GROUP, CUSTOMER_NAME, DELIVERY_NAME, SO_NUMBER, SOURCE
FROM (
SELECT
    REPLACE(ID.INVENTSERIALID, '-', '') AS SERIAL_FORMATTED
    ,
    CPST.NAME AS PART_DESCRIPTION
    ,
    CPST.ITEMID AS PART_ID
    ,
    CASE
        WHEN ITA.TELEMATICSITEMTYPE_CUSTOM = 'Tracker' THEN 'TRACKER'
        WHEN ITA.TELEMATICSITEMTYPE_CUSTOM = 'Keypad' THEN 'KEYPAD'
    ELSE 'ATTACHMENT'
    END AS DEVICE_TYPE
    ,
    SL.SALESPRICE AS SALES_PRICE
    ,
    IT.DATEPHYSICAL AS PHYSICAL_DATE
    ,
    SALESHEADER.CUSTGROUP AS CUSTOMER_GROUP
    ,
    GAB.NAME AS CUSTOMER_NAME
    ,
    SALESHEADER.DELIVERYNAME AS DELIVERY_NAME
    ,
    SALESHEADER.SALESID AS SO_NUMBER
    ,
    'D365' AS SOURCE
FROM
    ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.custpackingsliptrans CPST
LEFT JOIN
    ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.inventtransorigin ITO
    ON CPST.inventtransid = ITO.inventtransid
LEFT JOIN
    ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.inventtrans IT
    ON ITO.RECID = IT.inventtransorigin
    AND CPST.packingslipid = IT.packingslipid
LEFT JOIN
    ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.inventdim ID
    ON IT.inventdimid = ID.inventdimid
LEFT JOIN ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.salestable SALESHEADER
    ON CPST.salesid = SALESHEADER.salesid
LEFT JOIN ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.CUSTTABLE CT
    ON CT.ACCOUNTNUM = SALESHEADER.CUSTACCOUNT
LEFT JOIN ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.DIRPARTYTABLE GAB
    ON CT.PARTY = GAB.RECID
LEFT JOIN
    ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.custinvoicetrans CIT
    ON CIT.inventtransid = ITO.inventtransid
LEFT JOIN
    ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.SALESLINE SL
    ON SL.INVENTTRANSID = ITO.INVENTTRANSID
LEFT JOIN
    ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.INVENTTABLE ITA
    ON ITA.ITEMID = IT.ITEMID
WHERE
    ID.INVENTSERIALID IS NOT NULL
)
UNION
SELECT
SERIAL_FORMATTED, PART_DESCRIPTION, PART_ID,
CASE
    WHEN DEVICE_TYPE = 'Queclink' THEN 'TRACKER'
    WHEN DEVICE_TYPE = '2830' THEN 'TRACKER'
    WHEN DEVICE_TYPE = '3030' THEN 'TRACKER'
    WHEN DEVICE_TYPE = 'MC4+' THEN 'TRACKER'
    WHEN DEVICE_TYPE = 'MCX101' THEN 'TRACKER'
    WHEN DEVICE_TYPE = 'T3Camera' THEN 'CAMERA'
    WHEN DEVICE_TYPE = 'Bluetooth' THEN 'ATTACHMENT'
    WHEN DEVICE_TYPE = 'ECM' THEN 'ATTACHMENT'
    WHEN DEVICE_TYPE = 'Keypad' THEN 'KEYPAD'
    WHEN DEVICE_TYPE = 'FJ2500' THEN 'TRACKER'
    WHEN DEVICE_TYPE = 'MCX101' THEN 'TRACKER'
    WHEN DEVICE_TYPE = '730' THEN 'TRACKER'
    WHEN DEVICE_TYPE = '720' THEN 'TRACKER'
    WHEN DEVICE_TYPE = 'MC5' THEN 'TRACKER'
    WHEN DEVICE_TYPE = 'MC3' THEN 'TRACKER'
    ELSE 'ATTACHMENT'
END AS DEVICE_TYPE
    ,
    SALES_PRICE, PHYSICAL_DATE, CUSTOMER_GROUP, CUSTOMER_NAME, DELIVERY_NAME, SO_NUMBER, SOURCE
FROM
(
SELECT DISTINCT
    SERIAL_FORMATTED AS SERIAL_FORMATTED
    ,
    PART_DESCRIPTION AS PART_DESCRIPTION
    ,
    TRY_CAST('' AS STRING) AS PART_ID
    ,
        CASE
        WHEN PART_DESCRIPTION LIKE 'Queclink%' THEN 'Queclink'
        WHEN PART_DESCRIPTION LIKE '%Queclink%' THEN 'Queclink'
        WHEN PART_DESCRIPTION LIKE '%Queclink' THEN 'Queclink'
        WHEN PART_DESCRIPTION LIKE 'QUECLINK%' THEN 'Queclink'
        WHEN PART_DESCRIPTION LIKE '%QUECLINK%' THEN 'Queclink'
        WHEN PART_DESCRIPTION LIKE '%QUECLINK' THEN 'Queclink'
        WHEN PART_DESCRIPTION LIKE 'Quecklink%' THEN 'Queclink'
        WHEN PART_DESCRIPTION LIKE '%Quecklink%' THEN 'Queclink'
        WHEN PART_DESCRIPTION LIKE '%Quecklink' THEN 'Queclink'
        WHEN PART_DESCRIPTION LIKE '2830%' THEN '2830'
        WHEN PART_DESCRIPTION LIKE '%2830%' THEN '2830'
        WHEN PART_DESCRIPTION LIKE '%2830' THEN '2830'
        WHEN PART_DESCRIPTION LIKE '3030%' THEN '3030'
        WHEN PART_DESCRIPTION LIKE '%3030%' THEN '3030'
        WHEN PART_DESCRIPTION LIKE '%3030' THEN '3030'
        WHEN PART_DESCRIPTION LIKE 'Keypad%' THEN 'Keypad'
        WHEN PART_DESCRIPTION LIKE '%Keypad%' THEN 'Keypad'
        WHEN PART_DESCRIPTION LIKE '%Keypad' THEN 'Keypad'
        WHEN PART_DESCRIPTION LIKE 'MC4+%' THEN 'MC4+'
        WHEN PART_DESCRIPTION LIKE '%MC4+%' THEN 'MC4+'
        WHEN PART_DESCRIPTION LIKE '%MC4+' THEN 'MC4+'
        WHEN PART_DESCRIPTION LIKE 'MCX%' THEN 'MCX101'
        WHEN PART_DESCRIPTION LIKE '%MCX101%' THEN 'MCX101'
        WHEN PART_DESCRIPTION LIKE '%MCX101' THEN 'MCX101'
        WHEN PART_DESCRIPTION LIKE 'Cam%' THEN 'T3Camera'
        WHEN PART_DESCRIPTION LIKE '%Cam%' THEN 'T3Camera'
        WHEN PART_DESCRIPTION LIKE '%Cam' THEN 'T3Camera'
        WHEN PART_DESCRIPTION LIKE 'cam%' THEN 'T3Camera'
        WHEN PART_DESCRIPTION LIKE '%cam%' THEN 'T3Camera'
        WHEN PART_DESCRIPTION LIKE '%cam' THEN 'T3Camera'
        WHEN PART_DESCRIPTION LIKE 'CAM%' THEN 'T3Camera'
        WHEN PART_DESCRIPTION LIKE '%CAM%' THEN 'T3Camera'
        WHEN PART_DESCRIPTION LIKE '%CAM' THEN 'T3Camera'
        WHEN PART_DESCRIPTION LIKE 'ESCDM%' THEN 'T3Camera'
        WHEN PART_DESCRIPTION LIKE '%ESCDM%' THEN 'T3Camera'
        WHEN PART_DESCRIPTION LIKE '%ESCDM' THEN 'T3Camera'
        WHEN PART_DESCRIPTION LIKE 'BT%' THEN 'Bluetooth'
        WHEN PART_DESCRIPTION LIKE '%BT%' THEN 'Bluetooth'
        WHEN PART_DESCRIPTION LIKE '%BT' THEN 'Bluetooth'
        WHEN PART_DESCRIPTION LIKE 'Bluetooth%' THEN 'Bluetooth'
        WHEN PART_DESCRIPTION LIKE '%Bluetooth%' THEN 'Bluetooth'
        WHEN PART_DESCRIPTION LIKE '%Bluetooth' THEN 'Bluetooth'
        WHEN PART_DESCRIPTION LIKE 'KEYPAD%' THEN 'Keypad'
        WHEN PART_DESCRIPTION LIKE '%KEYPAD%' THEN 'Keypad'
        WHEN PART_DESCRIPTION LIKE '%KEYPAD' THEN 'Keypad'
        WHEN PART_DESCRIPTION LIKE '730%' THEN '730'
        WHEN PART_DESCRIPTION LIKE '%730%' THEN '730'
        WHEN PART_DESCRIPTION LIKE '%730' THEN '730'
        WHEN PART_DESCRIPTION LIKE 'Electronic Control Module%' THEN 'ECM'
        WHEN PART_DESCRIPTION LIKE '%Electronic Control Module%' THEN 'ECM'
        WHEN PART_DESCRIPTION LIKE '%Electronic Control Module' THEN 'ECM'
        WHEN PART_DESCRIPTION LIKE 'ECM%' THEN 'ECM'
        WHEN PART_DESCRIPTION LIKE '%ECM%' THEN 'ECM'
        WHEN PART_DESCRIPTION LIKE '%ECM' THEN 'ECM'
        WHEN PART_DESCRIPTION LIKE 'iBeacon%' THEN 'Bluetooth'
        WHEN PART_DESCRIPTION LIKE '%iBeacon%' THEN 'Bluetooth'
        WHEN PART_DESCRIPTION LIKE '%iBeacon' THEN 'Bluetooth'
        WHEN PART_DESCRIPTION LIKE 'FJ2500%' THEN 'FJ2500'
        WHEN PART_DESCRIPTION LIKE '%FJ2500%' THEN 'FJ2500'
        WHEN PART_DESCRIPTION LIKE '%FJ2500' THEN 'FJ2500'
        WHEN PART_DESCRIPTION LIKE '720%' THEN '720'
        WHEN PART_DESCRIPTION LIKE '%720%' THEN '720'
        WHEN PART_DESCRIPTION LIKE '%720' THEN '720'
        WHEN PART_DESCRIPTION LIKE 'MC-3%' THEN 'MC3'
        WHEN PART_DESCRIPTION LIKE '%MC-3%' THEN 'MC3'
        WHEN PART_DESCRIPTION LIKE '%MC-3' THEN 'MC3'
        WHEN PART_DESCRIPTION LIKE 'MC-4%' THEN 'MC4+'
        WHEN PART_DESCRIPTION LIKE '%MC-4%' THEN 'MC4+'
        WHEN PART_DESCRIPTION LIKE '%MC-4' THEN 'MC4+'
        WHEN PART_DESCRIPTION LIKE 'MC4%' THEN 'MC4+'
        WHEN PART_DESCRIPTION LIKE '%MC4%' THEN 'MC4+'
        WHEN PART_DESCRIPTION LIKE '%MC4' THEN 'MC4+'
        WHEN PART_DESCRIPTION LIKE 'MC3%' THEN 'MC3'
        WHEN PART_DESCRIPTION LIKE '%MC3%' THEN 'MC3'
        WHEN PART_DESCRIPTION LIKE '%MC3' THEN 'MC3'
        WHEN PART_DESCRIPTION LIKE 'MC5%' THEN 'MC5'
        WHEN PART_DESCRIPTION LIKE '%MC5%' THEN 'MC5'
        WHEN PART_DESCRIPTION LIKE '%MC5' THEN 'MC5'
    ELSE 'Attachment'
    END AS DEVICE_TYPE
    ,
    TRY_CAST('' AS NUMBER) AS SALES_PRICE
    ,
    REPLACE(SHIPPED, '00', '20') AS PHYSICAL_DATE
    ,
    TRY_CAST('' AS STRING) AS CUSTOMER_GROUP
    ,
    TRY_CAST('' AS STRING) AS CUSTOMER_NAME
    ,
    TRY_CAST('' AS STRING) AS DELIVERY_NAME
    ,
    SO_NUMBER AS SO_NUMBER
    ,
    'FISHBOWL' AS SOURCE
FROM
ANALYTICS.T3_SAAS_BILLING.LEGACY_SHIPMENT_DATA
)
)
)
WHERE SERIAL_NUMBER_SHIPPED_INSTANCE = 1
;;
  }

  dimension: SERIAL_FORMATTED {
    type: string
    sql: ${TABLE}.SERIAL_FORMATTED ;;
  }

  dimension: PART_DESCRIPTION {
    type: string
    sql:  ${TABLE}.PART_DESCRIPTION ;;
  }

  dimension: PART_ID {
    type: string
    sql: ${TABLE}.PART_ID ;;
  }

  dimension: DEVICE_TYPE {
    type: string
    sql: ${TABLE}.DEVICE_TYPE ;;
  }

  dimension: SALES_PRICE {
    type: number
    sql: ${TABLE}.SALES_PRICE ;;
  }

  dimension: PHYSICAL_DATE {
    type: date
    sql: ${TABLE}.PHYSICAL_DATE ;;
  }

  dimension: shipment_date {
    type: date
    datatype: date
    sql: ${PHYSICAL_DATE} ;;
    html: {{ value | date: "%b %-d, %Y" }} ;;
  }

  dimension: days_since_shipment {
    type: number
    sql: DATEDIFF('day', ${shipment_date}, CURRENT_DATE()) ;;
    value_format_name: "decimal_0"
    description: "Number of days between shipment date and the current date"
  }



  dimension: CUSTOMER_GROUP {
    type: string
    sql: ${TABLE}.CUSTOMER_GROUP;;
  }

  dimension: CUSTOMER_NAME {
    type: string
    sql: ${TABLE}.CUSTOMER_NAME ;;
  }

  dimension: DELIVERY_NAME {
    type: string
    sql: ${TABLE}.DELIVERY_NAME ;;
  }

  dimension: SO_NUMBER {
    type: string
    sql: ${TABLE}.SO_NUMBER ;;
  }

  dimension: SOURCE {
    type: string
    sql: ${TABLE}.SOURCE ;;
  }

  dimension: SERIAL_NUMBER_SHIPPED_INSTANCE {
    type: number
    sql: ${TABLE}.SERIAL_NUMBER_SHIPPED_INSTANCE ;;
  }

  dimension: shipped_to_ES {
    type: yesno
    sql: case
          when ${CUSTOMER_NAME} = 'EquipmentShare Core Solutions'
          then true
          else false
          end ;;
  }

  # dimension: days_since_shipment {
  #   type: number
  #   sql: DATEDIFF(day, CURRENT_DATE(), ${shipment_date});;
  # }


  measure: count {
    type: count
    drill_fields: [detail*]
  }

  set: detail {
    fields: [
      shipment_date,
      CUSTOMER_NAME,
      DELIVERY_NAME,
      SERIAL_FORMATTED,
      PART_ID,
      DEVICE_TYPE,
      PART_DESCRIPTION
      ]
  }


}
