view: telematics_warehouse_assignment_history {
    derived_table: {
      sql:

          --SUMMARY
      --TELE All Shipments--
      ----T3 SALES ACCT ENTRY TRACKER MANAGER PIECE----
--TOTAL TRACKER ASSIGNMENTS--
SELECT
    ASSET_ID
    ,
    ASSET_NAME
    ,
    DEVICE_ID
    ,
    DEVICE_SERIAL
    ,
    DEVICE_TYPE
    ,
    DATE_INSTALLED
    ,
    DATE_UNINSTALLED
    ,
    ROW_NUMBER() OVER(PARTITION BY DEVICE_SERIAL ORDER BY DATE_INSTALLED) AS SERIAL_NUMBER_INSTALL_INSTANCE
FROM
(
SELECT ASSET_ID, ASSET_NAME, TRACKER_ID AS DEVICE_ID, TRACKER_SERIAL AS DEVICE_SERIAL, 'TRACKER' AS DEVICE_TYPE, DATE_INSTALLED, DATE_UNINSTALLED FROM (
WITH TM_PLUS_TMH AS (
WITH TM_TOTAL_TRACKER AS (
SELECT
    TM.ASSET_ID AS ASSET_ID
    ,
    AST.NAME AS ASSET_NAME
    ,
    TM.COMPANY_ID AS COMPANY_ID
    ,
    TM.COMPANY_NAME AS COMPANY_NAME
    ,
    TM.TRACKER_ID AS TRACKER_ID
    ,
    TM.TRACKER_SERIAL AS TRACKER_SERIAL
    ,
    DATE(TM.TRACKER_LAST_DATE_INSTALLED) AS INSTALL_DATE
    ,
    DATE(ATA.DATE_UNINSTALLED) AS UNINSTALL_DATE
    ,
    CASE
        WHEN ATA.TRACKER_ID IS NOT NULL THEN 'TM'
        ELSE 'TM'
    END AS SOURCE
FROM ANALYTICS.BI_OPS.TELEMATICS_MOTHERSHIP TM
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSET_TRACKER_ASSIGNMENTS ATA
    ON TM.TRACKER_ID = ATA.TRACKER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS AST
    ON AST.ASSET_ID = ATA.ASSET_ID
WHERE TM.TRACKER_ID IS NOT NULL
    AND TM.TRACKER_SERIAL IS NOT NULL
    AND TM.TRACKER_LAST_DATE_INSTALLED IS NOT NULL
)
, TMH_TOTAL_TRACKER AS (
SELECT DISTINCT
    TMH.ASSET_ID AS ASSET_ID
    ,
    AST.NAME AS ASSET_NAME
    ,
    TMH.COMPANY_ID AS COMPANY_ID
    ,
    TMH.COMPANY_NAME AS COMPANY_NAME
    ,
    TMH.TRACKER_ID AS TRACKER_ID
    ,
    TMH.TRACKER_SERIAL AS TRACKER_SERIAL
    ,
    DATE(TMH.TRACKER_LAST_DATE_INSTALLED) AS INSTALL_DATE
    ,
    DATE(ATA.DATE_UNINSTALLED) AS UNINSTALL_DATE
    ,
    CASE
        WHEN ATA.TRACKER_ID IS NOT NULL THEN 'TMH'
        ELSE 'TMH'
    END AS SOURCE
FROM ANALYTICS.BI_OPS.TELEMATICS_MOTHERSHIP_HIST TMH
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSET_TRACKER_ASSIGNMENTS ATA
    ON TMH.TRACKER_ID = ATA.TRACKER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS AST
    ON AST.ASSET_ID = ATA.ASSET_ID
WHERE TMH.TRACKER_ID IS NOT NULL
    AND TMH.TRACKER_SERIAL IS NOT NULL
    AND TMH.TRACKER_LAST_DATE_INSTALLED IS NOT NULL
)
SELECT * FROM TMH_TOTAL_TRACKER WHERE TMH_TOTAL_TRACKER.TRACKER_ID NOT IN (SELECT TM_TOTAL_TRACKER.TRACKER_ID FROM TM_TOTAL_TRACKER)
UNION
SELECT * FROM TM_TOTAL_TRACKER WHERE TM_TOTAL_TRACKER.TRACKER_ID NOT IN (SELECT TMH_TOTAL_TRACKER.TRACKER_ID FROM TMH_TOTAL_TRACKER)
)
,
ESP_TOTAL_TRACKER AS (
SELECT
    ATA.ASSET_ID AS ASSET_ID
    ,
    AST.NAME AS ASSET_NAME
    ,
    ATA.COMPANY_ID AS COMPANY_ID
    ,
    COM.NAME AS COMPANY_NAME
    ,
    ATA.TRACKER_ID AS TRACKER_ID
    ,
    TRA.DEVICE_SERIAL AS TRACKER_SERIAL
    ,
    DATE(ATA.DATE_INSTALLED) AS DATE_INSTALLED
    ,
    DATE(ATA.DATE_UNINSTALLED) AS DATE_UNINSTALLED
    ,
    CASE
        WHEN ATA.TRACKER_ID IS NOT NULL THEN 'ESP'
        ELSE 'ESP'
    END AS SOURCE
FROM ES_WAREHOUSE.PUBLIC.ASSET_TRACKER_ASSIGNMENTS ATA
LEFT JOIN ES_WAREHOUSE.PUBLIC.TRACKERS TRA
    ON TRA.TRACKER_ID = ATA.TRACKER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS AST
    ON AST.ASSET_ID = ATA.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES COM
    ON COM.COMPANY_ID = ATA.COMPANY_ID
)
SELECT * FROM ESP_TOTAL_TRACKER WHERE ESP_TOTAL_TRACKER.TRACKER_ID NOT IN (SELECT TM_PLUS_TMH.TRACKER_ID FROM TM_PLUS_TMH)
UNION
SELECT * FROM TM_PLUS_TMH WHERE TM_PLUS_TMH.TRACKER_ID NOT IN (SELECT ESP_TOTAL_TRACKER.TRACKER_ID FROM ESP_TOTAL_TRACKER)
ORDER BY TRACKER_ID
)

--TOTAL CAMERAS ASSIGNMENTS--
UNION

SELECT ASSET_ID, ASSET_NAME, CAMERA_ID AS DEVICE_ID, CAMERA_SERIAL AS DEVICE_SERIAL, 'CAMERA' AS DEVICE_TYPE, DATE_INSTALLED, DATE_UNINSTALLED FROM (
WITH TM_PLUS_TMH AS (
WITH TM_TOTAL_CAMERA AS (
SELECT
    TM.ASSET_ID AS ASSET_ID
    ,
    AST.NAME AS ASSET_NAME
    ,
    TM.COMPANY_ID AS COMPANY_ID
    ,
    TM.COMPANY_NAME AS COMPANY_NAME
    ,
    TM.CAMERA_ID AS CAMERA_ID
    ,
    TM.CAMERA_SERIAL AS CAMERA_SERIAL
    ,
    DATE(TM.TRACKER_LAST_DATE_INSTALLED) AS INSTALL_DATE
    ,
    DATE(ATA.DATE_UNINSTALLED) AS UNINSTALL_DATE
    ,
    CASE
        WHEN ACA.CAMERA_ID IS NOT NULL THEN 'TM'
        ELSE 'TM'
    END AS SOURCE
FROM ANALYTICS.BI_OPS.TELEMATICS_MOTHERSHIP TM
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSET_CAMERA_ASSIGNMENTS ACA
    ON TM.CAMERA_ID = ACA.CAMERA_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSET_TRACKER_ASSIGNMENTS ATA
    ON TM.TRACKER_ID = ATA.TRACKER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS AST
    ON AST.ASSET_ID = ACA.ASSET_ID
WHERE TM.CAMERA_ID IS NOT NULL
    AND TM.CAMERA_SERIAL IS NOT NULL
    AND TM.TRACKER_LAST_DATE_INSTALLED IS NOT NULL
)
, TMH_TOTAL_CAMERA AS (
SELECT DISTINCT
    TMH.ASSET_ID AS ASSET_ID
    ,
    AST.NAME AS ASSET_NAME
    ,
    TMH.COMPANY_ID AS COMPANY_ID
    ,
    TMH.COMPANY_NAME AS COMPANY_NAME
    ,
    TMH.CAMERA_ID AS CAMERA_ID
    ,
    TMH.CAMERA_SERIAL AS CAMERA_SERIAL
    ,
    DATE(TMH.TRACKER_LAST_DATE_INSTALLED) AS INSTALL_DATE
    ,
    DATE(ATA.DATE_UNINSTALLED) AS UNINSTALL_DATE
    ,
    CASE
        WHEN ACA.CAMERA_ID IS NOT NULL THEN 'TMH'
        ELSE 'TMH'
    END AS SOURCE
FROM ANALYTICS.BI_OPS.TELEMATICS_MOTHERSHIP_HIST TMH
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSET_CAMERA_ASSIGNMENTS ACA
    ON TMH.CAMERA_ID = ACA.CAMERA_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSET_TRACKER_ASSIGNMENTS ATA
    ON TMH.TRACKER_ID = ATA.TRACKER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS AST
    ON AST.ASSET_ID = ACA.ASSET_ID
WHERE TMH.CAMERA_ID IS NOT NULL
    AND TMH.CAMERA_SERIAL IS NOT NULL
    AND TMH.TRACKER_LAST_DATE_INSTALLED IS NOT NULL
)
SELECT * FROM TM_TOTAL_CAMERA WHERE TM_TOTAL_CAMERA.CAMERA_ID NOT IN (SELECT TMH_TOTAL_CAMERA.CAMERA_ID FROM TMH_TOTAL_CAMERA)
UNION
SELECT * FROM TMH_TOTAL_CAMERA WHERE TMH_TOTAL_CAMERA.CAMERA_ID NOT IN (SELECT TM_TOTAL_CAMERA.CAMERA_ID FROM TM_TOTAL_CAMERA)
)
,
ESP_TOTAL_CAMERA AS (
SELECT
    ACA.ASSET_ID AS ASSET_ID
    ,
    AST.NAME AS ASSET_NAME
    ,
    AST.COMPANY_ID AS COMPANY_ID
    ,
    COM.NAME AS COMPANY_NAME
    ,
    ACA.CAMERA_ID AS CAMERA_ID
    ,
    CAM.device_serial AS CAMERA_SERIAL
    ,
    DATE(ATA.DATE_INSTALLED) AS DATE_INSTALLED
    ,
    DATE(ATA.DATE_UNINSTALLED) AS DATE_UNINSTALLED
    ,
    CASE
        WHEN ACA.CAMERA_ID IS NOT NULL THEN 'ESP'
        ELSE 'ESP'
    END AS SOURCE
FROM ES_WAREHOUSE.PUBLIC.ASSET_CAMERA_ASSIGNMENTS ACA
LEFT JOIN ES_WAREHOUSE.PUBLIC.CAMERAS CAM
    ON CAM.CAMERA_ID = ACA.CAMERA_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS AST
    ON AST.ASSET_ID = ACA.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSET_TRACKER_ASSIGNMENTS ATA
    ON AST.TRACKER_ID = ATA.TRACKER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES COM
    ON COM.COMPANY_ID = AST.COMPANY_ID
)
SELECT * FROM ESP_TOTAL_CAMERA WHERE ESP_TOTAL_CAMERA.CAMERA_ID NOT IN (SELECT TM_PLUS_TMH.CAMERA_ID FROM TM_PLUS_TMH)
UNION
SELECT * FROM TM_PLUS_TMH WHERE TM_PLUS_TMH.CAMERA_ID NOT IN (SELECT ESP_TOTAL_CAMERA.CAMERA_ID FROM ESP_TOTAL_CAMERA)
ORDER BY CAMERA_ID
)
--TOTAL KEYPADS ASSIGNMENTS--
UNION

SELECT ASSET_ID, ASSET_NAME, KEYPAD_ID AS DEVICE_ID, KEYPAD_SERIAL AS DEVICE_SERIAL, 'KEYPAD' AS DEVICE_TYPE, DATE_INSTALLED, DATE_UNINSTALLED FROM (
WITH TM_PLUS_TMH AS (
WITH TM_TOTAL_KEYPAD AS (
SELECT
    TM.ASSET_ID AS ASSET_ID
    ,
    AST.NAME AS ASSET_NAME
    ,
    TM.COMPANY_ID AS COMPANY_ID
    ,
    TM.COMPANY_NAME AS COMPANY_NAME
    ,
    TM.KEYPAD_ID AS KEYPAD_ID
    ,
    TM.KEYPAD_SERIAL AS KEYPAD_SERIAL
    ,
    DATE(TM.TRACKER_LAST_DATE_INSTALLED) AS INSTALL_DATE
    ,
    DATE(ATA.DATE_UNINSTALLED) AS UNINSTALL_DATE
    ,
    CASE
        WHEN AKA.KEYPAD_ID IS NOT NULL THEN 'TM'
        ELSE 'TM'
    END AS SOURCE
FROM ANALYTICS.BI_OPS.TELEMATICS_MOTHERSHIP TM
LEFT JOIN ES_WAREHOUSE.PUBLIC.KEYPAD_ASSET_ASSIGNMENTS AKA
    ON TM.KEYPAD_ID = AKA.KEYPAD_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSET_TRACKER_ASSIGNMENTS ATA
    ON TM.TRACKER_ID = ATA.TRACKER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS AST
    ON AST.ASSET_ID = AKA.ASSET_ID
WHERE TM.KEYPAD_ID IS NOT NULL
    AND TM.KEYPAD_SERIAL IS NOT NULL
    AND TM.TRACKER_LAST_DATE_INSTALLED IS NOT NULL
)
, TMH_TOTAL_KEYPAD AS (
SELECT DISTINCT
    TMH.ASSET_ID AS ASSET_ID
    ,
    AST.NAME AS ASSET_NAME
    ,
    TMH.COMPANY_ID AS COMPANY_ID
    ,
    TMH.COMPANY_NAME AS COMPANY_NAME
    ,
    TMH.KEYPAD_ID AS KEYPAD_ID
    ,
    TMH.KEYPAD_SERIAL AS KEYPAD_SERIAL
    ,
    DATE(TMH.TRACKER_LAST_DATE_INSTALLED) AS INSTALL_DATE
    ,
    DATE(ATA.DATE_UNINSTALLED) AS UNINSTALL_DATE
    ,
    CASE
        WHEN AKA.KEYPAD_ID IS NOT NULL THEN 'TMH'
        ELSE 'TMH'
    END AS SOURCE
FROM ANALYTICS.BI_OPS.TELEMATICS_MOTHERSHIP_HIST TMH
LEFT JOIN ES_WAREHOUSE.PUBLIC.KEYPAD_ASSET_ASSIGNMENTS AKA
    ON TMH.KEYPAD_ID = AKA.KEYPAD_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSET_TRACKER_ASSIGNMENTS ATA
    ON TMH.TRACKER_ID = ATA.TRACKER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS AST
    ON AST.ASSET_ID = AKA.ASSET_ID
WHERE TMH.KEYPAD_ID IS NOT NULL
    AND TMH.KEYPAD_SERIAL IS NOT NULL
    AND TMH.TRACKER_LAST_DATE_INSTALLED IS NOT NULL
)
SELECT * FROM TM_TOTAL_KEYPAD WHERE TM_TOTAL_KEYPAD.KEYPAD_ID NOT IN (SELECT TMH_TOTAL_KEYPAD.KEYPAD_ID FROM TMH_TOTAL_KEYPAD)
UNION
SELECT * FROM TMH_TOTAL_KEYPAD WHERE TMH_TOTAL_KEYPAD.KEYPAD_ID NOT IN (SELECT TM_TOTAL_KEYPAD.KEYPAD_ID FROM TM_TOTAL_KEYPAD)
)
,
ESP_TOTAL_KEYPAD AS (
SELECT
    AKA.ASSET_ID AS ASSET_ID
    ,
    AST.NAME AS ASSET_NAME
    ,
    AST.COMPANY_ID AS COMPANY_ID
    ,
    COM.NAME AS COMPANY_NAME
    ,
    AKA.KEYPAD_ID AS KEYPAD_ID
    ,
    KPD.SERIAL_NUMBER AS KEYPAD_SERIAL
    ,
    DATE(ATA.DATE_INSTALLED) AS DATE_INSTALLED
    ,
    DATE(ATA.DATE_UNINSTALLED) AS DATE_UNINSTALLED
    ,
    CASE
        WHEN AKA.KEYPAD_ID IS NOT NULL THEN 'ESP'
        ELSE 'ESP'
    END AS SOURCE
FROM ES_WAREHOUSE.PUBLIC.KEYPAD_ASSET_ASSIGNMENTS AKA
LEFT JOIN ES_WAREHOUSE.PUBLIC.KEYPADS KPD
    ON KPD.KEYPAD_ID = AKA.KEYPAD_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS AST
    ON AST.ASSET_ID = AKA.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSET_TRACKER_ASSIGNMENTS ATA
    ON AST.TRACKER_ID = ATA.TRACKER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES COM
    ON COM.COMPANY_ID = AST.COMPANY_ID
)
SELECT * FROM ESP_TOTAL_KEYPAD WHERE ESP_TOTAL_KEYPAD.KEYPAD_ID NOT IN (SELECT TM_PLUS_TMH.KEYPAD_ID FROM TM_PLUS_TMH)
UNION
SELECT * FROM TM_PLUS_TMH WHERE TM_PLUS_TMH.KEYPAD_ID NOT IN (SELECT ESP_TOTAL_KEYPAD.KEYPAD_ID FROM ESP_TOTAL_KEYPAD)
ORDER BY KEYPAD_ID
)
)
      ;;
    }

    dimension: ASSET_ID {
      type: string
      sql: ${TABLE}.ASSET_ID ;;
    }

    dimension: ASSET_NAME {
      type: string
      sql:  ${TABLE}.ASSET_NAME ;;
    }

  dimension: DEVICE_ID {
    type: string
    sql:  ${TABLE}.DEVICE_ID ;;
  }

    dimension: DEVICE_SERIAL {
      type: string
      sql: ${TABLE}.DEVICE_SERIAL ;;
    }

    dimension: DEVICE_TYPE {
      type: string
      sql: ${TABLE}.DEVICE_TYPE ;;
    }

    dimension: DATE_INSTALLED {
      type: date
      sql: ${TABLE}.DATE_INSTALLED ;;
    }

    dimension: DATE_UNINSTALLED {
      type: date
      sql: ${TABLE}.DATE_UNINSTALLED ;;
    }

    dimension: SERIAL_NUMBER_INSTALL_INSTANCE {
      type: number
      sql: ${TABLE}.SERIAL_NUMBER_INSTALL_INSTANCE;;
    }

  }
