view: 6b_copy {
  derived_table: {
    sql:

    --SUMMARY
SELECT
    *
    ,
    CONCAT(DYNAMIC_INDEX, TO_VARCHAR(UNINSTALLED_DATE)) AS UNINSTALL_STR_INDEX
    ,
    CONCAT(CONTRACT_DEAL_ID, SHIPPED_DEVICE_SERIAL) AS SHIPPED_STR_INDEX
    ,
    CONCAT(DYNAMIC_INDEX, ASSIGNMENT_DEVICE_SERIAL) AS ASSIGNED_STR_INDEX
FROM
(
SELECT row_number() OVER (ORDER BY CONTRACT_DEAL_ID) AS DYNAMIC_INDEX, *
FROM
(
SELECT * FROM
(
WITH DEALS AS
(
SELECT
    QUANTITY, CONTRACT_MRR, ES_ADMIN_ID, COMPANY_NAME, CONTRACT_DEAL_ID
    ,
    CASE
        WHEN CONTRACT_NAME LIKE '%36M' AND TERMS_END_DATE < SYSDATE() THEN REPLACE(CONTRACT_NAME, '36M', 'M2M')
        WHEN CONTRACT_NAME LIKE '%24M' AND TERMS_END_DATE < SYSDATE() THEN REPLACE(CONTRACT_NAME, '24M', 'M2M')
        WHEN CONTRACT_NAME LIKE '%12M' AND TERMS_END_DATE < SYSDATE() THEN REPLACE(CONTRACT_NAME, '12M', 'M2M')
        WHEN CONTRACT_NAME LIKE '%60M' AND TERMS_END_DATE < SYSDATE() THEN REPLACE(CONTRACT_NAME, '60M', 'M2M')
        ELSE CONTRACT_NAME
    END AS CONTRACT_NAME
    ,
    LINKED_ASSET_TYPE, TERMS_IN_MONTHS, CONTRACT_CLOSE_DATE, TERMS_END_DATE, BUNDLE_INSTALL_STATUS
FROM
(
SELECT
    SUM(PROPERTY_QUANTITY) AS QUANTITY,
    SUM(PROPERTY_AMOUNT) AS CONTRACT_MRR,
    PROPERTY_ES_ADMIN_ID AS ES_ADMIN_ID,
    PROPERTY_COMPANY_NAME AS COMPANY_NAME,
    DEAL_ID AS CONTRACT_DEAL_ID,
    CASE
        WHEN PROPERTY_NAME = 'Powered - Month to Month' THEN 'Powered - M2M'
        WHEN PROPERTY_NAME = 'Powered Tracker- Monthly' THEN 'Powered - M2M'
        WHEN PROPERTY_NAME = 'Non Powered Tracker- Monthly' THEN 'Non Powered - M2M'
        WHEN PROPERTY_NAME = 'Non Powered - Month to Month' THEN 'Non Powered - M2M'
        WHEN PROPERTY_NAME = 'Vehicle - Month to Month' THEN 'Vehicle - M2M'
        WHEN PROPERTY_NAME = 'Vehicle Tracker- Month to Month' THEN 'Vehicle - M2M'
        WHEN PROPERTY_NAME = 'MC4+ 36 Month Bundle' THEN 'Powered - 36M'
        WHEN PROPERTY_NAME = 'Plan - Track - 36 Month Bundle' THEN 'Powered - 36M'
        WHEN PROPERTY_NAME = 'Powered - 36 Month Bundle' THEN 'Powered - 36M'
        WHEN PROPERTY_NAME = 'Powered Tracker- 36 Month Bundle' THEN 'Powered - 36M'
        WHEN PROPERTY_NAME = 'Vehicle - 36 Month Bundle' THEN 'Vehicle - 36M'
        WHEN PROPERTY_NAME = 'Vehicle Tracker- 36 Month Bundle' THEN 'Vehicle - 36M'
        WHEN PROPERTY_NAME = 'T3 Fleet Cam 36 Month' THEN 'Camera - 36M'
        WHEN PROPERTY_NAME = 'Non Powered - 36 Month Bundle' THEN 'Non Powered - 36M'
        WHEN PROPERTY_NAME = 'Vehicle - Month to Month M2M' THEN 'Vehicle - M2M'
        WHEN PROPERTY_NAME = 'Vehicle - 12 Month Bundle' THEN 'Vehicle - 12M'
        WHEN PROPERTY_NAME = 'T3 Fleet Cam and Tracker - 36 Month' THEN 'T3 Fleet Cam and Tracker - 36M'
        WHEN PROPERTY_NAME = 'Non Powered Tracker- 36 Month Bundle' THEN 'Non Powered - 36M'
        WHEN PROPERTY_NAME = 'Vehicle HD w/ELD - 36 Month Bundle' THEN 'Vehicle HD w/ELD - 36M'
        WHEN PROPERTY_NAME = 'HD Vehicle w/ELD - 36 Month Bundle' THEN 'Vehicle HD w/ELD - 36M'
        WHEN PROPERTY_NAME = 'T3aaS Includes Install' THEN 'T3aaS Includes Install - M2M'
        WHEN PROPERTY_NAME = 'T3aaS Bluetooth Plan - 12 Months' THEN 'T3aaS Bluetooth Plan - 12M'
        WHEN PROPERTY_NAME = 'T3aaS Bluetooth Plan - 12 Months' THEN 'T3aaS Bluetooth Plan - 12M'
        WHEN PROPERTY_NAME = 'T3aaS Fleet Cam Add On 36 Months' THEN 'T3aaS Fleet Cam Add On - 36M'
        WHEN PROPERTY_NAME = 'T3aaS Fleet Cam Add On' THEN 'T3aaS Fleet Cam Add On - M2M'
        WHEN PROPERTY_NAME = 'T3aaS T3 Fleet Cam Add On 36 Months' THEN 'T3aaS Fleet Cam Add On - 36M'
        WHEN PROPERTY_NAME = 'T3aaS Includes Install with T3 Fleet Cam' THEN 'T3aaS Includes Install with T3 Fleet Cam - M2M'
        WHEN PROPERTY_NAME = 'Vehicle - 24 Month Bundle' THEN 'Vehicle - 24M'
        WHEN PROPERTY_NAME = 'Powered - 24 Month Bundle' THEN 'Powered - 24M'
        WHEN PROPERTY_NAME = 'Non Powered - 24 Month Bundle' THEN 'Non Powered - 24M'
        WHEN PROPERTY_NAME = 'Sprint Plan - Track - 36 Month BUN' THEN 'Sprint - 36M'
        WHEN PROPERTY_NAME = 'Sprint Plan - Track - 36 Month BUN' THEN 'Sprint - 36M'
        WHEN PROPERTY_NAME = 'Plan - Track 36 Month Bundle' THEN 'Powered - 36M'
        WHEN PROPERTY_NAME = 'T3 Fleet Cam Monthly' THEN 'Camera - M2M'
        WHEN PROPERTY_NAME = 'Powered - 60 Month Bundle' THEN 'Powered - 60M'
        WHEN PROPERTY_NAME = 'Plan - Track 60 Month Bundle' THEN 'Powered - 60M'
        WHEN PROPERTY_NAME = 'Plan - Track - 1 Month' THEN 'Powered - M2M'
        WHEN PROPERTY_NAME = 'Plan - Track - 60 Month - Non PW Bundle' THEN 'Non Powered - 60M'
        WHEN PROPERTY_NAME = 'Plan - Track - 60 Month Bundle' THEN 'Powered - 60M'
        WHEN PROPERTY_NAME = 'T3aaS Subscription with Self Install - Vehicle' THEN 'Vehicle - M2M'
        WHEN PROPERTY_NAME = 'T3aaS Subscription with Self Install - Powered Equipment' THEN 'Powered - M2M'
        ELSE PROPERTY_NAME
    END AS CONTRACT_NAME,
    LINKED_ASSET_TYPE AS LINKED_ASSET_TYPE,
    TERMS_IN_MONTHS AS TERMS_IN_MONTHS,
    CLOSE_DATE AS CONTRACT_CLOSE_DATE,
    TERMS_END_DATE AS TERMS_END_DATE,
    CASE
        WHEN PROPERTY_NAME LIKE '%Includes Install%' THEN 'Install Included'
        WHEN PROPERTY_NAME LIKE '%Includes Install' THEN 'Install Included'
        WHEN PROPERTY_NAME LIKE 'Includes Install%' THEN 'Install Included'
        ELSE 'Install Not Included'
    END AS BUNDLE_INSTALL_STATUS
FROM
(
SELECT
    DEAL.PROPERTY_ES_ADMIN_ID AS PROPERTY_ES_ADMIN_ID,
    DEAL.PROPERTY_COMPANY_NAME AS PROPERTY_COMPANY_NAME,
    LI.PROPERTY_PRODUCT_NAME,
    LI.PROPERTY_DESCRIPTION,
    LI.PROPERTY_HS_SKU,
    LI.PROPERTY_BUNDLE_DESCRIPTION,
    LI.PROPERTY_NAME AS PROPERTY_NAME,
    TO_VARCHAR(LI.PROPERTY_LINKED_ASSET_TYPE) AS LINKED_ASSET_TYPE,
    LI.PROPERTY_QUANTITY,
    LI.PROPERTY_AMOUNT,
    (LI.PROPERTY_AMOUNT / LI.PROPERTY_QUANTITY) AS ITEM_MRR,
    TO_VARCHAR(DEAL.DEAL_ID) AS DEAL_ID,
    LI.PROPERTY_HS_TERM_IN_MONTHS AS TERMS_IN_MONTHS,
    -- DEAL.PROPERTY_CLOSEDATE,
    CAST(DEAL.PROPERTY_ACTUAL_CLOSE_DATE AS DATE) AS CLOSE_DATE,
    CAST(DATEADD(MONTH,  LI.PROPERTY_HS_TERM_IN_MONTHS, DEAL.PROPERTY_ACTUAL_CLOSE_DATE) AS DATE) AS TERMS_END_DATE
FROM
    ANALYTICS.HUBSPOT_CUSTOMER_SUCCESS.LINE_ITEM LI
LEFT JOIN
     ANALYTICS.HUBSPOT_CUSTOMER_SUCCESS.LINE_ITEM_DEAL LID
     ON LI.ID = LID.LINE_ITEM_ID
LEFT JOIN
    ANALYTICS.HUBSPOT_CUSTOMER_SUCCESS.DEAL DEAL
    ON DEAL.DEAL_ID = LID.DEAL_ID
WHERE
    LI.PROPERTY_AMOUNT > 0
    AND DEAL.DEAL_PIPELINE_STAGE_ID = '20251023'
    AND LI.PROPERTY_LINKED_ASSET_TYPE IS NOT NULL
    AND LI.PROPERTY_AMOUNT > 0
    AND LI._FIVETRAN_DELETED = 'FALSE'
    -- AND DEAL.PROPERTY_COMPANY_NAME LIKE '5K Dirtworks%'
    -- OR LI.PROPERTY_NAME <> 'T3 Camera - Standard Mount'
    -- OR LI.PROPERTY_NAME <> 'T3 Install Fee'
    -- OR LI.PROPERTY_NAME <> 'T3 Install Hourly Rate'
    -- OR LI.PROPERTY_NAME <> 'ES Install Hourly Rate'
    -- OR LI.PROPERTY_NAME <> 'Harness'
)
GROUP BY
    ITEM_MRR, PROPERTY_ES_ADMIN_ID, PROPERTY_COMPANY_NAME, DEAL_ID, PROPERTY_NAME, LINKED_ASSET_TYPE, TERMS_END_DATE, TERMS_IN_MONTHS, CONTRACT_CLOSE_DATE, TERMS_END_DATE
ORDER BY
    DEAL_ID
)
)
, SHIPMENTS AS
(
SELECT * FROM
(
WITH TRACKTOSN AS (
    WITH SHIPPED AS (
        SELECT
            TO_VARCHAR(SERIAL_NUMBER) AS SERIAL_NUMBER,
            TO_VARCHAR(FORMATTED_SERIAL) AS FORMATTED_SERIAL,
            TO_VARCHAR(PART_DESCRIPTION) AS PART_DESCRIPTION,
            TO_VARCHAR(CUSTOMER_REF) AS CUSTOMER_REF,
            TO_VARCHAR(CUSTOMER_REF_F) AS CUSTOMER_REF_F,
            CASE
                WHEN SHIPPED LIKE '00%' THEN REPLACE(SHIPPED, '00', '20')
                WHEN SHIPPED LIKE '20%' THEN SHIPPED
            END AS SHIPPED
        FROM (
            SELECT
                ID.INVENTSERIALID AS SERIAL_NUMBER,
                REPLACE(ID.INVENTSERIALID, '-', '') AS FORMATTED_SERIAL,
                CPST.NAME AS PART_DESCRIPTION,
                TO_VARCHAR(SALESHEADER.CUSTOMERREF) AS CUSTOMER_REF,
                TO_VARCHAR(SALESHEADER.CUSTOMERREF) AS CUSTOMER_REF_F,
                SALESHEADER.DELIVERYDATE AS SHIPPED
            FROM
                ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.CUSTPACKINGSLIPTRANS CPST
            LEFT JOIN
                ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.INVENTTRANSORIGIN ITO
                ON CPST.INVENTTRANSID = ITO.INVENTTRANSID
            LEFT JOIN
                ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.INVENTTRANS IT
                ON ITO.RECID = IT.INVENTTRANSORIGIN
                AND CPST.PACKINGSLIPID = IT.PACKINGSLIPID
            LEFT JOIN
                ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.INVENTDIM ID
                ON IT.INVENTDIMID = ID.INVENTDIMID
            LEFT JOIN
                ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.CUSTPACKINGSLIPJOUR CPSJ
                ON CPST.PACKINGSLIPID = CPSJ.PACKINGSLIPID
            LEFT JOIN
                ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.WHSSHIPMENTTABLE WHSSHIP
                ON WHSSHIP.ORDERNUM = ITO.REFERENCEID
            LEFT JOIN
                ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.SALESTABLE SALESHEADER
                ON CPST.SALESID = SALESHEADER.SALESID
            WHERE
                ID.INVENTSERIALID IS NOT NULL
            UNION ALL
            SELECT DISTINCT
                SERIAL_NUMBER AS SERIAL_NUMBER,
                SERIALFORMATTED AS FORMATTED_SERIAL,
                PART_DESCRIPTION AS PART_DESCRIPTION,
                TO_VARCHAR(SO_NUMBER) AS CUSTOMER_REF,
                TO_VARCHAR(NUMERIC_SO_NUMBER) AS CUSTOMER_REF_F,
                SHIPPED AS SHIPPED
            FROM
                ANALYTICS.T3_SAAS_BILLING.FISHBOWL_SERIAL_NUMBERS_ON_SHIPMENTS
        )
    )
    , DEVICES AS (
    SELECT
        TRA.DEVICE_SERIAL AS DEVICE_SERIAL
        ,
        CONCAT('TRACKER', TRA.TRACKER_ID) AS DEVICE_ID
    FROM
        ES_WAREHOUSE.PUBLIC.TRACKERS TRA
    UNION
    SELECT
        CAM.DEVICE_SERIAL AS DEVICE_SERIAL
        ,
        CONCAT('CAMERA', CAM.CAMERA_ID) AS DEVICE_ID
    FROM
        ES_WAREHOUSE.PUBLIC.CAMERAS CAM
    )
    , ASSET_ASSIGNMENTS AS (
    SELECT
        CONCAT('TRACKER', ATA.TRACKER_ID) AS DEVICE_ID
        ,
        ATA.DATE_INSTALLED AS DATE_INSTALLED
        ,
        ATA.ASSET_ID AS ASSET_ID
    FROM
        ES_WAREHOUSE.PUBLIC.ASSET_TRACKER_ASSIGNMENTS ATA
    UNION
    SELECT
        CONCAT('CAMERA', ACA.CAMERA_ID) AS DEVICE_ID
        ,
        ACA.DATE_INSTALLED AS DATE_INSTALLED
        ,
        ACA.ASSET_ID AS ASSET_ID
    FROM
        ES_WAREHOUSE.PUBLIC.ASSET_CAMERA_ASSIGNMENTS ACA
    )
        SELECT
            SHIPPED.SHIPPED AS SHIPPED,
            SHIPPED.FORMATTED_SERIAL AS FORMATTED_SERIAL,
            SHIPPED.PART_DESCRIPTION AS PART_DESCRIPTION,
            SHIPPED.CUSTOMER_REF_F AS CUSTOMER_REF_F,
            DEVICES.DEVICE_SERIAL AS TRA_SERIAL,
            ASSET_ASSIGNMENTS.ASSET_ID,
            -- -- , KPA.SERIAL_NUMBER AS KPA_SERIAL
            -- -- , CAM.DEVICE_SERIAL AS CAM_SERIAL
            MIN(ASSET_ASSIGNMENTS.DATE_INSTALLED) AS FIRST_INSTALL
            -- , ATA.DATE_UNINSTALLED
            -- , TV.NAME, 'No tracker vendor' AS VENDOR
            -- , coalesce(TRACK.config_status, 'Unknown') as STATUS
            -- , concat(coalesce(TRACK.script_version, '0'), '.', coalesce(TRACK.config_version, '0')) as VERSION
        FROM
            SHIPPED
        LEFT JOIN
            DEVICES
            ON DEVICES.DEVICE_SERIAL = SHIPPED.FORMATTED_SERIAL
        -- LEFT JOIN
        --     ES_WAREHOUSE.PUBLIC.KEYPADS KPA
        --     ON KPA.SERIAL_NUMBER = SHIPPED.FORMATTED_SERIAL
        -- LEFT JOIN
        --     ES_WAREHOUSE.PUBLIC.CAMERAS CAM
        --     ON CAM.DEVICE_SERIAL = SHIPPED.FORMATTED_SERIAL
        LEFT JOIN
            ASSET_ASSIGNMENTS
            ON ASSET_ASSIGNMENTS.DEVICE_ID = DEVICES.DEVICE_ID
        -- LEFT JOIN
        --     ES_WAREHOUSE.PUBLIC.TRACKER_VENDORS TV
        --     ON TV.TRACKER_VENDOR_ID = TRA.VENDOR_ID
        -- LEFT JOIN
        --     ES_WAREHOUSE.TRACKERS.TRACKERS TRACK
        --     ON TRACK.DEVICE_SERIAL = TRA.DEVICE_SERIAL
        GROUP BY
            SHIPPED.SHIPPED, SHIPPED.FORMATTED_SERIAL, SHIPPED.PART_DESCRIPTION, SHIPPED.CUSTOMER_REF_F, DEVICES.DEVICE_SERIAL, ASSET_ASSIGNMENTS.ASSET_ID
)
, HUBTOSN AS (
    WITH SHIPPED AS (
        SELECT
            TO_VARCHAR(SERIAL_NUMBER) AS SERIAL_NUMBER,
            TO_VARCHAR(FORMATTED_SERIAL) AS FORMATTED_SERIAL,
            TO_VARCHAR(PART_DESCRIPTION) AS PART_DESCRIPTION,
            CASE
                WHEN PART_DESCRIPTION LIKE '%2830%' THEN '2830'
                WHEN PART_DESCRIPTION LIKE '2830%' THEN '2830'
                WHEN PART_DESCRIPTION LIKE '%2830' THEN '2830'
                WHEN PART_DESCRIPTION LIKE '%MC4+%' THEN 'MC4+'
                WHEN PART_DESCRIPTION LIKE 'MC4+%' THEN 'MC4+'
                WHEN PART_DESCRIPTION LIKE '%MC4+' THEN 'MC4+'
                WHEN PART_DESCRIPTION LIKE '%MC4PLUS%' THEN 'MC4+'
                WHEN PART_DESCRIPTION LIKE 'MC4PLUS%' THEN 'MC4+'
                WHEN PART_DESCRIPTION LIKE '%MC4PLUS' THEN 'MC4+'
                WHEN PART_DESCRIPTION LIKE '%MCX101%' THEN 'MCX101'
                WHEN PART_DESCRIPTION LIKE 'MCX101%' THEN 'MCX101'
                WHEN PART_DESCRIPTION LIKE '%MCX101+' THEN 'MCX101'
                WHEN PART_DESCRIPTION LIKE '%FJ2500%' THEN 'FJ2500'
                WHEN PART_DESCRIPTION LIKE 'FJ2500%' THEN 'FJ2500'
                WHEN PART_DESCRIPTION LIKE '%FJ2500' THEN 'FJ2500'
                WHEN PART_DESCRIPTION LIKE '%QUECLINK%' THEN 'Queclink'
                WHEN PART_DESCRIPTION LIKE 'QUECLINK%' THEN 'Queclink'
                WHEN PART_DESCRIPTION LIKE '%QUECLINK' THEN 'Queclink'
                WHEN PART_DESCRIPTION LIKE '%Queclink%' THEN 'Queclink'
                WHEN PART_DESCRIPTION LIKE 'Queclink%' THEN 'Queclink'
                WHEN PART_DESCRIPTION LIKE '%Queclink' THEN 'Queclink'
                WHEN PART_DESCRIPTION LIKE '%QUECKLINK%' THEN 'Queclink'
                WHEN PART_DESCRIPTION LIKE 'QUECKLINK%' THEN 'Queclink'
                WHEN PART_DESCRIPTION LIKE '%QUECKLINK' THEN 'Queclink'
                WHEN PART_DESCRIPTION LIKE '%Quecklink%' THEN 'Queclink'
                WHEN PART_DESCRIPTION LIKE 'Quecklink%' THEN 'Queclink'
                WHEN PART_DESCRIPTION LIKE '%Quecklink' THEN 'Queclink'
                WHEN PART_DESCRIPTION LIKE '%3030%' THEN '3030'
                WHEN PART_DESCRIPTION LIKE '3030%' THEN '3030'
                WHEN PART_DESCRIPTION LIKE '%3030' THEN '3030'
                WHEN PART_DESCRIPTION LIKE '%730%' THEN '730'
                WHEN PART_DESCRIPTION LIKE '730%' THEN '730'
                WHEN PART_DESCRIPTION LIKE '%730' THEN '730'
                WHEN PART_DESCRIPTION LIKE '%OWLCAM%' THEN 'Camera'
                WHEN PART_DESCRIPTION LIKE 'OWLCAM%' THEN 'Camera'
                WHEN PART_DESCRIPTION LIKE '%OWLCAM' THEN 'Camera'
                WHEN PART_DESCRIPTION LIKE '%MC3%' THEN 'MC3'
                WHEN PART_DESCRIPTION LIKE 'MC3%' THEN 'MC3'
                WHEN PART_DESCRIPTION LIKE '%MC3' THEN 'MC3'
                WHEN PART_DESCRIPTION LIKE '%MC-3%' THEN 'MC3'
                WHEN PART_DESCRIPTION LIKE 'MC-3%' THEN 'MC3'
                WHEN PART_DESCRIPTION LIKE '%MC-3' THEN 'MC3'
                WHEN PART_DESCRIPTION LIKE '%FLEETCAM%' THEN 'Camera'
                WHEN PART_DESCRIPTION LIKE 'FLEETCAM%' THEN 'Camera'
                WHEN PART_DESCRIPTION LIKE '%FLEETCAM' THEN 'Camera'
                WHEN PART_DESCRIPTION LIKE '%KEYPAD%' THEN 'Keypad'
                WHEN PART_DESCRIPTION LIKE 'KEYPAD%' THEN 'Keypad'
                WHEN PART_DESCRIPTION LIKE '%KEYPAD' THEN 'Keypad'
                WHEN PART_DESCRIPTION LIKE '%Keypad%' THEN 'Keypad'
                WHEN PART_DESCRIPTION LIKE 'Keypad%' THEN 'Keypad'
                WHEN PART_DESCRIPTION LIKE '%Keypad' THEN 'Keypad'
                WHEN PART_DESCRIPTION LIKE '%720%' THEN '720'
                WHEN PART_DESCRIPTION LIKE '720%' THEN '720'
                WHEN PART_DESCRIPTION LIKE '%720' THEN '720'
                WHEN PART_DESCRIPTION LIKE '%Slap-N-Track%' THEN 'Slap-N-Track'
                WHEN PART_DESCRIPTION LIKE 'Slap-N-Track%' THEN 'Slap-N-Track'
                WHEN PART_DESCRIPTION LIKE '%Slap-N-Track' THEN 'Slap-N-Track'
                WHEN PART_DESCRIPTION LIKE '%BLUETOOTH%' THEN 'Bluetooth'
                WHEN PART_DESCRIPTION LIKE 'BLUETOOTH%' THEN 'Bluetooth'
                WHEN PART_DESCRIPTION LIKE '%BLUETOOTH' THEN 'Bluetooth'
                WHEN PART_DESCRIPTION LIKE '%Bluetooth%' THEN 'Bluetooth'
                WHEN PART_DESCRIPTION LIKE 'Bluetooth%' THEN 'Bluetooth'
                WHEN PART_DESCRIPTION LIKE '%Bluetooth' THEN 'Bluetooth'
                WHEN PART_DESCRIPTION LIKE '%Bluetooth%' THEN 'Bluetooth'
                WHEN PART_DESCRIPTION LIKE 'Bluetooth%' THEN 'Bluetooth'
                WHEN PART_DESCRIPTION LIKE '%Bluetooth' THEN 'Bluetooth'
                WHEN PART_DESCRIPTION LIKE '%keypad%' THEN 'Keypad'
                WHEN PART_DESCRIPTION LIKE 'keypad%' THEN 'Keypad'
                WHEN PART_DESCRIPTION LIKE '%keypad' THEN 'Keypad'
                WHEN PART_DESCRIPTION LIKE '%iBeacon%' THEN 'iBeacon'
                WHEN PART_DESCRIPTION LIKE 'iBeacon%' THEN 'iBeacon'
                WHEN PART_DESCRIPTION LIKE '%iBeacon' THEN 'iBeacon'
                WHEN PART_DESCRIPTION LIKE '%Camera%' THEN 'Camera'
                WHEN PART_DESCRIPTION LIKE 'Camera%' THEN 'Camera'
                WHEN PART_DESCRIPTION LIKE '%Camera' THEN 'Camera'
                WHEN PART_DESCRIPTION LIKE '%CAMERA%' THEN 'Camera'
                WHEN PART_DESCRIPTION LIKE 'CAMERA%' THEN 'Camera'
                WHEN PART_DESCRIPTION LIKE '%CAMERA' THEN 'Camera'
                WHEN PART_DESCRIPTION LIKE '%BT%' THEN 'Bluetooth'
                WHEN PART_DESCRIPTION LIKE 'BT%' THEN 'Bluetooth'
                WHEN PART_DESCRIPTION LIKE '%BT' THEN 'Bluetooth'
                WHEN PART_DESCRIPTION LIKE '%MC4%' THEN 'MC4+'
                WHEN PART_DESCRIPTION LIKE 'MC4%' THEN 'MC4+'
                WHEN PART_DESCRIPTION LIKE '%MC4' THEN 'MC4+'
                WHEN PART_DESCRIPTION LIKE '%MCXM' THEN 'MCX101'
                WHEN PART_DESCRIPTION LIKE '%MCXM%' THEN 'MCX101'
                WHEN PART_DESCRIPTION LIKE 'MCXM%' THEN 'MCX101'
                WHEN PART_DESCRIPTION LIKE '%CAM' THEN 'Camera'
                WHEN PART_DESCRIPTION LIKE '%CAM%' THEN 'Camera'
                WHEN PART_DESCRIPTION LIKE 'CAM%' THEN 'Camera'
                ELSE NULL
            END AS PART_DESCRIPTION_F,
            TO_VARCHAR(CUSTOMER_REF) AS CUSTOMER_REF,
            TO_VARCHAR(CUSTOMER_REF_F) AS CUSTOMER_REF_F,
            SHIPPED AS SHIPPED
        FROM (
            SELECT
                ID.INVENTSERIALID AS SERIAL_NUMBER,
                REPLACE(ID.INVENTSERIALID, '-', '') AS FORMATTED_SERIAL,
                CPST.NAME AS PART_DESCRIPTION,
                TO_VARCHAR(SALESHEADER.CUSTOMERREF) AS CUSTOMER_REF,
                TO_VARCHAR(SALESHEADER.CUSTOMERREF) AS CUSTOMER_REF_F,
                SALESHEADER.DELIVERYDATE AS SHIPPED
            FROM
                ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.CUSTPACKINGSLIPTRANS CPST
            LEFT JOIN
                ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.INVENTTRANSORIGIN ITO
                ON CPST.INVENTTRANSID = ITO.INVENTTRANSID
            LEFT JOIN
                ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.INVENTTRANS IT
                ON ITO.RECID = IT.INVENTTRANSORIGIN
                AND CPST.PACKINGSLIPID = IT.PACKINGSLIPID
            LEFT JOIN
                ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.INVENTDIM ID
                ON IT.INVENTDIMID = ID.INVENTDIMID
            LEFT JOIN ANALYTICS.MICROSOFT_DYNAMICS_365_FNO.SALESTABLE SALESHEADER
                ON CPST.SALESID = SALESHEADER.SALESID
            WHERE
                ID.INVENTSERIALID IS NOT NULL
            UNION ALL
            SELECT DISTINCT
                SERIAL_NUMBER AS SERIAL_NUMBER,
                SERIALFORMATTED AS FORMATTED_SERIAL,
                PART_DESCRIPTION AS PART_DESCRIPTION,
                TO_VARCHAR(SO_NUMBER) AS CUSTOMER_REF,
                TO_VARCHAR(NUMERIC_SO_NUMBER) AS CUSTOMER_REF_F,
                SHIPPED AS SHIPPED
            FROM
                ANALYTICS.T3_SAAS_BILLING.FISHBOWL_SERIAL_NUMBERS_ON_SHIPMENTS
        )
    )
    , CONTRACT AS (
        SELECT
            TO_VARCHAR(DEAL.DEAL_ID) AS DEAL_ID,
            DEAL.PROPERTY_ES_ADMIN_ID AS ADMIN_ID,
            DEAL.PROPERTY_COMPANY_NAME AS COMPANY_NAME,
            LI.PROPERTY_NAME AS CONTRACT_NAME,
            CASE
                WHEN LI.PROPERTY_LINKED_ASSET_TYPE = 'Sprint-720' THEN '720'
                WHEN LI.PROPERTY_LINKED_ASSET_TYPE = 'Sprint-MC3' THEN 'MC3'
                WHEN LI.PROPERTY_LINKED_ASSET_TYPE = 'Morey Slap-N-Track' THEN 'Slap-N-Track'
                WHEN LI.PROPERTY_LINKED_ASSET_TYPE = 'Sentry Keypad' THEN 'Keypad'
                WHEN LI.PROPERTY_LINKED_ASSET_TYPE = 'T3FleetCam' THEN 'Camera'
                WHEN LI.PROPERTY_LINKED_ASSET_TYPE = 'T3Camera' THEN 'Camera'
                ELSE LI.PROPERTY_LINKED_ASSET_TYPE
            END AS LINKED_ASSET_TYPE,
            LI.PROPERTY_QUANTITY AS QUANTITY,
            LI.PROPERTY_AMOUNT AS AMOUNT,
            DIV0NULL(LI.PROPERTY_AMOUNT, LI.PROPERTY_QUANTITY) AS ITEM_MRR,
            DEAL.DEAL_ID AS DEAL_ID_F,
            LI.PROPERTY_HS_TERM_IN_MONTHS AS TERMS_IN_MONTHS,
            DEAL.PROPERTY_ACTUAL_CLOSE_DATE AS CLOSE_DATE,
            DATEADD(MONTH,  LI.PROPERTY_HS_TERM_IN_MONTHS, DEAL.PROPERTY_ACTUAL_CLOSE_DATE) AS TERMS_END_DATE,
            CASE
                WHEN DEAL.DEAL_PIPELINE_STAGE_ID = '20251023' THEN 'T3 Billing Initiated'
                ELSE 'Not Initiated for Billing'
            END AS DEAL_STAGE,
            DEAL.PROPERTY_INSTALLATION_TYPE_ AS INSTALL_TYPE
        FROM
            ANALYTICS.HUBSPOT_CUSTOMER_SUCCESS.LINE_ITEM LI
        LEFT JOIN
            ANALYTICS.HUBSPOT_CUSTOMER_SUCCESS.LINE_ITEM_DEAL LID
            ON LI.ID = LID.LINE_ITEM_ID
        LEFT JOIN
            ANALYTICS.HUBSPOT_CUSTOMER_SUCCESS.DEAL DEAL
            ON LID.DEAL_ID = DEAL.DEAL_ID
        WHERE
            DEAL.DEAL_PIPELINE_STAGE_ID = '20251023'
            AND LI.PROPERTY_LINKED_ASSET_TYPE IS NOT NULL
    )
    SELECT
        CONTRACT.DEAL_ID AS CONTRACT_DEAL_ID,
        CONTRACT.COMPANY_NAME AS COMPANY_NAME,
        CONTRACT.ADMIN_ID AS CONTRACT_ADMIN_ID,
        CONTRACT.CONTRACT_NAME AS CONTRACT_NAME,
        CONTRACT.LINKED_ASSET_TYPE AS LINKED_ASSET_TYPE,
        CONTRACT.ITEM_MRR AS ITEM_MRR,
        CONTRACT.TERMS_IN_MONTHS AS TERMS_IN_MONTHS,
        CONTRACT.CLOSE_DATE AS CLOSE_DATE,
        CONTRACT.TERMS_END_DATE AS TERMS_END_DATE,
        CONTRACT.INSTALL_TYPE AS INSTALL_TYPE,
        SHIPPED.FORMATTED_SERIAL AS FORMATTED_SERIAL
    FROM
        SHIPPED, CONTRACT
    WHERE
        CONTRACT.DEAL_ID = SHIPPED.CUSTOMER_REF_F
        AND PART_DESCRIPTION_F = LINKED_ASSET_TYPE
)
SELECT
    TO_VARCHAR(HUBTOSN.CONTRACT_DEAL_ID) AS CONTRACT_DEAL_ID,
    TRACKTOSN.CUSTOMER_REF_F AS CUSTOMER_REFERENCE,
    HUBTOSN.COMPANY_NAME AS COMPANY_NAME,
    HUBTOSN.CONTRACT_ADMIN_ID AS CONTRACT_ADMIN_ID,
    HUBTOSN.CONTRACT_NAME AS CONTRACT_NAME,
    HUBTOSN.INSTALL_TYPE AS INSTALL_TYPE,
    TO_VARCHAR(HUBTOSN.LINKED_ASSET_TYPE) AS LINKED_TRACKER_TYPE,
    TRACKTOSN.PART_DESCRIPTION AS SHIPPED_PART_DESCRIPTION,
    HUBTOSN.ITEM_MRR AS CONTRACT_ITEM_MRR,
    HUBTOSN.TERMS_IN_MONTHS AS CONTRACT_TERMS_IN_MONTHS,
    CAST(HUBTOSN.CLOSE_DATE AS DATE) AS CONTRACT_CLOSE_DATE,
    CAST(HUBTOSN.TERMS_END_DATE AS DATE) AS CONTRACT_TERMS_END_DATE,
    CAST(TRACKTOSN.SHIPPED AS DATE) AS SHIPPED_DATE,
    CAST(TRACKTOSN.FIRST_INSTALL AS DATE) AS FIRST_INSTALL_DATE,
    TRACKTOSN.FORMATTED_SERIAL AS TRACKER_SERIAL,
    TRACKTOSN.ASSET_ID AS ASSET_ID
FROM
    HUBTOSN, TRACKTOSN
WHERE
    HUBTOSN.FORMATTED_SERIAL = TRACKTOSN.FORMATTED_SERIAL
ORDER BY
    HUBTOSN.CONTRACT_DEAL_ID, HUBTOSN.CONTRACT_NAME, HUBTOSN.CLOSE_DATE
)
)
, ASSIGNMENTS AS
(
SELECT * FROM
(
SELECT
    ATA.ASSET_ID AS ASSET_ID,
    TRA.DEVICE_SERIAL AS TRACKER_SERIAL,
    CAST(TRA.CREATED AS DATE) AS CREATED,
    CAST(TRA.UPDATED AS DATE) AS UPDATED,
    -- -- KPA.SERIAL_NUMBER AS KPA_SERIAL,
    -- -- CAM.DEVICE_SERIAL AS CAM_SERIAL,
    CAST(ATA.DATE_INSTALLED AS DATE) AS INSTALLED,
    CAST(ATA.DATE_UNINSTALLED AS DATE) AS UNINSTALLED,
    ATA.COMPANY_ID AS COMPANY_ID,
    ASSETS.NAME AS ASSET_NAME
FROM
    ES_WAREHOUSE.PUBLIC.ASSET_TRACKER_ASSIGNMENTS ATA
JOIN
    ES_WAREHOUSE.PUBLIC.TRACKERS TRA
    ON ATA.TRACKER_ID = TRA.TRACKER_ID
JOIN
    ES_WAREHOUSE.PUBLIC.ASSETS ASSETS
    ON ATA.ASSET_ID = ASSETS.ASSET_ID
-- LEFT JOIN
--     ES_WAREHOUSE.PUBLIC.KEYPADS KPA
--     ON KPA.SERIAL_NUMBER = SHIPPED.FORMATTED_SERIAL
-- LEFT JOIN
--     ES_WAREHOUSE.PUBLIC.CAMERAS CAM
--     ON CAM.DEVICE_SERIAL = SHIPPED.FORMATTED_SERIAL
ORDER BY
    ATA.ASSET_ID
    )
)
SELECT
    DEALS.QUANTITY AS QUANTITY
    ,
    DEALS.CONTRACT_MRR AS CONTRACT_MRR
    ,
    DEALS.ES_ADMIN_ID AS ES_ADMIN_ID
    ,
    DEALS.COMPANY_NAME AS COMPANY_NAME
    ,
    DEALS.CONTRACT_DEAL_ID AS CONTRACT_DEAL_ID
    ,
    DEALS.CONTRACT_NAME AS CONTRACT_NAME
    ,
    DEALS.LINKED_ASSET_TYPE AS DEAL_LINKED_DEVICE_TYPE
    ,
    DEALS.TERMS_IN_MONTHS AS TERMS_IN_MONTH
    ,
    DEALS.CONTRACT_CLOSE_DATE AS CONTRACT_CLOSE_DATE
    ,
    DEALS.TERMS_END_DATE AS TERMS_END_DATE
    ,
    DEALS.BUNDLE_INSTALL_STATUS AS BUNDLE_INSTALL_STATUS
    ,
    SHIPMENTS.CUSTOMER_REFERENCE AS HUBSPOT_ID
    ,
    SHIPMENTS.LINKED_TRACKER_TYPE AS SHIPPED_LINKED_DEVICE_TYPE
    ,
    SHIPMENTS.SHIPPED_PART_DESCRIPTION  AS WAREHOUSE_PART_DESCRIPTION
    ,
    TO_DATE(SHIPMENTS.SHIPPED_DATE) AS SHIPPED_DATE
    ,
    SHIPMENTS.FIRST_INSTALL_DATE AS FIRST_INSTALL_DATE
    ,
    SHIPMENTS.INSTALL_TYPE AS INSTALL_TYPE
    ,
    SHIPMENTS.TRACKER_SERIAL AS SHIPPED_DEVICE_SERIAL
    ,
    ASSIGNMENTS.ASSET_ID AS ASSET_ID
    ,
    ASSIGNMENTS.TRACKER_SERIAL AS ASSIGNMENT_DEVICE_SERIAL
    ,
    ASSIGNMENTS.CREATED AS CREATED_DATE
    ,
    ASSIGNMENTS.UPDATED AS UPDATED_DATE
    ,
    ASSIGNMENTS.INSTALLED AS INSTALLED_DATE
    ,
    ASSIGNMENTS.UNINSTALLED AS UNINSTALLED_DATE
    ,
    ASSIGNMENTS.COMPANY_ID AS ASSIGNMENT_COMPANY_ID
    ,
    ASSIGNMENTS.ASSET_NAME AS ASSET_NAME
    ,
    CASE
    WHEN ASSIGNMENTS.INSTALLED IS NOT NULL AND ASSIGNMENTS.INSTALLED < ASSIGNMENTS.UNINSTALLED THEN 1
    ELSE 0
END AS DEACTIVATIONS,
CASE
    WHEN SHIPMENTS.FIRST_INSTALL_DATE IS NOT NULL AND ASSIGNMENTS.INSTALLED > ASSIGNMENTS.UNINSTALLED THEN 1
    ELSE 0
END AS LIVE_ASSET,
CASE
    WHEN ASSIGNMENTS.UNINSTALLED IS NULL OR ASSIGNMENTS.INSTALLED > ASSIGNMENTS.UNINSTALLED     AND SHIPMENTS.FIRST_INSTALL_DATE IS NOT NULL
THEN 1
    ELSE 0
END AS REASSIGNMENTS,
    CASE
        WHEN SHIPMENTS.SHIPPED_DATE IS NOT NULL AND SHIPMENTS.FIRST_INSTALL_DATE IS NULL THEN 'UNUSED TRACKER'
        WHEN SHIPMENTS.SHIPPED_DATE IS NULL THEN 'NOT SHIPPED'
        ELSE 'INITIALLY INSTALLED'
        END AS UNUSED_TRACKER,
FROM DEALS
LEFT JOIN
    SHIPMENTS
   ON ((DEALS.CONTRACT_DEAL_ID = SHIPMENTS.CONTRACT_DEAL_ID) AND DEALS.CONTRACT_DEAL_ID = SHIPMENTS.CUSTOMER_REFERENCE) AND  DEALS.LINKED_ASSET_TYPE = SHIPMENTS.LINKED_TRACKER_TYPE
LEFT JOIN
    ASSIGNMENTS
    ON SHIPMENTS.ASSET_ID = ASSIGNMENTS.ASSET_ID
ORDER BY
    DEALS.CONTRACT_DEAL_ID
)
WHERE DEAL_LINKED_DEVICE_TYPE NOT IN ('Sprint - 36M', 'Sprint - M2M')
)
)


      ;;
  }

  dimension: DYNAMIC_INDEX {
    type: number
    sql: ${TABLE}.DYNAMIC_INDEX ;;
    primary_key: yes
  }

  dimension: UNINSTALL_STR_INDEX {
    type: string
    sql: ${TABLE}.UNINSTALL_STR_INDEX ;;
  }

  dimension: SHIPPED_STR_INDEX {
    type: number
    sql: ${TABLE}.SHIPPED_STR_INDEX ;;
  }

  dimension: ASSIGNED_STR_INDEX {
    type: string
    sql: ${TABLE}.ASSIGNED_STR_INDEX ;;
  }

  dimension: QUANTITY {
    type: number
    sql: ${TABLE}.QUANTITY ;;
  }

  dimension: CONTRACT_MRR {
    type: number
    sql: ${TABLE}.CONTRACT_MRR ;;
  }

  dimension: ES_ADMIN_ID {
    type: number
    sql: ${TABLE}.ES_ADMIN_ID ;;
  }

  dimension: COMPANY_NAME {
    type: string
    sql: ${TABLE}.COMPANY_NAME ;;
  }

  dimension: CONTRACT_DEAL_ID {
    type: number
    sql: ${TABLE}.CONTRACT_DEAL_ID ;;
  }

  dimension: CONTRACT_NAME {
    type: string
    sql: ${TABLE}.CONTRACT_NAME ;;
  }


  dimension: DEAL_LINKED_DEVICE_TYPE {
    type: string
    sql: ${TABLE}.DEAL_LINKED_DEVICE_TYPE ;;
  }

  dimension: TERMS_IN_MONTH {
    type: date
    sql: ${TABLE}.TERMS_IN_MONTH ;;
  }

  dimension: CONTRACT_CLOSE_DATE {
    type: date
    sql: ${TABLE}.CONTRACT_CLOSE_DATE ;;
  }

  dimension: TERMS_END_DATE {
    type: date
    sql: ${TABLE}.TERMS_END_DATE ;;
  }

  dimension: BUNDLE_INSTALL_STATUS {
    type: string
    sql: ${TABLE}.BUNDLE_INSTALL_STATUS
        }

      dimension: HUBSPOT_ID {
      type: number
      sql: ${TABLE}.HUBSPOT_ID ;;
  }

  dimension: SHIPPED_LINKED_DEVICE_TYPE {
    type: string
    sql: ${TABLE}.SHIPPED_LINKED_DEVICE_TYPE ;;
  }

  dimension: WAREHOUSE_PART_DESCRIPTION {
    type: string
    sql: ${TABLE}.WAREHOUSE_PART_DESCRIPTION ;;
  }

  dimension: SHIPPED_DATE {
    type: date
    sql: ${TABLE}.SHIPPED_DATE ;;
  }

  dimension: FIRST_INSTALL_DATE {
    type: date
    sql: ${TABLE}.FIRST_INSTALL_DATE ;;
  }

  dimension: INSTALL_TYPE {
    type: string
    sql: ${TABLE}.INSTALL_TYPE ;;
  }


  dimension: SHIPPED_DEVICE_SERIAL {
    type: string
    sql: ${TABLE}.SHIPPED_DEVICE_SERIAL ;;
  }

  dimension: ASSET_ID {
    type: number
    sql: ${TABLE}.ASSET_ID ;;
  }

  dimension: ASSIGNMENT_DEVICE_SERIAL {
    type: string
    sql: ${TABLE}.ASSIGNMENT_DEVICE_SERIAL ;;
  }

  dimension: CREATED_DATE {
    type: date
    sql: ${TABLE}.CREATED_DATE ;;
  }

  dimension: UPDATED_DATE {
    type: date
    sql: ${TABLE}.UPDATED_DATE ;;
  }

  dimension: INSTALLED_DATE {
    type: date
    sql: ${TABLE}.INSTALLED_DATE ;;
  }

  dimension: UNINSTALLED_DATE {
    type: date
    sql: ${TABLE}.UNINSTALLED_DATE ;;
  }

  dimension: ASSIGNMENT_COMPANY_ID {
    type: number
    sql: ${TABLE}.ASSIGNMENT_COMPANY_ID ;;
  }

  dimension: ASSET_NAME {
    type: string
    sql: ${TABLE}.ASSET_NAME ;;
  }

    dimension: DEACTIVATIONS {
      type: number
      sql: CASE
          WHEN ${TABLE}.INSTALLED_DATE IS NOT NULL
               AND ${TABLE}.INSTALLED_DATE < ${TABLE}.UNINSTALLED_DATE THEN 1
          ELSE 0
       END ;;
    }

    dimension: LIVE_ASSET {
      type: number
      sql: CASE
          WHEN ${TABLE}.FIRST_INSTALL_DATE IS NOT NULL
               AND ${TABLE}.INSTALLED_DATE > ${TABLE}.UNINSTALLED_DATE THEN 1
          ELSE 0
       END ;;
    }

    dimension: REASSIGNMENTS {
      type: number
      sql: CASE
          WHEN ${TABLE}.UNINSTALLED_DATE IS NULL
               OR (${TABLE}.INSTALLED_DATE > ${TABLE}.UNINSTALLED_DATE
                   AND ${TABLE}.FIRST_INSTALL_DATE IS NOT NULL) THEN 1
          ELSE 0
       END ;;
    }

    dimension: UNUSED_TRACKER {
      type: string
      sql: CASE
          WHEN ${TABLE}.SHIPPED_DATE IS NOT NULL
               AND ${TABLE}.FIRST_INSTALL_DATE IS NULL THEN 'UNUSED TRACKER'
          WHEN ${TABLE}.SHIPPED_DATE IS NULL THEN 'NOT SHIPPED'
          ELSE 'INITIALLY INSTALLED'
       END ;;
    }
  }
