view: ap_payment_variances {
  derived_table: {
    sql: WITH YTD_VARIANCE_CTE AS (
          SELECT YTD, PRIOR_YTD,CASE WHEN YTD = 1 THEN SUM(PAYMENT_AMOUNT) WHEN PRIOR_YTD = 1 THEN -SUM(PAYMENT_AMOUNT) ELSE 0 END AS PAYMENT_YTD_VARIANCE,
          CASE WHEN PRIOR_YTD = 1 THEN SUM(PAYMENT_AMOUNT) ELSE 0 END AS PRIOR_YTD_PAYMENT
          FROM ANALYTICS.TREASURY.V_AP_ACTUAL_PAYMENTS_2
          GROUP BY YTD, PRIOR_YTD),
          QTD_VARIANCE_CTE AS (
          SELECT QTD, PRIOR_QTD,CASE WHEN QTD = 1 THEN SUM(PAYMENT_AMOUNT) WHEN PRIOR_QTD = 1 THEN -SUM(PAYMENT_AMOUNT) ELSE 0 END AS PAYMENT_QTD_VARIANCE,
          CASE WHEN PRIOR_QTD = 1 THEN SUM(PAYMENT_AMOUNT) ELSE 0 END AS PRIOR_QTD_PAYMENT
          FROM ANALYTICS.TREASURY.V_AP_ACTUAL_PAYMENTS_2
          GROUP BY QTD, PRIOR_QTD),
          MTD_VARIANCE_CTE AS (
          SELECT MTD, PRIOR_MTD,CASE WHEN MTD = 1 THEN SUM(PAYMENT_AMOUNT) WHEN PRIOR_MTD = 1 THEN -SUM(PAYMENT_AMOUNT) ELSE 0 END AS PAYMENT_MTD_VARIANCE,
          CASE WHEN PRIOR_MTD = 1 THEN SUM(PAYMENT_AMOUNT) ELSE 0 END AS PRIOR_MTD_PAYMENT
          FROM ANALYTICS.TREASURY.V_AP_ACTUAL_PAYMENTS_2
          GROUP BY MTD, PRIOR_MTD),
          WEEKLY_VARIANCE_CTE AS (
          SELECT CURRENT_WEEK, PRIOR_WEEK,CASE WHEN CURRENT_WEEK = 1 THEN SUM(PAYMENT_AMOUNT) WHEN PRIOR_WEEK = 1 THEN -SUM(PAYMENT_AMOUNT) ELSE 0 END AS PAYMENT_WEEKLY_VARIANCE,
          CASE WHEN PRIOR_WEEK = 1 THEN SUM(PAYMENT_AMOUNT) ELSE 0 END AS PRIOR_WEEK_PAYMENT
          FROM ANALYTICS.TREASURY.V_AP_ACTUAL_PAYMENTS_2
          GROUP BY CURRENT_WEEK, PRIOR_WEEK)
          SELECT 'YTD' AS VARIANCE_TYPE,SUM(PAYMENT_YTD_VARIANCE) AS YTD_VARIANCE, YTD_VARIANCE/NULLIF(SUM(PRIOR_YTD_PAYMENT),0) AS YTD_PCT_VARIANCE
          FROM YTD_VARIANCE_CTE
          UNION ALL
          SELECT 'QTD' AS VARIANCE_TYPE,SUM(PAYMENT_QTD_VARIANCE) AS QTD_VARIANCE, QTD_VARIANCE/NULLIF(SUM(PRIOR_QTD_PAYMENT),0) AS QTD_PCT_VARIANCE
          FROM QTD_VARIANCE_CTE
          UNION ALL
          SELECT 'MTD' AS VARIANCE_TYPE,SUM(PAYMENT_MTD_VARIANCE) AS MTD_VARIANCE, MTD_VARIANCE/NULLIF(SUM(PRIOR_MTD_PAYMENT),0) AS MTD_PCT_VARIANCE
          FROM MTD_VARIANCE_CTE
          UNION ALL
          SELECT 'WEEKLY' AS VARIANCE_TYPE,SUM(PAYMENT_WEEKLY_VARIANCE) AS WEEKLY_VARIANCE, WEEKLY_VARIANCE/NULLIF(SUM(PRIOR_WEEK_PAYMENT),0) AS WEEKLY_PCT_VARIANCE
          FROM WEEKLY_VARIANCE_CTE
                ;;
  }


  dimension: variance_type {
    type: string
    sql: ${TABLE}.VARIANCE_TYPE ;;
  }

  dimension: ytd_variance {
    type: number
    value_format: "$#,,;-$#,,;-"
    sql: ${TABLE}.YTD_VARIANCE ;;
  }

  dimension: ytd_pct_variance {
    type: number
    value_format: "#.#0%;-#.0%;-"
    sql: ${TABLE}.YTD_PCT_VARIANCE ;;
  }

  }
