view: construction_in_progress {
  derived_table: {
    sql: SELECT APRH.RECORDID AS BILL_NUMBER,
URL.RECORDNO AS URL_BILL_NUMBER,
APRH.VENDORID AS VENDOR_ID,
VEND.NAME AS VENDOR_NAME,
APBPMT.PAYMENTDATE AS PAYMENT_DATE,
APRHPAY.STATE AS STATE,
COA.ACCOUNTNO AS GL_ACCT_NUMBER,
COA.TITLE AS GL_ACCT_NAME,
APRD.ITEMID AS ITEM_ID,
APRD.DEPARTMENTID AS MARKET_ID,
MKT.TITLE AS MARKET_NAME,
URL.RECORD_URL AS BILL_URL,
APRH.YOOZ_URL AS INVOICE_URL,
SUM(APBPMT.AMOUNT) AS PAYMENT_AMOUNT
FROM ANALYTICS.INTACCT.APBILLPAYMENT APBPMT
LEFT JOIN ANALYTICS.INTACCT.APRECORD APRH ON APBPMT.RECORDKEY = APRH.RECORDNO AND APRH.RECORDTYPE IN ('apbill','apadjustment')
LEFT JOIN ANALYTICS.INTACCT.APDETAIL APRD ON APBPMT.PAIDITEMKEY = APRD.RECORDNO AND APRH.RECORDNO = APRD.RECORDKEY
LEFT JOIN ANALYTICS.INTACCT.VENDOR VEND ON APRH.VENDORID = VEND.VENDORID
LEFT JOIN ANALYTICS.INTACCT.GLACCOUNT COA ON
CASE WHEN APRD.ACCOUNTNO = '2014' THEN SUBSTRING(APRD.ITEMID, 2, 4) ELSE APRD.ACCOUNTNO END = COA.ACCOUNTNO
LEFT JOIN ANALYTICS.INTACCT.APRECORD APRHPAY ON APBPMT.PAYMENTKEY = APRHPAY.RECORDNO
LEFT JOIN ANALYTICS.INTACCT.DEPARTMENT AS MKT  ON APRD.DEPARTMENTID::VARCHAR = MKT.DEPARTMENTID::VARCHAR
LEFT JOIN
(SELECT RECORDNO,RECORD_URL
FROM ANALYTICS.PUBLIC.RECORD_URL
WHERE INTACCT_OBJECT = 'APBILL') URL ON APRH.RECORDNO = URL.RECORDNO
WHERE APBPMT.PAYMENTDATE >= '2019-01-01'
AND APBPMT.PAYMENTKEY = APBPMT.PARENTPYMT
AND APRHPAY.RECORDTYPE = 'appayment'
AND COA.ACCOUNTNO = '1509'
GROUP BY ALL
UNION ALL
SELECT APRH.RECORDID AS BILL_NUMBER,
URL.RECORDNO AS URL_BILL_NUMBER,
APRH.VENDORID AS VENDOR_ID,
VEND.NAME AS VENDOR_NAME,
APBPMT.PAYMENTDATE AS PAYMENT_DATE,
APRHPAY.STATE AS STATE,
COA.ACCOUNTNO AS GL_ACCT_NUMBER,
COA.TITLE AS GL_ACCT_NAME,
APRD.ITEMID AS ITEM_ID,
APRD.DEPARTMENTID AS MARKET_ID,
MKT.TITLE AS MARKET_NAME,
URL.RECORD_URL AS BILL_URL,
APRH.YOOZ_URL AS INVOICE_URL,
SUM(APBPMT.AMOUNT) AS PAYMENT_AMOUNT
FROM ANALYTICS.INTACCT.APBILLPAYMENT APBPMT
LEFT JOIN ANALYTICS.INTACCT.APRECORD APRH ON APBPMT.RECORDKEY = APRH.RECORDNO AND APRH.RECORDTYPE IN ('apbill','apadjustment')
LEFT JOIN ANALYTICS.INTACCT.APDETAIL APRD ON APBPMT.PAIDITEMKEY = APRD.RECORDNO AND APRH.RECORDNO = APRD.RECORDKEY
LEFT JOIN ANALYTICS.INTACCT.VENDOR VEND ON APRH.VENDORID = VEND.VENDORID
LEFT JOIN ANALYTICS.INTACCT.GLACCOUNT COA ON
CASE WHEN APRD.ACCOUNTNO = '2014' THEN SUBSTRING(APRD.ITEMID, 2, 4) ELSE APRD.ACCOUNTNO END = COA.ACCOUNTNO
LEFT JOIN ANALYTICS.INTACCT.APRECORD APRHPAY ON APBPMT.PAYMENTKEY = APRHPAY.RECORDNO
LEFT JOIN ANALYTICS.INTACCT.DEPARTMENT AS MKT  ON APRD.DEPARTMENTID::VARCHAR = MKT.DEPARTMENTID::VARCHAR
LEFT JOIN
(SELECT RECORDNO,RECORD_URL
FROM ANALYTICS.PUBLIC.RECORD_URL
WHERE INTACCT_OBJECT = 'APBILL') URL ON APRH.RECORDNO = URL.RECORDNO
WHERE APBPMT.PAYMENTDATE >= '2019-01-01'
AND APBPMT.PAYMENTKEY = APBPMT.PARENTPYMT
AND APRHPAY.RECORDTYPE = 'appayment'
AND COA.ACCOUNTNO = '2014'
AND APRD.ITEMID = 'A1509'
GROUP BY ALL
                ;;
  }

  ########## DIMENSIONS ##########

  dimension: bill_number {
    type: string
    sql: ${TABLE}.BILL_NUMBER ;;
  }


  dimension: vendor_id {
    type: string
    sql: ${TABLE}.VENDOR_ID ;;
  }

  dimension: vendor_name {
    type: string
    sql: ${TABLE}.VENDOR_NAME ;;
  }

  dimension: payment_date {
    type: date
    sql: ${TABLE}.PAYMENT_DATE ;;
  }

  dimension: state {
    type: string
    sql: ${TABLE}.STATE ;;
  }

  dimension: gl_account_number {
    label: "GL Account Number"
    type: string
    sql: ${TABLE}.GL_ACCT_NUMBER ;;
  }

  dimension: gl_account_name {
    label: "GL Account Name"
    type: string
    sql: ${TABLE}.GL_ACCT_NAME ;;
  }

  dimension: item_id {
    type: string
    sql: ${TABLE}.ITEM_ID ;;
  }

  dimension: market_id {
    type: string
    sql: ${TABLE}.MARKET_ID ;;
  }

  dimension: market_name {
    type: string
    sql: ${TABLE}.MARKET_NAME ;;
  }

  dimension: bill_url {
    label: "Link to Bill"
    type: string
    html: <font color="blue "><u><a href = "{{ value }}" target="_blank">Link to Bill</a></u></font>;;
    sql: ${TABLE}.BILL_URL ;;
  }

  dimension: invoice_url {
    label: "Link to Invoice"
    type: string
    html: <font color="blue "><u><a href = "{{ value }}" target="_blank">Link to Invoice</a></u></font>;;
    sql: ${TABLE}.INVOICE_URL ;;
  }

  ########## MEASURES ##########

  measure : payment_amount {
    type: sum
    value_format_name: usd
    drill_fields: [trx_details*]
    sql: ${TABLE}.PAYMENT_AMOUNT ;;
  }

  ########## DRILL_FIELDS ##########

  set: trx_details {
    fields: [market_name,market_id,vendor_name,vendor_id,bill_number,payment_date,state,gl_account_name,gl_account_number,item_id,bill_url,invoice_url,payment_amount]
  }

}
