view: sold_assets_payments_credits {
  derived_table: {
    sql: -- INVOICE DATA
SELECT I.INVOICE_NO AS SALES_INVOICE_NUMBER,'Invoice' AS TYPE,'' AS CREDIT_NOTE_NUMBER,0 AS PAYMENT_ID, LI.ASSET_ID,AA.SERIAL_NUMBER, C.NAME AS CUSTOMER_BUYER,
AA.YEAR,AA.MAKE AS MANUFACTURER_MAKE, AA.MODEL,I.INVOICE_DATE AS SALES_INVOICE_DATE, I.DUE_DATE AS PAYMENT_DUE_DATE, '2099-12-31'::DATE AS CREDIT_DATE,
'2099-12-31'::date AS PAYMENT_POSTED, '' AS PAYMENT_NUMBER, '' AS BANK_ACCOUNT, '' AS SALES_INVOICE_PMT_TYPE,
 LIT.NAME AS TRANSACTION_CATEGORY, VPP.PAYOUT_PROGRAM_NAME AS OWN_PROGRAM, SUM(AA.OEC) AS OEC,
SUM(LI.AMOUNT) AS INVOICE_AMOUNT, 0 AS PAYMENT_AMOUNT, 0 AS CREDIT_AMOUNT, SUM(LI.TAX_AMOUNT) AS TAX_AMOUNT
FROM ES_WAREHOUSE.PUBLIC.LINE_ITEMS AS LI
LEFT JOIN ES_WAREHOUSE.PUBLIC.INVOICES AS I ON LI.INVOICE_ID = I.INVOICE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.LINE_ITEM_TYPES AS LIT ON LI.LINE_ITEM_TYPE_ID = LIT.LINE_ITEM_TYPE_ID
LEFT JOIN ANALYTICS.PUBLIC.MARKET_REGION_XWALK AS MKT ON I.SHIP_FROM:branch_id = MKT.MARKET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C ON I.COMPANY_ID = C.COMPANY_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS_AGGREGATE AS AA ON AA.ASSET_ID = LI.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSET_PURCHASE_HISTORY AS APH ON AA.ASSET_ID = APH.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.FINANCIAL_SCHEDULES AS FS ON APH.FINANCIAL_SCHEDULE_ID = FS.FINANCIAL_SCHEDULE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.V_PAYOUT_PROGRAMS AS VPP ON LI.ASSET_ID = VPP.ASSET_ID
WHERE I.INVOICE_DATE::DATE >= '2022-01-01'
AND LI.LINE_ITEM_TYPE_ID IN (118,111,50,24,80,120,110,81)
GROUP BY I.INVOICE_NO , LI.ASSET_ID,AA.SERIAL_NUMBER, C.NAME ,
AA.YEAR,AA.MAKE , AA.MODEL,I.INVOICE_DATE , I.DUE_DATE,
LIT.NAME, VPP.PAYOUT_PROGRAM_NAME
UNION ALL
-- PAYMENT DATA
SELECT I.INVOICE_NO AS SALES_INVOICE_NUMBER,'Payment' AS TYPE,'' AS CREDIT_NOTE_NUMBER,PMT.PAYMENT_ID AS PAYMENT_ID, LI.ASSET_ID,AA.SERIAL_NUMBER, C.NAME AS CUSTOMER_BUYER,
AA.YEAR,AA.MAKE AS MANUFACTURER_MAKE, AA.MODEL,I.INVOICE_DATE AS SALES_INVOICE_DATE, I.DUE_DATE AS PAYMENT_DUE_DATE, '2099-12-31'::DATE AS CREDIT_DATE,
PA.DATE::DATE AS PAYMENT_POSTED, PMT.REFERENCE AS PAYMENT_NUMBER, BAER.INTACCT_BANK_ACCOUNT_ID AS BANK_ACCOUNT, PM.NAME AS SALES_INVOICE_PMT_TYPE,
 LIT.NAME AS TRANSACTION_CATEGORY, VPP.PAYOUT_PROGRAM_NAME AS OWN_PROGRAM, 0 AS OEC,
0  AS INVOICE_AMOUNT, IFF(SUM(LI.AMOUNT)<>0,SUM(PMT.AMOUNT),0) AS PAYMENT_AMOUNT, 0 AS CREDIT_AMOUNT, 0 AS TAX_AMOUNT
FROM ES_WAREHOUSE.PUBLIC.LINE_ITEMS AS LI
LEFT JOIN ES_WAREHOUSE.PUBLIC.INVOICES AS I ON LI.INVOICE_ID = I.INVOICE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.LINE_ITEM_TYPES AS LIT ON LI.LINE_ITEM_TYPE_ID = LIT.LINE_ITEM_TYPE_ID
LEFT JOIN ANALYTICS.PUBLIC.MARKET_REGION_XWALK AS MKT ON I.SHIP_FROM:branch_id = MKT.MARKET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C ON I.COMPANY_ID = C.COMPANY_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS_AGGREGATE AS AA ON AA.ASSET_ID = LI.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.PAYMENT_APPLICATIONS AS PA ON I.INVOICE_ID = PA.INVOICE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.PAYMENTS AS PMT ON PMT.PAYMENT_ID = PA.PAYMENT_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.BANK_ACCOUNT_ERP_REFS AS BAER ON PMT.BANK_ACCOUNT_ID = BAER.BANK_ACCOUNT_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.PAYMENT_METHOD_TYPES AS PM ON PMT.PAYMENT_METHOD_TYPE_ID = PM.PAYMENT_METHOD_TYPE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSET_PURCHASE_HISTORY AS APH ON AA.ASSET_ID = APH.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.FINANCIAL_SCHEDULES AS FS ON APH.FINANCIAL_SCHEDULE_ID = FS.FINANCIAL_SCHEDULE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.V_PAYOUT_PROGRAMS AS VPP ON LI.ASSET_ID = VPP.ASSET_ID
WHERE I.INVOICE_DATE::DATE >= '2022-01-01'
AND LI.LINE_ITEM_TYPE_ID IN (118,111,50,24,80,120,110,81)
GROUP BY I.INVOICE_NO ,PMT.PAYMENT_ID , LI.ASSET_ID,AA.SERIAL_NUMBER, C.NAME ,
AA.YEAR,AA.MAKE , AA.MODEL,I.INVOICE_DATE , I.DUE_DATE ,
PA.DATE::DATE , PMT.REFERENCE , BAER.INTACCT_BANK_ACCOUNT_ID , PM.NAME ,
 LIT.NAME , VPP.PAYOUT_PROGRAM_NAME
 UNION ALL
-- CREDIT NOTE DATA
SELECT I.INVOICE_NO AS SALES_INVOICE_NUMBER,'Credit' AS TYPE,CN.CREDIT_NOTE_NUMBER AS CREDIT_NOTE_NUMBER,0 AS PAYMENT_ID, LI.ASSET_ID,AA.SERIAL_NUMBER, C.NAME AS CUSTOMER_BUYER,
AA.YEAR,AA.MAKE AS MANUFACTURER_MAKE, AA.MODEL,I.INVOICE_DATE AS SALES_INVOICE_DATE, I.DUE_DATE AS PAYMENT_DUE_DATE, CNLI.DATE_UPDATED AS CREDIT_DATE,
'2099-12-31'::DATE AS PAYMENT_POSTED, '' AS PAYMENT_NUMBER, '' AS BANK_ACCOUNT, '' AS SALES_INVOICE_PMT_TYPE,
 LIT.NAME AS TRANSACTION_CATEGORY, VPP.PAYOUT_PROGRAM_NAME AS OWN_PROGRAM, 0 AS OEC,
0  AS INVOICE_AMOUNT, 0 AS PAYMENT_AMOUNT, SUM(CNLI.CREDIT_AMOUNT) AS CREDIT_AMOUNT, 0 AS TAX_AMOUNT
FROM ES_WAREHOUSE.PUBLIC.LINE_ITEMS AS LI
LEFT JOIN ES_WAREHOUSE.PUBLIC.INVOICES AS I ON LI.INVOICE_ID = I.INVOICE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.LINE_ITEM_TYPES AS LIT ON LI.LINE_ITEM_TYPE_ID = LIT.LINE_ITEM_TYPE_ID
LEFT JOIN ANALYTICS.PUBLIC.MARKET_REGION_XWALK AS MKT ON I.SHIP_FROM:branch_id = MKT.MARKET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C ON I.COMPANY_ID = C.COMPANY_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS_AGGREGATE AS AA ON AA.ASSET_ID = LI.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSET_PURCHASE_HISTORY AS APH ON AA.ASSET_ID = APH.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.FINANCIAL_SCHEDULES AS FS ON APH.FINANCIAL_SCHEDULE_ID = FS.FINANCIAL_SCHEDULE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.V_PAYOUT_PROGRAMS AS VPP ON LI.ASSET_ID = VPP.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.CREDIT_NOTES AS CN ON CN.ORIGINATING_INVOICE_ID = I.INVOICE_ID
LEFT JOIN ANALYTICS.INTACCT.ARRECORD ARR ON CN.CREDIT_NOTE_NUMBER = ARR.RECORDID AND ARR.RECORDTYPE = 'aradjustment'
LEFT JOIN ES_WAREHOUSE.PUBLIC.CREDIT_NOTE_LINE_ITEMS AS CNLI ON CN.CREDIT_NOTE_ID = CNLI.CREDIT_NOTE_ID AND CNLI.LINE_ITEM_ID = LI.LINE_ITEM_ID
WHERE I.INVOICE_DATE::DATE >= '2022-01-01'
AND LI.LINE_ITEM_TYPE_ID IN (118,111,50,24,80,120,110,81)
GROUP BY I.INVOICE_NO ,CN.CREDIT_NOTE_NUMBER , LI.ASSET_ID,AA.SERIAL_NUMBER, C.NAME ,
AA.YEAR,AA.MAKE , AA.MODEL,I.INVOICE_DATE , I.DUE_DATE , CNLI.DATE_UPDATED ,
LIT.NAME , VPP.PAYOUT_PROGRAM_NAME ;;
  }

  ########## DIMENSIONS ##########
  dimension: sales_invoice_number  {
    type: string
    sql: ${TABLE}.SALES_INVOICE_NUMBER ;;
  }

  dimension: type  {
    type: string
    sql: ${TABLE}.TYPE ;;
  }

  dimension: credit_note_number  {
    type: string
    sql: ${TABLE}.CREDIT_NOTE_NUMBER ;;
  }

  dimension: payment_id  {
    type: string
    sql: ${TABLE}.PAYMENT_ID ;;
  }

  dimension: asset_id  {
    type: string
    sql: ${TABLE}.ASSET_ID ;;
  }

  dimension: serial_number  {
    type: string
    sql: ${TABLE}.SERIAL_NUMBER ;;
  }

  dimension: customer_buyer  {
    type: string
    sql: ${TABLE}.CUSTOMER_BUYER ;;
  }

  dimension: year  {
    type: string
    sql: ${TABLE}.YEAR ;;
  }

  dimension: manufacturer_make  {
    type: string
    sql: ${TABLE}.MANUFACTURER_MAKE ;;
  }


  dimension: model  {
    type: string
    sql: ${TABLE}.MODEL ;;
  }

  dimension: payment_number  {
    type: string
    sql: ${TABLE}.PAYMENT_NUMBER ;;
  }

  dimension: bank_account  {
    type: string
    sql: ${TABLE}.BANK_ACCOUNT ;;
  }

  dimension: sales_invoice_payment_type  {
    type: string
    sql: ${TABLE}.SALES_INVOICE_PMT_TYPE ;;
  }

  dimension: transaction_category  {
    type: string
    sql: ${TABLE}.TRANSACTION_CATEGORY ;;
  }

  dimension: own_program  {
  label: "OWN Program"
    type: string
    sql: ${TABLE}.OWN_PROGRAM  ;;
  }


  ########## DATE ##########

  dimension: sales_invoice_date  {
    type: date
    sql: ${TABLE}.SALES_INVOICE_DATE ;;
  }

  dimension: payment_due_date {
    type: date
    sql: ${TABLE}.PAYMENT_DUE_DATE ;;
  }

  dimension: credit_date  {
    type: date
    sql: ${TABLE}.CREDIT_DATE ;;
  }

  dimension: payment_posted  {
    type: date
    sql: ${TABLE}.PAYMENT_POSTED ;;
  }

   ########## MEASURES ##########

  measure: oec  {
    label: "OEC"
    value_format: "$#,##0.#0;($#,##0.#0);-"
    type: sum
    sql: ${TABLE}.OEC ;;
  }

  measure: invoice_amount  {
    type: sum
    value_format: "$#,##0.#0;($#,##0.#0);-"
    sql: ${TABLE}.INVOICE_AMOUNT ;;
  }

  measure: payment_amount  {
    type: sum
    value_format: "$#,##0.#0;($#,##0.#0);-"
    sql: ${TABLE}.PAYMENT_AMOUNT ;;
  }

  measure: credit_amount  {
    type: sum
    value_format: "$#,##0.#0;($#,##0.#0);-"
    sql: ${TABLE}.CREDIT_AMOUNT ;;
  }

  measure: tax_amount  {
    type: sum
    value_format: "$#,##0.#0;($#,##0.#0);-"
    sql: ${TABLE}.TAX_AMOUNT ;;
  }

  }
