view: vendor_audit {

  derived_table: {
    sql:
       WITH DATE_CONTEXT AS (
    SELECT
        CURRENT_DATE AS TODAY,
--IDENTIFIES THE DATE OF QUERY BEING RAN AS START DATE FOR TIME BASED QUERY AGGREGATION.
        DATEADD(MONTH, -1, CURRENT_DATE) AS START_OF_MONTH,
        CURRENT_DATE AS END_OF_MONTH,
        DATEADD(MONTH, -12, CURRENT_DATE) AS START_12M,
--START FOR TRAILING 12

      CASE
      WHEN EXTRACT(MONTH FROM CURRENT_DATE) BETWEEN 1 AND 3 THEN DATEADD(YEAR, -1, DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '3 months')
      WHEN EXTRACT(MONTH FROM CURRENT_DATE) BETWEEN 4 AND 6 THEN DATEADD(YEAR, -1, DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '6 months')
      WHEN EXTRACT(MONTH FROM CURRENT_DATE) BETWEEN 7 AND 9 THEN DATEADD(YEAR, -1, DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '9 months')
      ELSE DATEADD(YEAR, -1, DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '12 months')
      END AS START_OF_QUARTER,

      --ASSUMPTION IS BEING MADE THAT THIS IS A STANDARD CALENDAR YEAR QUARTER. DETERMINE IF THIS IS APPROPRIATE OR IF IT IS A BUSINESS PERIOD, FISCAL YEAR PERIOD.
      DATEADD(DAY, -1, DATEADD(MONTH, 3, START_OF_QUARTER)) AS END_OF_QUARTER,

      DATE_TRUNC('year', CURRENT_DATE) AS START_OF_YEAR,
      DATEADD(YEAR, 1, DATE_TRUNC('year', CURRENT_DATE)) - INTERVAL '1 day' AS END_OF_YEAR,
      --ASSUMES CALENDAR YEAR START JAN 1 TO DEC 31 FOR EXPIRING THIS YEAR.

      -- Fiscal Year Definition (Starting from 01/01/2025)
      DATE '2025-01-01' AS FISCAL_YEAR_START,

      --START FOR FISCAL YEAR QUARTERLY AND ANNUAL BASED ON 01/01/2025 START DATE
      CASE
      WHEN CURRENT_DATE >= DATE '2025-01-01' AND CURRENT_DATE < DATE '2025-04-01' THEN DATE '2025-01-01'
      WHEN CURRENT_DATE >= DATE '2025-04-01' AND CURRENT_DATE < DATE '2025-07-01' THEN DATE '2025-04-01'
      WHEN CURRENT_DATE >= DATE '2025-07-01' AND CURRENT_DATE < DATE '2025-10-01' THEN DATE '2025-07-01'
      ELSE DATE '2025-10-01'
      END AS START_OF_FISCAL_QUARTER,

      DATEADD(DAY, -1, DATEADD(MONTH, 3, START_OF_FISCAL_QUARTER)) AS END_OF_FISCAL_QUARTER,

      DATEADD(YEAR, -1, DATE '2025-01-01') AS START_OF_FISCAL_YEAR,
      DATEADD(DAY, -1, DATEADD(YEAR, 1, START_OF_FISCAL_YEAR)) AS END_OF_FISCAL_YEAR
      )

      SELECT
      COUNT(*) AS TOTAL_VENDORS,
      --QUERY A: TOTAL COUNT
      COUNT(CASE WHEN V.STATUS = 'active' THEN 1 END) as COUNT_ACTIVE_VENDORS,
      --QUERY B: TOTAL ACTIVE VENDORS
      COUNT(CASE WHEN V.STATUS = 'inactive' THEN 1 END) as COUNT_INACTIVE_VENDORS,
      --QUERY B1: TOTAL ACTIVE VENDORS
      COUNT(CASE WHEN V.REQUIRES_COI = TRUE AND V.STATUS= 'active' THEN 1 END) AS COUNT_ACTIVE_VENDORS_REQUIRING_COI,
      --QUERY C: VENDORS THAT REQUIRE A COI (EQUIPMENT RENTALS)
      COUNT(CASE WHEN V.REQUIRES_COI = TRUE AND V.STATUS= 'inactive' THEN 1 END) AS COUNT_INACTIVE_VENDORS_REQUIRING_COI,
      --QUERY C1: INACTIVE VENDORS THAT REQUIRE A COI (EQUIPMENT RENTALS)
      COUNT(CASE WHEN V.COI_URL IS NOT NULL THEN 1 END) AS COUNT_VENDORS_WITH_COI_URL,
      --QUERY D: VENDORS THAT HAVE A CURRENT COI URL FROM HOUNDDOG
      -- ZJ Notes: Cautious on naming of VENDORS_VALID_COI_URL as having a URL on file is not same as VALID non-expired COI
      --JQP UPDATED FEB 20
      COUNT(CASE WHEN V.COI_URL IS NULL AND V.REQUIRES_COI = TRUE  THEN 1 END) AS VENDORS_WITHOUT_COI_URL,
      --QUERY E: VENDORS THAT ARE MISSING COI URL FROM HOUNDDOG
      COUNT(CASE WHEN V.COI_URL IS NULL AND V.REQUIRES_COI = TRUE AND V.STATUS = 'active' THEN 1 END) AS ACTIVE_VENDORS_WITHOUT_COI_URL,
      --QUERY E: VENDORS THAT ARE MISSING COI URL FROM HOUNDDOG
      COUNT(CASE WHEN V.COI_URL IS NULL AND V.REQUIRES_COI = TRUE AND V.STATUS = 'inactive' THEN 1 END) AS INACTIVE_VENDORS_WITHOUT_COI_URL,
      --QUERY E: VENDORS THAT ARE MISSING COI URL FROM HOUNDDOG
      -- ZJ Notes: Not all vendors require COI add "AND V.REQUIRES_COI = TRUE" in CASE statement
      --JQP UPDATED FEB 20

      -- Strict Monthly Expiration Query (Captures Last 1-Month Period Strictly)
      COUNT(CASE
      WHEN V.REQUIRES_COI = TRUE AND V.STATUS = 'active'
      AND V.EARLIEST_COI_EXPIRATION_DATE BETWEEN DATEADD(MONTH, -1, CURRENT_DATE) AND CURRENT_DATE
      THEN 1
      END) AS VENDORS_EXPIRING_THIS_MONTH,
      --QUERY F: CAPTURES COUNT OF EXPIRING COI BASED ON VENDOR DATE STRICTLY FOR THIS MONTH

      -- Strict Quarterly Expiration Query
      COUNT(CASE
      WHEN V.REQUIRES_COI = TRUE AND V.STATUS = 'active'
      AND V.EARLIEST_COI_EXPIRATION_DATE BETWEEN (SELECT START_OF_QUARTER FROM DATE_CONTEXT) AND (SELECT END_OF_QUARTER FROM DATE_CONTEXT)
      THEN 1
      END) AS VENDORS_EXPIRING_THIS_QUARTER,
      --QUERY G: CAPTURES COUNT OF EXPIRING COI BASED ON VENDOR DATE STRICTLY FOR THIS QUARTER

      -- Strict Annual Expiration Query
      COUNT(CASE
      WHEN V.REQUIRES_COI = TRUE AND V.STATUS = 'active'
      AND V.EARLIEST_COI_EXPIRATION_DATE BETWEEN (SELECT START_OF_YEAR FROM DATE_CONTEXT) AND (SELECT END_OF_YEAR FROM DATE_CONTEXT)
      THEN 1
      END) AS VENDORS_EXPIRING_THIS_YEAR,
      --QUERY H: CAPTURES COUNT OF EXPIRING COI BASED ON VENDOR DATE STRICTLY FOR THIS YEAR

      -- Strict Fiscal Year Expiration Queries
      COUNT(CASE
      WHEN V.REQUIRES_COI = TRUE AND V.STATUS = 'active'
      AND V.EARLIEST_COI_EXPIRATION_DATE BETWEEN (SELECT START_OF_FISCAL_QUARTER FROM DATE_CONTEXT) AND (SELECT END_OF_FISCAL_QUARTER FROM DATE_CONTEXT)
      THEN 1
      END) AS VENDORS_EXPIRING_THIS_FISCAL_QUARTER,
      --QUERY I: CAPTURES COUNT OF EXPIRING COI BASED ON VENDOR DATE STRICTLY FOR THIS FISCAL QUARTER

      COUNT(CASE
      WHEN V.REQUIRES_COI = TRUE AND V.STATUS = 'active'
      AND V.EARLIEST_COI_EXPIRATION_DATE BETWEEN (SELECT START_OF_FISCAL_YEAR FROM DATE_CONTEXT) AND (SELECT END_OF_FISCAL_YEAR FROM DATE_CONTEXT)
      THEN 1
      END) AS VENDORS_EXPIRING_THIS_FISCAL_YEAR,
      --QUERY J: CAPTURES COUNT OF EXPIRING COI BASED ON VENDOR DATE STRICTLY FOR THIS FISCAL YEAR

      COUNT(CASE
      WHEN V.REQUIRES_COI = TRUE AND V.STATUS = 'active'
      AND V.EARLIEST_COI_EXPIRATION_DATE IS NULL
      THEN 1
      END) AS VENDORS_WITHOUT_COI_EXPIRATION_DATE
      --QUERY K: CAPTURES COUNT OF VENDORS THAT REQUIRE A COI BUT HAVE NO RECORDED EXPIRATION DATE

      FROM ANALYTICS.INTACCT.VENDOR AS V;
      --ADDITIONAL UPDATES: ADDED A FISCAL YEAR FUNCTION FOR AGGREGATES THAT USES A PREDEFINED DATE.
      --ADDED COUNTS OF COI REQUIRED WITH NO RECORDED EXPIRATION DATE
      --ADDED VENDOR STATUS FOR REQUIRED URL ;;
  }
  # Dimensions
  dimension: vendor_id {
    type: string
    sql: ${TABLE}.VENDOR_ID ;;
  }

  dimension: vendor_status {
    type: string
    sql: ${TABLE}.STATUS ;;
  }

  dimension: requires_coi {
    type: yesno
    sql: ${TABLE}.REQUIRES_COI ;;
  }

  dimension: coi_url {
    type: string
    sql: ${TABLE}.COI_URL ;;
  }

  dimension: earliest_coi_expiration_date {
    type: date
    sql: ${TABLE}.EARLIEST_COI_EXPIRATION_DATE ;;
  }
}
