{{
    config(
        materialized='table',
        cluster_by=['geofence_id', 'asset_id', 'usage_date']
    )
}}

WITH COMPANY_GEOFENCES AS (
  SELECT company_id, geofence_id
  FROM es_warehouse.public.geofences
  WHERE 
    deleted = FALSE --NOT DELETED, AKA ACTIVE
    AND date_created::date <= current_date --NOT IN THE FUTURE 
  GROUP BY ALL 
),

OWNED_OR_RENTED_ASSETS AS (
  SELECT company_id, asset_id, NULL::DATE as start_date, NULL::DATE as end_date, 'OWNED' AS OWNERSHIP 
  FROM business_intelligence.triage.stg_t3__asset_info
  GROUP BY ALL 

  UNION 

  SELECT company_id, asset_id, rental_start_date as start_date, SCHEDULED_OFF_RENT_DATE as end_date, 'CURRENT RENTAL' AS OWNERSHIP
  FROM business_intelligence.triage.stg_t3__on_rent
  WHERE ASSET_ID IS NOT NULL 

  UNION

  SELECT rental_company_id as company_id, asset_id, start_date, end_date, 'PAST RENTAL' AS OWNERSHIP
  FROM business_intelligence.triage.stg_t3__company_values
  WHERE rental_id IS NOT NULL 
  -- FILTERS TO PAST RENTALS:
  AND ASSET_ID NOT IN (SELECT ASSET_ID FROM business_intelligence.triage.stg_t3__on_rent WHERE ASSET_ID IS NOT NULL GROUP BY 1)
  GROUP BY ALL 
),

ASSET_GEOFENCE_UNIVERSE AS 
(
SELECT 
    CG.COMPANY_ID,
    H.GEOFENCE_ID, 
    H.ASSET_ID, 
    H.report_range:start_range::DATE AS USAGE_DATE, 
    ORA.OWNERSHIP,
    -- SHOULD BE MAX OF 1 HOUR:
    SUM(CASE WHEN H.HOURS > 1 THEN 1 ELSE H.HOURS END) AS HOURS_IN_GEOFENCE
FROM es_warehouse.public.hourly_asset_geofence_usage H
INNER JOIN company_geofences CG USING (geofence_id)
INNER JOIN OWNED_OR_RENTED_ASSETS ORA 
    ON H.ASSET_ID = ORA.ASSET_ID
    AND CG.COMPANY_ID = ORA.COMPANY_ID
    AND (
        ORA.START_DATE IS NULL 
        OR H.report_range:start_range::DATE BETWEEN ORA.START_DATE AND ORA.END_DATE 
    ) 
-- LAST 365 DAYS:
WHERE H.report_range:start_range::DATE >= CURRENT_DATE-365
-- REMOVES BAD NEGATIVE HOUR DATA:
AND H.HOURS > 0 
GROUP BY ALL 
),


TOTAL_GEOFENCES AS 
(
SELECT * FROM ASSET_GEOFENCE_UNIVERSE

UNION 

-- JOINS IN CURRENT RENTALS WITH 0 GEOFENCE USAGE TO DATE:

SELECT COMPANY_ID, NULL AS GEOFENCE_ID, ASSET_ID, NULL::DATE AS USAGE_DATE, 'CURRENT RENTAL' AS OWERNSHIP, NULL AS HOURS_IN_GEOFENCE 
FROM business_intelligence.triage.stg_t3__on_rent
WHERE COMPANY_ID IN (SELECT COMPANY_ID FROM ASSET_GEOFENCE_UNIVERSE GROUP BY 1)
AND ASSET_ID NOT IN (SELECT ASSET_ID FROM ASSET_GEOFENCE_UNIVERSE GROUP BY 1)

-- UNION 

-- SELECT COMPANY_ID, GEOFENCE_ID, NULL AS ASSET_ID, NULL::DATE AS USAGE_DATE, NULL AS OWERNSHIP, NULL AS HOURS_IN_GEOFENCE FROM COMPANY_GEOFENCES
-- WHERE GEOFENCE_ID NOT IN (SELECT GEOFENCE_ID FROM ASSET_GEOFENCE_UNIVERSE GROUP BY ALL)
),


BASE_DATA AS 
(
SELECT 
    TG.*,
    G.NAME AS GEOFENCE_NAME,
    G.DATE_CREATED::DATE AS GEOFENCE_CREATED_DATE,
    G.GEOJSON,
    UG.GEOFENCE_LAST_USAGE_DATE,
    UG.GEOFENCE_UNDER_UTILIZATION_REASON,
    AI.CUSTOM_NAME AS ASSET,
    AI.ASSET_TYPE,
    A.ASSET_CLASS,
    UA.ASSET_LAST_USAGE_DATE,
    UA.ASSET_UNDER_UTILIZATION_REASON,
    AI.DRIVER_NAME,
    AI.MAKE,
    AI.MODEL,
    AI.SERIAL_NUMBER_VIN, 
    TH.TRACKER,
    TH.TRACKER_TYPE,
    TH.LATEST_REPORT_TIMESTAMP::DATE AS TRACKER_LAST_REPORT_DATE,
    TH.LAST_CHECKIN_TIMESTAMP::DATE AS TRACKER_LAST_CHECK_IN_DATE,
    CONCAT(TH.PUBLIC_HEALTH_STATUS, ' - ', TH.ASSET_HEALTH_DETAIL) AS TRACKER_HEALTH_STATUS,

    BDU.ON_TIME_UTC,
    BDU.RUN_TIME_UTC,
    BDU.IDLE_TIME_UTC,
    BDU.MILES_DRIVEN_UTC,
    
    BDU.ON_TIME_EST,
    BDU.RUN_TIME_EST,
    BDU.IDLE_TIME_EST,
    BDU.MILES_DRIVEN_EST,
    
    BDU.ON_TIME_CST,
    BDU.RUN_TIME_CST,
    BDU.IDLE_TIME_CST,
    BDU.MILES_DRIVEN_CST,
    
    BDU.ON_TIME_MNT,
    BDU.RUN_TIME_MNT,
    BDU.IDLE_TIME_MNT,
    BDU.MILES_DRIVEN_MNT,
    
    BDU.ON_TIME_WST,
    BDU.RUN_TIME_WST,
    BDU.IDLE_TIME_WST,
    BDU.MILES_DRIVEN_WST

FROM TOTAL_GEOFENCES TG 
LEFT JOIN business_intelligence.triage.stg_t3__asset_info AI USING(ASSET_ID)
LEFT JOIN es_warehouse.public.assets A USING(ASSET_ID)
LEFT JOIN es_warehouse.public.geofences G USING(GEOFENCE_ID)
LEFT JOIN business_intelligence.triage.stg_t3__telematics_health TH USING(ASSET_ID)
LEFT JOIN 
(
SELECT
    date,
    asset_id,

    -- UTC
    MAX(ON_TIME_UTC)        AS ON_TIME_UTC,
    MAX(RUN_TIME_UTC)       AS RUN_TIME_UTC,
    MAX(IDLE_TIME_UTC)      AS IDLE_TIME_UTC,
    MAX(MILES_DRIVEN_UTC)   AS MILES_DRIVEN_UTC,

    -- EST
    MAX(ON_TIME_EST)        AS ON_TIME_EST,
    MAX(RUN_TIME_EST)       AS RUN_TIME_EST,
    MAX(IDLE_TIME_EST)      AS IDLE_TIME_EST,
    MAX(MILES_DRIVEN_EST)   AS MILES_DRIVEN_EST,

    -- CST
    MAX(ON_TIME_CST)        AS ON_TIME_CST,
    MAX(RUN_TIME_CST)       AS RUN_TIME_CST,
    MAX(IDLE_TIME_CST)      AS IDLE_TIME_CST,
    MAX(MILES_DRIVEN_CST)   AS MILES_DRIVEN_CST,

    -- MNT
    MAX(ON_TIME_MNT)        AS ON_TIME_MNT,
    MAX(RUN_TIME_MNT)       AS RUN_TIME_MNT,
    MAX(IDLE_TIME_MNT)      AS IDLE_TIME_MNT,
    MAX(MILES_DRIVEN_MNT)   AS MILES_DRIVEN_MNT,

    -- WST
    MAX(ON_TIME_WST)        AS ON_TIME_WST,
    MAX(RUN_TIME_WST)       AS RUN_TIME_WST,
    MAX(IDLE_TIME_WST)      AS IDLE_TIME_WST,
    MAX(MILES_DRIVEN_WST)   AS MILES_DRIVEN_WST

FROM business_intelligence.triage.stg_t3__by_day_utilization
GROUP BY ALL 
) BDU ON BDU.DATE = TG.USAGE_DATE AND BDU.ASSET_ID = TG.ASSET_ID
LEFT JOIN 
(
SELECT 
    GEOFENCE_ID,
    MAX(USAGE_DATE) AS GEOFENCE_LAST_USAGE_DATE, 
    CASE 
    WHEN MAX(USAGE_DATE) IS NULL THEN 'HAS NEVER BEEN UTILIZED'
    WHEN MAX(USAGE_DATE) < CURRENT_DATE-90 THEN CONCAT('HAS BEEN ', TO_VARCHAR(DATEDIFF(MONTH, MAX(USAGE_DATE), CURRENT_DATE)), ' MONTHS SINCE LAST UTILIZED')
    ELSE NULL END AS GEOFENCE_UNDER_UTILIZATION_REASON
FROM TOTAL_GEOFENCES
GROUP BY ALL 
) UG USING(GEOFENCE_ID)
LEFT JOIN 
(
SELECT 
    ASSET_ID, 
    MAX(USAGE_DATE) AS ASSET_LAST_USAGE_DATE, 
    CASE 
    WHEN MAX(USAGE_DATE) IS NULL THEN 'HAS NEVER BEEN UTILIZED'
    WHEN MAX(USAGE_DATE) < CURRENT_DATE-90 THEN CONCAT('HAS BEEN ', TO_VARCHAR(DATEDIFF(MONTH, MAX(USAGE_DATE), CURRENT_DATE)), ' MONTHS SINCE LAST UTILIZED')
    ELSE NULL END AS ASSET_UNDER_UTILIZATION_REASON
FROM TOTAL_GEOFENCES
GROUP BY ALL 
) UA USING(ASSET_ID)
),

TIME_SERIES AS 
(
SELECT
  dateadd(
    day,
    '-' || row_number() over (order by null),
    dateadd(day, '+1', current_date())
  ) AS series_date 
FROM TABLE (generator(rowcount => 180)) D --last 180 days
),

PAST_USAGE AS 
(
SELECT 
    Y.GEOFENCE_ID,

    SUM(CASE WHEN Y.series_date BETWEEN CURRENT_DATE-6 AND CURRENT_DATE THEN Y.TOTAL_USAGE ELSE 0 END) AS L7D,
    SUM(CASE WHEN Y.series_date BETWEEN CURRENT_DATE-13 AND CURRENT_DATE-7 THEN Y.TOTAL_USAGE ELSE 0 END) AS P7D,
    SUM(CASE WHEN Y.series_date BETWEEN CURRENT_DATE-29 AND CURRENT_DATE THEN Y.TOTAL_USAGE ELSE 0 END) AS L30D,
    SUM(CASE WHEN Y.series_date BETWEEN CURRENT_DATE-59 AND CURRENT_DATE-30 THEN Y.TOTAL_USAGE ELSE 0 END) AS P30D,
    SUM(CASE WHEN Y.series_date BETWEEN CURRENT_DATE-89 AND CURRENT_DATE THEN Y.TOTAL_USAGE ELSE 0 END) AS L90D,
    SUM(CASE WHEN Y.series_date BETWEEN CURRENT_DATE-179 AND CURRENT_DATE-90 THEN Y.TOTAL_USAGE ELSE 0 END) AS P90D
FROM 
(
SELECT 
    X.*,
    COALESCE(GA.TOTAL_USAGE, 0) AS TOTAL_USAGE
FROM 
(
SELECT T.series_date, G.GEOFENCE_ID FROM 
TIME_SERIES T CROSS JOIN (SELECT GEOFENCE_ID FROM BASE_DATA GROUP BY ALL) G 
) X 
LEFT JOIN 
(SELECT GEOFENCE_ID, USAGE_DATE AS series_date, SUM(HOURS_IN_GEOFENCE) AS TOTAL_USAGE FROM BASE_DATA GROUP BY ALL) GA 
    USING(series_date, GEOFENCE_ID)
) Y 
GROUP BY ALL 
)


SELECT 
    B.*, P.PCT_CHG_7D, P.PCT_CHG_30D, P.PCT_CHG_90D
FROM BASE_DATA B 
LEFT JOIN 
(
SELECT 
    GEOFENCE_ID, 
    CASE WHEN L7D = 0 AND P7D = 0 THEN 0 WHEN P7D = 0 THEN 1 ELSE (L7D-P7D)/P7D END AS PCT_CHG_7D,
    CASE WHEN L30D = 0 AND P30D = 0 THEN 0 WHEN P30D = 0 THEN 1 ELSE (L30D-P30D)/P30D END AS PCT_CHG_30D,
    CASE WHEN L90D = 0 AND P90D = 0 THEN 0 WHEN P90D = 0 THEN 1 ELSE (L90D-P90D)/P90D END AS PCT_CHG_90D
FROM PAST_USAGE 
) P USING(GEOFENCE_ID)
-- DE-DUPLICATION:
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY
      company_id,
      geofence_id,
      asset_id,
      usage_date
  ORDER BY CASE WHEN ownership = 'OWNED' THEN 1 ELSE 2 END
) = 1