with source as (

    select * from {{ source('analytics_microsoft_dynamics', 'inventory_table') }}

),

renamed as (

    select
       -- ids
        id,
        itemid as item_id,
        batchnumgroupid,
        costgroupid,
        defaultdimension,
        intrastatcommodity,
        itembuyergroupid,
        primaryvendorid,
        propertyid,
        reqgroupid,
        serialnumgroupid,
        servicecodetable_in,
        sortcode,
        tableid,
        serviceaccountingcodetable_in,
        wfsoldpartnumber,
        productlifecyclestateid,
        esdbpartid_custom,



        -- strings
        sysdatastatecode,
        costmodel,
        matchingpolicy,
        pmfproducttype,
        salesmodel,
        salespricemodelbasic,
        batchmergedatecalculationmethod,
        bommanualreceipt,
        itemtype,
        namealias,
        ngpcodestable_fr,
        product,
        taxratetype,
        modifiedby,
        createdby,
        modifiedtransactionid,
        createdtransactionid,
        dataareaid,
        recversion,
        partition,
        sysrowversion,
        versionnumber,
        telematicsitemtype_custom as item_type,

        -- numerics
        abccontributionmargin,
        abcrevenue,
        abctieup,
        abcvalue,
        approxtaxvalue_br,
        bomlevel,
        density,
        depth,
        fiscallifonormalvalue,
        grossdepth,
        grossheight,
        grosswidth,
        height,
        minimumpalletquantity,
        netweight,
        pdscwwmsminimumpalletqty,
        pdscwwmsqtyperlayer,
        pdscwwmsstandardpalletqty,
        pdsshelflife,
        pdstargetfactor,
        pmfyieldpct,
        qtyperlayer,
        salescontributionratio,
        salespercentmarkup,
        scrapconst,
        scrapvar,
        standardpalletquantity,
        statisticsfactor,
        taraweight,
        taxpackagingqty,
        unitvolume,
        width,
        wmsarrivalhandlingtime,
        wmspickingqtytime,
        intrastatchargeperkg,
        costbomlevel,
        metgauge,
        metwidth,
        metgaugeend,
        metwidthend,
        revrecmedianpricemaximumtolerance,
        revrecmedianpriceminimumtolerance,
        autoreportfinished,
        fiscallifoavoidcalc,
        fiscallifonormalvaluecalc,
        forecastdmpinclude,
        icmsonservice_br,
        intrastatexclude,
        pdspotencyattribrecording,
        pdsvendorcheckitem,
        phantom,
        preventphysicaldimensionsync,
        bomwhsreleasepolicy,
        displayhazard_mx,
        bundle,
        revrecexcludefromcarveout,
        revrecmedianprice,
        revrecrevenuerecognitionenabled,
        revrecrevenuetype,
        revrecbundle,
        skipintracompanysync_ru,
        taxationorigin_br,
        usealtitemid,
        dsa_in,
        exciserecordtype_in,
        exempt_in,
        scaleindicator_br,
        nongst_in,
        hmimindicator,
        coodualuseproduct,
        metrawmaterialitem,
        metitemtypevalue,
        metitemtypevalueend,

        -- timestamps
        sink_created_on,
        sink_modified_on,
        modifieddatetime,
        createddatetime,
        modifiedon,
        createdon,
        _fivetran_synced,
        _fivetran_deleted,


    from source

)

select * from renamed
