with source as (
      select * from {{ source('analytics_microsoft_dynamics', 'sales_table') }}
),
renamed as (
    select
        -- ids
        id,
        addressrefrecid,
        addressreftableid,
        contactpersonid,
        salesid,
        statprocid,
        tableid,
        taxid,
        vatnumrecid,
        modifiedtransactionid,
        createdtransactionid,
        recid,
        servicecoderefrecid,

        -- strings
        autosummarymoduletype,
        bankdocumenttype,
        casetagging,
        constarget_jp,
        creditcardauthorizationerror,
        customsexportorder_in,
        customsshippingbill_in,
        deliverydatecontroltype,
        documentstatus,
        einvoicelinespec,
        fiscaldoctype_pl,
        freightsliptype,
        girotype,
        incltax,
        intercompanyallowindirectcreation,
        intercompanyallowindirectcreationorig,
        intercompanyautocreateorders,
        intercompanydirectdelivery,
        intercompanydirectdeliveryorig,
        intercompanyorder,
        intercompanyorigin,
        invoiceautonumbering_lt,
        itemtagging,
        listcode,
        mcrorderstopped,
        natureofassessee_in,
        onetimecustomer,
        packingslipautonumbering_lt,
        pallettagging,
        pdsbatchattribautores,
        releasestatus,
        reservation,
        returnreplacementcreated,
        returnstatus,
        salesstatus,
        salestype,
        settlevoucher,
        shipcarrierblindshipment,
        shipcarrierdlvtype,
        shipcarrierexpeditedshipment,
        shipcarrierfuelsurcharge,
        shipcarrierresidential,
        skipupdate,
        systementrysource,
        touched,
        unitedvatinvoice_lt,
        skipcreatemarkup,
        skiplineupdate,
        invoiceregister_lt,
        packingslipregister_lt,
        foreigntrade_mx,
        sourcecertificate_mx,
        vatnumtabletype,
        overridesalestax,
        mpsfullrunctpstatus,
        isintegration,
        mpsexcludesalesorder,
        mpsupdateexcludesalesorder,
        salesorderintegrationcreationtype,
        commissiontype_it,
        printdynamicqrcode_in,
        invoicetype_w,
        cfditemporaryexport_mx,
        credmanexcludesalesorder,
        credmanreleasedfromcreditcontrol,
        credmanrejected,
        credmanincreditcontrol,
        domprocessed,
        domignore,
        domexceptiontype,
        subbillcreatedfromsb,
        subbillsuppresschilditems,
        revrecfolloworiginalpricingmethod,
        revrecmultiplesoreallocation,
        gupskippricingcalculation,
        gupdelaypricingcalculation,
        sysdatastatecode,
        covstatus,
        creditcardcustrefid,
        creditnotereasoncode,
        currencycode,
        custaccount,
        custgroup,
        customerref,
        deadline,
        defaultdimension,
        deliveryname,
        deliverypostaladdress,
        directdebitmandate,
        dlvmode,
        dlvreason,
        dlvterm,
        email,
        estimate,
        inventlocationid,
        inventsiteid,
        invoiceaccount,
        languageid,
        manualentrychangepolicy,
        matchingagreement,
        payment,
        postingprofile,
        purchorderformnum,
        retailchanneltable,
        salesname,
        salesoriginid,
        shipcarrierpostaladdress,
        shippingdateconfirmed,
        shippingdaterequested,
        sourcedocumentheader,
        systementrychangepolicy,
        taxgroup,
        transportationdocument,
        workersalesresponsible,
        workersalestaker,
        accountingdistributiontemplate,
        fundingsource,
        reportingcurrencyfixedexchrate,
        phone,
        fintag,
        subbillbilltoname,
        subbillbilltopostaladdress,

        -- numerics
        cashdiscbasedate,
        cashdiscbasedays,
        cashdiscpercent,
        creditcardapprovalamount,
        discpercent,
        fixedduedate,
        fixedexchrate,
        smmsalesamounttotal,

        -- booleans
        creditcardauthorizationerror,
        touched,
        skipcreatemarkup,
        skiplineupdate,
        overridesalestax,
        isintegration,
        mpsexcludesalesorder,
        domprocessed,
        domignore,
        revrecfolloworiginalpricingmethod,
        skipupdate,
        unitedvatinvoice_lt,
        credmanexcludesalesorder,
        credmanreleasedfromcreditcontrol,
        credmanrejected,
        credmanincreditcontrol,

        -- dates
        deliverydate,
        deadline,
        receiptdateconfirmed,
        receiptdaterequested,
        returndeadline,
        returnitemnum,
        returnreasoncodeid,
        directdebitmandate,

        -- timestamps
        sink_created_on,
        sink_modified_on,
        createddatetime,
        createdon,
        modifieddatetime,
        modifiedon,
        _fivetran_deleted


    from source
)
select * from renamed
  