with source as (
    select * from {{ source('analytics_commission', 'commission_details_final') }}
),

renamed as (
    select
        commission_id,
        line_item_id,
        salesperson_user_id,
        invoice_id,
        invoice_no,
        order_id,
        order_date,
        market_id,
        market_name,
        parent_market_id,
        parent_market_name,
        region,
        region_name,
        district,
        ship_to_state,
        company_id,
        company_name,
        line_item_type_id,
        line_item_type,
        asset_id,
        invoice_asset_make,
        invoice_class_id,
        invoice_class,
        rental_class_id_from_rental,
        rental_class_from_line_item,
        line_item_amount,
        amount,
        email_address,
        employee_id,
        full_name,
        employee_title,
        transaction_type,
        employee_manager_id,
        employee_manager,
        salesperson_type_id,
        salesperson_type,
        employee_type,
        secondary_rep_count,
        rate_tier_id,
        rate_tier_name,
        book_rate,
        benchmark_rate,
        floor_rate,
        business_segment_id,
        rental_id,
        rental_date_created,
        rental_start_date,
        rental_billed_days,
        cheapest_period,
        quoted_rates,
        override_rate,
        is_exception,
        is_override,
        allocation_cost_center,
        commission_rate,
        transaction_date,
        billing_approved_date,
        split,
        transaction_type_id,
        is_payable,
        reimbursement_factor,
        credit_note_line_item_id,
        transaction_description,
        commission_month,
        commission_amount,
        paycheck_date,
        hidden,
        manual_adjustment_id,
        split_part(reverse(commission_id), '-', 1)::int as commission_type_id
    from source
)

select * from renamed
