with source as (
      select * from {{ source('analytics_commission', 'retail_commission_details_final') }}
),
renamed as (
    select
        COMMISSION_ID,
        LINE_ITEM_ID,
        SALESPERSON_USER_ID,
        INVOICE_ID,
        INVOICE_NO,
        ORDER_ID,
        INVOICE_CREATED_DATE,
        ORDER_DATE,
        MARKET_ID,
        MARKET_NAME,
        PARENT_MARKET_ID,
        PARENT_MARKET_NAME,
        REGION,
        REGION_NAME,
        DISTRICT,
        SHIP_TO_STATE,
        COMPANY_ID,
        COMPANY_NAME,
        LINE_ITEM_TYPE_ID,
        LINE_ITEM_TYPE,
        ASSET_ID,
        INVOICE_ASSET_MAKE,
        INVOICE_CLASS_ID,
        INVOICE_CLASS,
        LINE_ITEM_AMOUNT,
        AMOUNT,
        EMAIL_ADDRESS,
        EMPLOYEE_ID,
        FULL_NAME,
        EMPLOYEE_TITLE,
        TRANSACTION_TYPE,
        EMPLOYEE_MANAGER_ID,
        EMPLOYEE_MANAGER,
        SALESPERSON_TYPE_ID,
        SALESPERSON_TYPE,
        EMPLOYEE_TYPE,
        SECONDARY_REP_COUNT,
        PROFIT_MARGIN,
        NBV,
        FLOOR_RATE,
        BENCHMARK_RATE,
        ONLINE_RATE,
        RATE_TIER_ID,
        RATE_ACHIEVEMENT,
        IS_EXCEPTION,
        ALLOCATION_COST_CENTER,
        COMMISSION_RATE,
        TRANSACTION_DATE,
        BILLING_APPROVED_DATE,
        SPLIT,
        TRANSACTION_TYPE_ID,
        IS_PAYABLE,
        IS_FINALIZED,
        REIMBURSEMENT_FACTOR,
        CREDIT_NOTE_LINE_ITEM_ID,
        TRANSACTION_DESCRIPTION,
        COMMISSION_MONTH,
        COMMISSION_AMOUNT,
        PAYCHECK_DATE,
        HIDDEN,
        nullifzero(MANUAL_ADJUSTMENT_ID) as MANUAL_ADJUSTMENT_ID,
        null as requester_id,
        null as requester_full_name,
        null as description,
        null as comments,
        null as submitted_by,
        null as submitted_date,
        SPLIT_PART(REVERSE(commission_id), '-', 1)::int as commission_type_id
    from source
)
select * from renamed
  