{#--
    Macro: convert_snapshot_to_scd2
    Description:
        Converts snapshot-style input data (e.g., twice-daily inserts regardless of changes)
        into a collapsed slowly changing dimension type 2 (SCD2) table.
        This version supports incremental loading and works with Snowflake.

    Args:
        source_relation (str): ref() name of the source table
        unique_key (str or list): pass in the unique field(s) that would make up the surrogate key but not actually the surrogate key.
             This means the list should EXCLUDE scd fields (valid_from, valid_to, is_current)
        updated_ts (str): name of the timestamp column to use for valid_from and valid_to (e.g., _es_update_timestamp, _dbt_updated_timestamp)
        scd_fields (list[str], optional): specific columns to track changes on. If nothing is passed, it'll run scd on every field
        exclude_columns (list[str], optional): additional fields to exclude from selection
        filter_relation (list[str], optional): The `ref()` name of a dbt model used to filter `source_relation` rows.
            Only records where `unique_key` appears in this model will be included in SCD2 processing.
            Useful when you want to limit SCD2 logic to a subset of records (e.g., just salespeople).
        surrogate_key_name (str, optional):  Name of the surrogate key column to generate. 
            Default: `surrogate_key`. Default name can be overwritten to use a more domain-specific name 
            like `employee_key`, `salesperson_key`, or `quote_key`.
            The surrogate key is constructed using a hash of the `unique_key` columns and `valid_from`, 
            ensuring each historical version of an entity is uniquely and consistently identified.

    Returns:
        SQL string that implements SCD2 logic including valid_from, valid_to, is_current, and surrogate key.
--#}

{%- macro convert_snapshot_to_scd2(source_relation, unique_key, updated_ts, scd_fields=None, exclude_columns=[], filter_relation=[], surrogate_key_name='surrogate_key') -%}

{# START INPUT VALIDATION CHECK #}
{%- set unique_keys = unique_key if unique_key is iterable and unique_key is not string else [unique_key] -%}

{%- set unique_keys_lower = [] -%}
{%- for key in unique_keys -%}
  {%- do unique_keys_lower.append(key.lower()) -%}
{%- endfor -%}

{# This ensures we're passing in the natural keys and we're handling valid_from internally in this macro#}
{%- if surrogate_key_name.lower() in unique_keys_lower -%}
    {{ exceptions.raise_compiler_error("Invalid input parameter: unique_key should not be the surrogate key") }}
{%- elif '_valid_from' in unique_keys_lower -%}
    {{ exceptions.raise_compiler_error("Invalid input parameter: Remove '_valid_from' from unique_key parameter") }}
{%- else -%}
  {%- set surrogate_build_keys = unique_keys_lower + ['_valid_from'] -%}
{%- endif %}
{# END INPUT VALIDATION CHECK #}

{# exclude all scd2 fields since those will be regenerated #}
{%- set exclude_fields = ['_es_update_timestamp', '_valid_from', '_valid_to', '_is_current', '_dbt_updated_timestamp',
    updated_ts, surrogate_key_name] + exclude_columns | map('lower') | list -%}

{# get all fields if scd_fields is not specified #}
{%- if scd_fields is none -%}
  {%- set scd_fields = get_columns_except(source_relation, exclude=exclude_fields, return_as='list') -%}
{%- endif -%}

-- from stg to scd, the only field I do not want is _es_update_timestamp to show up in the table. But I do want to use it to build the scd table
-- from scd to scd, I want to get all fields except valid_from, valid_to, is_current, _dbt_updated_timestamp because these will be recreated in the process

{# ensure that there is no duplicate fields from scd_fields, in case of human error
 and ensures that we're not including the scd fields that will be generated by the macro #}
{%- set scd_fields_clean = [] -%}
{%- for col in scd_fields -%}
  {%- if col.lower() not in exclude_fields  -%}
    {%- do scd_fields_clean.append(col) -%}
  {%- endif -%}
{%- endfor %}


WITH new_data AS (
    SELECT
        {{ scd_fields_clean | join(',\n        ') }},
        {{ updated_ts }} AS _valid_from,
        NULL::timestamp AS _valid_to,
        TRUE AS _is_current,
        _dbt_updated_timestamp
    FROM {{ ref(source_relation) }}
    {% if filter_relation -%}
        WHERE {{ unique_keys_lower[0] }} IN (SELECT {{ unique_keys_lower[0] }} FROM {{ ref(filter_relation) }})
    {% endif -%}
    {% if is_incremental() -%}
        {% if not filter_relation %} WHERE {% else %} AND {% endif %}
        {{ updated_ts }} > (SELECT MAX(this._dbt_updated_timestamp) FROM {{ this }} this )
    {% endif -%}
),

{% if is_incremental() %}
current_data AS (
    SELECT *
    FROM {{ this }}
    WHERE _is_current = TRUE
),
{% endif %}

current_and_new_records AS (
    SELECT {{ scd_fields_clean | join(',\n        ') }},
        _valid_from,
        NULL::timestamp AS _valid_to,
        TRUE AS _is_current,
        _dbt_updated_timestamp
    FROM new_data

    {% if is_incremental() %}
    UNION ALL
    SELECT {{ scd_fields_clean | join(',\n        ') }},
        _valid_from,
        _valid_to,
        _is_current,
        _dbt_updated_timestamp
    FROM current_data
    {% endif %}
),

ranked AS (
    SELECT *,
        ROW_NUMBER() OVER (
            PARTITION BY {{ scd_fields_clean | join(', ') }}
            ORDER BY _valid_from
        ) AS rn_within_group,

        ROW_NUMBER() OVER (
            PARTITION BY {{ unique_keys_lower | join(', ') }}
            ORDER BY _valid_from
        ) AS rn_overall
    FROM current_and_new_records
),

grouped AS (
    SELECT *,
        rn_overall - rn_within_group AS grouping_key
    FROM ranked
),

collapsed AS (
    SELECT
        {{ scd_fields_clean | join(',\n        ') }},
        MIN(_valid_from) AS _valid_from
    FROM grouped
    GROUP BY {{ (scd_fields_clean + ['grouping_key']) | join(',\n        ') }}
),

validity AS (
    SELECT *,
        LEAD(_valid_from) OVER (
            PARTITION BY {{ unique_keys_lower | join(', ') }}
            ORDER BY _valid_from
        ) AS _valid_to_raw
    FROM collapsed
),

final AS (
    SELECT
        {% for col in scd_fields_clean %}
            {{ col }},
        {% endfor %}
        _valid_from,
        IFF(_valid_to_raw IS NULL, '9999-12-31'::timestamp, _valid_to_raw) AS _valid_to,
        IFF(_valid_to_raw IS NULL, TRUE, FALSE) AS _is_current,
        {{ dbt_updated_timestamp() }}
    FROM validity
)

SELECT {{ dbt_utils.generate_surrogate_key(surrogate_build_keys) }} AS {{ surrogate_key_name }}, * 
FROM final

{% endmacro %}
