SELECT
    sbcp.scd_billing_company_preference_id,
    sbcp.company_id,
    sbcp.prefs,
    sbcp.date_start,
    sbcp.date_end,
    sbcp.current_flag,
    sbcp._es_update_timestamp,
    sbcp.prefs:"bad_debt" AS prefs__bad_debt,
    sbcp.prefs:"four_week_billing_date" AS prefs__four_week_billing_date,
    sbcp.prefs:"internal_company" AS prefs__internal_company,
    sbcp.prefs:"legal_audit" AS prefs__legal_audit,
    sbcp.prefs:"managed_billing" AS prefs__managed_billing,
    sbcp.prefs:"rental_billing_cycle_strategy" AS prefs__rental_billing_cycle_strategy,
    sbcp.prefs:"is_paperless_billing" AS prefs__is_paperless_billing,
    sbcp.prefs:"monthly_statement_contacts" AS prefs__monthly_statement_contacts,
    sbcp.prefs:"in_bankruptcy" AS prefs__in_bankruptcy,
    sbcp.prefs:"national_account" AS prefs__national_account,
    sbcp.prefs:"legal_audit_time" AS prefs__legal_audit_time,
    sbcp.prefs:"cycle_billing_only" AS prefs__cycle_billing_only,
    sbcp.prefs:"disable_monthly_statements" AS prefs__disable_monthly_statements,
    sbcp.prefs:"general_services_administration" AS prefs__general_services_administration,
    sbcp.prefs:"invoice_contacts" AS prefs__invoice_contacts,
    sbcp.prefs:"primary_billing_contact_user_id" AS prefs__primary_billing_contact_user_id
FROM {{ source('es_warehouse_scd', 'scd_billing_company_preferences') }} as sbcp
