view: receipt_sync_difference {
  derived_table: {
    sql: SELECT
          COALESCE(CCVR.CORRECT_VENDOR_ID,VEND.EXTERNAL_ERP_VENDOR_REF) AS Vendor_ID,
          CONCAT(POH.PURCHASE_ORDER_NUMBER,SFX.SUFFIX) AS PO_Number,
          Round(SUM((PRL.ACCEPTED_QUANTITY + PRL.REJECTED_QUANTITY) * POL.PRICE_PER_UNIT),2) AS CostCapture_Amt,
          Round(INTPO.AMT,2) AS Intacct_Amt,
          INTPOH.STATE AS Intacct_State
      FROM
          "PROCUREMENT"."PUBLIC"."PURCHASE_ORDER_RECEIVERS" PRH
          JOIN "PROCUREMENT"."PUBLIC"."PURCHASE_ORDER_RECEIVER_ITEMS" PRL ON PRL.PURCHASE_ORDER_RECEIVER_ID = PRH.PURCHASE_ORDER_RECEIVER_ID
          JOIN "PROCUREMENT"."PUBLIC"."PURCHASE_ORDERS" POH ON POH.PURCHASE_ORDER_ID = PRH.PURCHASE_ORDER_ID
          JOIN "PROCUREMENT"."PUBLIC"."PURCHASE_ORDER_LINE_ITEMS" POL ON POL.PURCHASE_ORDER_LINE_ITEM_ID = PRL.PURCHASE_ORDER_LINE_ITEM_ID
          JOIN "PROCUREMENT"."PUBLIC"."ITEMS" ITM ON ITM.ITEM_ID = POL.ITEM_ID
          LEFT JOIN "ES_WAREHOUSE"."PURCHASES"."ENTITY_VENDOR_SETTINGS" VEND ON POH.VENDOR_ID = VEND.ENTITY_ID
          LEFT JOIN "ANALYTICS"."FINANCIAL_SYSTEMS"."COST_CAPTURE_VENDOR_REDIRECT" CCVR ON VEND.EXTERNAL_ERP_VENDOR_REF = CCVR.ORIGINAL_VENDOR_ID AND ACTIVE_END_DATE IS NULL
          LEFT JOIN
              (SELECT
                  PURCHASE_ORDER_RECEIVER_ID,
                  CASE WHEN RANK() OVER (PARTITION BY PURCHASE_ORDER_ID ORDER BY DATE_CREATED ASC) > 1 THEN CONCAT('-',(RANK() OVER (PARTITION BY PURCHASE_ORDER_ID ORDER BY DATE_CREATED ASC))) ELSE '' END AS "SUFFIX"
              FROM "PROCUREMENT"."PUBLIC"."PURCHASE_ORDER_RECEIVERS") SFX ON PRH.PURCHASE_ORDER_RECEIVER_ID = SFX.PURCHASE_ORDER_RECEIVER_ID
          LEFT JOIN (SELECT DOCHDRID, SUM(TOTAL) AS "AMT" FROM "ANALYTICS"."INTACCT"."PODOCUMENTENTRY" WHERE DOCPARID = 'Purchase Order' GROUP BY DOCHDRID) INTPO ON CONCAT('Purchase Order-',POH.PURCHASE_ORDER_NUMBER,SFX.SUFFIX) = INTPO.DOCHDRID
          LEFT JOIN "ANALYTICS"."INTACCT"."PODOCUMENT" INTPOH ON INTPO.DOCHDRID = INTPOH.DOCID
      WHERE
          POH.COMPANY_ID = 1854 AND
          PRH.RECEIVER_TYPE = 'RECEIPT' AND
          ITM.ITEM_TYPE != 'SERVICE' AND
          INTPOH.STATE = 'Pending'
      GROUP BY
          COALESCE(CCVR.CORRECT_VENDOR_ID,VEND.EXTERNAL_ERP_VENDOR_REF),
          CONCAT(POH.PURCHASE_ORDER_NUMBER,SFX.SUFFIX),
          ROUND(INTPO.AMT,2),
          INTPOH.STATE
      HAVING
          ROUND(CostCapture_Amt,2) != ROUND(Intacct_Amt,2)
       ;;
  }

  measure: count {
    type: count
    drill_fields: [detail*]
  }

  dimension: vendor_id {
    type: string
    sql: ${TABLE}."VENDOR_ID" ;;
  }

  dimension: po_number {
    type: string
    sql: ${TABLE}."PO_NUMBER" ;;
  }

  dimension: costcapture_amt {
    type: number
    sql: ${TABLE}."COSTCAPTURE_AMT" ;;
  }

  dimension: intacct_amt {
    type: number
    sql: ${TABLE}."INTACCT_AMT" ;;
  }

  dimension: intacct_state {
    type: string
    sql: ${TABLE}."INTACCT_STATE" ;;
  }

  set: detail {
    fields: [vendor_id, po_number, costcapture_amt, intacct_amt, intacct_state]
  }
}
