view: vendors_ytd_payments {
  derived_table: {
    sql: SELECT APRH.VENDORID AS VENDOR_ID,APRD.ACCOUNTNO AS GL_ACCT_NUMBER,COA.TITLE AS GL_ACCT_DESC,
    SUM(APBPMT.AMOUNT) AS YTD_PAYMENT_AMOUNT
FROM ANALYTICS.INTACCT.APBILLPAYMENT  AS APBPMT
LEFT JOIN ANALYTICS.INTACCT.APRECORD  AS APRH ON APBPMT.RECORDKEY = APRH.RECORDNO AND APRH.RECORDTYPE IN ('apbill','apadjustment')
LEFT JOIN ANALYTICS.INTACCT.APDETAIL  AS APRD ON APBPMT.PAIDITEMKEY = APRD.RECORDNO AND APRH.RECORDNO = APRD.RECORDKEY
LEFT JOIN ANALYTICS.INTACCT.VENDOR    AS VEND ON APRH.VENDORID = VEND.VENDORID
LEFT JOIN ANALYTICS.INTACCT.GLACCOUNT AS COA ON APRD.ACCOUNTNO = COA.ACCOUNTNO
LEFT JOIN ANALYTICS.INTACCT.APRECORD  AS APRHPAY ON APBPMT.PAYMENTKEY = APRHPAY.RECORDNO
WHERE YEAR(APBPMT.PAYMENTDATE) = YEAR(CURRENT_DATE) AND APBPMT.PAYMENTDATE <= CURRENT_DATE
AND APBPMT.PAYMENTKEY = APBPMT.PARENTPYMT --WHEN THESE DON'T EQUAL IT IS A CREDIT MEMO APPLICATION I THINK
AND APRHPAY.RECORDTYPE = 'appayment'
GROUP BY APRH.VENDORID,APRD.ACCOUNTNO,COA.TITLE
       ;;
  }



  dimension: vendor_id {
    type: string
    sql: ${TABLE}."VENDOR_ID" ;;
  }

  dimension: gl_acct_number {
    label: "GL Acct Number"
    type: string
    sql: ${TABLE}."GL_ACCT_NUMBER" ;;
  }

  dimension: gl_acct_desc {
    label: "GL Acct Description"
    type: string
    sql: ${TABLE}."GL_ACCT_DESC" ;;
  }

  dimension: ytd_payment_amount {
    type: number
    sql: iff(${TABLE}."YTD_PAYMENT_AMOUNT" is null,0,${TABLE}."YTD_PAYMENT_AMOUNT") ;;
  }
  }
