view: ytd_vendor_walk {
  derived_table: {
    sql:
     WITH MAIN_CTE AS (
    SELECT
        APRH.VENDORID AS VENDOR_ID,
        VEND.NAME AS VENDOR_NAME,
        APBPMT.PAYMENTDATE AS PAYMENT_DATE,
        APRD.ACCOUNTNO AS ACCOUNT,
        APBPMT.AMOUNT,
        aprd.ITEMID AS ITEM_ID,
        CASE
            WHEN APRD.ACCOUNTNO = '2014' THEN TRIM(RIGHT(aprd.ITEMID,4))
            WHEN APRD.ACCOUNTNO <> '2013' THEN APRD.ACCOUNTNO
            WHEN APRD.ACCOUNTNO = '2013' THEN NULL
            ELSE NULL
        END AS ACCOUNT_V2,
        CASE
            WHEN DATE_TRUNC('week', PAYMENT_DATE::DATE) = DATE_TRUNC('week', CURRENT_DATE::DATE) THEN TRUE
            ELSE FALSE
        END AS IS_CURRENT_WEEK,
        CASE
            WHEN PAYMENT_DATE::DATE BETWEEN DATE_TRUNC('year', CURRENT_DATE::DATE - INTERVAL '1 year')
                AND DATE_TRUNC('day', CURRENT_DATE::DATE - INTERVAL '1 year') THEN TRUE
            ELSE FALSE
        END AS LAST_YEAR_YTD_FLAG,
        CASE
            WHEN DATE_TRUNC('week', PAYMENT_DATE::DATE) = DATE_TRUNC('week', CURRENT_DATE::DATE - INTERVAL '1 year') THEN TRUE
            ELSE FALSE
        END AS IS_CURRENT_WEEK_LAST_YEAR,
        SSM.MAPPING_LV_1,
        SSM.MAPPING_LV_2,
        SSM.MAPPING_LV_3
    FROM
        ANALYTICS.INTACCT.APBILLPAYMENT APBPMT
        LEFT JOIN ANALYTICS.INTACCT.APRECORD APRH ON APBPMT.RECORDKEY = APRH.RECORDNO AND APRH.RECORDTYPE IN ('apbill','apadjustment')
        LEFT JOIN ANALYTICS.INTACCT.APDETAIL APRD ON APBPMT.PAIDITEMKEY = APRD.RECORDNO AND APRH.RECORDNO = APRD.RECORDKEY
        LEFT JOIN ANALYTICS.INTACCT.VENDOR VEND ON APRH.VENDORID = VEND.VENDORID
        LEFT JOIN ANALYTICS.INTACCT.GLACCOUNT COA ON APRD.ACCOUNTNO = COA.ACCOUNTNO
        LEFT JOIN ANALYTICS.INTACCT.APRECORD APRHPAY ON APBPMT.PAYMENTKEY = APRHPAY.RECORDNO
        LEFT JOIN ANALYTICS.TREASURY.SPEND_SUMMARY_MAPPING AS SSM ON ACCOUNT_V2 = SSM.ACCOUNT
    WHERE
        APBPMT.PAYMENTKEY = APBPMT.PARENTPYMT
        AND APRHPAY.RECORDTYPE = 'appayment'
        AND APRH.VENDORID <> 'V20249'
        AND APBPMT.AMOUNT > 1
),
CY_CTE AS (
    SELECT VENDOR_ID,MAPPING_LV_1, MAPPING_LV_2,SUM(AMOUNT) AS YTD_2024
    FROM MAIN_CTE
    WHERE (PAYMENT_DATE >= '2024-01-01') AND (IS_CURRENT_WEEK = FALSE)
    GROUP BY VENDOR_ID,MAPPING_LV_1,MAPPING_LV_2
),
PY_CTE AS (
    SELECT VENDOR_ID, MAPPING_LV_1,MAPPING_LV_2,SUM(AMOUNT) AS YTD_2023
    FROM MAIN_CTE
    WHERE (LAST_YEAR_YTD_FLAG = TRUE) AND (IS_CURRENT_WEEK_LAST_YEAR = FALSE)
    AND ACCOUNT NOT IN ('2515','2508','8106','2425')
    GROUP BY VENDOR_ID,MAPPING_LV_1,MAPPING_LV_2
),
COMBINED_CTE AS (
    SELECT
        CY.VENDOR_ID AS CY_VENDOR_ID,
        CY.YTD_2024,
        PY.VENDOR_ID AS PY_VENDOR_ID,
        PY.YTD_2023,
        CASE
            WHEN PY.YTD_2023 <> 0 AND COALESCE(CY.YTD_2024, 0) = 0 THEN 'Inactive Vendor'
            WHEN COALESCE(PY.YTD_2023, 0) = 0 AND CY.YTD_2024 <> 0 THEN 'New Vendor'
            WHEN PY.YTD_2023 <> 0 AND CY.YTD_2024 <> 0 THEN 'Existing Vendor'
            ELSE 'Research'
        END AS VENDOR_STATUS,
        CASE
            WHEN CY.VENDOR_ID IS NULL THEN PY.VENDOR_ID
            WHEN PY.VENDOR_ID IS NULL THEN CY.VENDOR_ID
            ELSE PY.VENDOR_ID
        END AS VENDOR_ID_TO_USE
    FROM CY_CTE AS CY
    FULL OUTER JOIN PY_CTE AS PY ON CY.VENDOR_ID = PY.VENDOR_ID
)
SELECT DISTINCT
    M.VENDOR_ID,
    CC.VENDOR_STATUS
FROM MAIN_CTE AS M
LEFT JOIN COMBINED_CTE AS CC ON M.VENDOR_ID = CC.VENDOR_ID_TO_USE
      ;;
  }

  ######## DIMENSIONS ########

  dimension: vendor_id  {
    type: string
    sql:  ${TABLE}."VENDOR_ID";;
  }

  dimension: vendor_status  {
    type: string
    sql:  ${TABLE}."VENDOR_STATUS";;
  }


  }
