SELECT
    g.geofence_id,
    g.geom,
    g.time_fence_id,
    g.location_id,
    g.alert_exit,
    g.name,
    g.deleted,
    g.alert_enter,
    g.company_id,
    g.geojson,
    g.deleted_date,
    g.geofence_type_id,
    g.state_id,
    g.date_created,
    'https://app.estrack.com/#/geofences/' || g.geofence_id as url_t3,
    g._es_update_timestamp,
    g.geojson:"geometry" AS geojson__geometry,
    g.geojson:"geometry":"coordinates" AS geojson__geometry__coordinates,
    g.geojson:"geometry":"type" AS geojson__geometry__type,
    g.geojson:"properties":"fill":"color" AS geojson__properties__fill__color,
    g.geojson:"properties":"fill" AS geojson__properties__fill,
    g.geojson:"properties":"stroke":"weight" AS geojson__properties__stroke__weight,
    g.geojson:"type" AS geojson__type,
    g.geojson:"properties":"fill":"opacity" AS geojson__properties__fill__opacity,
    g.geojson:"properties" AS geojson__properties,
    g.geojson:"name" AS geojson__name,
    g.geojson:"properties":"stroke" AS geojson__properties__stroke,
    g.geojson:"properties":"stroke":"color" AS geojson__properties__stroke__color
FROM {{ source('es_warehouse_public', 'geofences') }} as g
