SELECT
    ai.asset_id,
    ai.end_idle_incident_id,
    ai.trip_id,
    ai.end_timestamp,
    ai.start_idle_incident_id,
    ai.idle_threshold_seconds,
    ai.start_timestamp,
    ai.duration_seconds,
    ai.tracker_id,
    ai.idle_range,
    ai.asset_idle_id,
    ai.fuel_consumption_gallons_new,
    ai.fuel_consumed_gallons,
    ai.state_id,
    ai.street,
    ai.county,
    ai.city,
    ai.date_created,
    ai._es_update_timestamp,
    ai.idle_range:"end_bound" AS idle_range__end_bound,
    ai.idle_range:"start_bound" AS idle_range__start_bound,
    ai.idle_range:"end_range" AS idle_range__end_range,
    ai.idle_range:"start_range" AS idle_range__start_range
FROM {{ source('es_warehouse_public', 'asset_idles') }} as ai
