SELECT
    bcp.billing_company_preferences_id,
    bcp.company_id,
    bcp.rental_billing_cycle_strategy,
    bcp.prefs,
    bcp.date_created,
    bcp.date_updated,
    bcp._es_update_timestamp,
    bcp.prefs:"cycle_billing_only" AS prefs__cycle_billing_only,
    bcp.prefs:"disable_monthly_statements" AS prefs__disable_monthly_statements,
    bcp.prefs:"general_services_administration" AS prefs__general_services_administration,
    bcp.prefs:"in_bankruptcy" AS prefs__in_bankruptcy,
    bcp.prefs:"is_paperless_billing" AS prefs__is_paperless_billing,
    bcp.prefs:"legal_audit" AS prefs__legal_audit,
    bcp.prefs:"national_account" AS prefs__national_account,
    bcp.prefs:"rental_billing_cycle_strategy" AS prefs__rental_billing_cycle_strategy,
    bcp.prefs:"managed_billing" AS prefs__managed_billing,
    bcp.prefs:"legal_audit_time" AS prefs__legal_audit_time,
    bcp.prefs:"bad_debt" AS prefs__bad_debt,
    bcp.prefs:"four_week_billing_date" AS prefs__four_week_billing_date,
    bcp.prefs:"internal_company" AS prefs__internal_company,
    bcp.prefs:"invoice_contacts" AS prefs__invoice_contacts,
    bcp.prefs:"monthly_statement_contacts" AS prefs__monthly_statement_contacts,
    bcp.prefs:"primary_billing_contact_user_id" AS prefs__primary_billing_contact_user_id
FROM {{ source('es_warehouse_public', 'billing_company_preferences') }} as bcp
