SELECT
    hau.asset_usage_id,
    hau.asset_id,
    hau.on_time,
    hau.hauled_time,
    hau.hauling_time,
    hau.idle_time,
    hau.report_range,
    hau.source_metadata,
    hau.miles_driven,
    hau.hauled_distance,
    hau.hauling_distance,
    hau.overspeed_duration,
    hau.speeding_incident_count,
    hau.aggressive_incident_count,
    hau.impact_incident_count,
    hau.idle_incident_count,
    hau.trip_ids,
    hau._es_update_timestamp,
    hau.report_range:"end_bound" AS report_range__end_bound,
    hau.report_range:"start_bound" AS report_range__start_bound,
    hau.report_range:"end_range" AS report_range__end_range,
    hau.report_range:"start_range" AS report_range__start_range,
    hau.source_metadata:"trip_ids" AS source_metadata__trip_ids,
    hau.source_metadata:"asset_idle_ids" AS source_metadata__asset_idle_ids
FROM {{ source('es_warehouse_public', 'hourly_asset_usage') }} as hau
