SELECT
    tpr.third_party_rental_id,
    tpr.third_party_asset_id,
    tpr.location_id,
    tpr.company_id,
    tpr.rental_status_id,
    tpr.purchase_order_id,
    tpr.ordered_by_user_id,
    tpr.vendor_id,
    tpr.start_date,
    tpr.end_date,
    tpr.price_per_hour,
    tpr.price_per_day,
    tpr.price_per_week,
    tpr.price_per_month,
    tpr.tax_rate,
    tpr.off_rent_confirmation_no,
    tpr.date_deleted,
    tpr.rental_agreement_metadata,
    tpr.outside_rental_id,
    tpr.date_created,
    tpr.date_updated,
    tpr._es_update_timestamp,
    tpr.rental_agreement_metadata:"date_updated" AS rental_agreement_metadata__date_updated,
    tpr.rental_agreement_metadata:"download_filename" AS rental_agreement_metadata__download_filename,
    tpr.rental_agreement_metadata:"mime_type" AS rental_agreement_metadata__mime_type,
    tpr.rental_agreement_metadata:"url" AS rental_agreement_metadata__url,
    tpr.rental_agreement_metadata:"original_filename" AS rental_agreement_metadata__original_filename,
    tpr.rental_agreement_metadata:"size_bytes" AS rental_agreement_metadata__size_bytes
FROM {{ source('es_warehouse_public', 'third_party_rentals') }} as tpr
