SELECT
    haut.asset_usage_id,
    haut.asset_id,
    haut.on_time,
    haut.hauled_time,
    haut.hauling_time,
    haut.idle_time,
    haut.report_range,
    haut.source_metadata,
    haut.miles_driven,
    haut.hauled_distance,
    haut.hauling_distance,
    haut.overspeed_duration,
    haut.speeding_incident_count,
    haut.aggressive_incident_count,
    haut.impact_incident_count,
    haut.idle_incident_count,
    haut.trip_ids,
    haut._es_update_timestamp,
    haut.report_range:"end_bound" AS report_range__end_bound,
    haut.report_range:"start_bound" AS report_range__start_bound,
    haut.report_range:"end_range" AS report_range__end_range,
    haut.report_range:"start_range" AS report_range__start_range,
    haut.source_metadata:"trip_ids" AS source_metadata__trip_ids,
    haut.source_metadata:"asset_idle_ids" AS source_metadata__asset_idle_ids
FROM {{ source('es_warehouse_public', 'hourly_asset_usage_test') }} as haut
