SELECT
    amrl.api_media_request_log_id,
    amrl.camera_id,
    amrl.camera_vendor_id,
    amrl.tracking_incident_id,
    amrl.tracking_incident_notification_log_id,
    amrl.feed_id,
    amrl.request_id,
    amrl.post_url,
    amrl.data,
    amrl.response,
    amrl.send_error_msg,
    amrl.requested_timestamp,
    amrl.acknowledged_timestamp,
    amrl.requester_user_id,
    amrl.response_status_code,
    amrl.date_created,
    amrl._es_update_timestamp,
    amrl.data:"RecorderID" AS data__recorderid,
    amrl.data:"Storage" AS data__storage,
    amrl.data:"cameraId" AS data__cameraid,
    amrl.data:"ToTime" AS data__totime,
    amrl.data:"GoToDateTime" AS data__gotodatetime,
    amrl.data:"timestamp" AS data__timestamp,
    amrl.data:"title" AS data__title,
    amrl.data:"FromTime" AS data__fromtime,
    amrl.data:"CameraChannel" AS data__camerachannel,
    amrl.data:"camera" AS data__camera,
    amrl.data:"duration" AS data__duration,
    amrl.response:"errorType" AS response__errortype,
    amrl.response:"Exception":"HelpLink" AS response__exception__helplink,
    amrl.response:"Exception":"Message" AS response__exception__message,
    amrl.response:"MoreInfo":"ServiceStatus" AS response__moreinfo__servicestatus,
    amrl.response:"MoreInfo":"TargetID" AS response__moreinfo__targetid,
    amrl.response:"Exception" AS response__exception,
    amrl.response:"MoreInfo" AS response__moreinfo,
    amrl.response:"MoreInfo":"RequestID" AS response__moreinfo__requestid,
    amrl.response:"Exception":"Data":"TraceID" AS response__exception__data__traceid,
    amrl.response:"Exception":"HResult" AS response__exception__hresult,
    amrl.response:"Code" AS response__code,
    amrl.response:"Message" AS response__message,
    amrl.response:"requestId" AS response__requestid,
    amrl.response:"Exception":"Data" AS response__exception__data,
    amrl.response:"Exception":"InnerException" AS response__exception__innerexception,
    amrl.response:"MoreInfo":"Source" AS response__moreinfo__source,
    amrl.response:"Exception":"Source" AS response__exception__source,
    amrl.response:"Exception":"Data":"TraceIndex" AS response__exception__data__traceindex,
    amrl.response:"Exception":"StackTrace" AS response__exception__stacktrace
FROM {{ source('es_warehouse_public', 'api_media_request_logs') }} as amrl
