SELECT
    age.geofence_id,
    age.rental_id,
    age.encounter_time_range,
    age.asset_id,
    age.asset_geofence_encounter_id,
    age.start_odometer,
    age.end_odometer,
    age.start_hours,
    age.end_hours,
    age.start_tracking_event_id,
    age.end_tracking_event_id,
    age.start_location_old,
    age.end_location_old,
    age.start_location_geo,
    age.end_location_geo,
    age.start_location,
    age.end_location,
    age.encounter_start_timestamp,
    age.encounter_end_timestamp,
    age.date_created,
    age._es_update_timestamp,
    age.encounter_time_range:"end_bound" AS encounter_time_range__end_bound,
    age.encounter_time_range:"start_bound" AS encounter_time_range__start_bound,
    age.encounter_time_range:"end_range" AS encounter_time_range__end_range,
    age.encounter_time_range:"start_range" AS encounter_time_range__start_range,
    age.start_location:"type" AS start_location__type,
    age.start_location:"coordinates" AS start_location__coordinates,
    age.end_location:"type" AS end_location__type,
    age.end_location:"coordinates" AS end_location__coordinates
FROM {{ source('es_warehouse_public', 'asset_geofence_encounters') }} as age
