SELECT
    gli.id,
    gli.domain_id,
    gli.rental_id,
    gli.line_item_id,
    gli.invoice_id,
    gli.branch_id,
    gli.asset_id,
    gli.part_id,
    gli.line_item_type_id,
    gli.quantity,
    gli.price_per_unit,
    gli.sub_total,
    gli.tax,
    gli.total,
    gli.description,
    gli.extended_data,
    gli.payload,
    gli.created_date,
    gli.deleted_date,
    gli._es_update_timestamp,
    gli.extended_data:"rental" AS extended_data__rental,
    gli.extended_data:"rental":"cheapest_period_week_count" AS extended_data__rental__cheapest_period_week_count,
    gli.extended_data:"rental":"location" AS extended_data__rental__location,
    gli.extended_data:"rental":"location":"street_1" AS extended_data__rental__location__street_1,
    gli.extended_data:"rental":"price_per_month" AS extended_data__rental__price_per_month,
    gli.extended_data:"rental":"shift_info":"shift_type" AS extended_data__rental__shift_info__shift_type,
    gli.extended_data:"rental":"job_description" AS extended_data__rental__job_description,
    gli.extended_data:"rental":"order_id" AS extended_data__rental__order_id,
    gli.extended_data:"rental":"location":"state" AS extended_data__rental__location__state,
    gli.extended_data:"price" AS extended_data__price,
    gli.extended_data:"rental":"billable_days" AS extended_data__rental__billable_days,
    gli.extended_data:"rental":"cycle_billing_date" AS extended_data__rental__cycle_billing_date,
    gli.extended_data:"rental":"total_week_days" AS extended_data__rental__total_week_days,
    gli.extended_data:"billedFromContactFirstName" AS extended_data__billedfromcontactfirstname,
    gli.extended_data:"customerName" AS extended_data__customername,
    gli.extended_data:"jobSiteAddress" AS extended_data__jobsiteaddress,
    gli.extended_data:"purchaseOrderName" AS extended_data__purchaseordername,
    gli.extended_data:"startDate" AS extended_data__startdate,
    gli.extended_data:"orderId" AS extended_data__orderid,
    gli.extended_data:"damage_waiver" AS extended_data__damage_waiver,
    gli.extended_data:"edr_message" AS extended_data__edr_message,
    gli.extended_data:"settings":"cleaning_hourly_rate" AS extended_data__settings__cleaning_hourly_rate,
    gli.extended_data:"settings":"default_tax" AS extended_data__settings__default_tax,
    gli.extended_data:"settings":"invoice_start_number" AS extended_data__settings__invoice_start_number,
    gli.extended_data:"rental":"inventory_product_name" AS extended_data__rental__inventory_product_name,
    gli.extended_data:"rental":"is_below_floor_rate" AS extended_data__rental__is_below_floor_rate,
    gli.extended_data:"rental":"inventory_product_id" AS extended_data__rental__inventory_product_id,
    gli.extended_data:"rental":"equipment_assignments" AS extended_data__rental__equipment_assignments,
    gli.extended_data:"rental":"date_created" AS extended_data__rental__date_created,
    gli.extended_data:"rental":"delivery_required" AS extended_data__rental__delivery_required,
    gli.extended_data:"rental":"return_delivery_required" AS extended_data__rental__return_delivery_required,
    gli.extended_data:"rental":"location":"street_2" AS extended_data__rental__location__street_2,
    gli.extended_data:"rental":"external_id" AS extended_data__rental__external_id,
    gli.extended_data:"rental":"price_per_day" AS extended_data__rental__price_per_day,
    gli.extended_data:"rental":"billed_from_date" AS extended_data__rental__billed_from_date,
    gli.extended_data:"rental":"billing_week_days" AS extended_data__rental__billing_week_days,
    gli.extended_data:"transport_id" AS extended_data__transport_id,
    gli.extended_data:"assetName" AS extended_data__assetname,
    gli.extended_data:"billedFrom" AS extended_data__billedfrom,
    gli.extended_data:"billedToPhone" AS extended_data__billedtophone,
    gli.extended_data:"jobSiteNickName" AS extended_data__jobsitenickname,
    gli.extended_data:"pricePerWeek" AS extended_data__priceperweek,
    gli.extended_data:"rentalProtectionPlan":"name" AS extended_data__rentalprotectionplan__name,
    gli.extended_data:"billedToAddress" AS extended_data__billedtoaddress,
    gli.extended_data:"asset_class_id" AS extended_data__asset_class_id,
    gli.extended_data:"start_date" AS extended_data__start_date,
    gli.extended_data:"settings":"net_terms" AS extended_data__settings__net_terms,
    gli.extended_data:"rental":"one_time_charge" AS extended_data__rental__one_time_charge,
    gli.extended_data:"cleaning_id" AS extended_data__cleaning_id,
    gli.extended_data:"rental":"rental_bill_type" AS extended_data__rental__rental_bill_type,
    gli.extended_data:"facilitator_type" AS extended_data__facilitator_type,
    gli.extended_data:"rental":"asset_class" AS extended_data__rental__asset_class,
    gli.extended_data:"rental":"asset_name" AS extended_data__rental__asset_name,
    gli.extended_data:"rental":"timezone" AS extended_data__rental__timezone,
    gli.extended_data:"billedFromPhone" AS extended_data__billedfromphone,
    gli.extended_data:"rentalProtectionPlan" AS extended_data__rentalprotectionplan,
    gli.extended_data:"rentalProtectionPlan":"percent" AS extended_data__rentalprotectionplan__percent,
    gli.extended_data:"rentalProtectionPlan":"rental_protection_plan_id" AS extended_data__rentalprotectionplan__rental_protection_plan_id,
    gli.extended_data:"asset_class" AS extended_data__asset_class,
    gli.extended_data:"rate_day" AS extended_data__rate_day,
    gli.extended_data:"rental":"cycle_billing_day" AS extended_data__rental__cycle_billing_day,
    gli.extended_data:"lost_key_id" AS extended_data__lost_key_id,
    gli.extended_data:"delivery" AS extended_data__delivery,
    gli.extended_data:"delivery":"asset_id" AS extended_data__delivery__asset_id,
    gli.extended_data:"rental":"location":"zip_code" AS extended_data__rental__location__zip_code,
    gli.extended_data:"rental":"price_per_hour" AS extended_data__rental__price_per_hour,
    gli.extended_data:"part_number" AS extended_data__part_number,
    gli.extended_data:"rental":"asset_id" AS extended_data__rental__asset_id,
    gli.extended_data:"rental":"drop_off_delivery_required" AS extended_data__rental__drop_off_delivery_required,
    gli.extended_data:"rental":"end_date_estimated" AS extended_data__rental__end_date_estimated,
    gli.extended_data:"rental":"taxable" AS extended_data__rental__taxable,
    gli.extended_data:"rental":"price" AS extended_data__rental__price,
    gli.extended_data:"billedFromEmail" AS extended_data__billedfromemail,
    gli.extended_data:"isFlatMonthlyRate" AS extended_data__isflatmonthlyrate,
    gli.extended_data:"end_date" AS extended_data__end_date,
    gli.extended_data:"rate_week" AS extended_data__rate_week,
    gli.extended_data:"refueling_id" AS extended_data__refueling_id,
    gli.extended_data:"billedToEmail" AS extended_data__billedtoemail,
    gli.extended_data:"rate_month" AS extended_data__rate_month,
    gli.extended_data:"settings":"currency_symbol" AS extended_data__settings__currency_symbol,
    gli.extended_data:"rental":"equipment_class_name" AS extended_data__rental__equipment_class_name,
    gli.extended_data:"rental":"shift_info":"shift_type_id" AS extended_data__rental__shift_info__shift_type_id,
    gli.extended_data:"asset_id" AS extended_data__asset_id,
    gli.extended_data:"event_date" AS extended_data__event_date,
    gli.extended_data:"order_id" AS extended_data__order_id,
    gli.extended_data:"rental":"amount_received" AS extended_data__rental__amount_received,
    gli.extended_data:"rental":"borrower_user_id" AS extended_data__rental__borrower_user_id,
    gli.extended_data:"rental":"off_rent_date_requested" AS extended_data__rental__off_rent_date_requested,
    gli.extended_data:"rental":"rental_purchase_option_id" AS extended_data__rental__rental_purchase_option_id,
    gli.extended_data:"hours_spent" AS extended_data__hours_spent,
    gli.extended_data:"rental":"deleted" AS extended_data__rental__deleted,
    gli.extended_data:"rental":"lien_notice_sent" AS extended_data__rental__lien_notice_sent,
    gli.extended_data:"rental":"cycle_billing_period" AS extended_data__rental__cycle_billing_period,
    gli.extended_data:"billedFromContactName" AS extended_data__billedfromcontactname,
    gli.extended_data:"billedToContactFirstName" AS extended_data__billedtocontactfirstname,
    gli.extended_data:"billedToContactLastName" AS extended_data__billedtocontactlastname,
    gli.extended_data:"status" AS extended_data__status,
    gli.extended_data:"damage_waiver_percentage" AS extended_data__damage_waiver_percentage,
    gli.extended_data:"settings":"credit_limit" AS extended_data__settings__credit_limit,
    gli.extended_data:"settings":"tax_name" AS extended_data__settings__tax_name,
    gli.extended_data:"rental":"location":"city" AS extended_data__rental__location__city,
    gli.extended_data:"settings":"key_replacement_charge" AS extended_data__settings__key_replacement_charge,
    gli.extended_data:"rental":"cycle_bill_date" AS extended_data__rental__cycle_bill_date,
    gli.extended_data:"billedFromAddress" AS extended_data__billedfromaddress,
    gli.extended_data:"delivery":"scheduled_date" AS extended_data__delivery__scheduled_date,
    gli.extended_data:"rental":"price_per_week" AS extended_data__rental__price_per_week,
    gli.extended_data:"rental":"rental_id" AS extended_data__rental__rental_id,
    gli.extended_data:"rental":"is_flat_monthly_rate" AS extended_data__rental__is_flat_monthly_rate,
    gli.extended_data:"rental":"delivery_instructions" AS extended_data__rental__delivery_instructions,
    gli.extended_data:"rental":"rental_type_id" AS extended_data__rental__rental_type_id,
    gli.extended_data:"rental":"start_date_estimated" AS extended_data__rental__start_date_estimated,
    gli.extended_data:"rental_id" AS extended_data__rental_id,
    gli.extended_data:"rental":"rate_type_id" AS extended_data__rental__rate_type_id,
    gli.extended_data:"rental":"total_days" AS extended_data__rental__total_days,
    gli.extended_data:"transport_type" AS extended_data__transport_type,
    gli.extended_data:"billedFromContactLastName" AS extended_data__billedfromcontactlastname,
    gli.extended_data:"notes" AS extended_data__notes,
    gli.extended_data:"pricePerHour" AS extended_data__priceperhour,
    gli.extended_data:"salesPerson" AS extended_data__salesperson,
    gli.extended_data:"endDate" AS extended_data__enddate,
    gli.extended_data:"settings":"cycle_billing_period" AS extended_data__settings__cycle_billing_period,
    gli.extended_data:"id" AS extended_data__id,
    gli.extended_data:"rental":"jobsite" AS extended_data__rental__jobsite,
    gli.extended_data:"rate_hourly" AS extended_data__rate_hourly,
    gli.extended_data:"settings":"fuel_cost" AS extended_data__settings__fuel_cost,
    gli.extended_data:"rental":"is_flexible_rate" AS extended_data__rental__is_flexible_rate,
    gli.extended_data:"rental":"cheapest_period_hour_count" AS extended_data__rental__cheapest_period_hour_count,
    gli.extended_data:"rental":"cheapest_period_month_count" AS extended_data__rental__cheapest_period_month_count,
    gli.extended_data:"rental":"end_date" AS extended_data__rental__end_date,
    gli.extended_data:"rental":"start_date" AS extended_data__rental__start_date,
    gli.extended_data:"rental":"purchase_price" AS extended_data__rental__purchase_price,
    gli.extended_data:"delivery":"delivery_id" AS extended_data__delivery__delivery_id,
    gli.extended_data:"rental":"shift_info" AS extended_data__rental__shift_info,
    gli.extended_data:"rental":"drop_off_delivery_id" AS extended_data__rental__drop_off_delivery_id,
    gli.extended_data:"amount" AS extended_data__amount,
    gli.extended_data:"assetId" AS extended_data__assetid,
    gli.extended_data:"billedTo" AS extended_data__billedto,
    gli.extended_data:"pricePerDay" AS extended_data__priceperday,
    gli.extended_data:"settings" AS extended_data__settings,
    gli.extended_data:"settings":"fuel_unit" AS extended_data__settings__fuel_unit,
    gli.extended_data:"settings":"net_terms_period" AS extended_data__settings__net_terms_period,
    gli.extended_data:"settings":"tax_id" AS extended_data__settings__tax_id,
    gli.extended_data:"part_id" AS extended_data__part_id,
    gli.extended_data:"rental":"cheapest_period_day_count" AS extended_data__rental__cheapest_period_day_count,
    gli.extended_data:"rental":"location":"nickname" AS extended_data__rental__location__nickname,
    gli.extended_data:"delivery":"rental_id" AS extended_data__delivery__rental_id,
    gli.extended_data:"rental":"billed_to_date" AS extended_data__rental__billed_to_date,
    gli.extended_data:"rental":"rpp_percentage_as_decimal" AS extended_data__rental__rpp_percentage_as_decimal,
    gli.extended_data:"total" AS extended_data__total,
    gli.extended_data:"assetClass" AS extended_data__assetclass,
    gli.extended_data:"billedToContactName" AS extended_data__billedtocontactname,
    gli.extended_data:"pricePerMonth" AS extended_data__pricepermonth,
    gli.extended_data:"purchaseOrderId" AS extended_data__purchaseorderid,
    gli.extended_data:"rental":"equipment_class_id" AS extended_data__rental__equipment_class_id,
    gli.extended_data:"rental":"part_type_id" AS extended_data__rental__part_type_id,
    gli.extended_data:"rental":"rental_status_id" AS extended_data__rental__rental_status_id,
    gli.extended_data:"rental":"return_delivery_id" AS extended_data__rental__return_delivery_id,
    gli.extended_data:"rental":"rental_protection_plan_id" AS extended_data__rental__rental_protection_plan_id,
    gli.extended_data:"damage_noticed_id" AS extended_data__damage_noticed_id,
    gli.extended_data:"rental":"inventory_product_name_historical" AS extended_data__rental__inventory_product_name_historical,
    gli.extended_data:"netTermsId" AS extended_data__nettermsid,
    gli.extended_data:"orderPurchaseOrderReference" AS extended_data__orderpurchaseorderreference,
    gli.extended_data:"rental":"has_re_rent" AS extended_data__rental__has_re_rent,
    gli.extended_data:"rental":"quantity" AS extended_data__rental__quantity
FROM {{ source('es_warehouse_public', 'global_line_items') }} as gli
