SELECT
    d.asset_condition_snapshot_id,
    d.domain_id,
    d.rental_id,
    d.order_id,
    d.line_item_id,
    d.delivery_status_id,
    d.contact_phone_number,
    d.driver_user_id,
    d.scheduled_date,
    d.delivery_creation_type_id,
    d.delivery_company_id,
    d.facilitator_type_id,
    d.contact_name,
    d.location_id,
    d.run_name,
    d.note,
    d.asset_id,
    d.delivery_id,
    d.completed_date,
    d.charge,
    d.completed_by_user_id,
    d.quantity,
    d.assignment_id,
    d.assignment_type_id,
    d.part_id,
    d.delivery_details,
    d.origin_location_id,
    d.delivery_type_id,
    d.date_created,
    d.date_updated,
    d._es_update_timestamp,
    d.delivery_details:"damage_description" AS delivery_details__damage_description,
    d.delivery_details:"hours_reading" AS delivery_details__hours_reading,
    d.delivery_details:"fuel_reading" AS delivery_details__fuel_reading,
    d.delivery_details:"notes" AS delivery_details__notes,
    d.delivery_details:"odometer_reading" AS delivery_details__odometer_reading,
    d.delivery_details:"reporting_user_id" AS delivery_details__reporting_user_id
FROM {{ source('es_warehouse_public', 'deliveries') }} as d
