SELECT
    ndl.notification_delivery_log_id,
    ndl.user_id,
    ndl.tracking_incident_id,
    ndl.notification_type_id,
    ndl.created_at,
    ndl.recipient,
    ndl.message,
    ndl.message_varchar,
    ndl.delivered_at,
    ndl.delivery_message,
    ndl.tracking_diagnostic_codes_id,
    ndl.asset_alert_rule_id,
    ndl.description,
    ndl._es_update_timestamp,
    ndl.message:"is_entering" AS message__is_entering,
    ndl.message:"verb" AS message__verb,
    ndl.message:"content" AS message__content,
    ndl.message:"reply_to":"email" AS message__reply_to__email,
    ndl.message:"recipient" AS message__recipient,
    ndl.message:"threshold_alert_operand" AS message__threshold_alert_operand,
    ndl.message:"additional_information" AS message__additional_information,
    ndl.message:"incident_alert_type" AS message__incident_alert_type,
    ndl.message:"from":"email" AS message__from__email,
    ndl.message:"reply_to" AS message__reply_to,
    ndl.message:"tracking_settings" AS message__tracking_settings,
    ndl.message:"tracking_settings":"subscription_tracking":"enable" AS message__tracking_settings__subscription_tracking__enable,
    ndl.message:"threshold_alert_current_value" AS message__threshold_alert_current_value,
    ndl.message:"personalizations" AS message__personalizations,
    ndl.message:"asset_id" AS message__asset_id,
    ndl.message:"driver_name" AS message__driver_name,
    ndl.message:"subject" AS message__subject,
    ndl.message:"threshold_alert_unit" AS message__threshold_alert_unit,
    ndl.message:"template_id" AS message__template_id,
    ndl.message:"geofence_name" AS message__geofence_name,
    ndl.message:"asset_speed" AS message__asset_speed,
    ndl.message:"tracking_settings":"subscription_tracking" AS message__tracking_settings__subscription_tracking,
    ndl.message:"asset_status_alert_type" AS message__asset_status_alert_type,
    ndl.message:"threshold_exceeded_value_range" AS message__threshold_exceeded_value_range,
    ndl.message:"from":"name" AS message__from__name,
    ndl.message:"exceeded_by_amount" AS message__exceeded_by_amount,
    ndl.message:"from" AS message__from,
    ndl.message:"alert_time" AS message__alert_time,
    ndl.message:"application_link" AS message__application_link,
    ndl.message:"asset_custom_name" AS message__asset_custom_name,
    ndl.message:"asset_image" AS message__asset_image,
    ndl.message:"categories" AS message__categories,
    ndl.message:"posted_speed_limit" AS message__posted_speed_limit
FROM {{ source('es_warehouse_public', 'notification_delivery_logs') }} as ndl
