SELECT
    p.photo_id,
    p.uploading_user_id,
    p.filename,
    p.thumbnail,
    p.small,
    p.medium,
    p.large,
    p.file_problem,
    p.original_metadata,
    p._es_update_timestamp,
    p.original_metadata:"" AS original_metadata__,
    p.original_metadata:"GPSLongitude" AS original_metadata__gpslongitude,
    p.original_metadata:"WhiteBalance" AS original_metadata__whitebalance,
    p.original_metadata:"DPIWidth" AS original_metadata__dpiwidth,
    p.original_metadata:"Orientation" AS original_metadata__orientation,
    p.original_metadata:"ProfileName" AS original_metadata__profilename,
    p.original_metadata:"GPSLongitudeRef" AS original_metadata__gpslongituderef,
    p.original_metadata:"GPSProcessingMethod" AS original_metadata__gpsprocessingmethod,
    p.original_metadata:"DPIHeight" AS original_metadata__dpiheight,
    p.original_metadata:"ExposureTime" AS original_metadata__exposuretime,
    p.original_metadata:"kCGImageDestinationICCProfile" AS original_metadata__kcgimagedestinationiccprofile,
    p.original_metadata:"PixelHeight" AS original_metadata__pixelheight,
    p.original_metadata:"DateTime" AS original_metadata__datetime,
    p.original_metadata:"ISOSpeedRatings" AS original_metadata__isospeedratings,
    p.original_metadata:"ColorModel" AS original_metadata__colormodel,
    p.original_metadata:"FNumber" AS original_metadata__fnumber,
    p.original_metadata:"FocalLength" AS original_metadata__focallength,
    p.original_metadata:"GPSTimeStamp" AS original_metadata__gpstimestamp,
    p.original_metadata:"SubSecTimeOriginal" AS original_metadata__subsectimeoriginal,
    p.original_metadata:"PrimaryImage" AS original_metadata__primaryimage,
    p.original_metadata:"Make" AS original_metadata__make,
    p.original_metadata:"Model" AS original_metadata__model,
    p.original_metadata:"GPSAltitude" AS original_metadata__gpsaltitude,
    p.original_metadata:"GPSAltitudeRef" AS original_metadata__gpsaltituderef,
    p.original_metadata:"HasAlpha" AS original_metadata__hasalpha,
    p.original_metadata:"SubSecTimeDigitized" AS original_metadata__subsectimedigitized,
    p.original_metadata:"Depth" AS original_metadata__depth,
    p.original_metadata:"ImageLength" AS original_metadata__imagelength,
    p.original_metadata:"ImageWidth" AS original_metadata__imagewidth,
    p.original_metadata:"GPSLatitude" AS original_metadata__gpslatitude,
    p.original_metadata:"GPSLatitudeRef" AS original_metadata__gpslatituderef,
    p.original_metadata:"GPSDateStamp" AS original_metadata__gpsdatestamp,
    p.original_metadata:"PixelWidth" AS original_metadata__pixelwidth,
    p.original_metadata:"Flash" AS original_metadata__flash,
    p.original_metadata:"DateTimeDigitized" AS original_metadata__datetimedigitized,
    p.original_metadata:"SubSecTime" AS original_metadata__subsectime
FROM {{ source('es_warehouse_public', 'photos') }} as p
