SELECT
    ti.tracking_event_id,
    ti.optional_fields,
    ti.report_timestamp,
    ti.tracking_incident_type_id,
    ti.vendor_timestamp,
    ti.tracker_id,
    ti.trip_id,
    ti.tracking_incident_id,
    ti.duration,
    ti.asset_id,
    ti.geofence_id,
    ti.incident_viewed,
    ti.time_fence_id,
    ti.asset_incident_threshold_id,
    ti.created,
    ti._es_update_timestamp,
    ti.optional_fields:"startIncidentId" AS optional_fields__startincidentid,
    ti.optional_fields:"driver_id" AS optional_fields__driver_id,
    ti.optional_fields:"trip_odometer_miles" AS optional_fields__trip_odometer_miles,
    ti.optional_fields:"idle_threshold" AS optional_fields__idle_threshold,
    ti.optional_fields:"driver_location_timestamp" AS optional_fields__driver_location_timestamp,
    ti.optional_fields:"trip_distance_accumulator" AS optional_fields__trip_distance_accumulator,
    ti.optional_fields:"location_timezone_name" AS optional_fields__location_timezone_name,
    ti.optional_fields:"error" AS optional_fields__error,
    ti.optional_fields:"stop_driving_source" AS optional_fields__stop_driving_source,
    ti.optional_fields:"speed_unit" AS optional_fields__speed_unit,
    ti.optional_fields:"driver_asset_timestamp_difference" AS optional_fields__driver_asset_timestamp_difference,
    ti.optional_fields:"idleStartIncidentId" AS optional_fields__idlestartincidentid,
    ti.optional_fields:"gps_fix_timestamp" AS optional_fields__gps_fix_timestamp,
    ti.optional_fields:"maxSpeed" AS optional_fields__maxspeed,
    ti.optional_fields:"trip_ended_by" AS optional_fields__trip_ended_by,
    ti.optional_fields:"duration_error" AS optional_fields__duration_error,
    ti.optional_fields:"driver_longitude" AS optional_fields__driver_longitude,
    ti.optional_fields:"state":"id" AS optional_fields__state__id,
    ti.optional_fields:"durationError" AS optional_fields__durationerror,
    ti.optional_fields:"fuelUsage" AS optional_fields__fuelusage,
    ti.optional_fields:"elog_device_id" AS optional_fields__elog_device_id,
    ti.optional_fields:"vehicle_speed" AS optional_fields__vehicle_speed,
    ti.optional_fields:"location_time" AS optional_fields__location_time,
    ti.optional_fields:"voltage" AS optional_fields__voltage,
    ti.optional_fields:"state" AS optional_fields__state,
    ti.optional_fields:"ignition_on_incident_id" AS optional_fields__ignition_on_incident_id,
    ti.optional_fields:"odometer_using_speed_over_time" AS optional_fields__odometer_using_speed_over_time,
    ti.optional_fields:"speedStartIncidentId" AS optional_fields__speedstartincidentid,
    ti.optional_fields:"duration_fix_tracking_event_id" AS optional_fields__duration_fix_tracking_event_id,
    ti.optional_fields:"ignition_off_timestamp" AS optional_fields__ignition_off_timestamp,
    ti.optional_fields:"trip_odo_miles" AS optional_fields__trip_odo_miles,
    ti.optional_fields:"idleThreshold" AS optional_fields__idlethreshold,
    ti.optional_fields:"extreme_threshold_value" AS optional_fields__extreme_threshold_value,
    ti.optional_fields:"driver_distance_from_asset" AS optional_fields__driver_distance_from_asset,
    ti.optional_fields:"endIncidentTimestamp" AS optional_fields__endincidenttimestamp,
    ti.optional_fields:"state":"name" AS optional_fields__state__name,
    ti.optional_fields:"street" AS optional_fields__street,
    ti.optional_fields:"trip_distance_miles" AS optional_fields__trip_distance_miles,
    ti.optional_fields:"duplicate_error" AS optional_fields__duplicate_error,
    ti.optional_fields:"notify" AS optional_fields__notify,
    ti.optional_fields:"start_driving_incident_id" AS optional_fields__start_driving_incident_id,
    ti.optional_fields:"idleEndIncidentTimestamp" AS optional_fields__idleendincidenttimestamp,
    ti.optional_fields:"state":"abbreviation" AS optional_fields__state__abbreviation,
    ti.optional_fields:"county" AS optional_fields__county,
    ti.optional_fields:"posted_speed_limit" AS optional_fields__posted_speed_limit,
    ti.optional_fields:"source" AS optional_fields__source,
    ti.optional_fields:"driver_latitude" AS optional_fields__driver_latitude,
    ti.optional_fields:"driving_distance_miles" AS optional_fields__driving_distance_miles,
    ti.optional_fields:"city" AS optional_fields__city,
    ti.optional_fields:"ignition_on_timestamp" AS optional_fields__ignition_on_timestamp
FROM {{ source('es_warehouse_public', 'tracking_incidents') }} as ti
