SELECT
    cpoal.company_purchase_order_audit_log_id,
    cpoal.user_id,
    cpoal.action,
    cpoal.parameters,
    cpoal.date_created,
    cpoal._es_update_timestamp,
    cpoal.parameters:"changes":"duedate" AS parameters__changes__duedate,
    cpoal.parameters:"changes":"order_status" AS parameters__changes__order_status,
    cpoal.parameters:"changes":"submitted_at" AS parameters__changes__submitted_at,
    cpoal.parameters:"changes":"company_purchase_order_type_id" AS parameters__changes__company_purchase_order_type_id,
    cpoal.parameters:"changes":"created_at" AS parameters__changes__created_at,
    cpoal.parameters:"changes":"created_by_user_id" AS parameters__changes__created_by_user_id,
    cpoal.parameters:"changes":"equipment_class_id" AS parameters__changes__equipment_class_id,
    cpoal.parameters:"changes":"fuel_card" AS parameters__changes__fuel_card,
    cpoal.parameters:"changes":"invoice_date" AS parameters__changes__invoice_date,
    cpoal.parameters:"changes":"reconciliation_status" AS parameters__changes__reconciliation_status,
    cpoal.parameters:"changes":"odometer" AS parameters__changes__odometer,
    cpoal.parameters:"changes":"toll_transponder" AS parameters__changes__toll_transponder,
    cpoal.parameters:"changes":"fhwt" AS parameters__changes__fhwt,
    cpoal.parameters:"changes":"lienholder_on_title" AS parameters__changes__lienholder_on_title,
    cpoal.parameters:"changes":"sage_record_id" AS parameters__changes__sage_record_id,
    cpoal.parameters:"changes":"reconciliation_status_date" AS parameters__changes__reconciliation_status_date,
    cpoal.parameters:"changes":"week_to_be_paid" AS parameters__changes__week_to_be_paid,
    cpoal.parameters:"changes":"tire_rim_size" AS parameters__changes__tire_rim_size,
    cpoal.parameters:"company_purchase_order_id" AS parameters__company_purchase_order_id,
    cpoal.parameters:"changes":"note" AS parameters__changes__note,
    cpoal.parameters:"changes":"pending_schedule" AS parameters__changes__pending_schedule,
    cpoal.parameters:"changes":"registration_cost" AS parameters__changes__registration_cost,
    cpoal.parameters:"changes":"original_promise_date" AS parameters__changes__original_promise_date,
    cpoal.parameters:"changes":"due_date" AS parameters__changes__due_date,
    cpoal.parameters:"changes":"equipment_model_id" AS parameters__changes__equipment_model_id,
    cpoal.parameters:"changes":"release_date" AS parameters__changes__release_date,
    cpoal.parameters:"changes":"year" AS parameters__changes__year,
    cpoal.parameters:"changes":"company_purchase_order_line_item_number" AS parameters__changes__company_purchase_order_line_item_number,
    cpoal.parameters:"changes":"attachments" AS parameters__changes__attachments,
    cpoal.parameters:"changes":"license_plate" AS parameters__changes__license_plate,
    cpoal.parameters:"changes":"sales_tax" AS parameters__changes__sales_tax,
    cpoal.parameters:"changes":"gvwr" AS parameters__changes__gvwr,
    cpoal.parameters:"changes":"paid_date" AS parameters__changes__paid_date,
    cpoal.parameters:"changes":"payment_type" AS parameters__changes__payment_type,
    cpoal.parameters:"changes":"finance_status" AS parameters__changes__finance_status,
    cpoal.parameters:"changes":"net_terms_id" AS parameters__changes__net_terms_id,
    cpoal.parameters:"changes":"factory_build_specifications" AS parameters__changes__factory_build_specifications,
    cpoal.parameters:"changes":"license_state_id" AS parameters__changes__license_state_id,
    cpoal.parameters:"changes":"dot_unit_number" AS parameters__changes__dot_unit_number,
    cpoal.parameters:"changes":"tire_size" AS parameters__changes__tire_size,
    cpoal.parameters:"company_purchase_order_line_item_id" AS parameters__company_purchase_order_line_item_id,
    cpoal.parameters:"changes":"net_price" AS parameters__changes__net_price,
    cpoal.parameters:"changes":"approved_at" AS parameters__changes__approved_at,
    cpoal.parameters:"changes":"approved_by_user_id" AS parameters__changes__approved_by_user_id,
    cpoal.parameters:"changes":"company_purchase_order_line_item_id" AS parameters__changes__company_purchase_order_line_item_id,
    cpoal.parameters:"changes":"vendor_id" AS parameters__changes__vendor_id,
    cpoal.parameters:"changes":"asset_id" AS parameters__changes__asset_id,
    cpoal.parameters:"changes":"title_status" AS parameters__changes__title_status,
    cpoal.parameters:"changes":"deleted_at" AS parameters__changes__deleted_at,
    cpoal.parameters:"changes" AS parameters__changes,
    cpoal.parameters:"changes":"serial" AS parameters__changes__serial,
    cpoal.parameters:"changes":"submitted_by_user_id" AS parameters__changes__submitted_by_user_id,
    cpoal.parameters:"changes":"quantity" AS parameters__changes__quantity,
    cpoal.parameters:"changes":"pdf" AS parameters__changes__pdf,
    cpoal.parameters:"changes":"modified_at" AS parameters__changes__modified_at,
    cpoal.parameters:"changes":"titled_owner" AS parameters__changes__titled_owner,
    cpoal.parameters:"changes":"aftermarket_oec" AS parameters__changes__aftermarket_oec,
    cpoal.parameters:"changes":"invoice_due_date" AS parameters__changes__invoice_due_date,
    cpoal.parameters:"changes":"daystilldue" AS parameters__changes__daystilldue,
    cpoal.parameters:"changes":"invoice_number" AS parameters__changes__invoice_number,
    cpoal.parameters:"changes":"market_id" AS parameters__changes__market_id,
    cpoal.parameters:"changes":"license_expiration" AS parameters__changes__license_expiration,
    cpoal.parameters:"changes":"tax" AS parameters__changes__tax,
    cpoal.parameters:"changes":"current_promise_date" AS parameters__changes__current_promise_date,
    cpoal.parameters:"changes":"company_purchase_order_id" AS parameters__changes__company_purchase_order_id,
    cpoal.parameters:"changes":"freight_cost" AS parameters__changes__freight_cost,
    cpoal.parameters:"changes":"vin" AS parameters__changes__vin,
    cpoal.parameters:"changes":"title_processed" AS parameters__changes__title_processed,
    cpoal.parameters:"changes":"rebate" AS parameters__changes__rebate
FROM {{ source('es_warehouse_public', 'company_purchase_order_audit_log') }} as cpoal
