SELECT
    ndlo.notification_delivery_log_id,
    ndlo.user_id,
    ndlo.tracking_incident_id,
    ndlo.notification_type_id,
    ndlo.created_at,
    ndlo.recipient,
    ndlo.message,
    ndlo.message_varchar,
    ndlo.delivered_at,
    ndlo.delivery_message,
    ndlo.tracking_diagnostic_codes_id,
    ndlo.asset_alert_rule_id,
    ndlo._es_update_timestamp,
    ndlo.message:"verb" AS message__verb,
    ndlo.message:"is_entering" AS message__is_entering,
    ndlo.message:"recipient" AS message__recipient,
    ndlo.message:"threshold_alert_operand" AS message__threshold_alert_operand,
    ndlo.message:"reply_to":"email" AS message__reply_to__email,
    ndlo.message:"additional_information" AS message__additional_information,
    ndlo.message:"incident_alert_type" AS message__incident_alert_type,
    ndlo.message:"from":"email" AS message__from__email,
    ndlo.message:"reply_to" AS message__reply_to,
    ndlo.message:"threshold_alert_current_value" AS message__threshold_alert_current_value,
    ndlo.message:"asset_id" AS message__asset_id,
    ndlo.message:"subject" AS message__subject,
    ndlo.message:"threshold_alert_unit" AS message__threshold_alert_unit,
    ndlo.message:"personalizations" AS message__personalizations,
    ndlo.message:"driver_name" AS message__driver_name,
    ndlo.message:"template_id" AS message__template_id,
    ndlo.message:"geofence_name" AS message__geofence_name,
    ndlo.message:"asset_status_alert_type" AS message__asset_status_alert_type,
    ndlo.message:"threshold_exceeded_value_range" AS message__threshold_exceeded_value_range,
    ndlo.message:"alert_time" AS message__alert_time,
    ndlo.message:"application_link" AS message__application_link,
    ndlo.message:"asset_custom_name" AS message__asset_custom_name,
    ndlo.message:"asset_image" AS message__asset_image,
    ndlo.message:"from" AS message__from
FROM {{ source('es_warehouse_public', 'notification_delivery_logs_old') }} as ndlo
