---
version: 2
models:
  - name: stg_es_warehouse_public__payment_applications
    description: Model for es_warehouse.public.payment_applications
    columns:
      - name: payment_application_id
        description: ""
        data_tests:
          - not_null
          - unique
      - name: payment_id
        description: ""
      - name: invoice_id
        description: ""
      - name: amount
        description: ""
      - name: user_id
        description: ""
      - name: date
        description: ""
      - name: reversed_date
        description: ""
      - name: reversed_by_user_id
        description: ""
      - name: reversal_reason
        description: ""
      - name: payment_application_reversal_reason_id
        description: ""
      - name: _es_update_timestamp
        description: "{{ doc('_es_update_timestamp') }}"
