SELECT
    c.contract_id,
    c.type,
    c.terms,
    c.signature,
    c.date_signed,
    c.contract_type_id,
    c.title,
    c.last_sent,
    c.order_id,
    c.date_created,
    c._es_update_timestamp,
    c.terms:"billing":"email" AS terms__billing__email,
    c.terms:"billing":"reference" AS terms__billing__reference,
    c.terms:"billing":"salesperson_name" AS terms__billing__salesperson_name,
    c.terms:"market":"address" AS terms__market__address,
    c.terms:"market":"phone" AS terms__market__phone,
    c.terms:"billing" AS terms__billing,
    c.terms:"billing":"address" AS terms__billing__address,
    c.terms:"billing":"name" AS terms__billing__name,
    c.terms:"line_items" AS terms__line_items,
    c.terms:"order":"job_name" AS terms__order__job_name,
    c.terms:"order":"total" AS terms__order__total,
    c.terms:"order":"name" AS terms__order__name,
    c.terms:"market":"service_email" AS terms__market__service_email,
    c.terms:"billing":"is_company_tax_exempt" AS terms__billing__is_company_tax_exempt,
    c.terms:"order":"tax_percentage" AS terms__order__tax_percentage,
    c.terms:"order_id" AS terms__order_id,
    c.terms:"order":"subtotal" AS terms__order__subtotal,
    c.terms:"market":"name" AS terms__market__name,
    c.terms:"rentals" AS terms__rentals,
    c.terms:"order":"total_tax" AS terms__order__total_tax,
    c.terms:"version" AS terms__version,
    c.terms:"billing":"phone" AS terms__billing__phone,
    c.terms:"has_quote" AS terms__has_quote,
    c.terms:"jurisdiction" AS terms__jurisdiction,
    c.terms:"market" AS terms__market,
    c.terms:"order" AS terms__order,
    c.terms:"order":"job_phase_name" AS terms__order__job_phase_name
FROM {{ source('es_warehouse_public', 'contracts') }} as c
