SELECT
    gliv.id,
    gliv.domain_id,
    gliv.rental_id,
    gliv.line_item_id,
    gliv.invoice_id,
    gliv.branch_id,
    gliv.asset_id,
    gliv.part_id,
    gliv.line_item_type_id,
    gliv.quantity,
    gliv.price_per_unit,
    gliv.sub_total,
    gliv.tax,
    gliv.total,
    gliv.description,
    gliv.extended_data,
    gliv.payload,
    gliv.created_date,
    gliv._es_update_timestamp,
    gliv.extended_data:"rental" AS extended_data__rental,
    gliv.extended_data:"rental":"cheapest_period_week_count" AS extended_data__rental__cheapest_period_week_count,
    gliv.extended_data:"rental":"location" AS extended_data__rental__location,
    gliv.extended_data:"rental":"location":"street_1" AS extended_data__rental__location__street_1,
    gliv.extended_data:"rental":"price_per_month" AS extended_data__rental__price_per_month,
    gliv.extended_data:"rental":"location":"state" AS extended_data__rental__location__state,
    gliv.extended_data:"rental":"equipment_assignments" AS extended_data__rental__equipment_assignments,
    gliv.extended_data:"rental":"location":"street_2" AS extended_data__rental__location__street_2,
    gliv.extended_data:"rental":"price_per_day" AS extended_data__rental__price_per_day,
    gliv.extended_data:"rental":"rental_bill_type" AS extended_data__rental__rental_bill_type,
    gliv.extended_data:"delivery" AS extended_data__delivery,
    gliv.extended_data:"delivery":"asset_id" AS extended_data__delivery__asset_id,
    gliv.extended_data:"rental":"location":"zip_code" AS extended_data__rental__location__zip_code,
    gliv.extended_data:"rental":"price_per_hour" AS extended_data__rental__price_per_hour,
    gliv.extended_data:"part_number" AS extended_data__part_number,
    gliv.extended_data:"rental":"equipment_class_name" AS extended_data__rental__equipment_class_name,
    gliv.extended_data:"rental":"location":"city" AS extended_data__rental__location__city,
    gliv.extended_data:"delivery":"scheduled_date" AS extended_data__delivery__scheduled_date,
    gliv.extended_data:"rental":"price_per_week" AS extended_data__rental__price_per_week,
    gliv.extended_data:"rental":"rental_id" AS extended_data__rental__rental_id,
    gliv.extended_data:"rental":"cheapest_period_month_count" AS extended_data__rental__cheapest_period_month_count,
    gliv.extended_data:"rental":"end_date" AS extended_data__rental__end_date,
    gliv.extended_data:"rental":"start_date" AS extended_data__rental__start_date,
    gliv.extended_data:"delivery":"delivery_id" AS extended_data__delivery__delivery_id,
    gliv.extended_data:"rental":"cheapest_period_hour_count" AS extended_data__rental__cheapest_period_hour_count,
    gliv.extended_data:"delivery":"rental_id" AS extended_data__delivery__rental_id,
    gliv.extended_data:"rental":"cheapest_period_day_count" AS extended_data__rental__cheapest_period_day_count,
    gliv.extended_data:"rental":"location":"nickname" AS extended_data__rental__location__nickname,
    gliv.extended_data:"part_id" AS extended_data__part_id,
    gliv.payload:"damage_waiver" AS payload__damage_waiver,
    gliv.payload:"edr_message" AS payload__edr_message,
    gliv.payload:"rental" AS payload__rental,
    gliv.payload:"rental":"billable_days" AS payload__rental__billable_days,
    gliv.payload:"rental":"cycle_billing_date" AS payload__rental__cycle_billing_date,
    gliv.payload:"rental":"total_week_days" AS payload__rental__total_week_days,
    gliv.payload:"price" AS payload__price,
    gliv.payload:"settings":"cleaning_hourly_rate" AS payload__settings__cleaning_hourly_rate,
    gliv.payload:"settings":"default_tax" AS payload__settings__default_tax,
    gliv.payload:"settings":"invoice_start_number" AS payload__settings__invoice_start_number,
    gliv.payload:"asset_class_id" AS payload__asset_class_id,
    gliv.payload:"rental":"billing_week_days" AS payload__rental__billing_week_days,
    gliv.payload:"rental":"billed_from_date" AS payload__rental__billed_from_date,
    gliv.payload:"start_date" AS payload__start_date,
    gliv.payload:"transport_id" AS payload__transport_id,
    gliv.payload:"settings":"net_terms" AS payload__settings__net_terms,
    gliv.payload:"asset_class" AS payload__asset_class,
    gliv.payload:"rate_day" AS payload__rate_day,
    gliv.payload:"rental":"asset_class" AS payload__rental__asset_class,
    gliv.payload:"rental":"asset_name" AS payload__rental__asset_name,
    gliv.payload:"rental":"cycle_billing_day" AS payload__rental__cycle_billing_day,
    gliv.payload:"rental":"timezone" AS payload__rental__timezone,
    gliv.payload:"facilitator_type" AS payload__facilitator_type,
    gliv.payload:"cleaning_id" AS payload__cleaning_id,
    gliv.payload:"lost_key_id" AS payload__lost_key_id,
    gliv.payload:"rate_month" AS payload__rate_month,
    gliv.payload:"rate_week" AS payload__rate_week,
    gliv.payload:"end_date" AS payload__end_date,
    gliv.payload:"rental":"asset_id" AS payload__rental__asset_id,
    gliv.payload:"refueling_id" AS payload__refueling_id,
    gliv.payload:"settings":"currency_symbol" AS payload__settings__currency_symbol,
    gliv.payload:"damage_waiver_percentage" AS payload__damage_waiver_percentage,
    gliv.payload:"order_id" AS payload__order_id,
    gliv.payload:"rental":"cycle_billing_period" AS payload__rental__cycle_billing_period,
    gliv.payload:"status" AS payload__status,
    gliv.payload:"asset_id" AS payload__asset_id,
    gliv.payload:"settings":"credit_limit" AS payload__settings__credit_limit,
    gliv.payload:"settings":"key_replacement_charge" AS payload__settings__key_replacement_charge,
    gliv.payload:"settings":"tax_name" AS payload__settings__tax_name,
    gliv.payload:"hours_spent" AS payload__hours_spent,
    gliv.payload:"rental":"cycle_bill_date" AS payload__rental__cycle_bill_date,
    gliv.payload:"id" AS payload__id,
    gliv.payload:"rate_hourly" AS payload__rate_hourly,
    gliv.payload:"rental":"jobsite" AS payload__rental__jobsite,
    gliv.payload:"rental_id" AS payload__rental_id,
    gliv.payload:"rental":"total_days" AS payload__rental__total_days,
    gliv.payload:"transport_type" AS payload__transport_type,
    gliv.payload:"settings":"cycle_billing_period" AS payload__settings__cycle_billing_period,
    gliv.payload:"settings":"fuel_cost" AS payload__settings__fuel_cost,
    gliv.payload:"rental":"start_date" AS payload__rental__start_date,
    gliv.payload:"rental":"end_date" AS payload__rental__end_date,
    gliv.payload:"amount" AS payload__amount,
    gliv.payload:"settings" AS payload__settings,
    gliv.payload:"settings":"fuel_unit" AS payload__settings__fuel_unit,
    gliv.payload:"settings":"net_terms_period" AS payload__settings__net_terms_period,
    gliv.payload:"settings":"tax_id" AS payload__settings__tax_id,
    gliv.payload:"rental":"billed_to_date" AS payload__rental__billed_to_date,
    gliv.payload:"rental":"rpp_percentage_as_decimal" AS payload__rental__rpp_percentage_as_decimal,
    gliv.payload:"total" AS payload__total,
    gliv.payload:"damage_noticed_id" AS payload__damage_noticed_id
FROM {{ source('es_warehouse_public', 'global_line_items_v1') }} as gliv
