select
    current_date() as as_of_date,
    current_timestamp() as collected_at,
    s.dbt_scd_id,
    s.id,
    s.reservation_id,
    s.confirm_insurance,
    s.confirm_license,
    s.phone,
    s.vehicle_vin,
    s.email,
    s.customer_first_name,
    s.return_at,
    s.pickup_at,
    s.pickup_location,
    s.return_location,
    s.pickup_timezone,
    s.return_timezone,
    s.status,
    s.vehicle_model,
    s.customer_last_name,
    s.prefixed_id,
    s.pickup_location_id,
    s.return_location_id,
    s.vehicle_class,
    s.payment_balance,
    s.security_balance,
    s.platform,
    s.platform_id,
    s.notes,
    s.region_id,
    s.region_name,
    s.created_at,
    s.billing_complete,
    s.pickup_photos,
    s.return_photos,
    s.return_user_id,
    s.pickup_user_id,
    s.upload_return_photos,
    s.upload_pickup_photos,
    s.damage_waiver,
    s.charging_balance,
    s.charging_method,
    s.late,
    s.extended,
    s.returned_at,
    s.picked_up_at,
    s.updated_at,
    s.return_schedule_priority,
    s.pickup_schedule_priority,
    s.collections_status,
    s.gclid,
    s.tesla_rents_id,
    s.is_expired,
    s._fivetran_deleted,
    s._fivetran_synced,
    s.created_by_service,
    s.dbt_updated_at,
    s.dbt_snapshot_date,
    s.dbt_valid_from,
    s.dbt_valid_to,
    s.pickup_at_local_tz,
    s.pick_up_date,
from {{ ref('int_vsg_reservations_snapshot_enriched') }} s
where 1 = 1
    and s.dbt_valid_to is null
    and s.status = 'On Rent'
