select
    djrh.dds_job_number,
    djrh.object,
    djrh.job_type,
    djrh.run_by,
    djrh.queue_time,
    djrh.start_time,
    djrh.end_time,
    djrh.record_created,
    djrh.record_updated,
    djrh.record_deleted,
    djrh.status,
    djrh.error,
    djrh.file_list,
    array_size(split(djrh.file_list, ',')) as file_count,
    djrh.params,
    djrh.filters,
    djrh.level,
    djrh.fields,
    djrh.dds_job_name,
    djrh.subscription_key,
    djrh.dds_history_key,
    djrh._es_update_timestamp,
    djrh.params:"file_configuration" as params__file_configuration,
    djrh.params:"file_configuration":"delimiter" as params__file_configuration__delimiter,
    djrh.params:"file_configuration":"file_format" as params__file_configuration__file_format,
    djrh.params:"file_configuration":"include_headers" as params__file_configuration__include_headers,
    djrh.params:"file_configuration":"compress" as params__file_configuration__compress,
    djrh.params:"file_configuration":"enclosure" as params__file_configuration__enclosure,
    djrh.params:"cloud_delivery" as params__cloud_delivery,
    djrh.params:"job_type" as params__job_type,
    djrh.params:"file_configuration":"split_size" as params__file_configuration__split_size,
    djrh.params:"objects" as params__objects,
    djrh.params:"synchronized" as params__synchronized
from {{ source('analytics_intacct__etl', 'dds_job_run_history') }} as djrh
