view: vw_business_glossary_term {

  sql_table_name: NON_PROD_ES_METADATA.DATA_DICTIONARY.VW_BUSINESS_GLOSSARY_TERM ;;
  #

  dimension: BUSINESS_GLOSSARY_TERM_ID {
     type: number
     sql: ${TABLE}.BUSINESS_GLOSSARY_TERM_ID ;;
  }

  dimension: BUSINESS_GLOSSARY_TERM_CAPTION_TEXT {
     type: string
     sql: ${TABLE}.BUSINESS_GLOSSARY_TERM_CAPTION_TEXT ;;
  }

  dimension: BUSINESS_GLOSSARY_TERM_NAME {
     type: string
     sql: ${TABLE}.BUSINESS_GLOSSARY_TERM_NAME ;;
  }

  dimension: BUSINESS_GLOSSARY_TERM_ABBREVIATION_TEXT {
     type: string
     sql: ${TABLE}.BUSINESS_GLOSSARY_TERM_ABBREVIATION_TEXT ;;
  }

  dimension: BUSINESS_GLOSSARY_TERM_INITILISM_INDICATOR {
     type: string
     sql: ${TABLE}.BUSINESS_GLOSSARY_TERM_INITILISM_INDICATOR ;;
  }

  dimension: BUSINESS_GLOSSARY_TERM_ACRONYM_INDICATOR {
     type: string
     sql: ${TABLE}.BUSINESS_GLOSSARY_TERM_ACRONYM_INDICATOR ;;
  }

  dimension: BUSINESS_GLOSSARY_TERM_COLUMN_USE_INDICATOR {
     type: string
     sql: ${TABLE}.BUSINESS_GLOSSARY_TERM_COLUMN_USE_INDICATOR ;;
  }

  dimension: BUSINESS_GLOSSARY_TERM_DEFINITION_TEXT {
     type: string
     sql: ${TABLE}.BUSINESS_GLOSSARY_TERM_DEFINITION_TEXT ;;
  }

}

view: VW_BUSINESS_GLOSSARY_TERM_REFERENCE {

  sql_table_name: NON_PROD_ES_METADATA.DATA_DICTIONARY.VW_BUSINESS_GLOSSARY_TERM_REFERENCE ;;

  dimension: BUSINESS_GLOSSARY_TERM_REFERENCE_ID {
     type: number
     sql: ${TABLE}.BUSINESS_GLOSSARY_TERM_REFERENCE_ID ;;
  }

  dimension: BUSINESS_GLOSSARY_TERM_ID {
     type: number
     sql: ${TABLE}.BUSINESS_GLOSSARY_TERM_ID ;;
  }

  dimension: BUSINESS_GLOSSARY_TERM_REFERENCE_TYPE_NAME {
     type: string
     sql: ${TABLE}.BUSINESS_GLOSSARY_TERM_REFERENCE_TYPE_NAME ;;
  }

  dimension: BUSINESS_GLOSSARY_TERM_REFERENCE_TYPE_DATA_TYPE_NAME {
     type: string
     sql: ${TABLE}.BUSINESS_GLOSSARY_TERM_REFERENCE_TYPE_DATA_TYPE_NAME ;;
  }

  dimension: BUSINESS_GLOSSARY_TERM_REFERENCE_HTML_TEXT {
     type: string
     sql: ${TABLE}.BUSINESS_GLOSSARY_TERM_REFERENCE_HTML_TEXT ;;
  }

  dimension: BUSINESS_GLOSSARY_TERM_REFERENCE_GLOSSARY_TERM_ID {
     type: number
     sql: ${TABLE}.BUSINESS_GLOSSARY_TERM_REFERENCE_GLOSSARY_TERM_ID ;;
  }

  dimension: BUSINESS_GLOSSARY_TERM_CAPTION_TEXT {
     type: string
     sql: ${TABLE}.BUSINESS_GLOSSARY_TERM_CAPTION_TEXT ;;
  }

  dimension: BUSINESS_GLOSSARY_TERM_REFERENCE_URL_TEXT {
     type: string
     sql: ${TABLE}.BUSINESS_GLOSSARY_TERM_REFERENCE_URL_TEXT ;;
  }

  dimension: BUSINESS_GLOSSARY_TERM_REFERENCE_TEXT {
     type: string
     sql: ${TABLE}.BUSINESS_GLOSSARY_TERM_REFERENCE_TEXT ;;
  }

}
