SELECT
    poel._es_load_timestamp,
    poel.event_log_id,
    poel.purchase_order_id,
    poel.created_by_id,
    poel.changes,
    poel.event_type,
    poel.date_created,
    poel._es_update_timestamp,
    poel.changes:"receiver_id" AS changes__receiver_id,
    poel.changes:"fieldsChanged":"vendorSnapshotId" AS changes__fieldschanged__vendorsnapshotid,
    poel.changes:"fieldsChanged":"vendorSnapshotId":"after" AS changes__fieldschanged__vendorsnapshotid__after,
    poel.changes:"fieldsChanged":"promiseDate" AS changes__fieldschanged__promisedate,
    poel.changes:"fieldsChanged":"costCenterSnapshotId":"after" AS changes__fieldschanged__costcentersnapshotid__after,
    poel.changes:"amountApproved" AS changes__amountapproved,
    poel.changes:"editedLineItems" AS changes__editedlineitems,
    poel.changes:"fieldsChanged":"promiseDate":"before" AS changes__fieldschanged__promisedate__before,
    poel.changes:"fieldsChanged":"costCenterSnapshotId" AS changes__fieldschanged__costcentersnapshotid,
    poel.changes:"fieldsChanged":"costCenterSnapshotId":"before" AS changes__fieldschanged__costcentersnapshotid__before,
    poel.changes:"fieldsChanged":"promiseDate":"after" AS changes__fieldschanged__promisedate__after,
    poel.changes:"fieldsChanged":"deliverToSnapshotId":"after" AS changes__fieldschanged__delivertosnapshotid__after,
    poel.changes:"fieldsChanged":"deliverToSnapshotId":"before" AS changes__fieldschanged__delivertosnapshotid__before,
    poel.changes:"fieldsChanged":"reference":"after" AS changes__fieldschanged__reference__after,
    poel.changes:"fieldsChanged":"storeId" AS changes__fieldschanged__storeid,
    poel.changes:"adjustments" AS changes__adjustments,
    poel.changes:"addedLineItems" AS changes__addedlineitems,
    poel.changes:"fieldsChanged":"vendorSnapshotId":"before" AS changes__fieldschanged__vendorsnapshotid__before,
    poel.changes:"removedLineItems" AS changes__removedlineitems,
    poel.changes:"fieldsChanged":"reference":"before" AS changes__fieldschanged__reference__before,
    poel.changes:"fieldsChanged":"storeId":"after" AS changes__fieldschanged__storeid__after,
    poel.changes:"amountApproved":"currencyCode" AS changes__amountapproved__currencycode,
    poel.changes:"fieldsChanged" AS changes__fieldschanged,
    poel.changes:"fieldsChanged":"deliverToSnapshotId" AS changes__fieldschanged__delivertosnapshotid,
    poel.changes:"amountApproved":"amount" AS changes__amountapproved__amount,
    poel.changes:"fieldsChanged":"reference" AS changes__fieldschanged__reference,
    poel.changes:"fieldsChanged":"storeId":"before" AS changes__fieldschanged__storeid__before
FROM {{ source('procurement_public', 'purchase_order_event_logs') }} as poel
