view: vendor_reimbursements {
  derived_table: {
    sql:
-- INVOICE QUERY
WITH EXCLUDE_CTE AS (
SELECT DISTINCT SERIAL
FROM ANALYTICS.REIMBURSEMENTS.EXCLUDED_SERIALS
WHERE SERIAL IS NOT NULL
)
-- ALL MODELS
SELECT PO.VENDOR_ID,
C1.NAME AS VENDOR_NAME,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID) AS ORDER_NUMBER_GROUPED,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID,'-',POL.COMPANY_PURCHASE_ORDER_LINE_ITEM_NUMBER) AS ORDER_NUMBER,
POL.INVOICE_NUMBER,
POL.INVOICE_DATE,
POL.RELEASE_DATE,
POL.ASSET_ID,
COALESCE(POL.SERIAL,POL.VIN) AS SERIAL_VIN,
POL.ORDER_STATUS,
POL.FINANCE_STATUS,
EMA.NAME AS EQUIPMENT_MAKE,
EMO.NAME AS EQUIPMENT_MODEL,
POL.YEAR AS MODEL_YEAR,
POL.FACTORY_BUILD_SPECIFICATIONS,
AA.COMPANY_ID AS OWNER_ID,
C2.NAME AS OWNER_NAME,
POL.NET_PRICE,
POL.FREIGHT_COST,
POL.SALES_TAX,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.SALES_TAX,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS TOTAL_OEC,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS OEC_LESS_TAX,
PO.APPROVED_AT AS PO_APPROVED_DATE,
POL.NOTE,
V.RULE_ID,
V.RULE_YEAR,
R.RULE,
R.REIMBURSEMENT_RATE,
CASE
WHEN (V.RULE_ID = 1) AND (POL.FINANCE_STATUS NOT IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms') OR POL.FINANCE_STATUS IS NULL) THEN POL.NET_PRICE-(POL.NET_PRICE/1.05)
WHEN (V.RULE_ID = 13) AND (POL.FINANCE_STATUS NOT IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms') AND (ORDER_NUMBER_GROUPED <> 'BPO122241') OR POL.FINANCE_STATUS IS NULL) THEN POL.NET_PRICE-(POL.NET_PRICE/1.05)
WHEN (V.RULE_ID IN (2,3,4,5)) AND (POL.FINANCE_STATUS NOT IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms') OR POL.FINANCE_STATUS IS NULL) THEN R.REIMBURSEMENT_RATE * POL.NET_PRICE
WHEN (V.RULE_ID = 14) AND (POL.FINANCE_STATUS NOT IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms') AND (ORDER_NUMBER_GROUPED NOT IN ('SPO124008','SPO124009','SPO124010','SPO124011','SPO124012')) OR POL.FINANCE_STATUS IS NULL) THEN R.REIMBURSEMENT_RATE * POL.NET_PRICE
WHEN (V.RULE_ID = 22) AND (POL.FINANCE_STATUS NOT IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms') AND (ORDER_NUMBER_GROUPED NOT IN ('SPO124454')) OR POL.FINANCE_STATUS IS NULL) THEN R.REIMBURSEMENT_RATE * POL.NET_PRICE
WHEN (V.RULE_ID = 23) AND (POL.FINANCE_STATUS NOT IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms') AND (ORDER_NUMBER_GROUPED NOT IN ('SPO122563','SPO124540','SPO124687')) OR POL.FINANCE_STATUS IS NULL) THEN R.REIMBURSEMENT_RATE * POL.NET_PRICE
WHEN (V.RULE_ID IN (6,7)) AND (POL.FINANCE_STATUS NOT IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms') OR POL.FINANCE_STATUS IS NULL) THEN R.REIMBURSEMENT_RATE * TOTAL_OEC
WHEN (V.RULE_ID IN (8,9,29)) AND (POL.FINANCE_STATUS NOT IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms') OR POL.FINANCE_STATUS IS NULL) THEN R.REIMBURSEMENT_RATE * OEC_LESS_TAX
ELSE 0.00 END AS REIMBURSEMENT_AMOUNT
FROM ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_LINE_ITEMS AS POL
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDERS AS PO ON POL.COMPANY_PURCHASE_ORDER_ID = PO.COMPANY_PURCHASE_ORDER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_TYPES AS CPT ON PO.COMPANY_PURCHASE_ORDER_TYPE_ID = CPT.COMPANY_PURCHASE_ORDER_TYPE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C1 ON PO.VENDOR_ID = C1.COMPANY_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS_AGGREGATE AS AA ON POL.ASSET_ID = AA.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MODELS AS EMO ON POL.EQUIPMENT_MODEL_ID = EMO.EQUIPMENT_MODEL_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MAKES AS EMA ON EMO.EQUIPMENT_MAKE_ID = EMA.EQUIPMENT_MAKE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C2 ON AA.COMPANY_ID = C2.COMPANY_ID
INNER JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES AS V ON (PO.VENDOR_ID = V.VENDOR_ID) AND (V.RULE_YEAR = YEAR(POL.INVOICE_DATE))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES_RATES AS R ON V.RULE_ID = R.RULE_ID
WHERE C1.SUPPLY_VENDOR = TRUE
AND POL.DELETED_AT IS NULL
AND POL.INVOICE_DATE >= '2026-01-01' AND POL.INVOICE_DATE < '2026-04-01'
AND (COALESCE(POL.SERIAL, POL.VIN) NOT IN (SELECT DISTINCT SERIAL FROM EXCLUDE_CTE) OR COALESCE(POL.SERIAL, POL.VIN) IS NULL)
AND ORDER_NUMBER NOT IN ('SPO119483-2','SPO123276-2','SPO135767-1')
AND ORDER_NUMBER_GROUPED NOT IN ('BPO122241',
'SPO135927',
'SPO135928',
'SPO135929',
'SPO135930',
'SPO135931',
'SPO135932',
'SPO135933',
'SPO135934',
'SPO135935',
'SPO135936',
'SPO135944',
'SPO135937',
'SPO135945',
'SPO135938',
'SPO135939',
'SPO135940',
'SPO135941',
'SPO135946',
'SPO135947',
'SPO135948',
'SPO135949',
'SPO135942',
'SPO135943'
)
AND ((POL.NOTE NOT LIKE '%CPE%' AND POL.NOTE NOT LIKE '%IES%' AND POL.NOTE NOT LIKE '%VLP%') OR POL.NOTE IS NULL)
AND V.BASIS_TYPE <> 'Model Specific'
UNION ALL
-- MODEL SPECIFIC - MODEL
SELECT PO.VENDOR_ID,
C1.NAME AS VENDOR_NAME,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID) AS ORDER_NUMBER_GROUPED,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID,'-',POL.COMPANY_PURCHASE_ORDER_LINE_ITEM_NUMBER) AS ORDER_NUMBER,
POL.INVOICE_NUMBER,
POL.INVOICE_DATE,
POL.RELEASE_DATE,
POL.ASSET_ID,
COALESCE(POL.SERIAL,POL.VIN) AS SERIAL_VIN,
POL.ORDER_STATUS,
POL.FINANCE_STATUS,
EMA.NAME AS EQUIPMENT_MAKE,
EMO.NAME AS EQUIPMENT_MODEL,
POL.YEAR AS MODEL_YEAR,
POL.FACTORY_BUILD_SPECIFICATIONS,
AA.COMPANY_ID AS OWNER_ID,
C2.NAME AS OWNER_NAME,
POL.NET_PRICE,
POL.FREIGHT_COST,
POL.SALES_TAX,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.SALES_TAX,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS TOTAL_OEC,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS OEC_LESS_TAX,
PO.APPROVED_AT AS PO_APPROVED_DATE,
POL.NOTE,
V.RULE_ID,
V.RULE_YEAR,
R.RULE,
R.REIMBURSEMENT_RATE,
CASE WHEN POL.FINANCE_STATUS IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms')  THEN 0.00
WHEN (POL.FINANCE_STATUS NOT IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms') OR POL.FINANCE_STATUS IS NULL) THEN IFNULL(MS.REBATE_AMOUNT,0)  ELSE 0.00 END AS REIMBURSEMENT_AMOUNT
FROM ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_LINE_ITEMS AS POL
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDERS AS PO ON POL.COMPANY_PURCHASE_ORDER_ID = PO.COMPANY_PURCHASE_ORDER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_TYPES AS CPT ON PO.COMPANY_PURCHASE_ORDER_TYPE_ID = CPT.COMPANY_PURCHASE_ORDER_TYPE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C1 ON PO.VENDOR_ID = C1.COMPANY_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS_AGGREGATE AS AA ON POL.ASSET_ID = AA.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MODELS AS EMO ON POL.EQUIPMENT_MODEL_ID = EMO.EQUIPMENT_MODEL_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MAKES AS EMA ON EMO.EQUIPMENT_MAKE_ID = EMA.EQUIPMENT_MAKE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C2 ON AA.COMPANY_ID = C2.COMPANY_ID
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES AS V ON (PO.VENDOR_ID = V.VENDOR_ID) AND (V.RULE_YEAR = YEAR(POL.INVOICE_DATE))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.MANUFACTURE_SPECIFIC AS MS ON (LOWER(EMA.NAME) = LOWER(MS.MAKE)) AND (LOWER(EMO.NAME) = LOWER(MS.MODEL))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES_RATES AS R ON MS.RULE_ID = R.RULE_ID
WHERE C1.SUPPLY_VENDOR = TRUE
AND (EMO.NAME NOT ILIKE '%bucket%' OR EMO.NAME IS NULL)
AND POL.DELETED_AT IS NULL
AND POL.INVOICE_DATE >= '2026-01-01' AND POL.INVOICE_DATE < '2026-04-01'
AND POL.INVOICE_DATE::DATE >= MS.EFFECTIVE_DATE::DATE
AND (COALESCE(POL.SERIAL, POL.VIN) NOT IN (SELECT DISTINCT SERIAL FROM EXCLUDE_CTE) OR COALESCE(POL.SERIAL, POL.VIN) IS NULL)
AND MS.RULE_ID = 12
AND MS.TYPE = 'Model'
AND ((POL.NOTE NOT LIKE '%CPE%' AND POL.NOTE NOT LIKE '%IES%' AND POL.NOTE NOT LIKE '%VLP%') OR POL.NOTE IS NULL)
UNION ALL
-- MODEL SPECIFIC - FACTORY BUILD SPEC
SELECT PO.VENDOR_ID,
C1.NAME AS VENDOR_NAME,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID) AS ORDER_NUMBER_GROUPED,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID,'-',POL.COMPANY_PURCHASE_ORDER_LINE_ITEM_NUMBER) AS ORDER_NUMBER,
POL.INVOICE_NUMBER,
POL.INVOICE_DATE,
POL.RELEASE_DATE,
POL.ASSET_ID,
COALESCE(POL.SERIAL,POL.VIN) AS SERIAL_VIN,
POL.ORDER_STATUS,
POL.FINANCE_STATUS,
EMA.NAME AS EQUIPMENT_MAKE,
EMO.NAME AS EQUIPMENT_MODEL,
POL.YEAR AS MODEL_YEAR,
POL.FACTORY_BUILD_SPECIFICATIONS,
AA.COMPANY_ID AS OWNER_ID,
C2.NAME AS OWNER_NAME,
POL.NET_PRICE,
POL.FREIGHT_COST,
POL.SALES_TAX,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.SALES_TAX,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS TOTAL_OEC,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS OEC_LESS_TAX,
PO.APPROVED_AT AS PO_APPROVED_DATE,
POL.NOTE,
V.RULE_ID,
V.RULE_YEAR,
R.RULE,
R.REIMBURSEMENT_RATE,
CASE WHEN POL.FINANCE_STATUS  IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms')  THEN 0.00
WHEN (POL.FINANCE_STATUS NOT IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms') OR POL.FINANCE_STATUS IS NULL) THEN IFNULL(MS.REBATE_AMOUNT,0) ELSE 0.00 END AS REIMBURSEMENT_AMOUNT
FROM ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_LINE_ITEMS AS POL
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDERS AS PO ON POL.COMPANY_PURCHASE_ORDER_ID = PO.COMPANY_PURCHASE_ORDER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_TYPES AS CPT ON PO.COMPANY_PURCHASE_ORDER_TYPE_ID = CPT.COMPANY_PURCHASE_ORDER_TYPE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C1 ON PO.VENDOR_ID = C1.COMPANY_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS_AGGREGATE AS AA ON POL.ASSET_ID = AA.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MODELS AS EMO ON POL.EQUIPMENT_MODEL_ID = EMO.EQUIPMENT_MODEL_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MAKES AS EMA ON EMO.EQUIPMENT_MAKE_ID = EMA.EQUIPMENT_MAKE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C2 ON AA.COMPANY_ID = C2.COMPANY_ID
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES AS V ON (PO.VENDOR_ID = V.VENDOR_ID) AND (V.RULE_YEAR = YEAR(POL.INVOICE_DATE))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.MANUFACTURE_SPECIFIC AS MS
ON (LOWER(EMA.NAME) = LOWER(MS.MAKE)) AND (LOWER(EMO.NAME) = LOWER(MS.MODEL)) AND (LOWER(POL.FACTORY_BUILD_SPECIFICATIONS) = LOWER(MS.FACTORY_BUILD_SPEC))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES_RATES AS R ON MS.RULE_ID = R.RULE_ID
WHERE C1.SUPPLY_VENDOR = TRUE
AND (EMO.NAME NOT ILIKE '%bucket%' OR EMO.NAME IS NULL)
AND POL.DELETED_AT IS NULL
AND POL.INVOICE_DATE >= '2026-01-01' AND POL.INVOICE_DATE < '2026-04-01'
AND POL.INVOICE_DATE::DATE >= MS.EFFECTIVE_DATE::DATE
AND (COALESCE(POL.SERIAL, POL.VIN) NOT IN (SELECT DISTINCT SERIAL FROM EXCLUDE_CTE) OR COALESCE(POL.SERIAL, POL.VIN) IS NULL)
AND MS.RULE_ID = 11
AND MS.TYPE = 'Factory Build Spec'
AND ((POL.NOTE NOT LIKE '%CPE%' AND POL.NOTE NOT LIKE '%IES%' AND POL.NOTE NOT LIKE '%VLP%') OR POL.NOTE IS NULL)
UNION ALL
-- MODEL SPECIFIC - PO
SELECT PO.VENDOR_ID,
C1.NAME AS VENDOR_NAME,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID) AS ORDER_NUMBER_GROUPED,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID,'-',POL.COMPANY_PURCHASE_ORDER_LINE_ITEM_NUMBER) AS ORDER_NUMBER,
POL.INVOICE_NUMBER,
POL.INVOICE_DATE,
POL.RELEASE_DATE,
POL.ASSET_ID,
COALESCE(POL.SERIAL,POL.VIN) AS SERIAL_VIN,
POL.ORDER_STATUS,
POL.FINANCE_STATUS,
EMA.NAME AS EQUIPMENT_MAKE,
EMO.NAME AS EQUIPMENT_MODEL,
POL.YEAR AS MODEL_YEAR,
POL.FACTORY_BUILD_SPECIFICATIONS,
AA.COMPANY_ID AS OWNER_ID,
C2.NAME AS OWNER_NAME,
POL.NET_PRICE,
POL.FREIGHT_COST,
POL.SALES_TAX,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.SALES_TAX,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS TOTAL_OEC,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS OEC_LESS_TAX,
PO.APPROVED_AT AS PO_APPROVED_DATE,
POL.NOTE,
V.RULE_ID,
V.RULE_YEAR,
R.RULE,
R.REIMBURSEMENT_RATE,
CASE WHEN POL.FINANCE_STATUS  IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms')  THEN 0.00
WHEN (V.RULE_ID NOT IN (24)) AND (POL.FINANCE_STATUS NOT IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms') OR POL.FINANCE_STATUS IS NULL) THEN IFNULL(MS.REBATE_AMOUNT,0)
ELSE 0.00 END AS REIMBURSEMENT_AMOUNT
FROM ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_LINE_ITEMS AS POL
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDERS AS PO ON POL.COMPANY_PURCHASE_ORDER_ID = PO.COMPANY_PURCHASE_ORDER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_TYPES AS CPT ON PO.COMPANY_PURCHASE_ORDER_TYPE_ID = CPT.COMPANY_PURCHASE_ORDER_TYPE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C1 ON PO.VENDOR_ID = C1.COMPANY_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS_AGGREGATE AS AA ON POL.ASSET_ID = AA.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MODELS AS EMO ON POL.EQUIPMENT_MODEL_ID = EMO.EQUIPMENT_MODEL_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MAKES AS EMA ON EMO.EQUIPMENT_MAKE_ID = EMA.EQUIPMENT_MAKE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C2 ON AA.COMPANY_ID = C2.COMPANY_ID
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES AS V ON (PO.VENDOR_ID = V.VENDOR_ID) AND (V.RULE_YEAR = YEAR(POL.INVOICE_DATE))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.MANUFACTURE_SPECIFIC AS MS ON (ORDER_NUMBER_GROUPED = MS.PO_NUMBER)
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES_RATES AS R ON MS.RULE_ID = R.RULE_ID
WHERE C1.SUPPLY_VENDOR = TRUE
AND (EMO.NAME NOT ILIKE '%bucket%' OR EMO.NAME IS NULL)
AND POL.DELETED_AT IS NULL
AND POL.INVOICE_DATE >= '2026-01-01' AND POL.INVOICE_DATE < '2026-04-01'
AND POL.INVOICE_DATE::DATE >= MS.EFFECTIVE_DATE::DATE
AND (COALESCE(POL.SERIAL, POL.VIN) NOT IN (SELECT DISTINCT SERIAL FROM EXCLUDE_CTE) OR COALESCE(POL.SERIAL, POL.VIN) IS NULL)
AND MS.RULE_ID = 10
AND MS.TYPE = 'PO'
AND ((POL.NOTE NOT LIKE '%CPE%' AND POL.NOTE NOT LIKE '%IES%' AND POL.NOTE NOT LIKE '%VLP%') OR POL.NOTE IS NULL)
UNION ALL
-- Illinois Tool Works - PO - 5% Total OEC, less Tax
SELECT PO.VENDOR_ID,
C1.NAME AS VENDOR_NAME,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID) AS ORDER_NUMBER_GROUPED,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID,'-',POL.COMPANY_PURCHASE_ORDER_LINE_ITEM_NUMBER) AS ORDER_NUMBER,
POL.INVOICE_NUMBER,
POL.INVOICE_DATE,
POL.RELEASE_DATE,
POL.ASSET_ID,
COALESCE(POL.SERIAL,POL.VIN) AS SERIAL_VIN,
POL.ORDER_STATUS,
POL.FINANCE_STATUS,
EMA.NAME AS EQUIPMENT_MAKE,
EMO.NAME AS EQUIPMENT_MODEL,
POL.YEAR AS MODEL_YEAR,
POL.FACTORY_BUILD_SPECIFICATIONS,
AA.COMPANY_ID AS OWNER_ID,
C2.NAME AS OWNER_NAME,
POL.NET_PRICE,
POL.FREIGHT_COST,
POL.SALES_TAX,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.SALES_TAX,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS TOTAL_OEC,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS OEC_LESS_TAX,
PO.APPROVED_AT AS PO_APPROVED_DATE,
POL.NOTE,
V.RULE_ID,
V.RULE_YEAR,
R.RULE,
R.REIMBURSEMENT_RATE,
CASE WHEN POL.FINANCE_STATUS  IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms')  THEN 0.00
WHEN (V.RULE_ID = 24) AND (POL.FINANCE_STATUS NOT IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms') OR POL.FINANCE_STATUS IS NULL) THEN IFNULL(R.REIMBURSEMENT_RATE*OEC_LESS_TAX,0)
ELSE 0.00 END AS REIMBURSEMENT_AMOUNT
FROM ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_LINE_ITEMS AS POL
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDERS AS PO ON POL.COMPANY_PURCHASE_ORDER_ID = PO.COMPANY_PURCHASE_ORDER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_TYPES AS CPT ON PO.COMPANY_PURCHASE_ORDER_TYPE_ID = CPT.COMPANY_PURCHASE_ORDER_TYPE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C1 ON PO.VENDOR_ID = C1.COMPANY_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS_AGGREGATE AS AA ON POL.ASSET_ID = AA.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MODELS AS EMO ON POL.EQUIPMENT_MODEL_ID = EMO.EQUIPMENT_MODEL_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MAKES AS EMA ON EMO.EQUIPMENT_MAKE_ID = EMA.EQUIPMENT_MAKE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C2 ON AA.COMPANY_ID = C2.COMPANY_ID
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES AS V ON (PO.VENDOR_ID = V.VENDOR_ID) AND (V.RULE_YEAR = YEAR(POL.INVOICE_DATE))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.MANUFACTURE_SPECIFIC AS MS ON (ORDER_NUMBER_GROUPED = MS.PO_NUMBER)
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES_RATES AS R ON MS.RULE_ID = R.RULE_ID
WHERE C1.SUPPLY_VENDOR = TRUE
AND (EMO.NAME NOT ILIKE '%bucket%' OR EMO.NAME IS NULL)
AND POL.DELETED_AT IS NULL
AND POL.INVOICE_DATE >= '2026-01-01' AND POL.INVOICE_DATE < '2026-04-01'
AND POL.INVOICE_DATE::DATE >= MS.EFFECTIVE_DATE::DATE
AND (COALESCE(POL.SERIAL, POL.VIN) NOT IN (SELECT DISTINCT SERIAL FROM EXCLUDE_CTE) OR COALESCE(POL.SERIAL, POL.VIN) IS NULL)
AND MS.RULE_ID = 24
AND MS.TYPE = 'PO'
AND ((POL.NOTE NOT LIKE '%CPE%' AND POL.NOTE NOT LIKE '%IES%' AND POL.NOTE NOT LIKE '%VLP%') OR POL.NOTE IS NULL)
UNION ALL
-- TAKEUCHI - FACTORY BUILD SPEC
SELECT PO.VENDOR_ID,
C1.NAME AS VENDOR_NAME,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID) AS ORDER_NUMBER_GROUPED,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID,'-',POL.COMPANY_PURCHASE_ORDER_LINE_ITEM_NUMBER) AS ORDER_NUMBER,
POL.INVOICE_NUMBER,
POL.INVOICE_DATE,
POL.RELEASE_DATE,
POL.ASSET_ID,
COALESCE(POL.SERIAL,POL.VIN) AS SERIAL_VIN,
POL.ORDER_STATUS,
POL.FINANCE_STATUS,
EMA.NAME AS EQUIPMENT_MAKE,
EMO.NAME AS EQUIPMENT_MODEL,
POL.YEAR AS MODEL_YEAR,
POL.FACTORY_BUILD_SPECIFICATIONS,
AA.COMPANY_ID AS OWNER_ID,
C2.NAME AS OWNER_NAME,
POL.NET_PRICE,
POL.FREIGHT_COST,
POL.SALES_TAX,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.SALES_TAX,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS TOTAL_OEC,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS OEC_LESS_TAX,
PO.APPROVED_AT AS PO_APPROVED_DATE,
POL.NOTE,
V.RULE_ID,
V.RULE_YEAR,
R.RULE,
R.REIMBURSEMENT_RATE,
CASE WHEN POL.FINANCE_STATUS  IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms')  THEN 0.00
WHEN (POL.FINANCE_STATUS NOT IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms') OR POL.FINANCE_STATUS IS NULL) THEN IFNULL(MS.REBATE_AMOUNT,0) ELSE 0.00 END AS REIMBURSEMENT_AMOUNT
FROM ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_LINE_ITEMS AS POL
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDERS AS PO ON POL.COMPANY_PURCHASE_ORDER_ID = PO.COMPANY_PURCHASE_ORDER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_TYPES AS CPT ON PO.COMPANY_PURCHASE_ORDER_TYPE_ID = CPT.COMPANY_PURCHASE_ORDER_TYPE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C1 ON PO.VENDOR_ID = C1.COMPANY_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS_AGGREGATE AS AA ON POL.ASSET_ID = AA.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MODELS AS EMO ON POL.EQUIPMENT_MODEL_ID = EMO.EQUIPMENT_MODEL_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MAKES AS EMA ON EMO.EQUIPMENT_MAKE_ID = EMA.EQUIPMENT_MAKE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C2 ON AA.COMPANY_ID = C2.COMPANY_ID
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES AS V ON (PO.VENDOR_ID = V.VENDOR_ID) AND (V.RULE_YEAR = YEAR(POL.INVOICE_DATE))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.MANUFACTURE_SPECIFIC AS MS
ON (LOWER(EMA.NAME) = LOWER(MS.MAKE)) AND (LOWER(EMO.NAME) = LOWER(MS.MODEL)) AND (LOWER(POL.FACTORY_BUILD_SPECIFICATIONS) = LOWER(MS.FACTORY_BUILD_SPEC))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES_RATES AS R ON MS.RULE_ID = R.RULE_ID
WHERE C1.SUPPLY_VENDOR = TRUE
AND (EMO.NAME NOT ILIKE '%bucket%' OR EMO.NAME IS NULL)
AND POL.DELETED_AT IS NULL
AND POL.INVOICE_DATE >= '2026-01-01' AND POL.INVOICE_DATE < '2026-04-01'
AND POL.INVOICE_DATE::DATE >= MS.EFFECTIVE_DATE::DATE
AND (COALESCE(POL.SERIAL, POL.VIN) NOT IN (SELECT DISTINCT SERIAL FROM EXCLUDE_CTE) OR COALESCE(POL.SERIAL, POL.VIN) IS NULL)
AND MS.RULE_ID = 21
AND MS.TYPE = 'Factory Build Spec'
AND ((POL.NOTE NOT LIKE '%CPE%' AND POL.NOTE NOT LIKE '%IES%' AND POL.NOTE NOT LIKE '%VLP%') OR POL.NOTE IS NULL)
UNION ALL
-- TAKEUCHI - MODEL
SELECT PO.VENDOR_ID,
C1.NAME AS VENDOR_NAME,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID) AS ORDER_NUMBER_GROUPED,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID,'-',POL.COMPANY_PURCHASE_ORDER_LINE_ITEM_NUMBER) AS ORDER_NUMBER,
POL.INVOICE_NUMBER,
POL.INVOICE_DATE,
POL.RELEASE_DATE,
POL.ASSET_ID,
COALESCE(POL.SERIAL,POL.VIN) AS SERIAL_VIN,
POL.ORDER_STATUS,
POL.FINANCE_STATUS,
EMA.NAME AS EQUIPMENT_MAKE,
EMO.NAME AS EQUIPMENT_MODEL,
POL.YEAR AS MODEL_YEAR,
POL.FACTORY_BUILD_SPECIFICATIONS,
AA.COMPANY_ID AS OWNER_ID,
C2.NAME AS OWNER_NAME,
POL.NET_PRICE,
POL.FREIGHT_COST,
POL.SALES_TAX,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.SALES_TAX,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS TOTAL_OEC,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS OEC_LESS_TAX,
PO.APPROVED_AT AS PO_APPROVED_DATE,
POL.NOTE,
V.RULE_ID,
V.RULE_YEAR,
R.RULE,
R.REIMBURSEMENT_RATE,
CASE WHEN POL.FINANCE_STATUS IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms')  THEN 0.00
WHEN (POL.FINANCE_STATUS NOT IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms') OR POL.FINANCE_STATUS IS NULL) THEN IFNULL(MS.REBATE_AMOUNT,0)  ELSE 0.00 END AS REIMBURSEMENT_AMOUNT
FROM ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_LINE_ITEMS AS POL
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDERS AS PO ON POL.COMPANY_PURCHASE_ORDER_ID = PO.COMPANY_PURCHASE_ORDER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_TYPES AS CPT ON PO.COMPANY_PURCHASE_ORDER_TYPE_ID = CPT.COMPANY_PURCHASE_ORDER_TYPE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C1 ON PO.VENDOR_ID = C1.COMPANY_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS_AGGREGATE AS AA ON POL.ASSET_ID = AA.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MODELS AS EMO ON POL.EQUIPMENT_MODEL_ID = EMO.EQUIPMENT_MODEL_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MAKES AS EMA ON EMO.EQUIPMENT_MAKE_ID = EMA.EQUIPMENT_MAKE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C2 ON AA.COMPANY_ID = C2.COMPANY_ID
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES AS V ON (PO.VENDOR_ID = V.VENDOR_ID) AND (V.RULE_YEAR = YEAR(POL.INVOICE_DATE))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.MANUFACTURE_SPECIFIC AS MS ON (LOWER(EMA.NAME) = LOWER(MS.MAKE)) AND (LOWER(EMO.NAME) = LOWER(MS.MODEL))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES_RATES AS R ON MS.RULE_ID = R.RULE_ID
WHERE C1.SUPPLY_VENDOR = TRUE
AND (EMO.NAME NOT ILIKE '%bucket%' OR EMO.NAME IS NULL)
AND POL.DELETED_AT IS NULL
AND POL.INVOICE_DATE >= '2026-01-01' AND POL.INVOICE_DATE < '2026-04-01'
AND POL.INVOICE_DATE::DATE >= MS.EFFECTIVE_DATE::DATE
AND (COALESCE(POL.SERIAL, POL.VIN) NOT IN (SELECT DISTINCT SERIAL FROM EXCLUDE_CTE) OR COALESCE(POL.SERIAL, POL.VIN) IS NULL)
AND MS.RULE_ID = 21
AND MS.TYPE = 'Model'
AND ((POL.NOTE NOT LIKE '%CPE%' AND POL.NOTE NOT LIKE '%IES%' AND POL.NOTE NOT LIKE '%VLP%') OR POL.NOTE IS NULL)
UNION ALL
-- HUSQVARNA - MODEL
SELECT PO.VENDOR_ID,
C1.NAME AS VENDOR_NAME,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID) AS ORDER_NUMBER_GROUPED,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID,'-',POL.COMPANY_PURCHASE_ORDER_LINE_ITEM_NUMBER) AS ORDER_NUMBER,
POL.INVOICE_NUMBER,
POL.INVOICE_DATE,
POL.RELEASE_DATE,
POL.ASSET_ID,
COALESCE(POL.SERIAL,POL.VIN) AS SERIAL_VIN,
POL.ORDER_STATUS,
POL.FINANCE_STATUS,
EMA.NAME AS EQUIPMENT_MAKE,
EMO.NAME AS EQUIPMENT_MODEL,
POL.YEAR AS MODEL_YEAR,
POL.FACTORY_BUILD_SPECIFICATIONS,
AA.COMPANY_ID AS OWNER_ID,
C2.NAME AS OWNER_NAME,
POL.NET_PRICE,
POL.FREIGHT_COST,
POL.SALES_TAX,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.SALES_TAX,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS TOTAL_OEC,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS OEC_LESS_TAX,
PO.APPROVED_AT AS PO_APPROVED_DATE,
POL.NOTE,
V.RULE_ID,
V.RULE_YEAR,
R.RULE,
R.REIMBURSEMENT_RATE,
CASE WHEN POL.FINANCE_STATUS IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms')  THEN 0.00
WHEN (POL.FINANCE_STATUS NOT IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms') OR POL.FINANCE_STATUS IS NULL) THEN IFNULL(POL.NET_PRICE*MS.REBATE_AMOUNT,0)  ELSE 0.00 END AS REIMBURSEMENT_AMOUNT
FROM ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_LINE_ITEMS AS POL
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDERS AS PO ON POL.COMPANY_PURCHASE_ORDER_ID = PO.COMPANY_PURCHASE_ORDER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_TYPES AS CPT ON PO.COMPANY_PURCHASE_ORDER_TYPE_ID = CPT.COMPANY_PURCHASE_ORDER_TYPE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C1 ON PO.VENDOR_ID = C1.COMPANY_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS_AGGREGATE AS AA ON POL.ASSET_ID = AA.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MODELS AS EMO ON POL.EQUIPMENT_MODEL_ID = EMO.EQUIPMENT_MODEL_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MAKES AS EMA ON EMO.EQUIPMENT_MAKE_ID = EMA.EQUIPMENT_MAKE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C2 ON AA.COMPANY_ID = C2.COMPANY_ID
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES AS V ON (PO.VENDOR_ID = V.VENDOR_ID) AND (V.RULE_YEAR = YEAR(POL.INVOICE_DATE))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.MANUFACTURE_SPECIFIC AS MS ON (LOWER(EMA.NAME) = LOWER(MS.MAKE)) AND (LOWER(EMO.NAME) = LOWER(MS.MODEL))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES_RATES AS R ON MS.RULE_ID = R.RULE_ID
WHERE C1.SUPPLY_VENDOR = TRUE
AND (EMO.NAME NOT ILIKE '%bucket%' OR EMO.NAME IS NULL)
AND POL.DELETED_AT IS NULL
AND POL.INVOICE_DATE >= '2026-01-01' AND POL.INVOICE_DATE < '2026-04-01'
AND POL.INVOICE_DATE::DATE >= MS.EFFECTIVE_DATE::DATE
AND (COALESCE(POL.SERIAL, POL.VIN) NOT IN (SELECT DISTINCT SERIAL FROM EXCLUDE_CTE) OR COALESCE(POL.SERIAL, POL.VIN) IS NULL)
AND MS.RULE_ID = 18
AND MS.TYPE = 'Model'
AND ((POL.NOTE NOT LIKE '%CPE%' AND POL.NOTE NOT LIKE '%IES%' AND POL.NOTE NOT LIKE '%VLP%') OR POL.NOTE IS NULL)
UNION ALL
-- CURRY SUPPLY - PO
SELECT PO.VENDOR_ID,
C1.NAME AS VENDOR_NAME,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID) AS ORDER_NUMBER_GROUPED,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID,'-',POL.COMPANY_PURCHASE_ORDER_LINE_ITEM_NUMBER) AS ORDER_NUMBER,
POL.INVOICE_NUMBER,
POL.INVOICE_DATE,
POL.RELEASE_DATE,
POL.ASSET_ID,
COALESCE(POL.SERIAL,POL.VIN) AS SERIAL_VIN,
POL.ORDER_STATUS,
POL.FINANCE_STATUS,
EMA.NAME AS EQUIPMENT_MAKE,
EMO.NAME AS EQUIPMENT_MODEL,
POL.YEAR AS MODEL_YEAR,
POL.FACTORY_BUILD_SPECIFICATIONS,
AA.COMPANY_ID AS OWNER_ID,
C2.NAME AS OWNER_NAME,
POL.NET_PRICE,
POL.FREIGHT_COST,
POL.SALES_TAX,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.SALES_TAX,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS TOTAL_OEC,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS OEC_LESS_TAX,
PO.APPROVED_AT AS PO_APPROVED_DATE,
POL.NOTE,
V.RULE_ID,
V.RULE_YEAR,
R.RULE,
R.REIMBURSEMENT_RATE,
CASE WHEN POL.FINANCE_STATUS  IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms')  THEN 0.00
WHEN (POL.FINANCE_STATUS NOT IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms') OR POL.FINANCE_STATUS IS NULL) THEN IFNULL(MS.REBATE_AMOUNT,0)
ELSE 0.00 END AS REIMBURSEMENT_AMOUNT
FROM ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_LINE_ITEMS AS POL
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDERS AS PO ON POL.COMPANY_PURCHASE_ORDER_ID = PO.COMPANY_PURCHASE_ORDER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_TYPES AS CPT ON PO.COMPANY_PURCHASE_ORDER_TYPE_ID = CPT.COMPANY_PURCHASE_ORDER_TYPE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C1 ON PO.VENDOR_ID = C1.COMPANY_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS_AGGREGATE AS AA ON POL.ASSET_ID = AA.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MODELS AS EMO ON POL.EQUIPMENT_MODEL_ID = EMO.EQUIPMENT_MODEL_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MAKES AS EMA ON EMO.EQUIPMENT_MAKE_ID = EMA.EQUIPMENT_MAKE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C2 ON AA.COMPANY_ID = C2.COMPANY_ID
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES AS V ON (PO.VENDOR_ID = V.VENDOR_ID) AND (V.RULE_YEAR = YEAR(POL.INVOICE_DATE))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.MANUFACTURE_SPECIFIC AS MS ON (ORDER_NUMBER_GROUPED = MS.PO_NUMBER)
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES_RATES AS R ON MS.RULE_ID = R.RULE_ID
WHERE C1.SUPPLY_VENDOR = TRUE
AND (EMO.NAME NOT ILIKE '%bucket%' OR EMO.NAME IS NULL)
AND POL.DELETED_AT IS NULL
AND POL.INVOICE_DATE >= '2026-01-01' AND POL.INVOICE_DATE < '2026-04-01'
AND POL.INVOICE_DATE::DATE >= MS.EFFECTIVE_DATE::DATE
AND (COALESCE(POL.SERIAL, POL.VIN) NOT IN (SELECT DISTINCT SERIAL FROM EXCLUDE_CTE) OR COALESCE(POL.SERIAL, POL.VIN) IS NULL)
AND MS.RULE_ID = 16
AND MS.TYPE = 'PO'
AND ((POL.NOTE NOT LIKE '%CPE%' AND POL.NOTE NOT LIKE '%IES%' AND POL.NOTE NOT LIKE '%VLP%') OR POL.NOTE IS NULL)
UNION ALL
-- JLG - MODEL
SELECT PO.VENDOR_ID,
C1.NAME AS VENDOR_NAME,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID) AS ORDER_NUMBER_GROUPED,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID,'-',POL.COMPANY_PURCHASE_ORDER_LINE_ITEM_NUMBER) AS ORDER_NUMBER,
POL.INVOICE_NUMBER,
POL.INVOICE_DATE,
POL.RELEASE_DATE,
POL.ASSET_ID,
COALESCE(POL.SERIAL,POL.VIN) AS SERIAL_VIN,
POL.ORDER_STATUS,
POL.FINANCE_STATUS,
EMA.NAME AS EQUIPMENT_MAKE,
EMO.NAME AS EQUIPMENT_MODEL,
POL.YEAR AS MODEL_YEAR,
POL.FACTORY_BUILD_SPECIFICATIONS,
AA.COMPANY_ID AS OWNER_ID,
C2.NAME AS OWNER_NAME,
POL.NET_PRICE,
POL.FREIGHT_COST,
POL.SALES_TAX,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.SALES_TAX,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS TOTAL_OEC,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS OEC_LESS_TAX,
PO.APPROVED_AT AS PO_APPROVED_DATE,
POL.NOTE,
V.RULE_ID,
V.RULE_YEAR,
R.RULE,
R.REIMBURSEMENT_RATE,
CASE WHEN POL.FINANCE_STATUS IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms')  THEN 0.00
WHEN (POL.FINANCE_STATUS NOT IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms') OR POL.FINANCE_STATUS IS NULL) THEN IFNULL(R.REIMBURSEMENT_RATE*OEC_LESS_TAX,0)  ELSE 0.00 END AS REIMBURSEMENT_AMOUNT
FROM ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_LINE_ITEMS AS POL
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDERS AS PO ON POL.COMPANY_PURCHASE_ORDER_ID = PO.COMPANY_PURCHASE_ORDER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_TYPES AS CPT ON PO.COMPANY_PURCHASE_ORDER_TYPE_ID = CPT.COMPANY_PURCHASE_ORDER_TYPE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C1 ON PO.VENDOR_ID = C1.COMPANY_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS_AGGREGATE AS AA ON POL.ASSET_ID = AA.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MODELS AS EMO ON POL.EQUIPMENT_MODEL_ID = EMO.EQUIPMENT_MODEL_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MAKES AS EMA ON EMO.EQUIPMENT_MAKE_ID = EMA.EQUIPMENT_MAKE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C2 ON AA.COMPANY_ID = C2.COMPANY_ID
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES AS V ON (PO.VENDOR_ID = V.VENDOR_ID) AND (V.RULE_YEAR = YEAR(POL.INVOICE_DATE))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.MANUFACTURE_SPECIFIC AS MS ON (LOWER(EMA.NAME) = LOWER(MS.MAKE)) AND (LOWER(EMO.NAME) = LOWER(MS.MODEL))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES_RATES AS R ON MS.RULE_ID = R.RULE_ID
WHERE C1.SUPPLY_VENDOR = TRUE
AND (EMO.NAME NOT ILIKE '%bucket%' OR EMO.NAME IS NULL)
AND POL.DELETED_AT IS NULL
AND POL.INVOICE_DATE >= '2026-01-01' AND POL.INVOICE_DATE < '2026-04-01'
AND POL.INVOICE_DATE::DATE >= MS.EFFECTIVE_DATE::DATE
AND (COALESCE(POL.SERIAL, POL.VIN) NOT IN (SELECT DISTINCT SERIAL FROM EXCLUDE_CTE) OR COALESCE(POL.SERIAL, POL.VIN) IS NULL)
AND MS.RULE_ID = 15
AND MS.TYPE = 'Model'
AND ((POL.NOTE NOT LIKE '%CPE%' AND POL.NOTE NOT LIKE '%IES%' AND POL.NOTE NOT LIKE '%VLP%') OR POL.NOTE IS NULL)
UNION ALL
-- MODEL SPECIFIC - MODEL - DOOSAN
SELECT PO.VENDOR_ID,
C1.NAME AS VENDOR_NAME,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID) AS ORDER_NUMBER_GROUPED,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID,'-',POL.COMPANY_PURCHASE_ORDER_LINE_ITEM_NUMBER) AS ORDER_NUMBER,
POL.INVOICE_NUMBER,
POL.INVOICE_DATE,
POL.RELEASE_DATE,
POL.ASSET_ID,
COALESCE(POL.SERIAL,POL.VIN) AS SERIAL_VIN,
POL.ORDER_STATUS,
POL.FINANCE_STATUS,
EMA.NAME AS EQUIPMENT_MAKE,
EMO.NAME AS EQUIPMENT_MODEL,
POL.YEAR AS MODEL_YEAR,
POL.FACTORY_BUILD_SPECIFICATIONS,
AA.COMPANY_ID AS OWNER_ID,
C2.NAME AS OWNER_NAME,
POL.NET_PRICE,
POL.FREIGHT_COST,
POL.SALES_TAX,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.SALES_TAX,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS TOTAL_OEC,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS OEC_LESS_TAX,
PO.APPROVED_AT AS PO_APPROVED_DATE,
POL.NOTE,
V.RULE_ID,
V.RULE_YEAR,
R.RULE,
R.REIMBURSEMENT_RATE,
CASE WHEN POL.FINANCE_STATUS IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms')  THEN 0.00
WHEN (POL.FINANCE_STATUS NOT IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms') OR POL.FINANCE_STATUS IS NULL) THEN IFNULL(MS.REBATE_AMOUNT,0)  ELSE 0.00 END AS REIMBURSEMENT_AMOUNT
FROM ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_LINE_ITEMS AS POL
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDERS AS PO ON POL.COMPANY_PURCHASE_ORDER_ID = PO.COMPANY_PURCHASE_ORDER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_TYPES AS CPT ON PO.COMPANY_PURCHASE_ORDER_TYPE_ID = CPT.COMPANY_PURCHASE_ORDER_TYPE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C1 ON PO.VENDOR_ID = C1.COMPANY_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS_AGGREGATE AS AA ON POL.ASSET_ID = AA.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MODELS AS EMO ON POL.EQUIPMENT_MODEL_ID = EMO.EQUIPMENT_MODEL_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MAKES AS EMA ON EMO.EQUIPMENT_MAKE_ID = EMA.EQUIPMENT_MAKE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C2 ON AA.COMPANY_ID = C2.COMPANY_ID
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES AS V ON (PO.VENDOR_ID = V.VENDOR_ID) AND (V.RULE_YEAR = YEAR(POL.INVOICE_DATE))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.MANUFACTURE_SPECIFIC AS MS ON (LOWER(EMA.NAME) = LOWER(MS.MAKE)) AND (LOWER(EMO.NAME) = LOWER(MS.MODEL))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES_RATES AS R ON MS.RULE_ID = R.RULE_ID
WHERE C1.SUPPLY_VENDOR = TRUE
AND (EMO.NAME NOT ILIKE '%bucket%' OR EMO.NAME IS NULL)
AND POL.DELETED_AT IS NULL
AND POL.INVOICE_DATE >= '2026-01-01' AND POL.INVOICE_DATE < '2026-04-01'
AND POL.INVOICE_DATE::DATE >= MS.EFFECTIVE_DATE::DATE
AND (COALESCE(POL.SERIAL, POL.VIN) NOT IN (SELECT DISTINCT SERIAL FROM EXCLUDE_CTE) OR COALESCE(POL.SERIAL, POL.VIN) IS NULL)
AND MS.RULE_ID = 17
AND MS.TYPE = 'Model'
AND MS.PO_NUMBER_LINES IS NULL
AND MS.PO_NUMBER IS NULL
AND ((POL.NOTE NOT LIKE '%CPE%' AND POL.NOTE NOT LIKE '%IES%' AND POL.NOTE NOT LIKE '%VLP%') OR POL.NOTE IS NULL)
AND ORDER_NUMBER <> 'SPO134561-1'
UNION ALL
-- MODEL SPECIFIC - PO - DOOSAN
SELECT PO.VENDOR_ID,
C1.NAME AS VENDOR_NAME,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID) AS ORDER_NUMBER_GROUPED,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID,'-',POL.COMPANY_PURCHASE_ORDER_LINE_ITEM_NUMBER) AS ORDER_NUMBER,
POL.INVOICE_NUMBER,
POL.INVOICE_DATE,
POL.RELEASE_DATE,
POL.ASSET_ID,
COALESCE(POL.SERIAL,POL.VIN) AS SERIAL_VIN,
POL.ORDER_STATUS,
POL.FINANCE_STATUS,
EMA.NAME AS EQUIPMENT_MAKE,
EMO.NAME AS EQUIPMENT_MODEL,
POL.YEAR AS MODEL_YEAR,
POL.FACTORY_BUILD_SPECIFICATIONS,
AA.COMPANY_ID AS OWNER_ID,
C2.NAME AS OWNER_NAME,
POL.NET_PRICE,
POL.FREIGHT_COST,
POL.SALES_TAX,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.SALES_TAX,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS TOTAL_OEC,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS OEC_LESS_TAX,
PO.APPROVED_AT AS PO_APPROVED_DATE,
POL.NOTE,
V.RULE_ID,
V.RULE_YEAR,
R.RULE,
R.REIMBURSEMENT_RATE,
CASE WHEN POL.FINANCE_STATUS  IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms')  THEN 0.00
WHEN (V.RULE_ID  = 17) AND (POL.FINANCE_STATUS NOT IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms') OR POL.FINANCE_STATUS IS NULL) THEN IFNULL(MS.REBATE_AMOUNT,0)
ELSE 0.00 END AS REIMBURSEMENT_AMOUNT
FROM ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_LINE_ITEMS AS POL
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDERS AS PO ON POL.COMPANY_PURCHASE_ORDER_ID = PO.COMPANY_PURCHASE_ORDER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_TYPES AS CPT ON PO.COMPANY_PURCHASE_ORDER_TYPE_ID = CPT.COMPANY_PURCHASE_ORDER_TYPE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C1 ON PO.VENDOR_ID = C1.COMPANY_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS_AGGREGATE AS AA ON POL.ASSET_ID = AA.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MODELS AS EMO ON POL.EQUIPMENT_MODEL_ID = EMO.EQUIPMENT_MODEL_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MAKES AS EMA ON EMO.EQUIPMENT_MAKE_ID = EMA.EQUIPMENT_MAKE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C2 ON AA.COMPANY_ID = C2.COMPANY_ID
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES AS V ON (PO.VENDOR_ID = V.VENDOR_ID) AND (V.RULE_YEAR = YEAR(POL.INVOICE_DATE))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.MANUFACTURE_SPECIFIC AS MS ON (ORDER_NUMBER_GROUPED = MS.PO_NUMBER) AND (LOWER(EMA.NAME) = LOWER(MS.MAKE)) AND (LOWER(EMO.NAME) = LOWER(MS.MODEL))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES_RATES AS R ON MS.RULE_ID = R.RULE_ID
WHERE C1.SUPPLY_VENDOR = TRUE
AND (EMO.NAME NOT ILIKE '%bucket%' OR EMO.NAME IS NULL)
AND POL.DELETED_AT IS NULL
AND POL.INVOICE_DATE >= '2026-01-01' AND POL.INVOICE_DATE < '2026-04-01'
AND POL.INVOICE_DATE::DATE >= MS.EFFECTIVE_DATE::DATE
AND MS.RULE_ID = 17
AND MS.TYPE = 'PO'
AND MS.PO_NUMBER_LINES IS NULL
AND ORDER_NUMBER <> 'SPO134561-1'
AND ((POL.NOTE NOT LIKE '%CPE%' AND POL.NOTE NOT LIKE '%IES%' AND POL.NOTE NOT LIKE '%VLP%') OR POL.NOTE IS NULL)
UNION ALL
-- MODEL SPECIFIC - PO - DOOSAN - PO_NUMBER_LINES
SELECT PO.VENDOR_ID,
C1.NAME AS VENDOR_NAME,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID) AS ORDER_NUMBER_GROUPED,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID,'-',POL.COMPANY_PURCHASE_ORDER_LINE_ITEM_NUMBER) AS ORDER_NUMBER,
POL.INVOICE_NUMBER,
POL.INVOICE_DATE,
POL.RELEASE_DATE,
POL.ASSET_ID,
COALESCE(POL.SERIAL,POL.VIN) AS SERIAL_VIN,
POL.ORDER_STATUS,
POL.FINANCE_STATUS,
EMA.NAME AS EQUIPMENT_MAKE,
EMO.NAME AS EQUIPMENT_MODEL,
POL.YEAR AS MODEL_YEAR,
POL.FACTORY_BUILD_SPECIFICATIONS,
AA.COMPANY_ID AS OWNER_ID,
C2.NAME AS OWNER_NAME,
POL.NET_PRICE,
POL.FREIGHT_COST,
POL.SALES_TAX,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.SALES_TAX,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS TOTAL_OEC,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS OEC_LESS_TAX,
PO.APPROVED_AT AS PO_APPROVED_DATE,
POL.NOTE,
V.RULE_ID,
V.RULE_YEAR,
R.RULE,
R.REIMBURSEMENT_RATE,
CASE WHEN POL.FINANCE_STATUS  IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms')  THEN 0.00
WHEN (V.RULE_ID  IN (17)) AND (POL.FINANCE_STATUS NOT IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms') OR POL.FINANCE_STATUS IS NULL) THEN IFNULL(MS.REBATE_AMOUNT,0)
ELSE 0.00 END AS REIMBURSEMENT_AMOUNT
FROM ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_LINE_ITEMS AS POL
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDERS AS PO ON POL.COMPANY_PURCHASE_ORDER_ID = PO.COMPANY_PURCHASE_ORDER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_TYPES AS CPT ON PO.COMPANY_PURCHASE_ORDER_TYPE_ID = CPT.COMPANY_PURCHASE_ORDER_TYPE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C1 ON PO.VENDOR_ID = C1.COMPANY_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS_AGGREGATE AS AA ON POL.ASSET_ID = AA.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MODELS AS EMO ON POL.EQUIPMENT_MODEL_ID = EMO.EQUIPMENT_MODEL_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MAKES AS EMA ON EMO.EQUIPMENT_MAKE_ID = EMA.EQUIPMENT_MAKE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C2 ON AA.COMPANY_ID = C2.COMPANY_ID
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES AS V ON (PO.VENDOR_ID = V.VENDOR_ID) AND (V.RULE_YEAR = YEAR(POL.INVOICE_DATE))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.MANUFACTURE_SPECIFIC AS MS ON (ORDER_NUMBER = MS.PO_NUMBER_LINES) AND (LOWER(EMA.NAME) = LOWER(MS.MAKE))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES_RATES AS R ON MS.RULE_ID = R.RULE_ID
WHERE C1.SUPPLY_VENDOR = TRUE
AND (EMO.NAME NOT ILIKE '%bucket%' OR EMO.NAME IS NULL)
AND POL.DELETED_AT IS NULL
AND POL.INVOICE_DATE >= '2026-01-01' AND POL.INVOICE_DATE < '2026-04-01'
AND POL.INVOICE_DATE::DATE >= MS.EFFECTIVE_DATE::DATE
AND MS.RULE_ID = 17
AND MS.TYPE = 'PO'
AND MS.PO_NUMBER_LINES IS NOT NULL
AND ((POL.NOTE NOT LIKE '%CPE%' AND POL.NOTE NOT LIKE '%IES%' AND POL.NOTE NOT LIKE '%VLP%') OR POL.NOTE IS NULL)
UNION ALL
-- MODEL SPECIFIC - MODEL - Fayat
SELECT PO.VENDOR_ID,
C1.NAME AS VENDOR_NAME,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID) AS ORDER_NUMBER_GROUPED,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID,'-',POL.COMPANY_PURCHASE_ORDER_LINE_ITEM_NUMBER) AS ORDER_NUMBER,
POL.INVOICE_NUMBER,
POL.INVOICE_DATE,
POL.RELEASE_DATE,
POL.ASSET_ID,
COALESCE(POL.SERIAL,POL.VIN) AS SERIAL_VIN,
POL.ORDER_STATUS,
POL.FINANCE_STATUS,
EMA.NAME AS EQUIPMENT_MAKE,
EMO.NAME AS EQUIPMENT_MODEL,
POL.YEAR AS MODEL_YEAR,
POL.FACTORY_BUILD_SPECIFICATIONS,
AA.COMPANY_ID AS OWNER_ID,
C2.NAME AS OWNER_NAME,
POL.NET_PRICE,
POL.FREIGHT_COST,
POL.SALES_TAX,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.SALES_TAX,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS TOTAL_OEC,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS OEC_LESS_TAX,
PO.APPROVED_AT AS PO_APPROVED_DATE,
POL.NOTE,
V.RULE_ID,
V.RULE_YEAR,
R.RULE,
R.REIMBURSEMENT_RATE,
CASE WHEN POL.FINANCE_STATUS IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms')  THEN 0.00
WHEN (POL.FINANCE_STATUS NOT IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms') OR POL.FINANCE_STATUS IS NULL) THEN IFNULL(MS.REBATE_AMOUNT,0)  ELSE 0.00 END AS REIMBURSEMENT_AMOUNT
FROM ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_LINE_ITEMS AS POL
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDERS AS PO ON POL.COMPANY_PURCHASE_ORDER_ID = PO.COMPANY_PURCHASE_ORDER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_TYPES AS CPT ON PO.COMPANY_PURCHASE_ORDER_TYPE_ID = CPT.COMPANY_PURCHASE_ORDER_TYPE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C1 ON PO.VENDOR_ID = C1.COMPANY_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS_AGGREGATE AS AA ON POL.ASSET_ID = AA.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MODELS AS EMO ON POL.EQUIPMENT_MODEL_ID = EMO.EQUIPMENT_MODEL_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MAKES AS EMA ON EMO.EQUIPMENT_MAKE_ID = EMA.EQUIPMENT_MAKE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C2 ON AA.COMPANY_ID = C2.COMPANY_ID
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES AS V ON (PO.VENDOR_ID = V.VENDOR_ID) AND (V.RULE_YEAR = YEAR(POL.INVOICE_DATE))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.MANUFACTURE_SPECIFIC AS MS ON (LOWER(EMA.NAME) = LOWER(MS.MAKE)) AND (LOWER(EMO.NAME) = LOWER(MS.MODEL))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES_RATES AS R ON MS.RULE_ID = R.RULE_ID
WHERE C1.SUPPLY_VENDOR = TRUE
AND (EMO.NAME NOT ILIKE '%bucket%' OR EMO.NAME IS NULL)
AND POL.DELETED_AT IS NULL
AND POL.INVOICE_DATE >= '2026-01-01' AND POL.INVOICE_DATE < '2026-04-01'
AND POL.INVOICE_DATE::DATE >= MS.EFFECTIVE_DATE::DATE
AND (COALESCE(POL.SERIAL, POL.VIN) NOT IN (SELECT DISTINCT SERIAL FROM EXCLUDE_CTE) OR COALESCE(POL.SERIAL, POL.VIN) IS NULL)
AND MS.RULE_ID = 25
AND MS.TYPE = 'Model'
AND ((POL.NOTE NOT LIKE '%CPE%' AND POL.NOTE NOT LIKE '%IES%' AND POL.NOTE NOT LIKE '%VLP%') OR POL.NOTE IS NULL)
--AND (POL.NOTE NOT ILIKE '%This line is NET 75%' OR POL.NOTE IS NULL)
UNION ALL
-- MODEL SPECIFIC - PO - Cummins
SELECT PO.VENDOR_ID,
C1.NAME AS VENDOR_NAME,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID) AS ORDER_NUMBER_GROUPED,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID,'-',POL.COMPANY_PURCHASE_ORDER_LINE_ITEM_NUMBER) AS ORDER_NUMBER,
POL.INVOICE_NUMBER,
POL.INVOICE_DATE,
POL.RELEASE_DATE,
POL.ASSET_ID,
COALESCE(POL.SERIAL,POL.VIN) AS SERIAL_VIN,
POL.ORDER_STATUS,
POL.FINANCE_STATUS,
EMA.NAME AS EQUIPMENT_MAKE,
EMO.NAME AS EQUIPMENT_MODEL,
POL.YEAR AS MODEL_YEAR,
POL.FACTORY_BUILD_SPECIFICATIONS,
AA.COMPANY_ID AS OWNER_ID,
C2.NAME AS OWNER_NAME,
POL.NET_PRICE,
POL.FREIGHT_COST,
POL.SALES_TAX,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.SALES_TAX,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS TOTAL_OEC,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS OEC_LESS_TAX,
PO.APPROVED_AT AS PO_APPROVED_DATE,
POL.NOTE,
V.RULE_ID,
V.RULE_YEAR,
R.RULE,
R.REIMBURSEMENT_RATE,
CASE WHEN POL.FINANCE_STATUS  IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms')  THEN 0.00
WHEN (V.RULE_ID NOT IN (24)) AND (POL.FINANCE_STATUS NOT IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms') OR POL.FINANCE_STATUS IS NULL) THEN IFNULL(MS.REBATE_AMOUNT,0)
ELSE 0.00 END AS REIMBURSEMENT_AMOUNT
FROM ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_LINE_ITEMS AS POL
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDERS AS PO ON POL.COMPANY_PURCHASE_ORDER_ID = PO.COMPANY_PURCHASE_ORDER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_TYPES AS CPT ON PO.COMPANY_PURCHASE_ORDER_TYPE_ID = CPT.COMPANY_PURCHASE_ORDER_TYPE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C1 ON PO.VENDOR_ID = C1.COMPANY_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS_AGGREGATE AS AA ON POL.ASSET_ID = AA.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MODELS AS EMO ON POL.EQUIPMENT_MODEL_ID = EMO.EQUIPMENT_MODEL_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MAKES AS EMA ON EMO.EQUIPMENT_MAKE_ID = EMA.EQUIPMENT_MAKE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C2 ON AA.COMPANY_ID = C2.COMPANY_ID
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES AS V ON (PO.VENDOR_ID = V.VENDOR_ID) AND (V.RULE_YEAR = YEAR(POL.INVOICE_DATE))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.MANUFACTURE_SPECIFIC AS MS ON (ORDER_NUMBER = MS.PO_NUMBER_LINES)
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES_RATES AS R ON MS.RULE_ID = R.RULE_ID
WHERE C1.SUPPLY_VENDOR = TRUE
AND (EMO.NAME NOT ILIKE '%bucket%' OR EMO.NAME IS NULL)
AND POL.DELETED_AT IS NULL
AND POL.INVOICE_DATE >= '2026-01-01' AND POL.INVOICE_DATE < '2026-04-01'
AND POL.INVOICE_DATE::DATE >= MS.EFFECTIVE_DATE::DATE
AND (COALESCE(POL.SERIAL, POL.VIN) NOT IN (SELECT DISTINCT SERIAL FROM EXCLUDE_CTE) OR COALESCE(POL.SERIAL, POL.VIN) IS NULL)
AND MS.RULE_ID = 27
AND MS.TYPE = 'PO'
AND ((POL.NOTE NOT LIKE '%CPE%' AND POL.NOTE NOT LIKE '%IES%' AND POL.NOTE NOT LIKE '%VLP%') OR POL.NOTE IS NULL)
UNION ALL
-- MODEL SPECIFIC - PO - CUSTOM TRUCK
SELECT PO.VENDOR_ID,
C1.NAME AS VENDOR_NAME,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID) AS ORDER_NUMBER_GROUPED,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID,'-',POL.COMPANY_PURCHASE_ORDER_LINE_ITEM_NUMBER) AS ORDER_NUMBER,
POL.INVOICE_NUMBER,
POL.INVOICE_DATE,
POL.RELEASE_DATE,
POL.ASSET_ID,
COALESCE(POL.SERIAL,POL.VIN) AS SERIAL_VIN,
POL.ORDER_STATUS,
POL.FINANCE_STATUS,
EMA.NAME AS EQUIPMENT_MAKE,
EMO.NAME AS EQUIPMENT_MODEL,
POL.YEAR AS MODEL_YEAR,
POL.FACTORY_BUILD_SPECIFICATIONS,
AA.COMPANY_ID AS OWNER_ID,
C2.NAME AS OWNER_NAME,
POL.NET_PRICE,
POL.FREIGHT_COST,
POL.SALES_TAX,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.SALES_TAX,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS TOTAL_OEC,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS OEC_LESS_TAX,
PO.APPROVED_AT AS PO_APPROVED_DATE,
POL.NOTE,
V.RULE_ID,
V.RULE_YEAR,
R.RULE,
R.REIMBURSEMENT_RATE,
CASE WHEN POL.FINANCE_STATUS  IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms')  THEN 0.00
WHEN (V.RULE_ID NOT IN (24)) AND (POL.FINANCE_STATUS NOT IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms') OR POL.FINANCE_STATUS IS NULL) THEN IFNULL(MS.REBATE_AMOUNT,0)
ELSE 0.00 END AS REIMBURSEMENT_AMOUNT
FROM ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_LINE_ITEMS AS POL
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDERS AS PO ON POL.COMPANY_PURCHASE_ORDER_ID = PO.COMPANY_PURCHASE_ORDER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_TYPES AS CPT ON PO.COMPANY_PURCHASE_ORDER_TYPE_ID = CPT.COMPANY_PURCHASE_ORDER_TYPE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C1 ON PO.VENDOR_ID = C1.COMPANY_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS_AGGREGATE AS AA ON POL.ASSET_ID = AA.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MODELS AS EMO ON POL.EQUIPMENT_MODEL_ID = EMO.EQUIPMENT_MODEL_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MAKES AS EMA ON EMO.EQUIPMENT_MAKE_ID = EMA.EQUIPMENT_MAKE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C2 ON AA.COMPANY_ID = C2.COMPANY_ID
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES AS V ON (PO.VENDOR_ID = V.VENDOR_ID) AND (V.RULE_YEAR = YEAR(POL.INVOICE_DATE))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.MANUFACTURE_SPECIFIC AS MS ON (ORDER_NUMBER_GROUPED = MS.PO_NUMBER)
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES_RATES AS R ON MS.RULE_ID = R.RULE_ID
WHERE C1.SUPPLY_VENDOR = TRUE
AND (EMO.NAME NOT ILIKE '%bucket%' OR EMO.NAME IS NULL)
AND POL.DELETED_AT IS NULL
AND POL.INVOICE_DATE >= '2026-01-01' AND POL.INVOICE_DATE < '2026-04-01'
AND POL.INVOICE_DATE::DATE >= MS.EFFECTIVE_DATE::DATE
AND MS.RULE_ID = 28
AND MS.TYPE = 'PO'
AND ((POL.NOTE NOT LIKE '%CPE%' AND POL.NOTE NOT LIKE '%IES%' AND POL.NOTE NOT LIKE '%VLP%') OR POL.NOTE IS NULL)
UNION ALL
-- MODEL SPECIFIC - MODEL - CNH
SELECT PO.VENDOR_ID,
C1.NAME AS VENDOR_NAME,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID) AS ORDER_NUMBER_GROUPED,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID,'-',POL.COMPANY_PURCHASE_ORDER_LINE_ITEM_NUMBER) AS ORDER_NUMBER,
POL.INVOICE_NUMBER,
POL.INVOICE_DATE,
POL.RELEASE_DATE,
POL.ASSET_ID,
COALESCE(POL.SERIAL,POL.VIN) AS SERIAL_VIN,
POL.ORDER_STATUS,
POL.FINANCE_STATUS,
EMA.NAME AS EQUIPMENT_MAKE,
EMO.NAME AS EQUIPMENT_MODEL,
POL.YEAR AS MODEL_YEAR,
POL.FACTORY_BUILD_SPECIFICATIONS,
AA.COMPANY_ID AS OWNER_ID,
C2.NAME AS OWNER_NAME,
POL.NET_PRICE,
POL.FREIGHT_COST,
POL.SALES_TAX,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.SALES_TAX,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS TOTAL_OEC,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS OEC_LESS_TAX,
PO.APPROVED_AT AS PO_APPROVED_DATE,
POL.NOTE,
V.RULE_ID,
V.RULE_YEAR,
R.RULE,
R.REIMBURSEMENT_RATE,
CASE WHEN POL.FINANCE_STATUS IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms')  THEN 0.00
WHEN (POL.FINANCE_STATUS NOT IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms') OR POL.FINANCE_STATUS IS NULL) THEN IFNULL(MS.REBATE_AMOUNT,0)  ELSE 0.00 END AS REIMBURSEMENT_AMOUNT
FROM ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_LINE_ITEMS AS POL
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDERS AS PO ON POL.COMPANY_PURCHASE_ORDER_ID = PO.COMPANY_PURCHASE_ORDER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_TYPES AS CPT ON PO.COMPANY_PURCHASE_ORDER_TYPE_ID = CPT.COMPANY_PURCHASE_ORDER_TYPE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C1 ON PO.VENDOR_ID = C1.COMPANY_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS_AGGREGATE AS AA ON POL.ASSET_ID = AA.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MODELS AS EMO ON POL.EQUIPMENT_MODEL_ID = EMO.EQUIPMENT_MODEL_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MAKES AS EMA ON EMO.EQUIPMENT_MAKE_ID = EMA.EQUIPMENT_MAKE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C2 ON AA.COMPANY_ID = C2.COMPANY_ID
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES AS V ON (PO.VENDOR_ID = V.VENDOR_ID) AND (V.RULE_YEAR = YEAR(POL.INVOICE_DATE))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.MANUFACTURE_SPECIFIC AS MS ON (LOWER(EMA.NAME) = LOWER(MS.MAKE)) AND (LOWER(EMO.NAME) = LOWER(MS.MODEL))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES_RATES AS R ON MS.RULE_ID = R.RULE_ID
WHERE C1.SUPPLY_VENDOR = TRUE
AND (EMO.NAME NOT ILIKE '%bucket%' OR EMO.NAME IS NULL)
AND POL.DELETED_AT IS NULL
AND POL.INVOICE_DATE >= '2026-01-01' AND POL.INVOICE_DATE < '2026-04-01'
AND POL.INVOICE_DATE::DATE >= MS.EFFECTIVE_DATE::DATE
AND (COALESCE(POL.SERIAL, POL.VIN) NOT IN (SELECT DISTINCT SERIAL FROM EXCLUDE_CTE) OR COALESCE(POL.SERIAL, POL.VIN) IS NULL)
and order_number_grouped <> 'SPO137036'
AND MS.RULE_ID = 26
AND MS.TYPE = 'Model'
AND MS.PO_NUMBER_LINES IS NULL
AND MS.PO_NUMBER IS NULL
AND ORDER_NUMBER NOT IN ('SPO134608-1','SPO134609-1')
--AND ORDER_NUMBER_GROUPED NOT IN ('SPO134612', 'SPO134608',  'SPO134609',  'SPO137036')
AND ((POL.NOTE NOT LIKE '%CPE%' AND POL.NOTE NOT LIKE '%IES%' AND POL.NOTE NOT LIKE '%VLP%') OR POL.NOTE IS NULL)
UNION ALL
-- MODEL SPECIFIC - PO - CNH
SELECT PO.VENDOR_ID,
C1.NAME AS VENDOR_NAME,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID) AS ORDER_NUMBER_GROUPED,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID,'-',POL.COMPANY_PURCHASE_ORDER_LINE_ITEM_NUMBER) AS ORDER_NUMBER,
POL.INVOICE_NUMBER,
POL.INVOICE_DATE,
POL.RELEASE_DATE,
POL.ASSET_ID,
COALESCE(POL.SERIAL,POL.VIN) AS SERIAL_VIN,
POL.ORDER_STATUS,
POL.FINANCE_STATUS,
EMA.NAME AS EQUIPMENT_MAKE,
EMO.NAME AS EQUIPMENT_MODEL,
POL.YEAR AS MODEL_YEAR,
POL.FACTORY_BUILD_SPECIFICATIONS,
AA.COMPANY_ID AS OWNER_ID,
C2.NAME AS OWNER_NAME,
POL.NET_PRICE,
POL.FREIGHT_COST,
POL.SALES_TAX,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.SALES_TAX,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS TOTAL_OEC,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS OEC_LESS_TAX,
PO.APPROVED_AT AS PO_APPROVED_DATE,
POL.NOTE,
V.RULE_ID,
V.RULE_YEAR,
R.RULE,
R.REIMBURSEMENT_RATE,
CASE WHEN POL.FINANCE_STATUS  IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms')  THEN 0.00
WHEN (V.RULE_ID  = 26) AND (POL.FINANCE_STATUS NOT IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms') OR POL.FINANCE_STATUS IS NULL) THEN IFNULL(MS.REBATE_AMOUNT,0)
ELSE 0.00 END AS REIMBURSEMENT_AMOUNT
FROM ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_LINE_ITEMS AS POL
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDERS AS PO ON POL.COMPANY_PURCHASE_ORDER_ID = PO.COMPANY_PURCHASE_ORDER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_TYPES AS CPT ON PO.COMPANY_PURCHASE_ORDER_TYPE_ID = CPT.COMPANY_PURCHASE_ORDER_TYPE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C1 ON PO.VENDOR_ID = C1.COMPANY_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS_AGGREGATE AS AA ON POL.ASSET_ID = AA.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MODELS AS EMO ON POL.EQUIPMENT_MODEL_ID = EMO.EQUIPMENT_MODEL_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MAKES AS EMA ON EMO.EQUIPMENT_MAKE_ID = EMA.EQUIPMENT_MAKE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C2 ON AA.COMPANY_ID = C2.COMPANY_ID
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES AS V ON (PO.VENDOR_ID = V.VENDOR_ID) AND (V.RULE_YEAR = YEAR(POL.INVOICE_DATE))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.MANUFACTURE_SPECIFIC AS MS ON (ORDER_NUMBER_GROUPED = MS.PO_NUMBER) AND (LOWER(EMA.NAME) = LOWER(MS.MAKE)) AND (LOWER(EMO.NAME) = LOWER(MS.MODEL))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES_RATES AS R ON MS.RULE_ID = R.RULE_ID
WHERE C1.SUPPLY_VENDOR = TRUE
AND (EMO.NAME NOT ILIKE '%bucket%' OR EMO.NAME IS NULL)
AND POL.DELETED_AT IS NULL
AND POL.INVOICE_DATE >= '2026-01-01' AND POL.INVOICE_DATE < '2026-04-01'
AND POL.INVOICE_DATE::DATE >= MS.EFFECTIVE_DATE::DATE
AND MS.RULE_ID = 26
AND MS.TYPE = 'PO'
AND MS.PO_NUMBER_LINES IS NULL
AND ORDER_NUMBER NOT IN ('SPO134608-1','SPO134609-1')
AND ((POL.NOTE NOT LIKE '%CPE%' AND POL.NOTE NOT LIKE '%IES%' AND POL.NOTE NOT LIKE '%VLP%') OR POL.NOTE IS NULL)
UNION ALL
-- MODEL SPECIFIC - PO - CNH - PO_NUMBER_LINES
SELECT PO.VENDOR_ID,
C1.NAME AS VENDOR_NAME,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID) AS ORDER_NUMBER_GROUPED,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID,'-',POL.COMPANY_PURCHASE_ORDER_LINE_ITEM_NUMBER) AS ORDER_NUMBER,
POL.INVOICE_NUMBER,
POL.INVOICE_DATE,
POL.RELEASE_DATE,
POL.ASSET_ID,
COALESCE(POL.SERIAL,POL.VIN) AS SERIAL_VIN,
POL.ORDER_STATUS,
POL.FINANCE_STATUS,
EMA.NAME AS EQUIPMENT_MAKE,
EMO.NAME AS EQUIPMENT_MODEL,
POL.YEAR AS MODEL_YEAR,
POL.FACTORY_BUILD_SPECIFICATIONS,
AA.COMPANY_ID AS OWNER_ID,
C2.NAME AS OWNER_NAME,
POL.NET_PRICE,
POL.FREIGHT_COST,
POL.SALES_TAX,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.SALES_TAX,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS TOTAL_OEC,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS OEC_LESS_TAX,
PO.APPROVED_AT AS PO_APPROVED_DATE,
POL.NOTE,
V.RULE_ID,
V.RULE_YEAR,
R.RULE,
R.REIMBURSEMENT_RATE,
CASE WHEN POL.FINANCE_STATUS  IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms')  THEN 0.00
WHEN (V.RULE_ID  IN (26)) AND (POL.FINANCE_STATUS NOT IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms') OR POL.FINANCE_STATUS IS NULL) THEN IFNULL(MS.REBATE_AMOUNT,0)
ELSE 0.00 END AS REIMBURSEMENT_AMOUNT
FROM ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_LINE_ITEMS AS POL
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDERS AS PO ON POL.COMPANY_PURCHASE_ORDER_ID = PO.COMPANY_PURCHASE_ORDER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_TYPES AS CPT ON PO.COMPANY_PURCHASE_ORDER_TYPE_ID = CPT.COMPANY_PURCHASE_ORDER_TYPE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C1 ON PO.VENDOR_ID = C1.COMPANY_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS_AGGREGATE AS AA ON POL.ASSET_ID = AA.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MODELS AS EMO ON POL.EQUIPMENT_MODEL_ID = EMO.EQUIPMENT_MODEL_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MAKES AS EMA ON EMO.EQUIPMENT_MAKE_ID = EMA.EQUIPMENT_MAKE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C2 ON AA.COMPANY_ID = C2.COMPANY_ID
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES AS V ON (PO.VENDOR_ID = V.VENDOR_ID) AND (V.RULE_YEAR = YEAR(POL.INVOICE_DATE))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.MANUFACTURE_SPECIFIC AS MS ON (ORDER_NUMBER = MS.PO_NUMBER_LINES)
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES_RATES AS R ON MS.RULE_ID = R.RULE_ID
WHERE C1.SUPPLY_VENDOR = TRUE
AND (EMO.NAME NOT ILIKE '%bucket%' OR EMO.NAME IS NULL)
AND POL.DELETED_AT IS NULL
AND POL.INVOICE_DATE >= '2026-01-01' AND POL.INVOICE_DATE < '2026-04-01'
AND POL.INVOICE_DATE::DATE >= MS.EFFECTIVE_DATE::DATE
AND MS.RULE_ID = 26
AND MS.TYPE = 'PO'
AND MS.PO_NUMBER_LINES IS NOT NULL
AND ((POL.NOTE NOT LIKE '%CPE%' AND POL.NOTE NOT LIKE '%IES%' AND POL.NOTE NOT LIKE '%VLP%') OR POL.NOTE IS NULL)
UNION ALL
-- MODEL SPECIFIC - FACTORY BUILD SPEC -- DOOSAN
SELECT PO.VENDOR_ID,
C1.NAME AS VENDOR_NAME,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID) AS ORDER_NUMBER_GROUPED,
CONCAT(CPT.prefix,'PO',POL.COMPANY_PURCHASE_ORDER_ID,'-',POL.COMPANY_PURCHASE_ORDER_LINE_ITEM_NUMBER) AS ORDER_NUMBER,
POL.INVOICE_NUMBER,
POL.INVOICE_DATE,
POL.RELEASE_DATE,
POL.ASSET_ID,
COALESCE(POL.SERIAL,POL.VIN) AS SERIAL_VIN,
POL.ORDER_STATUS,
POL.FINANCE_STATUS,
EMA.NAME AS EQUIPMENT_MAKE,
EMO.NAME AS EQUIPMENT_MODEL,
POL.YEAR AS MODEL_YEAR,
POL.FACTORY_BUILD_SPECIFICATIONS,
AA.COMPANY_ID AS OWNER_ID,
C2.NAME AS OWNER_NAME,
POL.NET_PRICE,
POL.FREIGHT_COST,
POL.SALES_TAX,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.SALES_TAX,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS TOTAL_OEC,
COALESCE(POL.NET_PRICE,0) + COALESCE(POL.FREIGHT_COST,0) + COALESCE(POL.AFTERMARKET_OEC,0) - COALESCE(POL.REBATE,0) AS OEC_LESS_TAX,
PO.APPROVED_AT AS PO_APPROVED_DATE,
POL.NOTE,
V.RULE_ID,
V.RULE_YEAR,
R.RULE,
R.REIMBURSEMENT_RATE,
CASE WHEN POL.FINANCE_STATUS  IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms')  THEN 0.00
WHEN (POL.FINANCE_STATUS NOT IN ('Dealership Floor Plan','Dealer Floor Plan','Demo Unit','Dealer - Net Terms') OR POL.FINANCE_STATUS IS NULL) THEN IFNULL(MS.REBATE_AMOUNT,0) ELSE 0.00 END AS REIMBURSEMENT_AMOUNT
FROM ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_LINE_ITEMS AS POL
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDERS AS PO ON POL.COMPANY_PURCHASE_ORDER_ID = PO.COMPANY_PURCHASE_ORDER_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANY_PURCHASE_ORDER_TYPES AS CPT ON PO.COMPANY_PURCHASE_ORDER_TYPE_ID = CPT.COMPANY_PURCHASE_ORDER_TYPE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C1 ON PO.VENDOR_ID = C1.COMPANY_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.ASSETS_AGGREGATE AS AA ON POL.ASSET_ID = AA.ASSET_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MODELS AS EMO ON POL.EQUIPMENT_MODEL_ID = EMO.EQUIPMENT_MODEL_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.EQUIPMENT_MAKES AS EMA ON EMO.EQUIPMENT_MAKE_ID = EMA.EQUIPMENT_MAKE_ID
LEFT JOIN ES_WAREHOUSE.PUBLIC.COMPANIES AS C2 ON AA.COMPANY_ID = C2.COMPANY_ID
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES AS V ON (PO.VENDOR_ID = V.VENDOR_ID) AND (V.RULE_YEAR = YEAR(POL.INVOICE_DATE))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.MANUFACTURE_SPECIFIC AS MS
ON (LOWER(EMA.NAME) = LOWER(MS.MAKE)) AND (LOWER(EMO.NAME) = LOWER(MS.MODEL)) AND (LOWER(POL.FACTORY_BUILD_SPECIFICATIONS) = LOWER(MS.FACTORY_BUILD_SPEC))
LEFT JOIN ANALYTICS.REIMBURSEMENTS.VENDOR_RULES_RATES AS R ON MS.RULE_ID = R.RULE_ID
WHERE C1.SUPPLY_VENDOR = TRUE
AND (EMO.NAME NOT ILIKE '%bucket%' OR EMO.NAME IS NULL)
AND POL.DELETED_AT IS NULL
AND POL.INVOICE_DATE >= '2026-01-01' AND POL.INVOICE_DATE < '2026-04-01'
AND POL.INVOICE_DATE::DATE >= MS.EFFECTIVE_DATE::DATE
AND (COALESCE(POL.SERIAL, POL.VIN) NOT IN (SELECT DISTINCT SERIAL FROM EXCLUDE_CTE) OR COALESCE(POL.SERIAL, POL.VIN) IS NULL)
AND MS.RULE_ID = 17
AND MS.TYPE = 'Factory Build Spec'
AND ((POL.NOTE NOT LIKE '%CPE%' AND POL.NOTE NOT LIKE '%IES%' AND POL.NOTE NOT LIKE '%VLP%') OR POL.NOTE IS NULL)
    ;;
  }


  ################# DIMENSIONS #################

  dimension: vendor_id {
    type: number
    value_format_name: id
    sql: ${TABLE}."VENDOR_ID" ;;
  }

  dimension: note {
    type: string
    sql: ${TABLE}."NOTE" ;;
  }

  dimension: vendor_name {
    type:  string
    sql: ${TABLE}."VENDOR_NAME" ;;
  }

  dimension: order_number_grouped {
    type: string
    sql: ${TABLE}."ORDER_NUMBER_GROUPED" ;;
  }

  dimension: order_number {
    type: string
    sql: ${TABLE}."ORDER_NUMBER" ;;
  }

  dimension: asset_id {
    type: number
    value_format_name: id
    sql: ${TABLE}."ASSET_ID" ;;
  }

  dimension: order_status  {
    type: string
    sql: ${TABLE}."ORDER_STATUS" ;;
  }

  dimension: finance_status {
    type: string
    sql: ${TABLE}."FINANCE_STATUS" ;;
  }

  dimension: equipment_make {
    type: string
    sql: ${TABLE}."EQUIPMENT_MAKE" ;;
  }

  dimension: equipment_model  {
    type: string
    sql: ${TABLE}."EQUIPMENT_MODEL" ;;
  }

  dimension: model_year {
    type: number
    value_format_name: id
    sql: ${TABLE}."MODEL_YEAR" ;;
  }

  dimension: owner_id {
    type: number
    value_format_name: id
    sql: ${TABLE}."OWNER_ID" ;;
  }

  dimension: owner_name {
    type: string
    sql: ${TABLE}."OWNER_NAME" ;;
  }

  dimension: rule_id {
    type: number
    value_format_name: id
    sql: ${TABLE}."RULE_ID" ;;
  }

  dimension: rule_year {
    type: number
    value_format_name: id
    sql: ${TABLE}."RULE_YEAR" ;;
  }

  dimension: rule {
    type: string
    sql: ${TABLE}."RULE" ;;
  }

  dimension_group: invoice {
    type: time
    convert_tz: no
    timeframes: [
      raw,
      time,
      date,
      week,
      month,
      quarter,
      year
    ]
    sql: ${TABLE}."INVOICE_DATE" ;;
  }

  dimension_group: release {
    type: time
    convert_tz: no
    timeframes: [
      raw,
      time,
      date,
      week,
      month,
      quarter,
      year
    ]
    sql: ${TABLE}."RELEASE" ;;
  }

  dimension_group: po_approved {
    type: time
    convert_tz: no
    timeframes: [
      raw,
      time,
      date,
      week,
      month,
      quarter,
      year
    ]
    sql: ${TABLE}."PO_APPROVED_DATE" ;;
  }

  dimension: reimbursement_rate {
    type: number
    value_format_name: percent_0
    sql: ${TABLE}."REIMBURSEMENT_RATE" ;;
  }

  dimension: invoice_number {
    type: string
    sql: ${TABLE}."INVOICE_NUMBER" ;;
  }

  dimension: factory_build_specifications {
    type: string
    sql: ${TABLE}."FACTORY_BUILD_SPECIFICATIONS" ;;
  }

  dimension: serial_vin {
    label: "Serial_VIN"
    type: string
    sql: ${TABLE}."SERIAL_VIN" ;;
  }



  ################# MEASURES #################

  measure: reimbursement_amount {
    type: sum
    value_format_name: usd
    drill_fields: [trx_details*]
    sql: ${TABLE}."REIMBURSEMENT_AMOUNT" ;;
  }

  measure: net_price {
    type: sum
    value_format_name: usd
    sql: ${TABLE}."NET_PRICE" ;;
  }

  measure: total_oec {
    label: "Total OEC"
    type: sum
    value_format_name: usd
    sql: ${TABLE}."TOTAL_OEC" ;;
  }

  measure: oec_less_tax {
    label: "OEC Less Tax"
    type: sum
    value_format_name: usd
    sql: ${TABLE}."OEC_LESS_TAX" ;;
  }

################# DRILL FIELDS #################

  set: trx_details {
    fields: [vendor_name,vendor_id,order_number,order_number_grouped,asset_id,serial_vin,invoice_number,invoice_date, po_approved_date,
order_status,finance_status,equipment_make,equipment_model,model_year,factory_build_specifications,owner_id,owner_name,net_price,rule,rule_year,
net_price,total_oec,oec_less_tax,reimbursement_rate,reimbursement_amount, note
    ]
  }















  }
