view: dim_dates {
  sql_table_name: "PLATFORM"."GOLD"."V_DATES" ;;

  # PRIMARY KEY
  dimension: date_key {
    primary_key: yes
    type: string
    sql: ${TABLE}."DATE_KEY" ;;
    hidden: yes
  }

  # DATE DIMENSIONS
  dimension_group: dt {
    type: time
    timeframes: [
      raw,
      date,
      week,
      month,
      quarter,
      year,
      day_of_week,
      day_of_month,
      day_of_year
    ]
    convert_tz: no
    datatype: date
    sql: ${TABLE}."DATE" ;;
    description: "Calendar date"
  }

  # These fields are auto-generated by dimension_group: dt above
  # dt_day_of_week, dt_month, dt_quarter, dt_year are automatically created

  dimension: dt_day_of_week_number {
    type: number
    sql: ${TABLE}."DAY_OF_WEEK" ;;
    description: "Day of week number (1=Monday)"
    hidden: yes
  }

  # BUSINESS DATE FLAGS
  dimension: is_weekend {
    type: yesno
    sql: ${TABLE}."DAY_OF_WEEK" IN (6, 7) ;;
    description: "Date falls on weekend"
  }

  dimension: is_weekday {
    type: yesno
    sql: ${TABLE}."DAY_OF_WEEK" BETWEEN 1 AND 5 ;;
    description: "Date falls on weekday"
  }

  # MEASURES
  measure: count {
    type: count
    description: "Number of dates"
  }
}
